# ********RoostGPT********

# Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Testing the Nobel Prize API Endpoint

  Background:
    * def urlBase = karate.properties['NOBEL_API_HOST']
    * url urlBase

  Scenario Outline: Verify successful response for category and year
    Given path '/2.1/nobelPrize/<category>/<year>'
    When method GET
    Then status 200
    And match response == '''
    {
      "nobelPrize": {
        "awardYear": '#integer',
        "awardYear": '#? _ >= 1901',
        "category": {
          "en": '#string',
          "se": '#string'
        },
        "categoryFullName": {
          "en": '#string',
          "se": '#string'
        },
        "dateAwarded": '#? _ == /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/',
        "prizeAmount": '#integer',
        "prizeAmountAdjusted": '#integer',
        "topMotivation": {
          "en": '#string',
          "se": '#string'
        },
        "laureates": [
          {
            "id": '#? _ >= 1',
            "name": {
              "en": '#string',
              "se": '#string'
            },
            "portion": '#string',
            "sortOrder": '#string',
            "motivation": {
              "en": '#string'
            },
            "links": [
              {
                "rel": '#string',
                "href": '#string',
                "action": '#string',
                "types": '#string'
              }
            ]
          }
        ]
      }
    }'''

    Examples:
      | category  | year |
      | physics   | 2020 |
      | chemistry | 2015 |
      | medicine  | 1989 |

  Scenario Outline: Bad request for malformed category/year
    Given path '/2.1/nobelPrize/<category>/<year>'
    When method GET
    Then status <code>
    And match response == '''
    {
      "code": '#string',
      "message": '#string'
    }'''

    Examples:
      | category | year | code |
      | invalid  | 1900 | 400  |
      | physics  | abc  | 400  |

  Scenario Outline: Resource not found for unavailable category/year
    Given path '/2.1/nobelPrize/<category>/<year>'
    When method GET
    Then status 404
    And match response == '''
    {
      "code": '#string',
      "message": '#string'
    }'''

    Examples:
      | category   | year |
      | literature | 1800 |
      | peace      | 2100 |

  Scenario Outline: Verify semantic error for category/year mismatch
    Given path '/2.1/nobelPrize/<category>/<year>'
    When method GET
    Then status 422
    And match response == '''
    {
      "code": '#string',
      "message": '#string'
    }'''

    Examples:
      | category   | year |
      | invalidCat | 1989 |
      | medicine   | test |
