/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=registerHints_a9eb20a924
ROOST_METHOD_SIG_HASH=registerHints_4cbaa06045

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-report-test/1751018734/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/aot/SpringAiCoreRuntimeHintsTest.java
Tests:
    "@Test
@Test
void core() {
    var runtimeHints = new RuntimeHints();
    var springAiCore = new SpringAiCoreRuntimeHints();
    springAiCore.registerHints(runtimeHints, null);
    assertThat(runtimeHints).matches(resource().forResource("embedding/embedding-model-dimensions.properties"));
    assertThat(runtimeHints).matches(reflection().onMethod(FunctionCallback.class, "getDescription"));
    assertThat(runtimeHints).matches(reflection().onMethod(FunctionCallback.class, "getInputTypeSchema"));
    assertThat(runtimeHints).matches(reflection().onMethod(FunctionCallback.class, "getName"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-report-test/1751018734/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/aot/ToolRuntimeHintsTests.java
Tests:
    "@Test
@Test
void registerHints() {
    RuntimeHints runtimeHints = new RuntimeHints();
    ToolRuntimeHints toolRuntimeHints = new ToolRuntimeHints();
    toolRuntimeHints.registerHints(runtimeHints, null);
    assertThat(runtimeHints).matches(reflection().onType(DefaultToolCallResultConverter.class));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-report-test/1751018734/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/aot/KnuddelsRuntimeHintsTest.java
Tests:
    "@Test
@Test
void knuddels() {
    var runtimeHints = new RuntimeHints();
    var knuddels = new KnuddelsRuntimeHints();
    knuddels.registerHints(runtimeHints, null);
    assertThat(runtimeHints).matches(resource().forResource("com/knuddels/jtokkit/cl100k_base.tiktoken"));
}
"
Scenario [1]: Verify Reflection Registration for Chat Message Types

Details:
  TestName: verifyReflectionRegistrationForChatMessageTypes
  Description: Ensure that the `registerHints` method correctly registers all types specified in the `chatTypes` set for reflection.

Execution:
  Arrange: Create an instance of RuntimeHints, and instantiate the SpringAiCoreRuntimeHints class. Retrieve the expected list of types to be registered for reflection (including AbstractMessage.class, AssistantMessage.class, ToolResponseMessage.class, Message.class, MessageType.class, UserMessage.class, SystemMessage.class, DefaultFunctionCallbackResolver.class, FunctionCallback.class).
  Act: Invoke the `registerHints` method, passing in the RuntimeHints instance and a null ClassLoader.
  Assert: Check that each type is registered for reflection using `reflections().onType()` assertions.
Validation:
  Ensure the method correctly handles all `chatTypes` entries. Validation confirms compatibility with reflection-based frameworks and ensures that all specified types are registered.

*/

// ********RoostGPT********

package org.springframework.ai.aot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.aot.hint.ExecutableMode;
import org.springframework.aot.hint.RuntimeHints;
import org.springframework.core.io.ClassPathResource;
import org.springframework.ai.chat.messages.*;
import java.lang.reflect.Method;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Set;
import org.springframework.ai.chat.messages.AbstractMessage;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.messages.Message;
import org.springframework.ai.chat.messages.MessageType;
import org.springframework.ai.chat.messages.SystemMessage;
import org.springframework.ai.chat.messages.ToolResponseMessage;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.model.function.DefaultFunctionCallbackResolver;
import org.springframework.ai.model.function.FunctionCallback;
import org.springframework.aot.hint.RuntimeHintsRegistrar;
import org.springframework.lang.NonNull;
import org.springframework.lang.Nullable;
import org.springframework.util.ReflectionUtils;

class SpringAiCoreRuntimeHintsRegisterHintsTest {

	@Mock
	private RuntimeHints runtimeHintsMock;

	private SpringAiCoreRuntimeHints springAiCoreRuntimeHints;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
		springAiCoreRuntimeHints = new SpringAiCoreRuntimeHints();
	}

	@Test
	@Tag("valid")
	public void verifyReflectionRegistrationForChatMessageTypes() {
		// Arrange
		var expectedChatTypes = Set.of(AbstractMessage.class, AssistantMessage.class, ToolResponseMessage.class,
				Message.class, MessageType.class, UserMessage.class, SystemMessage.class,
				DefaultFunctionCallbackResolver.class, FunctionCallback.class);
		// Act
		springAiCoreRuntimeHints.registerHints(runtimeHintsMock, null);
		// Assert
		for (var type : expectedChatTypes) {
			verify(runtimeHintsMock.reflection(), times(1)).registerType(type);
		}
	}

	@Test
	@Tag("valid")
	public void verifyReflectionRegistrationForFunctionCallbackMethods() {
		// Arrange
		Method getDescription = ReflectionUtils.findMethod(FunctionCallback.class, "getDescription");
		Method getInputTypeSchema = ReflectionUtils.findMethod(FunctionCallback.class, "getInputTypeSchema");
		Method getName = ReflectionUtils.findMethod(FunctionCallback.class, "getName");
		// Act
		springAiCoreRuntimeHints.registerHints(runtimeHintsMock, null);
		// Assert
		assertNotNull(getDescription);
		assertNotNull(getInputTypeSchema);
		assertNotNull(getName);
		verify(runtimeHintsMock.reflection(), times(1)).registerMethod(getDescription, ExecutableMode.INVOKE);
		verify(runtimeHintsMock.reflection(), times(1)).registerMethod(getInputTypeSchema, ExecutableMode.INVOKE);
		verify(runtimeHintsMock.reflection(), times(1)).registerMethod(getName, ExecutableMode.INVOKE);
	}

	@Test
	@Tag("valid")
	public void verifyResourceRegistration() {
		// Arrange
		var expectedResources = Set.of(
				new ClassPathResource("antlr4/org/springframework/ai/vectorstore/filter/antlr4/Filters.g4"),
				new ClassPathResource("embedding/embedding-model-dimensions.properties"));
		// Act
		springAiCoreRuntimeHints.registerHints(runtimeHintsMock, null);
		// Assert
		for (var resource : expectedResources) {
			verify(runtimeHintsMock.resources(), times(1)).registerResource(resource);
		}
	}

	@Test
	@Tag("boundary")
	public void verifyMethodHandlesNullClassLoaderGracefully() {
		// Act and Assert
		assertDoesNotThrow(() -> springAiCoreRuntimeHints.registerHints(runtimeHintsMock, null));
	}

	@Test
	@Tag("invalid")
	public void verifyInvalidTypeDoesNotCauseError() {
		// Arrange
		var invalidType = RuntimeHints.class; // TODO: Replace with a non-existent type to
												// test error handling.
		// Act and Assert
		assertDoesNotThrow(() -> springAiCoreRuntimeHints.registerHints(runtimeHintsMock, null));
		verify(runtimeHintsMock.reflection(), never()).registerType(invalidType);
	}

}