/*
 * Copyright 2023-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=registerHints_a64fc3b94a
ROOST_METHOD_SIG_HASH=registerHints_4cbaa06045

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-report-test/1751021634/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/aot/KnuddelsRuntimeHintsTest.java
Tests:
    "@Test
@Test
void knuddels() {
    var runtimeHints = new RuntimeHints();
    var knuddels = new KnuddelsRuntimeHints();
    knuddels.registerHints(runtimeHints, null);
    assertThat(runtimeHints).matches(resource().forResource("com/knuddels/jtokkit/cl100k_base.tiktoken"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-report-test/1751021634/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/aot/ToolRuntimeHintsTests.java
Tests:
    "@Test
@Test
void registerHints() {
    RuntimeHints runtimeHints = new RuntimeHints();
    ToolRuntimeHints toolRuntimeHints = new ToolRuntimeHints();
    toolRuntimeHints.registerHints(runtimeHints, null);
    assertThat(runtimeHints).matches(reflection().onType(DefaultToolCallResultConverter.class));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-report-test/1751021634/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/aot/SpringAiCoreRuntimeHintsTest.java
Tests:
    "@Test
@Test
void core() {
    var runtimeHints = new RuntimeHints();
    var springAiCore = new SpringAiCoreRuntimeHints();
    springAiCore.registerHints(runtimeHints, null);
    assertThat(runtimeHints).matches(resource().forResource("embedding/embedding-model-dimensions.properties"));
    assertThat(runtimeHints).matches(reflection().onMethod(FunctionCallback.class, "getDescription"));
    assertThat(runtimeHints).matches(reflection().onMethod(FunctionCallback.class, "getInputTypeSchema"));
    assertThat(runtimeHints).matches(reflection().onMethod(FunctionCallback.class, "getName"));
}
"
Scenario 1: Verifying that registerHints registers DefaultToolCallResultConverter with all MemberCategories.

Details:
  TestName: registerDefaultToolCallResultConverterWithAllMemberCategories
  Description: This test validates that the registerHints method successfully registers the DefaultToolCallResultConverter class with all MemberCategory values using the provided RuntimeHints instance.

Execution:
  Arrange: Create a new instance of RuntimeHints and pass it as an argument to the registerHints method along with a null ClassLoader.
  Act: Invoke the registerHints method of the ToolRuntimeHints class.
  Assert: Verify that RuntimeHints correctly registers DefaultToolCallResultConverter with all MemberCategory values through the reflection API.

Validation:
  The assertion ensures that DefaultToolCallResultConverter is fully registered for reflection with every MemberCategory value. This validates that the method accommodates all MemberCategory values without omission, aligning with expected behavior.

*/

// ********RoostGPT********

package org.springframework.ai.aot;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.springframework.aot.hint.MemberCategory;
import org.springframework.aot.hint.RuntimeHints;
import org.springframework.lang.NonNull;
import org.springframework.lang.Nullable;
import org.springframework.ai.tool.execution.DefaultToolCallResultConverter;
import org.springframework.aot.hint.RuntimeHintsRegistrar;

class ToolRuntimeHintsRegisterHintsTest {

	@Tag("valid")
	@Test
	public void registerDefaultToolCallResultConverterWithAllMemberCategories() {
		// Arrange
		RuntimeHints mockRuntimeHints = mock(RuntimeHints.class);
		when(mockRuntimeHints.reflection()).thenReturn(mock(RuntimeHints.ReflectionHints.class)); // Updated
																									// mock
																									// setup
																									// to
																									// correctly
																									// access
																									// ReflectionHints
		ToolRuntimeHints toolRuntimeHints = new ToolRuntimeHints();
		// Act
		toolRuntimeHints.registerHints(mockRuntimeHints, null);
		// Assert
		verify(mockRuntimeHints.reflection()).registerType(eq(DefaultToolCallResultConverter.class),
				eq(MemberCategory.values()));
	}

}