/*
 * Copyright 2023-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=registerHints_a64fc3b94a
ROOST_METHOD_SIG_HASH=registerHints_4cbaa06045

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-report-test/1751028335/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/aot/ToolRuntimeHintsTests.java
Tests:
    "@Test
@Test
void registerHints() {
    RuntimeHints runtimeHints = new RuntimeHints();
    ToolRuntimeHints toolRuntimeHints = new ToolRuntimeHints();
    toolRuntimeHints.registerHints(runtimeHints, null);
    assertThat(runtimeHints).matches(reflection().onType(DefaultToolCallResultConverter.class));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-report-test/1751028335/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/aot/SpringAiCoreRuntimeHintsTest.java
Tests:
    "@Test
@Test
void core() {
    var runtimeHints = new RuntimeHints();
    var springAiCore = new SpringAiCoreRuntimeHints();
    springAiCore.registerHints(runtimeHints, null);
    assertThat(runtimeHints).matches(resource().forResource("embedding/embedding-model-dimensions.properties"));
    assertThat(runtimeHints).matches(reflection().onMethod(FunctionCallback.class, "getDescription"));
    assertThat(runtimeHints).matches(reflection().onMethod(FunctionCallback.class, "getInputTypeSchema"));
    assertThat(runtimeHints).matches(reflection().onMethod(FunctionCallback.class, "getName"));
}
"

File Path: /var/tmp/Roost/RoostGPT/java-report-test/1751028335/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/aot/KnuddelsRuntimeHintsTest.java
Tests:
    "@Test
@Test
void knuddels() {
    var runtimeHints = new RuntimeHints();
    var knuddels = new KnuddelsRuntimeHints();
    knuddels.registerHints(runtimeHints, null);
    assertThat(runtimeHints).matches(resource().forResource("com/knuddels/jtokkit/cl100k_base.tiktoken"));
}
"
Scenario 1: Successful registration of DefaultToolCallResultConverter with valid MemberCategory values.

Details:
  TestName: successfullyRegistersDefaultToolCallResultConverter
  Description: This test checks if the method correctly registers the DefaultToolCallResultConverter with valid MemberCategory values, ensuring proper functionality when the method is invoked with standard parameters.

Execution:
  Arrange: Create an instance of RuntimeHints and ToolRuntimeHints. Ensure MemberCategory.values() are available.
  Act: Call the `registerHints` method with the RuntimeHints object. Pass `null` for the classLoader parameter.
  Assert: Verify if the DefaultToolCallResultConverter class is successfully registered with all MemberCategory values using assertions specific to RuntimeHints.

Validation:
  The assertion ensures that the reflection registration for DefaultToolCallResultConverter is performed successfully for all member categories. This test is significant as it validates the core functionality of the `registerHints` method.

*/

// ********RoostGPT********

package org.springframework.ai.aot;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import org.springframework.aot.hint.RuntimeHints;
import org.springframework.aot.hint.MemberCategory;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import org.springframework.ai.tool.execution.DefaultToolCallResultConverter;
import org.springframework.aot.hint.RuntimeHintsRegistrar;
import org.springframework.lang.NonNull;
import org.springframework.lang.Nullable;

public class ToolRuntimeHintsRegisterHintsTest {

	// Test function was failing due to compilation error:
	// RuntimeHints class does not have a ReflectionHints nested class
	// Updated the test logic to use method chaining, as per the provided registerHints
	// function

	@Tag("valid")
	@Test
	public void successfullyRegistersDefaultToolCallResultConverter() {
		// Arrange
		RuntimeHints runtimeHintsMock = Mockito.mock(RuntimeHints.class);
		MemberCategory[] memberCategories = MemberCategory.values();

		// Mock reflection() method directly in RuntimeHints to return the chain function
		Mockito.doNothing()
			.when(runtimeHintsMock)
			.reflection()
			.registerType(eq(DefaultToolCallResultConverter.class), eq(memberCategories));

		ToolRuntimeHints toolRuntimeHints = new ToolRuntimeHints();

		// Act
		toolRuntimeHints.registerHints(runtimeHintsMock, null);

		// Assert
		verify(runtimeHintsMock.reflection()).registerType(eq(DefaultToolCallResultConverter.class),
				eq(memberCategories));
	}

}