/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test single_test_file using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getModel_a8d99c0d89
ROOST_METHOD_SIG_HASH=getModel_bb1c8044bd


Scenario [1]: Verify that the getModel method returns the model value that was explicitly set through the setModel method.

Details:
  TestName: returnsSetModelValue
  Description: This test ensures that the getModel method correctly returns the value of the model field, after explicitly setting a valid model string using the setModel method. The test validates that the state of the object persists correctly and the getter reflects the assigned model value.
Execution:
  Arrange:
    - Instantiate the ImageOptionsBuilder using its static builder method.
    - Set a specific model value using the builder's model(String model) method.
    - Build the options object and retrieve the nested DefaultImageModelOptions object.
  Act:
    - Call the getModel method on the DefaultImageModelOptions object.
  Assert:
    - Use JUnit assertions to verify that the returned model is equal to the initially set model.
Validation:
    This test ensures that the model property in the DefaultImageModelOptions object is correctly set and returned. It verifies that the getter method accurately retrieves the stored value, which is crucial for maintaining the integrity of user-defined input within the application.

*/

// ********RoostGPT********

package org.springframework.ai.image;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Assertions;

public class DefaultImageModelOptionsGetModelTest {

	@Test
	@Tag("valid")
	public void returnsSetModelValue() {
		// Arrange
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		String expectedModel = "custom-model"; // Replace with desired model value
		builder.model(expectedModel);
		ImageOptions options = builder.build();
		// Act
		String actualModel = options.getModel();
		// Assert
		Assertions.assertEquals((String) expectedModel, (String) actualModel,
				"Model value should be correctly set and retrieved.");
	}

	@Test
	@Tag("invalid")
	public void returnsNullWhenModelNotSet() {
		// Arrange
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		ImageOptions options = builder.build();
		// Act
		String actualModel = options.getModel();
		// Assert
		Assertions.assertNull((String) actualModel, "Model value should be null when not explicitly set.");
	}

	@Test
	@Tag("boundary")
	public void returnsEmptyStringWhenModelSetToEmptyString() {
		// Arrange
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		String expectedModel = ""; // Replace with desired model value
		builder.model(expectedModel);
		ImageOptions options = builder.build();
		// Act
		String actualModel = options.getModel();
		// Assert
		Assertions.assertEquals((String) expectedModel, (String) actualModel,
				"Model value should be correctly set to an empty string.");
	}

}