/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test single_test_file using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getInstructions_9a3bc3a0a6
ROOST_METHOD_SIG_HASH=getInstructions_d65434e23a

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/chat/client/advisor/SimpleLoggerAdvisorTests.java
Tests:
    "@Test
private void validate(String content, CapturedOutput output) {
    assertThat(content).isEqualTo("Your answer is ZXY");
    UserMessage userMessage = (UserMessage) this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(userMessage.getText()).isEqualToIgnoringWhitespace("Please answer my question XYZ");
    assertThat(output.getOut()).contains("request: AdvisedRequest", "userText=Please answer my question XYZ");
    assertThat(output.getOut()).contains("response:", "finishReason");
}
"

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/chat/client/ChatClientTest.java
Tests:
    "@Test
@Test
void defaultSystemText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    given(this.chatModel.stream(this.promptCaptor.capture())).willReturn(Flux.generate(() -> new ChatResponse(List.of(new Generation(new AssistantMessage("response")))), (state, sink) -> {
        sink.next(state);
        sink.complete();
        return state;
    }));
    var chatClient = ChatClient.builder(this.chatModel).defaultSystem("Default system text").build();
    var content = chatClient.prompt("What's Spring AI?").call().content();
    assertThat(content).isEqualTo("response");
    Message systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("Default system text");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    content = join(chatClient.prompt("What's Spring AI?").stream().content());
    assertThat(content).isEqualTo("response");
    systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("Default system text");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);

    content = chatClient.prompt("What's Spring AI?").system("Override default system text").call().content();
    assertThat(content).isEqualTo("response");
    systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("Override default system text");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);

    content = join(chatClient.prompt("What's Spring AI?").system("Override default system text").stream().content());
    assertThat(content).isEqualTo("response");
    systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("Override default system text");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
}
"
    "@Test
@Test
void defaultSystemTextLambda() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    given(this.chatModel.stream(this.promptCaptor.capture())).willReturn(Flux.generate(() -> new ChatResponse(List.of(new Generation(new AssistantMessage("response")))), (state, sink) -> {
        sink.next(state);
        sink.complete();
        return state;
    }));
    var chatClient = ChatClient.builder(this.chatModel).defaultSystem(s -> s.text("Default system text {param1}, {param2}").param("param1", "value1").param("param2", "value2")).build();
    var content = chatClient.prompt("What's Spring AI?").call().content();
    assertThat(content).isEqualTo("response");
    Message systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("Default system text value1, value2");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);

    content = join(chatClient.prompt("What's Spring AI?").stream().content());
    assertThat(content).isEqualTo("response");
    systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("Default system text value1, value2");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);

    content = chatClient.prompt("What's Spring AI?").system(s -> s.param("param1", "value1New")).call().content();
    assertThat(content).isEqualTo("response");
    systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("Default system text value1New, value2");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);

    content = join(chatClient.prompt("What's Spring AI?").system(s -> s.param("param1", "value1New")).stream().content());
    assertThat(content).isEqualTo("response");
    systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("Default system text value1New, value2");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);

    content = chatClient.prompt("What's Spring AI?").system(s -> s.text("Override default system text {param3}").param("param3", "value3")).call().content();
    assertThat(content).isEqualTo("response");
    systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("Override default system text value3");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);

    content = join(chatClient.prompt("What's Spring AI?").system(s -> s.text("Override default system text {param3}").param("param3", "value3")).stream().content());
    assertThat(content).isEqualTo("response");
    systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("Override default system text value3");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
}
"
    "@Test
@Test
void mutateDefaults() {
    FunctionCallingOptions options = new DefaultFunctionCallingOptions();
    given(this.chatModel.getDefaultOptions()).willReturn(options);
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    given(this.chatModel.stream(this.promptCaptor.capture())).willReturn(Flux.generate(() -> new ChatResponse(List.of(new Generation(new AssistantMessage("response")))), (state, sink) -> {
        sink.next(state);
        sink.complete();
        return state;
    }));

    var chatClient = ChatClient.builder(this.chatModel).defaultSystem(s -> s.text("Default system text {param1}, {param2}").param("param1", "value1").param("param2", "value2")).defaultFunctions("fun1", "fun2").defaultFunctions(FunctionCallback.builder().function("fun3", mockFunction).description("fun3description").inputType(String.class).build()).defaultUser(u -> u.text("Default user text {uparam1}, {uparam2}").param("uparam1", "value1").param("uparam2", "value2").media(MimeTypeUtils.IMAGE_JPEG, new DefaultResourceLoader().getResource("classpath:/bikes.json"))).build();

    var content = chatClient.prompt().call().content();
    assertThat(content).isEqualTo("response");
    Prompt prompt = this.promptCaptor.getValue();
    Message systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("Default system text value1, value2");
    UserMessage userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Default user text value1, value2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    var fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");

    content = join(chatClient.prompt().stream().content());
    assertThat(content).isEqualTo("response");
    prompt = this.promptCaptor.getValue();
    systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("Default system text value1, value2");
    userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Default user text value1, value2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");


    chatClient = chatClient.mutate().defaultSystem("Mutated default system text {param1}, {param2}").defaultFunctions("fun4").defaultUser("Mutated default user text {uparam1}, {uparam2}").build();

    content = chatClient.prompt().call().content();
    assertThat(content).isEqualTo("response");
    prompt = this.promptCaptor.getValue();
    systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("Mutated default system text value1, value2");
    userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Mutated default user text value1, value2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2", "fun4");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");

    content = join(chatClient.prompt().stream().content());
    assertThat(content).isEqualTo("response");
    prompt = this.promptCaptor.getValue();
    systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("Mutated default system text value1, value2");
    userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Mutated default user text value1, value2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2", "fun4");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");
}
"
    "@Test
@Test
void mutatePrompt() {
    FunctionCallingOptions options = new DefaultFunctionCallingOptions();
    given(this.chatModel.getDefaultOptions()).willReturn(options);
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    given(this.chatModel.stream(this.promptCaptor.capture())).willReturn(Flux.generate(() -> new ChatResponse(List.of(new Generation(new AssistantMessage("response")))), (state, sink) -> {
        sink.next(state);
        sink.complete();
        return state;
    }));

    var chatClient = ChatClient.builder(this.chatModel).defaultSystem(s -> s.text("Default system text {param1}, {param2}").param("param1", "value1").param("param2", "value2")).defaultFunctions("fun1", "fun2").defaultFunctions(FunctionCallback.builder().function("fun3", mockFunction).description("fun3description").inputType(String.class).build()).defaultUser(u -> u.text("Default user text {uparam1}, {uparam2}").param("uparam1", "value1").param("uparam2", "value2").media(MimeTypeUtils.IMAGE_JPEG, new DefaultResourceLoader().getResource("classpath:/bikes.json"))).build();
    var content = chatClient.prompt().system("New default system text {param1}, {param2}").user(u -> u.param("uparam1", "userValue1").param("uparam2", "userValue2")).functions("fun5").mutate().
    build().prompt().call().content();

    assertThat(content).isEqualTo("response");
    Prompt prompt = this.promptCaptor.getValue();
    Message systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("New default system text value1, value2");
    UserMessage userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Default user text userValue1, userValue2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    var fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2", "fun5");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");


    content = join(chatClient.prompt().system("New default system text {param1}, {param2}").user(u -> u.param("uparam1", "userValue1").param("uparam2", "userValue2")).functions("fun5").mutate().
    build().prompt().stream().content());

    assertThat(content).isEqualTo("response");
    prompt = this.promptCaptor.getValue();
    systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("New default system text value1, value2");
    userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Default user text userValue1, userValue2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2", "fun5");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");
}
"
    "@Test
@Test
void defaultUserText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).defaultUser("Default user text").build();
    var content = chatClient.prompt().call().content();
    assertThat(content).isEqualTo("response");
    Message userMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(userMessage.getText()).isEqualTo("Default user text");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);

    content = chatClient.prompt().user("Override default user text").call().content();
    assertThat(content).isEqualTo("response");
    userMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(userMessage.getText()).isEqualTo("Override default user text");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
}
"
    "@Test
@Test
void simpleUserPromptAsString() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    assertThat(ChatClient.builder(this.chatModel).build().prompt("User prompt").call().content()).isEqualTo("response");
    Message userMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(userMessage.getText()).isEqualTo("User prompt");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
}
"
    "@Test
@Test
void simpleUserPrompt() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    assertThat(ChatClient.builder(this.chatModel).build().prompt().user("User prompt").call().content()).isEqualTo("response");
    Message userMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(userMessage.getText()).isEqualTo("User prompt");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
}
"
    "@Test
@Test
void simpleUserPromptObject() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var media = new Media(MimeTypeUtils.IMAGE_JPEG, new DefaultResourceLoader().getResource("classpath:/bikes.json"));
    UserMessage message = new UserMessage("User prompt", List.of(media));
    Prompt prompt = new Prompt(message);
    assertThat(ChatClient.builder(this.chatModel).build().prompt(prompt).call().content()).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(1);
    Message userMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("User prompt");
    assertThat(((UserMessage) userMessage).getMedia()).hasSize(1);
}
"
    "@Test
@Test
void simpleSystemPrompt() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    String response = ChatClient.builder(this.chatModel).build().prompt("What's Spring AI?").system("System prompt").call().content();
    assertThat(response).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(2);
    Message systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("System prompt");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
}
"
    "@Test
@Test
void complexCall() throws MalformedURLException {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var options = FunctionCallingOptions.builder().build();
    given(this.chatModel.getDefaultOptions()).willReturn(options);
    var url = new URL("https:

    ChatClient client = ChatClient.builder(this.chatModel).defaultSystem("System text").defaultFunctions("function1").build();
    String response = client.prompt().user(u -> u.text("User text {music}").param("music", "Rock").media(MimeTypeUtils.IMAGE_PNG, url)).call().content();

    assertThat(response).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(2);
    Message systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("System text");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    UserMessage userMessage = (UserMessage) this.promptCaptor.getValue().getInstructions().get(1);
    assertThat(userMessage.getText()).isEqualTo("User text Rock");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_PNG);
    assertThat(userMessage.getMedia().iterator().next().getData()).isEqualTo("https:
    FunctionCallingOptions runtieOptions = (FunctionCallingOptions) this.promptCaptor.getValue().getOptions();
    assertThat(runtieOptions.getFunctions()).containsExactly("function1");
    assertThat(options.getFunctions()).isEmpty();
}
"
    "@Test
@Test
void whenPromptWithStringContent() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    var content = chatClient.prompt("my question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(1);
    var userMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(userMessage.getText()).isEqualTo("my question");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
}
"
    "@Test
@Test
void whenPromptWithMessages() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    var prompt = new Prompt(new SystemMessage("instructions"), new UserMessage("my question"));
    var content = chatClient.prompt(prompt).call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(2);
    var userMessage = this.promptCaptor.getValue().getInstructions().get(1);
    assertThat(userMessage.getText()).isEqualTo("my question");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
}
"
    "@Test
@Test
void whenPromptWithStringContentAndUserText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    var content = chatClient.prompt("my question").user("another question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(2);
    var userMessage = this.promptCaptor.getValue().getInstructions().get(1);
    assertThat(userMessage.getText()).isEqualTo("another question");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
}
"
    "@Test
@Test
void whenPromptWithHistoryAndUserText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    var prompt = new Prompt(new UserMessage("my question"), new AssistantMessage("your answer"));
    var content = chatClient.prompt(prompt).user("another question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(3);
    var userMessage = this.promptCaptor.getValue().getInstructions().get(2);
    assertThat(userMessage.getText()).isEqualTo("another question");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
}
"
    "@Test
@Test
void whenPromptWithUserMessageAndUserText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    var prompt = new Prompt(new UserMessage("my question"));
    var content = chatClient.prompt(prompt).user("another question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(2);
    var userMessage = this.promptCaptor.getValue().getInstructions().get(1);
    assertThat(userMessage.getText()).isEqualTo("another question");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
}
"
    "@Test
@Test
void whenMessagesWithHistoryAndUserText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    List<Message> messages = List.of(new UserMessage("my question"), new AssistantMessage("your answer"));
    var content = chatClient.prompt().messages(messages).user("another question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(3);
    var userMessage = this.promptCaptor.getValue().getInstructions().get(2);
    assertThat(userMessage.getText()).isEqualTo("another question");
}
"
    "@Test
@Test
void whenMessagesWithUserMessageAndUserText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    List<Message> messages = List.of(new UserMessage("my question"));
    var content = chatClient.prompt().messages(messages).user("another question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(2);
    var userMessage = this.promptCaptor.getValue().getInstructions().get(1);
    assertThat(userMessage.getText()).isEqualTo("another question");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
}
"
    "@Test
@Test
void whenPromptWithMessagesAndSystemText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    var prompt = new Prompt(new UserMessage("my question"), new AssistantMessage("your answer"));
    var content = chatClient.prompt(prompt).system("instructions").user("another question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(4);
    var systemMessage = this.promptCaptor.getValue().getInstructions().get(2);
    assertThat(systemMessage.getText()).isEqualTo("instructions");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
}
"
    "@Test
@Test
void whenPromptWithSystemMessageAndNoSystemText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    var prompt = new Prompt(new SystemMessage("instructions"), new UserMessage("my question"));
    var content = chatClient.prompt(prompt).user("another question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(3);
    var systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("instructions");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
}
"
    "@Test
@Test
void whenPromptWithSystemMessageAndSystemText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    var prompt = new Prompt(new SystemMessage("instructions"), new UserMessage("my question"));
    var content = chatClient.prompt(prompt).system("other instructions").user("another question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(4);
    var systemMessage = this.promptCaptor.getValue().getInstructions().get(2);
    assertThat(systemMessage.getText()).isEqualTo("other instructions");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
}
"
    "@Test
@Test
void whenMessagesAndSystemText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    List<Message> messages = List.of(new UserMessage("my question"), new AssistantMessage("your answer"));
    var content = chatClient.prompt().messages(messages).system("instructions").user("another question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(4);
    var systemMessage = this.promptCaptor.getValue().getInstructions().get(2);
    assertThat(systemMessage.getText()).isEqualTo("instructions");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
}
"
    "@Test
@Test
void whenMessagesWithSystemMessageAndNoSystemText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    List<Message> messages = List.of(new SystemMessage("instructions"), new UserMessage("my question"));
    var content = chatClient.prompt().messages(messages).user("another question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(3);
    var systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("instructions");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
}
"
    "@Test
@Test
void whenMessagesWithSystemMessageAndSystemText() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var chatClient = ChatClient.builder(this.chatModel).build();
    List<Message> messages = List.of(new SystemMessage("instructions"), new UserMessage("my question"));
    var content = chatClient.prompt().messages(messages).system("other instructions").user("another question").call().content();
    assertThat(content).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(4);
    var systemMessage = this.promptCaptor.getValue().getInstructions().get(2);
    assertThat(systemMessage.getText()).isEqualTo("other instructions");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
}
"

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/prompt/PromptTests.java
Tests:
    "@Test
@Test
void newApiPlaygroundTests() {

    String templateText = "Hello '{firstName}' '{lastName}' from Unix";
    PromptTemplate pt = new PromptTemplate(templateText);
    final Map<String, Object> model = new HashMap<>();
    model.put("firstName", "Nick");

    Assertions.assertThatThrownBy(() -> pt.render(model)).isInstanceOf(IllegalStateException.class).hasMessage("Not all template variables were replaced. Missing variable names are [lastName]");

    pt.add("lastName", "Park");
    String promptString = pt.render(model);
    assertThat(promptString).isEqualTo("Hello 'Nick' 'Park' from Unix");

    promptString = pt.render(model);
    assertThat(promptString).isEqualTo("Hello 'Nick' 'Park' from Unix");

    Prompt prompt = pt.create(model);
    assertThat(prompt.getContents()).isNotNull();
    assertThat(prompt.getInstructions()).isNotEmpty().hasSize(1);
    System.out.println(prompt.getContents());
    String systemTemplate = "You are a helpful assistant that translates {input_language} to {output_language}.";

    Map<String, Object> systemModel = new HashMap();
    systemModel.put("input_language", "English");
    systemModel.put("output_language", "French");
    String humanTemplate = "{text}";
    Map<String, Object> humanModel = new HashMap();
    humanModel.put("text", "I love programming");


    PromptTemplate promptTemplate = new SystemPromptTemplate(systemTemplate);
    Prompt systemPrompt = promptTemplate.create(systemModel);

    promptTemplate = new PromptTemplate(humanTemplate);

    Prompt humanPrompt = promptTemplate.create(humanModel);



}
"
    "@Test
@Test
public void testPromptCopy() {
    String template = "Hello, {name}! Your age is {age}.";
    Map<String, Object> model = new HashMap<>();
    model.put("name", "Alice");
    model.put("age", 30);
    PromptTemplate promptTemplate = new PromptTemplate(template, model);
    ChatOptions chatOptions = ChatOptions.builder().temperature(0.5).maxTokens(100).build();
    Prompt prompt = promptTemplate.create(model, chatOptions);
    Prompt copiedPrompt = prompt.copy();
    assertThat(prompt).isNotSameAs(copiedPrompt);
    assertThat(prompt.getOptions()).isNotSameAs(copiedPrompt.getOptions());
    assertThat(prompt.getInstructions()).isNotSameAs(copiedPrompt.getInstructions());
}
"

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/chat/client/ChatClientAdvisorTests.java
Tests:
    "@Test
@Test
public void promptChatMemory() {
    var builder = ChatResponseMetadata.builder().id("124").usage(new MessageAggregator.DefaultUsage(1, 2, 3)).model("gpt4o").keyValue("created", 0L).keyValue("system-fingerprint", "john doe");
    ChatResponseMetadata chatResponseMetadata = builder.build();
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("Hello John"))), chatResponseMetadata)).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("Your name is John"))), chatResponseMetadata));
    ChatMemory chatMemory = new InMemoryChatMemory();
    var chatClient = ChatClient.builder(this.chatModel).defaultSystem("Default system text.").defaultAdvisors(new PromptChatMemoryAdvisor(chatMemory)).build();
    ChatResponse chatResponse = chatClient.prompt().user("my name is John").call().chatResponse();
    String content = chatResponse.getResult().getOutput().getText();
    assertThat(content).isEqualTo("Hello John");
    Message systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualToIgnoringWhitespace("""
        Default system text.

        Use the conversation memory from the MEMORY section to provide accurate answers.

        ---------------------
        MEMORY:
        ---------------------
        """);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    Message userMessage = this.promptCaptor.getValue().getInstructions().get(1);
    assertThat(userMessage.getText()).isEqualToIgnoringWhitespace("my name is John");
    content = chatClient.prompt().user("What is my name?").call().content();
    assertThat(content).isEqualTo("Your name is John");
    systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualToIgnoringWhitespace("""
        Default system text.

        Use the conversation memory from the MEMORY section to provide accurate answers.

        ---------------------
        MEMORY:
        USER:my name is John
        ASSISTANT:Hello John
        ---------------------
        """);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    userMessage = this.promptCaptor.getValue().getInstructions().get(1);
    assertThat(userMessage.getText()).isEqualToIgnoringWhitespace("What is my name?");
}
"
    "@Test
@Test
public void streamingPromptChatMemory() {
    given(this.chatModel.stream(this.promptCaptor.capture())).willReturn(Flux.generate(() -> new ChatResponse(List.of(new Generation(new AssistantMessage("Hello John")))), (state, sink) -> {
        sink.next(state);
        sink.complete();
        return state;
    })).willReturn(Flux.generate(() -> new ChatResponse(List.of(new Generation(new AssistantMessage("Your name is John")))), (state, sink) -> {
        sink.next(state);
        sink.complete();
        return state;
    }));
    ChatMemory chatMemory = new InMemoryChatMemory();
    var chatClient = ChatClient.builder(this.chatModel).defaultSystem("Default system text.").defaultAdvisors(new PromptChatMemoryAdvisor(chatMemory)).build();
    var content = join(chatClient.prompt().user("my name is John").stream().content());
    assertThat(content).isEqualTo("Hello John");
    Message systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualToIgnoringWhitespace("""
        Default system text.

        Use the conversation memory from the MEMORY section to provide accurate answers.

        ---------------------
        MEMORY:
        ---------------------
        """);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    Message userMessage = this.promptCaptor.getValue().getInstructions().get(1);
    assertThat(userMessage.getText()).isEqualToIgnoringWhitespace("my name is John");
    content = join(chatClient.prompt().user("What is my name?").stream().content());
    assertThat(content).isEqualTo("Your name is John");
    systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualToIgnoringWhitespace("""
        Default system text.

        Use the conversation memory from the MEMORY section to provide accurate answers.

        ---------------------
        MEMORY:
        USER:my name is John
        ASSISTANT:Hello John
        ---------------------
        """);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    userMessage = this.promptCaptor.getValue().getInstructions().get(1);
    assertThat(userMessage.getText()).isEqualToIgnoringWhitespace("What is my name?");
}
"

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/chat/client/DefaultChatClientTests.java
Tests:
    "@Test
@Test
void whenSimplePromptThenChatResponse() {
    ChatModel chatModel = mock(ChatModel.class);
    ArgumentCaptor<Prompt> promptCaptor = ArgumentCaptor.forClass(Prompt.class);
    given(chatModel.call(promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    ChatClient chatClient = new DefaultChatClientBuilder(chatModel).build();
    DefaultChatClient.DefaultChatClientRequestSpec chatClientRequestSpec = (DefaultChatClient.DefaultChatClientRequestSpec) chatClient.prompt("my question");
    DefaultChatClient.DefaultCallResponseSpec spec = new DefaultChatClient.DefaultCallResponseSpec(chatClientRequestSpec);
    ChatResponse chatResponse = spec.chatResponse();
    assertThat(chatResponse).isNotNull();
    assertThat(chatResponse.getResult().getOutput().getText()).isEqualTo("response");
    Prompt actualPrompt = promptCaptor.getValue();
    assertThat(actualPrompt.getInstructions()).hasSize(1);
    assertThat(actualPrompt.getInstructions().get(0).getText()).isEqualTo("my question");
}
"
    "@Test
@Test
void whenFullPromptThenChatResponse() {
    ChatModel chatModel = mock(ChatModel.class);
    ArgumentCaptor<Prompt> promptCaptor = ArgumentCaptor.forClass(Prompt.class);
    given(chatModel.call(promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    ChatClient chatClient = new DefaultChatClientBuilder(chatModel).build();
    Prompt prompt = new Prompt(new SystemMessage("instructions"), new UserMessage("my question"));
    DefaultChatClient.DefaultChatClientRequestSpec chatClientRequestSpec = (DefaultChatClient.DefaultChatClientRequestSpec) chatClient.prompt(prompt);
    DefaultChatClient.DefaultCallResponseSpec spec = new DefaultChatClient.DefaultCallResponseSpec(chatClientRequestSpec);
    ChatResponse chatResponse = spec.chatResponse();
    assertThat(chatResponse).isNotNull();
    assertThat(chatResponse.getResult().getOutput().getText()).isEqualTo("response");
    Prompt actualPrompt = promptCaptor.getValue();
    assertThat(actualPrompt.getInstructions()).hasSize(2);
    assertThat(actualPrompt.getInstructions().get(0).getText()).isEqualTo("instructions");
    assertThat(actualPrompt.getInstructions().get(1).getText()).isEqualTo("my question");
}
"
    "@Test
@Test
void whenPromptAndUserTextThenChatResponse() {
    ChatModel chatModel = mock(ChatModel.class);
    ArgumentCaptor<Prompt> promptCaptor = ArgumentCaptor.forClass(Prompt.class);
    given(chatModel.call(promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    ChatClient chatClient = new DefaultChatClientBuilder(chatModel).build();
    Prompt prompt = new Prompt(new SystemMessage("instructions"), new UserMessage("my question"));
    DefaultChatClient.DefaultChatClientRequestSpec chatClientRequestSpec = (DefaultChatClient.DefaultChatClientRequestSpec) chatClient.prompt(prompt).user("another question");
    DefaultChatClient.DefaultCallResponseSpec spec = new DefaultChatClient.DefaultCallResponseSpec(chatClientRequestSpec);
    ChatResponse chatResponse = spec.chatResponse();
    assertThat(chatResponse).isNotNull();
    assertThat(chatResponse.getResult().getOutput().getText()).isEqualTo("response");
    Prompt actualPrompt = promptCaptor.getValue();
    assertThat(actualPrompt.getInstructions()).hasSize(3);
    assertThat(actualPrompt.getInstructions().get(0).getText()).isEqualTo("instructions");
    assertThat(actualPrompt.getInstructions().get(1).getText()).isEqualTo("my question");
    assertThat(actualPrompt.getInstructions().get(2).getText()).isEqualTo("another question");
}
"
    "@Test
@Test
void whenUserTextAndMessagesThenChatResponse() {
    ChatModel chatModel = mock(ChatModel.class);
    ArgumentCaptor<Prompt> promptCaptor = ArgumentCaptor.forClass(Prompt.class);
    given(chatModel.call(promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    ChatClient chatClient = new DefaultChatClientBuilder(chatModel).build();
    List<Message> messages = List.of(new SystemMessage("instructions"), new UserMessage("my question"));
    DefaultChatClient.DefaultChatClientRequestSpec chatClientRequestSpec = (DefaultChatClient.DefaultChatClientRequestSpec) chatClient.prompt().user("another question").messages(messages);
    DefaultChatClient.DefaultCallResponseSpec spec = new DefaultChatClient.DefaultCallResponseSpec(chatClientRequestSpec);
    ChatResponse chatResponse = spec.chatResponse();
    assertThat(chatResponse).isNotNull();
    assertThat(chatResponse.getResult().getOutput().getText()).isEqualTo("response");
    Prompt actualPrompt = promptCaptor.getValue();
    assertThat(actualPrompt.getInstructions()).hasSize(3);
    assertThat(actualPrompt.getInstructions().get(0).getText()).isEqualTo("instructions");
    assertThat(actualPrompt.getInstructions().get(1).getText()).isEqualTo("my question");
    assertThat(actualPrompt.getInstructions().get(2).getText()).isEqualTo("another question");
}
"
    "@Test
@Test
void whenSimplePromptThenFluxChatResponse() {
    ChatModel chatModel = mock(ChatModel.class);
    ArgumentCaptor<Prompt> promptCaptor = ArgumentCaptor.forClass(Prompt.class);
    given(chatModel.stream(promptCaptor.capture())).willReturn(Flux.just(new ChatResponse(List.of(new Generation(new AssistantMessage("response"))))));
    ChatClient chatClient = new DefaultChatClientBuilder(chatModel).build();
    DefaultChatClient.DefaultChatClientRequestSpec chatClientRequestSpec = (DefaultChatClient.DefaultChatClientRequestSpec) chatClient.prompt("my question");
    DefaultChatClient.DefaultStreamResponseSpec spec = new DefaultChatClient.DefaultStreamResponseSpec(chatClientRequestSpec);
    ChatResponse chatResponse = spec.chatResponse().blockLast();
    assertThat(chatResponse).isNotNull();
    assertThat(chatResponse.getResult().getOutput().getText()).isEqualTo("response");
    Prompt actualPrompt = promptCaptor.getValue();
    assertThat(actualPrompt.getInstructions()).hasSize(1);
    assertThat(actualPrompt.getInstructions().get(0).getText()).isEqualTo("my question");
}
"
    "@Test
@Test
void whenFullPromptThenFluxChatResponse() {
    ChatModel chatModel = mock(ChatModel.class);
    ArgumentCaptor<Prompt> promptCaptor = ArgumentCaptor.forClass(Prompt.class);
    given(chatModel.stream(promptCaptor.capture())).willReturn(Flux.just(new ChatResponse(List.of(new Generation(new AssistantMessage("response"))))));
    ChatClient chatClient = new DefaultChatClientBuilder(chatModel).build();
    Prompt prompt = new Prompt(new SystemMessage("instructions"), new UserMessage("my question"));
    DefaultChatClient.DefaultChatClientRequestSpec chatClientRequestSpec = (DefaultChatClient.DefaultChatClientRequestSpec) chatClient.prompt(prompt);
    DefaultChatClient.DefaultStreamResponseSpec spec = new DefaultChatClient.DefaultStreamResponseSpec(chatClientRequestSpec);
    ChatResponse chatResponse = spec.chatResponse().blockLast();
    assertThat(chatResponse).isNotNull();
    assertThat(chatResponse.getResult().getOutput().getText()).isEqualTo("response");
    Prompt actualPrompt = promptCaptor.getValue();
    assertThat(actualPrompt.getInstructions()).hasSize(2);
    assertThat(actualPrompt.getInstructions().get(0).getText()).isEqualTo("instructions");
    assertThat(actualPrompt.getInstructions().get(1).getText()).isEqualTo("my question");
}
"
    "@Test
@Test
void whenPromptAndUserTextThenFluxChatResponse() {
    ChatModel chatModel = mock(ChatModel.class);
    ArgumentCaptor<Prompt> promptCaptor = ArgumentCaptor.forClass(Prompt.class);
    given(chatModel.stream(promptCaptor.capture())).willReturn(Flux.just(new ChatResponse(List.of(new Generation(new AssistantMessage("response"))))));
    ChatClient chatClient = new DefaultChatClientBuilder(chatModel).build();
    Prompt prompt = new Prompt(new SystemMessage("instructions"), new UserMessage("my question"));
    DefaultChatClient.DefaultChatClientRequestSpec chatClientRequestSpec = (DefaultChatClient.DefaultChatClientRequestSpec) chatClient.prompt(prompt).user("another question");
    DefaultChatClient.DefaultStreamResponseSpec spec = new DefaultChatClient.DefaultStreamResponseSpec(chatClientRequestSpec);
    ChatResponse chatResponse = spec.chatResponse().blockLast();
    assertThat(chatResponse).isNotNull();
    assertThat(chatResponse.getResult().getOutput().getText()).isEqualTo("response");
    Prompt actualPrompt = promptCaptor.getValue();
    assertThat(actualPrompt.getInstructions()).hasSize(3);
    assertThat(actualPrompt.getInstructions().get(0).getText()).isEqualTo("instructions");
    assertThat(actualPrompt.getInstructions().get(1).getText()).isEqualTo("my question");
    assertThat(actualPrompt.getInstructions().get(2).getText()).isEqualTo("another question");
}
"
    "@Test
@Test
void whenUserTextAndMessagesThenFluxChatResponse() {
    ChatModel chatModel = mock(ChatModel.class);
    ArgumentCaptor<Prompt> promptCaptor = ArgumentCaptor.forClass(Prompt.class);
    given(chatModel.stream(promptCaptor.capture())).willReturn(Flux.just(new ChatResponse(List.of(new Generation(new AssistantMessage("response"))))));
    ChatClient chatClient = new DefaultChatClientBuilder(chatModel).build();
    List<Message> messages = List.of(new SystemMessage("instructions"), new UserMessage("my question"));
    DefaultChatClient.DefaultChatClientRequestSpec chatClientRequestSpec = (DefaultChatClient.DefaultChatClientRequestSpec) chatClient.prompt().user("another question").messages(messages);
    DefaultChatClient.DefaultStreamResponseSpec spec = new DefaultChatClient.DefaultStreamResponseSpec(chatClientRequestSpec);
    ChatResponse chatResponse = spec.chatResponse().blockLast();
    assertThat(chatResponse).isNotNull();
    assertThat(chatResponse.getResult().getOutput().getText()).isEqualTo("response");
    Prompt actualPrompt = promptCaptor.getValue();
    assertThat(actualPrompt.getInstructions()).hasSize(3);
    assertThat(actualPrompt.getInstructions().get(0).getText()).isEqualTo("instructions");
    assertThat(actualPrompt.getInstructions().get(1).getText()).isEqualTo("my question");
    assertThat(actualPrompt.getInstructions().get(2).getText()).isEqualTo("another question");
}
"

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/chat/client/ChatClientResponseEntityTests.java
Tests:
    "@Test
@Test
public void responseEntityTest() {
    ChatResponseMetadata metadata = ChatResponseMetadata.builder().keyValue("key1", "value1").build();
    var chatResponse = new ChatResponse(List.of(new Generation(new AssistantMessage("""
        {"name":"John", "age":30}
        """))), metadata);
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(chatResponse);
    ResponseEntity<ChatResponse, MyBean> responseEntity = ChatClient.builder(this.chatModel).build().prompt().user("Tell me about John").call().responseEntity(MyBean.class);
    assertThat(responseEntity.getResponse()).isEqualTo(chatResponse);
    assertThat(responseEntity.getResponse().getMetadata().get("key1").toString()).isEqualTo("value1");
    assertThat(responseEntity.getEntity()).isEqualTo(new MyBean("John", 30));
    Message userMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).contains("Tell me about John");
}
"
    "@Test
@Test
public void parametrizedResponseEntityTest() {
    var chatResponse = new ChatResponse(List.of(new Generation(new AssistantMessage("""
        [
        	{"name":"Max", "age":10},
        	{"name":"Adi", "age":13}
        ]
        """))));
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(chatResponse);
    ResponseEntity<ChatResponse, List<MyBean>> responseEntity = ChatClient.builder(this.chatModel).build().prompt().user("Tell me about them").call().responseEntity(new ParameterizedTypeReference<List<MyBean>>() {
    });
    assertThat(responseEntity.getResponse()).isEqualTo(chatResponse);
    assertThat(responseEntity.getEntity().get(0)).isEqualTo(new MyBean("Max", 10));
    assertThat(responseEntity.getEntity().get(1)).isEqualTo(new MyBean("Adi", 13));
    Message userMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).contains("Tell me about them");
}
"
    "@Test
@Test
public void customSoCResponseEntityTest() {
    var chatResponse = new ChatResponse(List.of(new Generation(new AssistantMessage("""
        	{"name":"Max", "age":10},
        """))));
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(chatResponse);
    ResponseEntity<ChatResponse, Map<String, Object>> responseEntity = ChatClient.builder(this.chatModel).build().prompt().user("Tell me about Max").call().responseEntity(new MapOutputConverter());
    assertThat(responseEntity.getResponse()).isEqualTo(chatResponse);
    assertThat(responseEntity.getEntity().get("name")).isEqualTo("Max");
    assertThat(responseEntity.getEntity().get("age")).isEqualTo(10);
    Message userMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).contains("Tell me about Max");
}
"

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/chat/client/advisor/QuestionAnswerAdvisorTests.java
Tests:
    "@Test
@Test
public void qaAdvisorWithDynamicFilterExpressions() {

    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("Your answer is ZXY"))), ChatResponseMetadata.builder().id("678").model("model1").keyValue("key6", "value6").metadata(Map.of("key1", "value1")).promptMetadata(null).rateLimit(new RateLimit() {

        @Override
        public Long getRequestsLimit() {
            return 5L;
        }

        @Override
        public Long getRequestsRemaining() {
            return 6L;
        }

        @Override
        public Duration getRequestsReset() {
            return Duration.ofSeconds(7);
        }

        @Override
        public Long getTokensLimit() {
            return 8L;
        }

        @Override
        public Long getTokensRemaining() {
            return 8L;
        }

        @Override
        public Duration getTokensReset() {
            return Duration.ofSeconds(9);
        }
    }).usage(new DefaultUsage(6, 7)).build()));

    given(this.vectorStore.similaritySearch(this.vectorSearchCaptor.capture())).willReturn(List.of(new Document("doc1"), new Document("doc2")));
    var qaAdvisor = new QuestionAnswerAdvisor(this.vectorStore, SearchRequest.builder().similarityThreshold(0.99d).topK(6).build());
    var chatClient = ChatClient.builder(this.chatModel).defaultSystem("Default system text.").defaultAdvisors(qaAdvisor).build();

    var response = chatClient.prompt().user("Please answer my question XYZ").advisors(a -> a.param(QuestionAnswerAdvisor.FILTER_EXPRESSION, "type == 'Spring'")).call().chatResponse();


    assertThat(response.getMetadata().getModel()).isEqualTo("model1");
    assertThat(response.getMetadata().getId()).isEqualTo("678");
    assertThat(response.getMetadata().getRateLimit().getRequestsLimit()).isEqualTo(5L);
    assertThat(response.getMetadata().getRateLimit().getRequestsRemaining()).isEqualTo(6L);
    assertThat(response.getMetadata().getRateLimit().getRequestsReset()).isEqualTo(Duration.ofSeconds(7));
    assertThat(response.getMetadata().getRateLimit().getTokensLimit()).isEqualTo(8L);
    assertThat(response.getMetadata().getRateLimit().getTokensRemaining()).isEqualTo(8L);
    assertThat(response.getMetadata().getRateLimit().getTokensReset()).isEqualTo(Duration.ofSeconds(9));
    assertThat(response.getMetadata().getUsage().getPromptTokens()).isEqualTo(6L);
    assertThat(response.getMetadata().getUsage().getCompletionTokens()).isEqualTo(7L);
    assertThat(response.getMetadata().getUsage().getTotalTokens()).isEqualTo(6L + 7L);
    assertThat(response.getMetadata().get("key6").toString()).isEqualTo("value6");
    assertThat(response.getMetadata().get("key1").toString()).isEqualTo("value1");
    String content = response.getResult().getOutput().getText();
    assertThat(content).isEqualTo("Your answer is ZXY");
    Message systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    System.out.println(systemMessage.getText());
    assertThat(systemMessage.getText()).isEqualToIgnoringWhitespace("""
        Default system text.
        """);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    Message userMessage = this.promptCaptor.getValue().getInstructions().get(1);
    assertThat(userMessage.getText()).isEqualToIgnoringWhitespace("""
        Please answer my question XYZ
        Context information is below, surrounded by ---------------------

        ---------------------
        doc1
        doc2
        ---------------------

        Given the context and provided history information and not prior knowledge,
        reply to the user comment. If the answer is not in the context, inform
        the user that you can't answer the question.
        """);
    assertThat(this.vectorSearchCaptor.getValue().getFilterExpression()).isEqualTo(new FilterExpressionBuilder().eq("type", "Spring").build());
    assertThat(this.vectorSearchCaptor.getValue().getSimilarityThreshold()).isEqualTo(0.99d);
    assertThat(this.vectorSearchCaptor.getValue().getTopK()).isEqualTo(6);
}
"
    "@Test
@Test
public void qaAdvisorTakesUserTextParametersIntoAccountForSimilaritySearch() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("Your answer is ZXY"))), ChatResponseMetadata.builder().build()));
    given(this.vectorStore.similaritySearch(this.vectorSearchCaptor.capture())).willReturn(List.of(new Document("doc1"), new Document("doc2")));
    var chatClient = ChatClient.builder(this.chatModel).build();
    var qaAdvisor = new QuestionAnswerAdvisor(this.vectorStore, SearchRequest.builder().build());
    var userTextTemplate = "Please answer my question {question}";

    chatClient.prompt().user(u -> u.text(userTextTemplate).param("question", "XYZ")).advisors(qaAdvisor).call().chatResponse();

    var expectedQuery = "Please answer my question XYZ";
    var userPrompt = this.promptCaptor.getValue().getInstructions().get(0).getText();
    assertThat(userPrompt).doesNotContain(userTextTemplate);
    assertThat(userPrompt).contains(expectedQuery);
    assertThat(this.vectorSearchCaptor.getValue().getQuery()).isEqualTo(expectedQuery);
}
"
    "@Test
@Test
public void qaAdvisorTakesUserParameterizedUserMessagesIntoAccountForSimilaritySearch() {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("Your answer is ZXY"))), ChatResponseMetadata.builder().build()));
    given(this.vectorStore.similaritySearch(this.vectorSearchCaptor.capture())).willReturn(List.of(new Document("doc1"), new Document("doc2")));
    var chatClient = ChatClient.builder(this.chatModel).build();
    var qaAdvisor = new QuestionAnswerAdvisor(this.vectorStore, SearchRequest.builder().build());
    var userTextTemplate = "Please answer my question {question}";
    var userPromptTemplate = new PromptTemplate(userTextTemplate, Map.of("question", "XYZ"));
    var userMessage = userPromptTemplate.createMessage();

    chatClient.prompt(new Prompt(userMessage)).advisors(qaAdvisor).call().chatResponse();

    var expectedQuery = "Please answer my question XYZ";
    var userPrompt = this.promptCaptor.getValue().getInstructions().get(0).getText();
    assertThat(userPrompt).doesNotContain(userTextTemplate);
    assertThat(userPrompt).contains(expectedQuery);
    assertThat(this.vectorSearchCaptor.getValue().getQuery()).isEqualTo(expectedQuery);
}
"
Scenario 1: Verify retrieval of messages when messages list is initialized with content.

Details:
  TestName: retrieveMessagesFromInitializedList.
  Description: Verify that the method `getInstructions` returns the initialized list of `ImageMessage` objects when the `messages` field is populated with data. This test checks that the method correctly returns the list field values associated with the `messages` property.

Execution:
  Arrange: Initialize the `messages` field in the `ImagePrompt` class with a list of `ImageMessage` objects.
  Act: Invoke the `getInstructions` method.
  Assert: Verify the returned list matches the initialized values in the `messages` field, ensuring correct list retrieval.

Validation:
  Verify that the method returns the `messages` field directly without modification or transformation. This ensures the correctness and consistency of list data handling for properly populated scenarios in the application.

---

Scenario 2: Verify retrieval of messages when messages list is null.

Details:
  TestName: retrieveNullMessagesReturnsEmptyList.
  Description: Verify that the method `getInstructions` handles the scenario when the `messages` field is null by returning an empty list or a null reference safely.

Execution:
  Arrange: Ensure the `messages` field in the `ImagePrompt` class is null.
  Act: Invoke the `getInstructions` method.
  Assert: Verify whether the returned list is either null or an empty list, based on the implementation specifics.

Validation:
  Ensure the method handles null field values gracefully without causing runtime exceptions. Proper handling of null scenarios is critical for application stability across various feature implementations.

---

Scenario 3: Verify immutability of returned messages list when the underlying field is modified.

Details:
  TestName: maintainIntegrityAgainstModifications.
  Description: Verify that the returned list from `getInstructions` remains consistent and unaffected by modifications to the `messages` field after retrieval.

Execution:
  Arrange: Populate the `messages` field with a list of `ImageMessage` objects in `ImagePrompt`. Retrieve the list using `getInstructions`.
  Act: Modify the `messages` field (e.g., adding or removing elements).
  Assert: Verify that the previously retrieved list remains unaffected by modifications to the `messages` field.

Validation:
  Confirm the integrity of the returned list as independent from the underlying field after retrieval. This test ensures that modifications in `ImagePrompt` don’t unintentionally impact references accessed outside the class.

---

Scenario 4: Test retrieval of messages when messages list has duplicate entries.

Details:
  TestName: retrieveDuplicateEntriesCorrectly.
  Description: Ensure the `getInstructions` method correctly handles scenarios where the `messages` list contains duplicate `ImageMessage` entries.

Execution:
  Arrange: Populate the `messages` field in `ImagePrompt` with a list containing duplicate `ImageMessage` objects.
  Act: Invoke the `getInstructions` method.
  Assert: Verify that all duplicate entries in the `messages` list are accurately returned by the method.

Validation:
  Verify that the duplicate entries aren’t filtered out or altered during the retrieval process, ensuring the correctness of the list data irrespective of internal redundancy in entries.

---

Scenario 5: Test retrieval of an empty messages list.

Details:
  TestName: retrieveInstructionsFromEmptyList.
  Description: Verify that `getInstructions` correctly handles scenarios where the `messages` field is initialized as an empty list without elements.

Execution:
  Arrange: Initialize the `messages` field in the `ImagePrompt` class as an empty list.
  Act: Invoke the `getInstructions` method.
  Assert: Verify that the returned list is empty.

Validation:
  Check the method against scenarios where an empty list is initialized. Ensuring proper handling of boundary cases like empty collections is essential for application reliability.

---

Scenario 6: Verify interaction between messages and image model options on retrieval.

Details:
  TestName: verifyMessageInteractionWithImageOptions.
  Description: Verify whether any unintended dependencies exist between the `messages` field retrieval through `getInstructions` and the `imageModelOptions` field.

Execution:
  Arrange: Set both `messages` (initialized list) and `imageModelOptions` (null or populated object) in the `ImagePrompt` class.
  Act: Invoke the `getInstructions` method.
  Assert: Verify that the returned `messages` list is unaffected by the value or state of the `imageModelOptions` field.

Validation:
  Confirm that `getInstructions` works independently without unintended dependencies or coupling with other fields. This ensures encapsulation and avoids implementation bugs.

---

Scenario 7: Check the performance of `getInstructions` with a large list.

Details:
  TestName: performanceWithLargeMessagesList.
  Description: Evaluate the performance and correctness of `getInstructions` when the `messages` field contains a very large list of `ImageMessage` objects.

Execution:
  Arrange: Populate the `messages` field with a large list (e.g., 10,000+ elements).
  Act: Invoke the `getInstructions` method.
  Assert: Verify that all elements are retrieved correctly and measure the execution speed to ensure performance viability.

Validation:
  Validate that the method can handle large datasets efficiently without runtime delays or memory-related issues. Confirm its suitability for high-load scenarios.

---

Scenario 8: Test interaction between `getInstructions` and the `equals` method.

Details:
  TestName: validateInteractionWithEqualsMethod.
  Description: Verify consistency between the result of `getInstructions` and the internal logic of the `equals(Object)` method for the `messages` list comparison.

Execution:
  Arrange: Populate the `messages` field with a list in two `ImagePrompt` objects.
  Act: Call `getInstructions()` on both objects and check their equality using the `equals` method.
  Assert: Verify that equality comparisons align with the underlying list content correctly.

Validation:
  Ensure synchronization between field value retrieval via `getInstructions` and object-level equality. Validate that list content consistency aligns across related behaviors.

---

Scenario 9: Test component string formatting of `getInstructions`.

Details:
  TestName: validateStringRepresentationForInstructions.
  Description: Verify that the retrieved values from `getInstructions` are accurately represented in the `toString` method implementation.

Execution:
  Arrange: Populate the `messages` list with values and invoke both `getInstructions` and `toString`.
  Act: Invoke the `ImagePrompt` class’s `toString` method.
  Assert: Validate that the string output includes the expected list content.

Validation:
  Validate the proper formatting and representation of underlying fields in string conversions. This confirms accurate readability of data for debugging or logging purposes.

---

Scenario 10: Test retrieval of a messages list containing null entries.

Details:
  TestName: retrieveMessagesWithNullValues.
  Description: Ensure that `getInstructions` correctly handles a `messages` list that includes null elements without runtime errors or unintended behaviors.

Execution:
  Arrange: Populate the `messages` field with a list containing null and non-null `ImageMessage` entries.
  Act: Invoke the `getInstructions` method.
  Assert: Verify that null values in the `messages` list are correctly returned as part of the list.

Validation:
  Ensure the method handles and reflects null values within the list gracefully. Validate consistency in tangible user interface or API layer scenarios requiring explicit null handling.

*/

// ********RoostGPT********

package org.springframework.ai.image;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import java.util.Collections;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.*;
import java.util.Objects;
import org.springframework.ai.model.ModelRequest;

public class ImagePromptGetInstructionsTest {

	@Test
	@Tag("valid")
	public void retrieveMessagesFromInitializedList() {
		List<ImageMessage> initializedMessages = List.of(new ImageMessage("Message1"), new ImageMessage("Message2"));
		ImagePrompt imagePrompt = new ImagePrompt(initializedMessages);
		List<ImageMessage> result = imagePrompt.getInstructions();
		assertEquals(initializedMessages, result, "The returned list should match the initialized messages.");
	}

	@Test
	@Tag("boundary")
	public void retrieveNullMessagesReturnsEmptyList() {
		ImagePrompt imagePrompt = new ImagePrompt((List<ImageMessage>) null);
		List<ImageMessage> result = imagePrompt.getInstructions();
		assertTrue(result == null || result.isEmpty(), "The returned list should be null or empty.");
	}

	@Test
	@Tag("valid")
	public void maintainIntegrityAgainstModifications() {
		List<ImageMessage> initialMessages = List.of(new ImageMessage("Message1"));
		ImagePrompt imagePrompt = new ImagePrompt(initialMessages);
		List<ImageMessage> result = imagePrompt.getInstructions();
		initialMessages.add(new ImageMessage("NewMessage")); // Modifying the original
																// list
		assertEquals(1, result.size(),
				"The retrieved list should remain unaffected by modifications to the original list.");
	}

	@Test
	@Tag("valid")
	public void retrieveDuplicateEntriesCorrectly() {
		ImageMessage duplicateMessage = new ImageMessage("DuplicateMessage");
		List<ImageMessage> initializedMessages = List.of(duplicateMessage, duplicateMessage);
		ImagePrompt imagePrompt = new ImagePrompt(initializedMessages);
		List<ImageMessage> result = imagePrompt.getInstructions();
		assertEquals(initializedMessages, result, "The returned list should include duplicate entries.");
	}

	@Test
	@Tag("boundary")
	public void retrieveInstructionsFromEmptyList() {
		List<ImageMessage> emptyList = Collections.emptyList();
		ImagePrompt imagePrompt = new ImagePrompt(emptyList);
		List<ImageMessage> result = imagePrompt.getInstructions();
		assertTrue(result.isEmpty(), "The returned list should be empty.");
	}

	@Test
	@Tag("integration")
	public void verifyMessageInteractionWithImageOptions() {
		List<ImageMessage> initializedMessages = List.of(new ImageMessage("Message1"));
		ImageOptions options = null; // TODO: Replace with valid ImageOptions instance
		ImagePrompt imagePrompt = new ImagePrompt(initializedMessages, options);
		List<ImageMessage> result = imagePrompt.getInstructions();
		assertEquals(initializedMessages, result,
				"The returned list should not be affected by the imageModelOptions field value.");
	}

	@Test
	@Tag("valid")
	public void performanceWithLargeMessagesList() {
		// TODO: Replace X with a large number for testing
		List<ImageMessage> largeMessages = Collections.nCopies(10000, new ImageMessage("Message"));
		ImagePrompt imagePrompt = new ImagePrompt(largeMessages);
		List<ImageMessage> result = imagePrompt.getInstructions();
		assertEquals(largeMessages, result, "The method should handle large lists efficiently.");
	}

	@Test
	@Tag("integration")
	public void validateInteractionWithEqualsMethod() {
		List<ImageMessage> messages1 = List.of(new ImageMessage("Message1"));
		List<ImageMessage> messages2 = List.of(new ImageMessage("Message1"));
		ImagePrompt prompt1 = new ImagePrompt(messages1);
		ImagePrompt prompt2 = new ImagePrompt(messages2);
		boolean areEqual = prompt1.equals(prompt2);
		assertTrue(areEqual, "Equality comparisons should match the content of the messages field.");
	}

	@Test
	@Tag("integration")
	public void validateStringRepresentationForInstructions() {
		List<ImageMessage> initializedMessages = List.of(new ImageMessage("Message1"));
		ImagePrompt imagePrompt = new ImagePrompt(initializedMessages);
		String stringRepresentation = imagePrompt.toString();
		assertTrue(stringRepresentation.contains("Message1"),
				"The string representation should include messages content.");
	}

	@Test
	@Tag("boundary")
	public void retrieveMessagesWithNullValues() {
		List<ImageMessage> initializedMessages = List.of(new ImageMessage("Message1"), null);
		ImagePrompt imagePrompt = new ImagePrompt(initializedMessages);
		List<ImageMessage> result = imagePrompt.getInstructions();
		assertEquals(initializedMessages, result, "The retrieved list should include null values.");
	}

}