/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test single_test_file using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getCreated_fac686db21
ROOST_METHOD_SIG_HASH=getCreated_5e37bcb6e6


Scenario 1: Verify method retrieves the default value of 'created' when uninitialized

Details:
  TestName: getCreatedWhenUninitialized
  Description: This test validates the behavior of the getCreated() method when the 'created' field has not been explicitly assigned a value and retains its default state of null.

Execution:
  Arrange: Instantiate an object of the ImageResponseMetadata class. Do not assign any value to the 'created' field.
  Act: Call the getCreated() method on the instantiated object.
  Assert: Check if the method returns null.

Validation:
  The assertion verifies that the method correctly retrieves the default value of 'created' (null). This is significant because initializing fields to their default value is a key part of Java object behavior, and the method should reflect this appropriately.

*/

// ********RoostGPT********

package org.springframework.ai.image;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.springframework.ai.model.MutableResponseMetadata;

public class ImageResponseMetadataGetCreatedTest {

	@Tag("valid")
	@Test
	public void testGetCreatedWhenUninitialized() {
		// Arrange
		ImageResponseMetadata metadata = new ImageResponseMetadata();
		// Act
		Long created = metadata.getCreated();
		// Assert
		assertNotNull(created, "Created timestamp should not be null by default");
		assertTrue(created > 0, "Created timestamp should be a positive value");
	}

	@Tag("valid")
	@Test
	public void testGetCreatedWhenInitializedWithCustomTimestamp() {
		// Arrange
		Long customTimestamp = System.currentTimeMillis();
		ImageResponseMetadata metadata = new ImageResponseMetadata(customTimestamp);
		// Act
		Long created = metadata.getCreated();
		// Assert
		assertNotNull(created, "Created timestamp should not be null for initialized value");
		assertEquals(customTimestamp, created, "Created timestamp should match the provided custom timestamp");
	}

	@Tag("boundary")
	@Test
	public void testGetCreatedBoundaryTimestampValue() {
		// Arrange
		Long boundaryTimestamp = 0L; // Minimum valid boundary timestamp
		ImageResponseMetadata metadata = new ImageResponseMetadata(boundaryTimestamp);
		// Act
		Long created = metadata.getCreated();
		// Assert
		assertNotNull(created, "Created timestamp should not be null for boundary value");
		assertEquals(boundaryTimestamp, created, "Created timestamp should match the boundary value");
	}

	@Tag("valid")
	@Test
	public void testGetCreatedWhenUsingSystemGeneratedTimestamp() {
		// Arrange
		Long lowThreshold = System.currentTimeMillis();
		ImageResponseMetadata metadata = new ImageResponseMetadata();
		// Act
		Long created = metadata.getCreated();
		// Assert
		assertNotNull(created, "Created timestamp should not be null");
		assertTrue(created >= lowThreshold,
				"Generated timestamp should be equal to or greater than the current system time");
	}

	@Tag("boundary")
	@Test
	public void testGetCreatedWithMaxAllowedTimestamp() {
		// Arrange
		Long maxTimestamp = Long.MAX_VALUE; // TODO: Replace with the desired max
											// timestamp if needed
		ImageResponseMetadata metadata = new ImageResponseMetadata(maxTimestamp);
		// Act
		Long created = metadata.getCreated();
		// Assert
		assertNotNull(created, "Created timestamp should not be null for maximum allowed value");
		assertEquals(maxTimestamp, created, "Created timestamp should match the maximum allowed timestamp");
	}

}