/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test single_test_file using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=width_1289342d4b
ROOST_METHOD_SIG_HASH=width_02111d9ead

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/image/observation/DefaultImageModelObservationConventionTests.java
Tests:
    "@Test
@Test
void shouldHaveHighCardinalityKeyValuesWhenDefined() {
    ImageModelObservationContext observationContext = ImageModelObservationContext.builder().imagePrompt(generateImagePrompt()).provider("superprovider").requestOptions(ImageOptionsBuilder.builder().model("mistral").N(1).height(1080).width(1920).style("sketch").responseFormat("base64").build()).build();
    assertThat(this.observationConvention.getHighCardinalityKeyValues(observationContext)).contains(KeyValue.of(AiObservationAttributes.REQUEST_IMAGE_RESPONSE_FORMAT.value(), "base64"), KeyValue.of(AiObservationAttributes.REQUEST_IMAGE_SIZE.value(), "1920x1080"), KeyValue.of(AiObservationAttributes.REQUEST_IMAGE_STYLE.value(), "sketch"));
}
"
Scenario 1: Verify Setting a Valid Width Value Updates DefaultImageModelOptions

Details:
  TestName: setValidWidthUpdatesOptions.
  Description: Ensure that calling the `width(Integer width)` method correctly sets the width field in the private `DefaultImageModelOptions` instance when a valid value is passed. Verify that the updated field reflects the expected changes.

Execution:
  Arrange: Create an instance of `ImageOptionsBuilder` using its `builder()` method. Define a valid width value (e.g., 1920).
  Act: Call the `width(Integer width)` method on the `ImageOptionsBuilder` instance, passing the valid width value. Use the `build()` method to retrieve the updated `DefaultImageModelOptions` instance.
  Assert: Assert that the width in the resulting `DefaultImageModelOptions` object matches the input value of 1920.
Validation:
  Verify that `this.options.setWidth(width)` correctly updates the `width` field within the `DefaultImageModelOptions`. This confirms the integrity of the `width` method and its ability to modify the associated property when a valid parameter is provided.

---

Scenario 2: Test Handling of Null Width Value

Details:
  TestName: setNullWidthHandlesGracefully.
  Description: Ensure that calling the `width(Integer width)` method with a null value does not throw an exception and correctly updates the `DefaultImageModelOptions` instance.

Execution:
  Arrange: Create an instance of `ImageOptionsBuilder` using its `builder()` method.
  Act: Call the `width(Integer width)` method with a null value. Use the `build()` method to retrieve the updated `DefaultImageModelOptions` object.
  Assert: Assert that the width field in `DefaultImageModelOptions` is set to null.
Validation:
  Confirm that the `width(Integer width)` method gracefully handles null inputs, ensuring no runtime exceptions occur. This scenario reduces potential failures when dealing with edge case inputs.

---

Scenario 3: Behavior When Width Method Is Invoked Multiple Times

Details:
  TestName: multipleWidthCallsOverridePreviouslySetValues.
  Description: Ensure the latest call to the `width(Integer width)` method overrides the previously set width value.

Execution:
  Arrange: Create an instance of `ImageOptionsBuilder`. Make sequential calls to the width method with different values (e.g., 1280 and then 1080).
  Act: Call the `width(Integer width)` method on the `ImageOptionsBuilder` instance twice, with distinct parameters. Retrieve updated `DefaultImageModelOptions` using the `build()` method.
  Assert: Confirm that the width field matches the value passed in the last invocation (1080).
Validation:
  Validate that the method behaves as expected when called successively, ensuring subsequent calls overwrite earlier ones. This is crucial for predictability in the API design.

---

Scenario 4: Validate Integration of Width with Other Methods in ImageOptionsBuilder

Details:
  TestName: widthMethodIntegrationWithOtherProperties.
  Description: Verify that setting a width value alongside other `ImageOptionsBuilder` attributes results in a consistently updated `DefaultImageModelOptions`.

Execution:
  Arrange: Create an instance of `ImageOptionsBuilder`. Apply multiple methods (`model("testModel")` and `height(720)`) alongside `width(1280)`.
  Act: Call the `width(Integer width)` method, followed by other setters like `model()` and `height()`. Retrieve the `DefaultImageModelOptions` object using the `build()` method.
  Assert: Assert that all specified fields match the corresponding input values—width equals 1280, height equals 720, and model equals "testModel".
Validation:
  Validate holistic integration among multiple methods of `ImageOptionsBuilder` and ensure that the `width` method does not interfere with other field updates.

---

Scenario 5: Check Correct Object Reference Return Behavior

Details:
  TestName: widthMethodReturnsBuilderInstance.
  Description: Ensure that the `width(Integer width)` method correctly returns the instance of `ImageOptionsBuilder`, enabling method chaining.

Execution:
  Arrange: Create an instance of `ImageOptionsBuilder`.
  Act: Call the `width(Integer width)` method and evaluate the returned object reference using method chaining to call another setter.
  Assert: Assert that the returned reference allows further method chaining and updating fields (successfully call another setter like `height()`).
Validation:
  Confirm that `width(Integer width)` adheres to the fluent interface design pattern, allowing seamless chaining of multiple attributes on the builder.

---

Scenario 6: Test Large Input Values and Their Impact on Width

Details:
  TestName: setLargeWidthValueSuccessfully.
  Description: Ensure that providing a large width value (e.g., Integer.MAX_VALUE) is handled correctly, updating the `DefaultImageModelOptions` field without issues.

Execution:
  Arrange: Create an instance of `ImageOptionsBuilder`. Define a large width value (Integer.MAX_VALUE).
  Act: Call the `width(Integer width)` method, passing the large value. Retrieve the updated `DefaultImageModelOptions` object using the `build()` method.
  Assert: Assert that the width field in `DefaultImageModelOptions` is equal to Integer.MAX_VALUE.
Validation:
  Confirm that the method reliably handles extreme numeric input bounds like Integer.MAX_VALUE, ensuring system robustness against potential overflow errors.

---

Scenario 7: Verify Default Value Behavior in Width Field

Details:
  TestName: defaultWidthFieldWhenUnmodified.
  Description: Ensure the `width` field in `DefaultImageModelOptions` remains in its default unmodified state if the `width(Integer width)` method is never called.

Execution:
  Arrange: Create an instance of `ImageOptionsBuilder`.
  Act: Use the `build()` method directly without invoking `width(Integer width)` first.
  Assert: Assert that the width field in the `DefaultImageModelOptions` object is unmodified (likely null or some default value).
Validation:
  Verify that the method does not alter default behavior unless explicitly invoked, ensuring proper initial object state management.

---

Scenario 8: Minimal Width Value Test

Details:
  TestName: setMinimalWidthValueSuccessfully.
  Description: Ensure that setting the minimal width value (e.g., 1) updates the `DefaultImageModelOptions` object without errors.

Execution:
  Arrange: Create an instance of `ImageOptionsBuilder`.
  Act: Call the `width(Integer width)` method with a minimal value of 1. Retrieve the updated `DefaultImageModelOptions` object using the `build()` method.
  Assert: Assert that the width field in `DefaultImageModelOptions` equals 1.
Validation:
  Validate correct handling of the smallest possible width value, ensuring no issues in edge-case scenarios.

---

Scenario 9: Test Non-Integer Input Behavior

Details:
  TestName: nonIntegerWidthCompilationError.
  Description: Ensure the `width(Integer width)` method only accepts Integer inputs, causing a compilation failure when provided with incompatible types.

Execution:
  Arrange: Prepare to call the `width(Integer width)` method with a non-Integer input, such as a String or Float (e.g., "testWidth").
  Act: Attempt to compile code with the invalid argument.
  Assert: Confirm that the code fails to compile due to type mismatch.
Validation:
  Verify that compiler-level type enforcement ensures input validity, enhancing type safety and reducing runtime errors.


*/

// ********RoostGPT********

package org.springframework.ai.image;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;

class ImageOptionsBuilderWidthTest {

	@Test
	@Tag("valid")
	public void setValidWidthUpdatesOptions() {
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		int validWidth = 1920;
		ImageOptions options = builder.width(validWidth).build();
		assertEquals((Integer) validWidth, options.getWidth());
	}

	@Test
	@Tag("valid")
	public void setNullWidthHandlesGracefully() {
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		ImageOptions options = builder.width(null).build();
		assertNull(options.getWidth());
	}

	@Test
	@Tag("valid")
	public void multipleWidthCallsOverridePreviouslySetValues() {
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		int firstWidth = 1280;
		int secondWidth = 1080;
		ImageOptions options = builder.width(firstWidth).width(secondWidth).build();
		assertEquals((Integer) secondWidth, options.getWidth());
	}

	@Test
	@Tag("integration")
	public void widthMethodIntegrationWithOtherProperties() {
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		int width = 1280;
		int height = 720;
		String model = "testModel";
		ImageOptions options = builder.width(width).height(height).model(model).build();
		assertEquals((Integer) width, options.getWidth());
		assertEquals((Integer) height, options.getHeight());
		assertEquals(model, options.getModel());
	}

	@Test
	@Tag("valid")
	public void widthMethodReturnsBuilderInstance() {
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		assertNotNull(builder.width(1280).height(720));
	}

	@Test
	@Tag("boundary")
	public void setLargeWidthValueSuccessfully() {
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		int largeWidth = Integer.MAX_VALUE;
		ImageOptions options = builder.width(largeWidth).build();
		assertEquals((Integer) largeWidth, options.getWidth());
	}

	@Test
	@Tag("valid")
	public void defaultWidthFieldWhenUnmodified() {
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		ImageOptions options = builder.build();
		assertNull(options.getWidth());
	}

	@Test
	@Tag("boundary")
	public void setMinimalWidthValueSuccessfully() {
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		int minimalWidth = 1;
		ImageOptions options = builder.width(minimalWidth).build();
		assertEquals((Integer) minimalWidth, options.getWidth());
	}

	@Test
	@Tag("invalid")
	public void nonIntegerWidthCompilationError() {
		// TODO: Test is theoretical since compilation failure cannot be tested in runtime
		// Ensure using incompatible types like String or Float in method arguments causes
		// a compile-time error.
		// Example: builder.width("testWidth"); // Should fail compilation.
	}

}