/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test single_test_file using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=height_ad6428bfaf
ROOST_METHOD_SIG_HASH=height_cae928d398

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/image/observation/DefaultImageModelObservationConventionTests.java
Tests:
    "@Test
@Test
void shouldHaveHighCardinalityKeyValuesWhenDefined() {
    ImageModelObservationContext observationContext = ImageModelObservationContext.builder().imagePrompt(generateImagePrompt()).provider("superprovider").requestOptions(ImageOptionsBuilder.builder().model("mistral").N(1).height(1080).width(1920).style("sketch").responseFormat("base64").build()).build();
    assertThat(this.observationConvention.getHighCardinalityKeyValues(observationContext)).contains(KeyValue.of(AiObservationAttributes.REQUEST_IMAGE_RESPONSE_FORMAT.value(), "base64"), KeyValue.of(AiObservationAttributes.REQUEST_IMAGE_SIZE.value(), "1920x1080"), KeyValue.of(AiObservationAttributes.REQUEST_IMAGE_STYLE.value(), "sketch"));
}
"
Scenario 1: Verify the height method sets height successfully.

Details:
  TestName: heightSetsHeightSuccessfully
  Description: This test ensures that the `height` method successfully sets the height value in the nested `DefaultImageModelOptions` instance. It verifies that the value assigned to height is stored correctly.

Execution:
  Arrange:
    - Create an instance of `ImageOptionsBuilder` using the `builder` method.
    - Define an expected height value to be passed to the `height` method.

  Act:
    - Call the `height` method with the defined height value.
    - Retrieve the `DefaultImageModelOptions` object from the `ImageOptionsBuilder` via the `build` method and check the height field using its getter method (`getHeight`).

  Assert:
    - Validate that the height retrieved from the nested `DefaultImageModelOptions` matches the height value that was provided via the `height` method.

Validation:
  - This test aims to confirm that the `height` method correctly sets the height in the class. Accurate field assignments are critical to functional class behavior.

---

Scenario 2: Test the chaining functionality of the height method.

Details:
  TestName: heightMethodSupportsMethodChaining
  Description: Verify that the `height` method in `ImageOptionsBuilder` supports method chaining by returning an instance of `ImageOptionsBuilder`.

Execution:
  Arrange:
    - Create an instance of `ImageOptionsBuilder` using the `builder` method.

  Act:
    - Invoke the `height` method and check the returned object type.

  Assert:
    - Validate that the returned object is an instance of `ImageOptionsBuilder`.

Validation:
  - Method chaining allows for improved readability and usability of the builder class. Validating the chaining mechanism ensures the intended design pattern functions correctly.

---

Scenario 3: Verify the height method handles null height input.

Details:
  TestName: heightHandlesNullInput
  Description: This test verifies how the `height` method behaves when a `null` value is passed as its parameter. It ensures the system can handle null inputs without throwing unexpected errors.

Execution:
  Arrange:
    - Create an instance of `ImageOptionsBuilder` using the `builder` method.

  Act:
    - Call the `height` method with `null` as the parameter.
    - Retrieve the `DefaultImageModelOptions` object from `ImageOptionsBuilder` via the `build` method and check the height field using its getter method (`getHeight`).

  Assert:
    - Validate that the height retrieved is `null`.

Validation:
  - This test examines whether the system handles `null` values gracefully, ensuring a robust implementation of the `height` method.

---

Scenario 4: Check the height method handles boundary value inputs.

Details:
  TestName: heightHandlesBoundaryValues
  Description: This test validates whether the `height` method correctly handles boundary values for permissible parameter input, such as `Integer.MIN_VALUE` and `Integer.MAX_VALUE`.

Execution:
  Arrange:
    - Create an instance of `ImageOptionsBuilder` using the `builder` method.
    - Define test values for the boundary inputs: `Integer.MIN_VALUE` and `Integer.MAX_VALUE`.

  Act:
    - Call the `height` method with the boundary values separately.
    - Retrieve the `DefaultImageModelOptions` object from `ImageOptionsBuilder` via `build`, and check the height field using its getter method (`getHeight`) for each value.

  Assert:
    - Validate that the height field correctly reflects the boundary values assigned.

Validation:
  - Ensuring valid handling of extreme input values promotes reliability in edge-case scenarios critical to production systems.

---

Scenario 5: Ensure height method updates an existing height value.

Details:
  TestName: heightOverwritesExistingValue
  Description: Verify that invoking the `height` method will overwrite an already assigned height value in `DefaultImageModelOptions`.

Execution:
  Arrange:
    - Create an instance of `ImageOptionsBuilder` using the `builder` method.
    - Call the `height` method initially with a height value (e.g., 100).

  Act:
    - Update the height by invoking the `height` method again with a different value (e.g., 200).
    - Retrieve the `DefaultImageModelOptions` using the `build` method, and check the height field using its getter method (`getHeight`).

  Assert:
    - Validate that the height field reflects the latest value assigned (200).

Validation:
  - Ensuring a smooth update mechanism confirms the mutable behavior of the builder class, necessary for dynamically configuring object properties.

---

Scenario 6: Verify height method interaction with other builder methods.

Details:
  TestName: heightWorksWithOtherBuilderMethods
  Description: This test evaluates whether the `height` method functions correctly in conjunction with other fluent builder methods, and whether method chaining retains accuracy across multiple calls.

Execution:
  Arrange:
    - Create an instance of `ImageOptionsBuilder` using the `builder` method.
    - Call other builder methods (`width`, `model`) before and after invoking `height`.

  Act:
    - Use the `height` method to set a value and subsequently retrieve the `DefaultImageModelOptions` instance using `build`.

  Assert:
    - Validate that each property, including height, matches the values assigned during chained calls.

Validation:
  - Cohesion across builder methods ensures the class design supports seamless configuration of related attributes.

---

Scenario 7: Ensure height method adheres to immutability of options variable.

Details:
  TestName: heightUpdatesWithinImmutability
  Description: Verify that the `height` method correctly updates the height field in the `DefaultImageModelOptions` object without modifying the immutable `options` variable itself.

Execution:
  Arrange:
    - Retrieve and store a reference to the `options` object from an instance of `ImageOptionsBuilder`.

  Act:
    - Invoke the `height` method with a specific value (e.g., 120).
    - Retrieve the height field via the `build` method and compare immutability of the parent `options` variable.

  Assert:
    - Validate that the `options` variable remains immutable. Changes apply only within encapsulated fields.

Validation:
  - Maintaining immutability prevents external code from inadvertently altering the state of the parent options instance.

*/

// ********RoostGPT********

package org.springframework.ai.image;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;

class ImageOptionsBuilderHeightTest {

	@Test
	@Tag("valid")
	public void heightSetsHeightSuccessfully() {
		// Arrange
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		Integer expectedHeight = 150; // TODO: Change the value if needed
		// Act
		builder.height(expectedHeight);
		Integer actualHeight = builder.build().getHeight();
		// Assert
		assertEquals((Integer) expectedHeight, actualHeight, "Height should match the expected value.");
	}

	@Test
	@Tag("valid")
	public void heightMethodSupportsMethodChaining() {
		// Arrange
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		// Act
		ImageOptionsBuilder returnedBuilder = builder.height(120);
		// Assert
		assertTrue(returnedBuilder instanceof ImageOptionsBuilder, "Height method should support method chaining.");
	}

	@Test
	@Tag("invalid")
	public void heightHandlesNullInput() {
		// Arrange
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		// Act
		builder.height(null);
		Integer actualHeight = builder.build().getHeight();
		// Assert
		assertNull(actualHeight, "Height should be null when null input is passed.");
	}

	@Test
	@Tag("boundary")
	public void heightHandlesBoundaryValues() {
		// Arrange
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		Integer minHeight = Integer.MIN_VALUE;
		Integer maxHeight = Integer.MAX_VALUE;
		// Act & Assert (Min Value)
		builder.height(minHeight);
		Integer actualMinHeight = builder.build().getHeight();
		assertEquals((Integer) minHeight, actualMinHeight, "Height should correctly handle Integer.MIN_VALUE.");
		// Act & Assert (Max Value)
		builder.height(maxHeight);
		Integer actualMaxHeight = builder.build().getHeight();
		assertEquals((Integer) maxHeight, actualMaxHeight, "Height should correctly handle Integer.MAX_VALUE.");
	}

	@Test
	@Tag("valid")
	public void heightOverwritesExistingValue() {
		// Arrange
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		Integer initialHeight = 100; // TODO: Adjust initial height value
		Integer newHeight = 200; // TODO: Adjust new height value
		// Act
		builder.height(initialHeight);
		builder.height(newHeight);
		Integer actualHeight = builder.build().getHeight();
		// Assert
		assertEquals((Integer) newHeight, actualHeight, "Height should be updated to the latest value.");
	}

	@Test
	@Tag("integration")
	public void heightWorksWithOtherBuilderMethods() {
		// Arrange
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		Integer expectedWidth = 300; // TODO: Adjust width value
		String expectedModel = "TestModel"; // TODO: Adjust model value
		Integer expectedHeight = 250; // TODO: Adjust height value
		// Act
		builder.width(expectedWidth).model(expectedModel).height(expectedHeight);
		ImageOptions options = builder.build();
		// Assert
		assertEquals((Integer) expectedWidth, options.getWidth(), "Width should match the expected value.");
		assertEquals(expectedModel, options.getModel(), "Model should match the expected value.");
		assertEquals((Integer) expectedHeight, options.getHeight(), "Height should match the expected value.");
	}

	@Test
	@Tag("valid")
	public void heightUpdatesWithinImmutability() {
		// Arrange
		ImageOptionsBuilder builder = ImageOptionsBuilder.builder();
		ImageOptions initialOptions = builder.build(); // Capture initial state
		Integer updatedHeight = 120; // TODO: Adjust height value
		// Act
		builder.height(updatedHeight);
		ImageOptions updatedOptions = builder.build();
		// Assert
		assertNotSame(initialOptions, updatedOptions, "Options should be immutable and independent after updates.");
		assertEquals((Integer) updatedHeight, updatedOptions.getHeight(), "Height should match the updated value.");
	}

}