/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test single_test_file using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getOptions_677b61bccd
ROOST_METHOD_SIG_HASH=getOptions_87ffd73502

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/prompt/PromptTemplateTest.java
Tests:
    "@Test
@Test
public void testCreateWithEmptyModelAndChatOptions() {
    String template = "This is a test prompt with no variables";
    PromptTemplate promptTemplate = new PromptTemplate(template);
    ChatOptions chatOptions = ChatOptions.builder().temperature(0.7).topK(3).build();
    Prompt prompt = promptTemplate.create(chatOptions);
    assertThat(prompt).isNotNull();
    assertThat(prompt.getContents()).isEqualTo(template);
    assertThat(prompt.getOptions()).isEqualTo(chatOptions);
}
"
    "@Test
@Test
public void testCreateWithModelAndChatOptions() {
    String template = "Hello, {name}! Your age is {age}.";
    Map<String, Object> model = new HashMap<>();
    model.put("name", "Alice");
    model.put("age", 30);
    PromptTemplate promptTemplate = new PromptTemplate(template, model);
    ChatOptions chatOptions = ChatOptions.builder().temperature(0.5).maxTokens(100).build();
    Prompt prompt = promptTemplate.create(model, chatOptions);
    assertThat(prompt).isNotNull();
    assertThat(prompt.getContents()).isEqualTo("Hello, Alice! Your age is 30.");
    assertThat(prompt.getOptions()).isEqualTo(chatOptions);
}
"
    "@Test
@Test
public void testCreateWithOverriddenModelAndChatOptions() {
    String template = "Hello, {name}! Your favorite color is {color}.";
    Map<String, Object> initialModel = new HashMap<>();
    initialModel.put("name", "Bob");
    initialModel.put("color", "blue");
    PromptTemplate promptTemplate = new PromptTemplate(template, initialModel);
    Map<String, Object> overriddenModel = new HashMap<>();
    overriddenModel.put("color", "red");
    ChatOptions chatOptions = ChatOptions.builder().temperature(0.8).build();
    Prompt prompt = promptTemplate.create(overriddenModel, chatOptions);
    assertThat(prompt).isNotNull();
    assertThat(prompt.getContents()).isEqualTo("Hello, Bob! Your favorite color is red.");
    assertThat(prompt.getOptions()).isEqualTo(chatOptions);
}
"

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/chat/client/ChatClientTest.java
Tests:
    "@Test
@Test
void mutateDefaults() {
    FunctionCallingOptions options = new DefaultFunctionCallingOptions();
    given(this.chatModel.getDefaultOptions()).willReturn(options);
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    given(this.chatModel.stream(this.promptCaptor.capture())).willReturn(Flux.generate(() -> new ChatResponse(List.of(new Generation(new AssistantMessage("response")))), (state, sink) -> {
        sink.next(state);
        sink.complete();
        return state;
    }));

    var chatClient = ChatClient.builder(this.chatModel).defaultSystem(s -> s.text("Default system text {param1}, {param2}").param("param1", "value1").param("param2", "value2")).defaultFunctions("fun1", "fun2").defaultFunctions(FunctionCallback.builder().function("fun3", mockFunction).description("fun3description").inputType(String.class).build()).defaultUser(u -> u.text("Default user text {uparam1}, {uparam2}").param("uparam1", "value1").param("uparam2", "value2").media(MimeTypeUtils.IMAGE_JPEG, new DefaultResourceLoader().getResource("classpath:/bikes.json"))).build();

    var content = chatClient.prompt().call().content();
    assertThat(content).isEqualTo("response");
    Prompt prompt = this.promptCaptor.getValue();
    Message systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("Default system text value1, value2");
    UserMessage userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Default user text value1, value2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    var fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");

    content = join(chatClient.prompt().stream().content());
    assertThat(content).isEqualTo("response");
    prompt = this.promptCaptor.getValue();
    systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("Default system text value1, value2");
    userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Default user text value1, value2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");


    chatClient = chatClient.mutate().defaultSystem("Mutated default system text {param1}, {param2}").defaultFunctions("fun4").defaultUser("Mutated default user text {uparam1}, {uparam2}").build();

    content = chatClient.prompt().call().content();
    assertThat(content).isEqualTo("response");
    prompt = this.promptCaptor.getValue();
    systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("Mutated default system text value1, value2");
    userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Mutated default user text value1, value2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2", "fun4");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");

    content = join(chatClient.prompt().stream().content());
    assertThat(content).isEqualTo("response");
    prompt = this.promptCaptor.getValue();
    systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("Mutated default system text value1, value2");
    userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Mutated default user text value1, value2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2", "fun4");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");
}
"
    "@Test
@Test
void mutatePrompt() {
    FunctionCallingOptions options = new DefaultFunctionCallingOptions();
    given(this.chatModel.getDefaultOptions()).willReturn(options);
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    given(this.chatModel.stream(this.promptCaptor.capture())).willReturn(Flux.generate(() -> new ChatResponse(List.of(new Generation(new AssistantMessage("response")))), (state, sink) -> {
        sink.next(state);
        sink.complete();
        return state;
    }));

    var chatClient = ChatClient.builder(this.chatModel).defaultSystem(s -> s.text("Default system text {param1}, {param2}").param("param1", "value1").param("param2", "value2")).defaultFunctions("fun1", "fun2").defaultFunctions(FunctionCallback.builder().function("fun3", mockFunction).description("fun3description").inputType(String.class).build()).defaultUser(u -> u.text("Default user text {uparam1}, {uparam2}").param("uparam1", "value1").param("uparam2", "value2").media(MimeTypeUtils.IMAGE_JPEG, new DefaultResourceLoader().getResource("classpath:/bikes.json"))).build();
    var content = chatClient.prompt().system("New default system text {param1}, {param2}").user(u -> u.param("uparam1", "userValue1").param("uparam2", "userValue2")).functions("fun5").mutate().
    build().prompt().call().content();

    assertThat(content).isEqualTo("response");
    Prompt prompt = this.promptCaptor.getValue();
    Message systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("New default system text value1, value2");
    UserMessage userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Default user text userValue1, userValue2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    var fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2", "fun5");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");


    content = join(chatClient.prompt().system("New default system text {param1}, {param2}").user(u -> u.param("uparam1", "userValue1").param("uparam2", "userValue2")).functions("fun5").mutate().
    build().prompt().stream().content());

    assertThat(content).isEqualTo("response");
    prompt = this.promptCaptor.getValue();
    systemMessage = prompt.getInstructions().get(0);
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    assertThat(systemMessage.getText()).isEqualTo("New default system text value1, value2");
    userMessage = (UserMessage) prompt.getInstructions().get(1);
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getText()).isEqualTo("Default user text userValue1, userValue2");
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_JPEG);
    fco = (FunctionCallingOptions) prompt.getOptions();
    assertThat(fco.getFunctions()).containsExactly("fun1", "fun2", "fun5");
    assertThat(fco.getFunctionCallbacks().iterator().next().getName()).isEqualTo("fun3");
}
"
    "@Test
@Test
void complexCall() throws MalformedURLException {
    given(this.chatModel.call(this.promptCaptor.capture())).willReturn(new ChatResponse(List.of(new Generation(new AssistantMessage("response")))));
    var options = FunctionCallingOptions.builder().build();
    given(this.chatModel.getDefaultOptions()).willReturn(options);
    var url = new URL("https:

    ChatClient client = ChatClient.builder(this.chatModel).defaultSystem("System text").defaultFunctions("function1").build();
    String response = client.prompt().user(u -> u.text("User text {music}").param("music", "Rock").media(MimeTypeUtils.IMAGE_PNG, url)).call().content();

    assertThat(response).isEqualTo("response");
    assertThat(this.promptCaptor.getValue().getInstructions()).hasSize(2);
    Message systemMessage = this.promptCaptor.getValue().getInstructions().get(0);
    assertThat(systemMessage.getText()).isEqualTo("System text");
    assertThat(systemMessage.getMessageType()).isEqualTo(MessageType.SYSTEM);
    UserMessage userMessage = (UserMessage) this.promptCaptor.getValue().getInstructions().get(1);
    assertThat(userMessage.getText()).isEqualTo("User text Rock");
    assertThat(userMessage.getMessageType()).isEqualTo(MessageType.USER);
    assertThat(userMessage.getMedia()).hasSize(1);
    assertThat(userMessage.getMedia().iterator().next().getMimeType()).isEqualTo(MimeTypeUtils.IMAGE_PNG);
    assertThat(userMessage.getMedia().iterator().next().getData()).isEqualTo("https:
    FunctionCallingOptions runtieOptions = (FunctionCallingOptions) this.promptCaptor.getValue().getOptions();
    assertThat(runtieOptions.getFunctions()).containsExactly("function1");
    assertThat(options.getFunctions()).isEmpty();
}
"

File Path: /var/tmp/Roost/RoostGPT/single_test_file/2ec39d9d-e569-4d8d-8a9b-8dc5bbb26c8c/source/spring-ai/spring-ai-core/src/test/java/org/springframework/ai/prompt/PromptTests.java
Tests:
    "@Test
@Test
public void testPromptCopy() {
    String template = "Hello, {name}! Your age is {age}.";
    Map<String, Object> model = new HashMap<>();
    model.put("name", "Alice");
    model.put("age", 30);
    PromptTemplate promptTemplate = new PromptTemplate(template, model);
    ChatOptions chatOptions = ChatOptions.builder().temperature(0.5).maxTokens(100).build();
    Prompt prompt = promptTemplate.create(model, chatOptions);
    Prompt copiedPrompt = prompt.copy();
    assertThat(prompt).isNotSameAs(copiedPrompt);
    assertThat(prompt.getOptions()).isNotSameAs(copiedPrompt.getOptions());
    assertThat(prompt.getInstructions()).isNotSameAs(copiedPrompt.getInstructions());
}
"
Scenario 1: Verify behavior when `imageModelOptions` is null

Details:
  TestName: getOptionsReturnsNullWhenOptionsAreUnset
  Description: Verify that the `getOptions` method returns `null` when the `imageModelOptions` field is not initialized and remains at its default value, which is `null`.

Execution:
  Arrange: Create an instance of the `ImagePrompt` class without initializing `imageModelOptions`.
  Act: Invoke the `getOptions` method.
  Assert: Compare the value returned by `getOptions` to `null`.

Validation:
  Clarify that the `getOptions` method appropriately reflects the state of the `imageModelOptions` field as `null`. Ensure that the method's behavior matches expectations when no options are set. This test confirms proper handling of uninitialized fields.

---

Scenario 2: Verify behavior with non-null `imageModelOptions`

Details:
  TestName: getOptionsReturnsNonNull
  Description: Validate that the `getOptions` method successfully returns a non-null value when the `imageModelOptions` field is initialized to a valid `ImageOptions` instance.

Execution:
  Arrange: Create an instance of the `ImageOptions` class, initialize it with relevant attributes, and assign it to the `imageModelOptions` field of the `ImagePrompt` instance.
  Act: Invoke the `getOptions` method.
  Assert: Compare the value returned by `getOptions` to the initialized `ImageOptions` instance.

Validation:
  Confirm that the `getOptions` method accurately reflects the assigned value of the `imageModelOptions` field. This test ensures proper functionality when the `imageModelOptions` is explicitly initialized.

---

Scenario 3: Ensure immutability of `imageModelOptions`

Details:
  TestName: getOptionsReturnsSameInstanceEachTime
  Description: Verify that the `getOptions` method consistently returns the same instance of the `imageModelOptions` field and does not duplicate or create new instances of the value.

Execution:
  Arrange: Create an instance of `ImageOptions` and assign it to `imageModelOptions`. Call `getOptions` repeatedly.
  Act: Invoke the `getOptions` method twice consecutively.
  Assert: Check that the returned objects from both calls are identical using reference equality (`==`).

Validation:
  Ensure that the method does not alter the assigned instance or create unnecessary duplicates. This test confirms that the `ImagePrompt` object correctly maintains field immutability.

---

Scenario 4: Validate interaction with `equals` method

Details:
  TestName: getOptionsEqualityCheck
  Description: Verify that the `imageModelOptions` returned by `getOptions` is consistent with the value used in the `equals` method comparison.

Execution:
  Arrange: Create two `ImagePrompt` objects with identical `imageModelOptions` values. Compare both objects using the `equals` method.
  Act: Retrieve `imageModelOptions` using `getOptions` and validate the `equals` check.
  Assert: Ensure that objects with the same `imageModelOptions` return `true` for the `equals` method comparison.

Validation:
  Verify that the `imageModelOptions` returned by `getOptions` aligns with the field used in the `equals` comparison. This test ensures proper behavior when comparing objects where the `imageModelOptions` is identical.

---

Scenario 5: Validate behavior with overridden `toString` method

Details:
  TestName: getOptionsPresenceInToString
  Description: Ensure the `imageModelOptions` value returned by `getOptions` is accurately represented as part of the overridden `toString` output.

Execution:
  Arrange: Create an `ImagePrompt` object with a valid `imageModelOptions` instance.
  Act: Invoke the `getOptions` method and explicitly check its representation within the output of `toString`.
  Assert: Verify that the `imageModelOptions` value appears accurately inside the `toString` string.

Validation:
  Confirm that the field value returned by `getOptions` is properly represented in the string output of the `toString` method. This test ensures that appropriate debug information is included.

---

Scenario 6: Edge case - Validate behavior after modifying instance attributes

Details:
  TestName: getOptionsReflectsStateOfField
  Description: Test how the `getOptions` method behaves after dynamically changing the `imageModelOptions` field from one value to another.

Execution:
  Arrange: Create an `ImagePrompt` object with a valid initial `ImageOptions` instance. Change the `imageModelOptions` to a different instance directly without invoking `getOptions`.
  Act: Invoke `getOptions` after the field mutation.
  Assert: Verify that the returned value matches the updated instance of `imageModelOptions`.

Validation:
  Ensure that the method properly reflects the current state of the `imageModelOptions` field. This test confirms correct interaction between the field and the method.

---

Scenario 7: Validate consistency with dependent methods

Details:
  TestName: getOptionsConsistencyWithMessageRelatedMethods
  Description: Verify that `getOptions` properly interacts with other methods of the `ImagePrompt` class, ensuring no unexpected interference with `getInstructions`.

Execution:
  Arrange: Create an `ImagePrompt` instance with both `imageModelOptions` and `messages` initialized to non-null values.
  Act: Invoke `getOptions` and `getInstructions` in sequence and ensure no unexpected behavior between the two methods.
  Assert: Validate that no cross-method errors occur, such as interference or shared dependencies.

Validation:
  Confirm that `getOptions` operates independently of other methods like `getInstructions`. This test ensures clear separation of concerns and predictable behavior.

---

Scenario 8: Validate behavior in object hash calculation

Details:
  TestName: getOptionsConsistencyWithHashCode
  Description: Ensure that the value returned by `getOptions` is consistent with the object's hash calculation, as implemented in the `hashCode` method.

Execution:
  Arrange: Create an `ImagePrompt` object with `imageModelOptions` initialized to a known instance. Compute the object's hash code after invoking `getOptions`.
  Act: Compare the hash code before and after accessing `getOptions`.
  Assert: Verify that the hash code remains unchanged and reflects the current state of the object.

Validation:
  Confirm that `imageModelOptions` as retrieved by `getOptions` is included in hash calculations. This test ensures consistency in field-dependent natural object methods like `hashCode`.

---

Scenario 9: Validate null safety of dependent methods

Details:
  TestName: getOptionsWithNullMessages
  Description: Test the behavior of `getOptions` when the `messages` field remains null, ensuring no interference between unrelated fields initialized as null.

Execution:
  Arrange: Create an `ImagePrompt` object with `messages` explicitly set to null and `imageModelOptions` set to a valid instance.
  Act: Invoke `getOptions`.
  Assert: Verify that the null state of `messages` does not affect the return value of `getOptions`.

Validation:
  Confirm that `getOptions` handles null states of unrelated fields gracefully without interference. This test ensures predictable functionality when optional fields are null.

*/

// ********RoostGPT********

package org.springframework.ai.image;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.Collections;
import org.junit.jupiter.api.*;
import java.util.List;
import java.util.Objects;
import org.springframework.ai.model.ModelRequest;

public class ImagePromptGetOptionsTest {

	@Test
	@Tag("valid")
	public void getOptionsReturnsNullWhenOptionsAreUnset() {
		ImagePrompt prompt = new ImagePrompt("Sample instructions");
		assertNull(prompt.getOptions());
	}

	@Test
	@Tag("valid")
	public void getOptionsReturnsNonNull() {
		ImageOptions options = ImageOptionsBuilder.builder().build(); // Modified
																		// according to
																		// accessible
																		// static method
		ImagePrompt prompt = new ImagePrompt("Sample instructions", options);
		assertEquals((ImageOptions) options, prompt.getOptions());
	}

	@Test
	@Tag("boundary")
	public void getOptionsReturnsSameInstanceEachTime() {
		ImageOptions options = ImageOptionsBuilder.builder().build(); // Modified
																		// according to
																		// accessible
																		// static method
		ImagePrompt prompt = new ImagePrompt("Sample instructions", options);
		assertSame(prompt.getOptions(), prompt.getOptions());
	}

	@Test
	@Tag("valid")
	public void getOptionsEqualityCheck() {
		ImageOptions options = ImageOptionsBuilder.builder().build(); // Modified
																		// according to
																		// accessible
																		// static method
		ImagePrompt prompt1 = new ImagePrompt("Instruction 1", options);
		ImagePrompt prompt2 = new ImagePrompt("Instruction 2", options);
		assertTrue(prompt1.getOptions().equals(prompt2.getOptions())); // Improved
																		// comparison
																		// logic
	}

	@Test
	@Tag("integration")
	public void getOptionsPresenceInToString() {
		ImageOptions options = ImageOptionsBuilder.builder().build(); // Modified
																		// according to
																		// accessible
																		// static method
		ImagePrompt prompt = new ImagePrompt("Sample instructions", options);
		String toStringResult = prompt.toString();
		assertTrue(toStringResult.contains(options.getResponseFormat())); // Modified to
																			// verify
																			// string
																			// representation
																			// properly
	}

	@Test
	@Tag("boundary")
	public void getOptionsReflectsStateOfField() {
		ImageOptions initialOptions = ImageOptionsBuilder.builder().build(); // Modified
																				// according
																				// to
																				// accessible
																				// static
																				// method
		ImageOptions updatedOptions = ImageOptionsBuilder.builder().build(); // Modified
																				// according
																				// to
																				// accessible
																				// static
																				// method
		ImagePrompt prompt = new ImagePrompt("Sample instructions", initialOptions);
		prompt = new ImagePrompt("Sample instructions", updatedOptions); // Creating new
																			// instance
																			// since
																			// "fields"
																			// are
																			// immutable.
		assertEquals((ImageOptions) updatedOptions, prompt.getOptions());
	}

	@Test
	@Tag("integration")
	public void getOptionsConsistencyWithMessageRelatedMethods() {
		ImageOptions options = ImageOptionsBuilder.builder().build(); // Modified
																		// according to
																		// accessible
																		// static method
		ImageMessage message = new ImageMessage("Sample message text");
		ImagePrompt prompt = new ImagePrompt(Collections.singletonList(message), options);
		assertEquals((ImageOptions) options, prompt.getOptions());
		assertEquals(Collections.singletonList(message), prompt.getInstructions());
	}

	@Test
	@Tag("valid")
	public void getOptionsConsistencyWithHashCode() {
		ImageOptions options = ImageOptionsBuilder.builder().build(); // Modified
																		// according to
																		// accessible
																		// static method
		ImagePrompt prompt = new ImagePrompt("Sample instructions", options);
		int initialHashCode = prompt.hashCode();
		assertEquals(initialHashCode, prompt.hashCode());
	}

	@Test
	@Tag("invalid")
	public void getOptionsWithNullMessages() {
		ImageOptions options = ImageOptionsBuilder.builder().build(); // Modified
																		// according to
																		// accessible
																		// static method
		ImagePrompt prompt = new ImagePrompt((List<ImageMessage>) null, options); // Ensuring
																					// correct
																					// constructor
																					// is
																					// used
		assertEquals((ImageOptions) options, prompt.getOptions());
	}

}