/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=equals_a7549f8659
ROOST_METHOD_SIG_HASH=equals_ded257778a

"""
  Scenario 1: Testing the equality of two similar AbstractMessage objects

  Details:
    TestName: testEqualsWithSameObject.
    Description: This test is designed to confirm that the equals method can accurately determine when two AbstractMessage instances share the same property values.
  Execution:
    Arrange: Instantiate two AbstractMessage objects with identical property values.
    Act: Use the equals method to evaluate the equivalence of the two objects.
    Assert: Confirm that the equals method returns true.
  Validation:
    The assertion verifies that the equals method correctly identifies when two objects are identical. This is critical as incorrect comparison can lead to bugs in code execution.

  Scenario 2: Testing the equality of two dissimilar AbstractMessage objects

  Details:
    TestName: testEqualsWithDifferentObject.
    Description: This test checks the equals method's ability to identify when two AbstractMessage instances don't share the same property values.
  Execution:
    Arrange: Create two different AbstractMessage objects with differing property values.
    Act: Invoke the equals method to examine the equivalence of the two objects.
    Assert: Assert that the equals method returns false.
  Validation:
    The assertion verifies that the equals method accurately identifies different objects. This is important because it ensures that distinct instances are not incorrectly classified as identical.

  Scenario 3: Testing the equality method when null is passed as an argument

  Details:
    TestName: testEqualsWithNull.
    Description: This test ensures that the equals method correctly returns false when the provided argument is null.
  Execution:
    Arrange: Instantiate an AbstractMessage object.
    Act: Invoke the equals method, passing null as an argument.
    Assert: Assert that the equals method returns false.
  Validation:
    The assertion validates that equals identifies when the parameter is null. This guarantees that the application can safely use equals without null pointer exceptions.

  Scenario 4: Testing the equality method with an object of a different class

  Details:
    TestName: testEqualsWithDifferentClass.
    Description: This test verifies that the equals method returns false when called with an argument of a different class.
  Execution:
    Arrange: Create an AbstractMessage object and an object of a different class.
    Act: Run the equals method on the AbstractMessage object, passing in the object of a different class.
    Assert: Verify that the equals method returns false.
  Validation:
    This assertion ensures that the equals method can accurately identify when an object is not an instance of AbstractMessage. This is crucial for avoiding class-casting exceptions and ensuring accurate comparison.
""",efbc9f9a-56d1-4570-8728-646cbc767608
*/

// ********RoostGPT********

package org.springframework.ai.chat.messages;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.Charset;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.springframework.core.io.Resource;
import org.springframework.util.Assert;
import org.springframework.util.StreamUtils;

public class AbstractMessageEqualsTest {

	@Category(Categories.valid.class)
	@Test
	public void testEqualsWithSameObject() {
		Map<String, Object> metadata = new HashMap<String, Object>();
		AbstractMessage message1 = new AbstractMessage(MessageType.USER, "Hello", metadata);
		AbstractMessage message2 = new AbstractMessage(MessageType.USER, "Hello", metadata);
		Assert.isTrue(message1.equals(message2), "Expecting objects to be equal but they are not");
	}

	@Category(Categories.valid.class)
	@Test
	public void testEqualsWithDifferentObject() {
		Map<String, Object> metadata = new HashMap<String, Object>();
		AbstractMessage message1 = new AbstractMessage(MessageType.USER, "Hello", metadata);
		AbstractMessage message2 = new AbstractMessage(MessageType.SYSTEM, "Hello", metadata);
		Assert.isTrue(!message1.equals(message2), "Expecting objects to not be equal but they are");
	}

	@Category(Categories.valid.class)
	@Test
	public void testEqualsWithNull() {
		Map<String, Object> metadata = new HashMap<String, Object>();
		AbstractMessage message1 = new AbstractMessage(MessageType.USER, "Hello", metadata);
		Assert.isTrue(!message1.equals(null), "Expecting objects to not be equal but they are");
	}

	@Category(Categories.valid.class)
	@Test
	public void testEqualsWithDifferentClass() {
		Map<String, Object> metadata = new HashMap<String, Object>();
		AbstractMessage message1 = new AbstractMessage(MessageType.USER, "Hello", metadata);
		String someOtherObject = new String("Other Class");
		Assert.isTrue(!message1.equals(someOtherObject), "Expecting objects to not be equal but they are");
	}

}