/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getMetadata_d6b7297ade
ROOST_METHOD_SIG_HASH=getMetadata_7d74bc2570

Scenario 1: Testing the return value of getMetadata function
Details:
  TestName: testGetMetadataReturn
  Description: The test is meant to verify the return value of getMetadata function whether it returns the appropriate metadata map.
  Execution:
    Arrange: Create an instance of AbstractMessage class and set the metadata field with a predefined map.
    Act: Call the getMetadata().
    Assert: Assert if the returned map equals the predefined map.
  Validation:
    The test is to validate whether the getMetadata function in the AbstractMessage class returns the exact content of the metadata field. If the result is as expected, it accounts for successful data retrieval from the metadata field.

Scenario 2: Testing the immutability of getMetadata function
Details:
  TestName: testGetMetadataImmutability
  Description: To ensure that getMetadata() does not return a reference to its internal structure but a clone, to preserve immutability.
  Execution:
    Arrange: Create an instance of AbstractMessage with a predefined metadata map.
    Act: Call the getMetadata() method and then modify the returned map.
    Assert: Assert whether the modification has affected the original map in the AbstractMessage instance.
  Validation:
    The test validates whether the getMetadata method returns a new Map object rather than a reference to its internal Map. If it returns a new Map, it ensures data encapsulation and the immutability of the object's state.

Scenario 3: Handling null value in getMetadata method
Details:
  TestName: testGetMetadataWithNull
  Description: To check how the getMetadata() function handles when no value is set for the metadata field.
  Execution:
    Arrange: Create an instance of AbstractMessage without setting any value to the metadata.
    Act: Call the getMetadata() method.
    Assert: Assert if the method returns null.
  Validation:
    The test is to validate how the getMetadata function handles null. If it correctly returns null when the metadata map is not initialized, it can guarantee object safety by avoiding unexpected NullPointerException.,0b220b3f-ffeb-4670-a150-56b8d7fb63ca
*/

// ********RoostGPT********

package org.springframework.ai.chat.messages;

import org.junit.Assert;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import java.util.HashMap;
import java.util.Map;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.Charset;
import java.util.Objects;
import org.springframework.core.io.Resource;
import org.springframework.util.Assert;
import org.springframework.util.StreamUtils;

public class AbstractMessageGetMetadataTest {

	@Test
	@Category(Categories.valid.class)
	public void testGetMetadataReturn() {
		Map<String, Object> predefinedMap = new HashMap<>();
		predefinedMap.put("Key", "Value");
		AbstractMessage abstractMessage = new AbstractMessage(MessageType.SYSTEM, "Test", predefinedMap);
		Map<String, Object> actualMetadata = abstractMessage.getMetadata();
		Assert.assertEquals(predefinedMap, actualMetadata);
	}

	@Test
	@Category(Categories.valid.class)
	public void testGetMetadataImmutability() {
		Map<String, Object> predefinedMap = new HashMap<>();
		predefinedMap.put("Key", "Value");
		AbstractMessage abstractMessage = new AbstractMessage(MessageType.SYSTEM, "Test", predefinedMap);
		Map<String, Object> returnedMap = abstractMessage.getMetadata();
		returnedMap.put("ExtraKey", "ExtraValue");
		Assert.assertNotEquals(abstractMessage.getMetadata(), returnedMap);
	}

	@Test
	@Category(Categories.invalid.class)
	public void testGetMetadataWithNull() {
		AbstractMessage abstractMessage = new AbstractMessage(MessageType.SYSTEM, "Test", null);
		Assert.assertNull(abstractMessage.getMetadata());
	}

}