/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=equals_f865b030b5
ROOST_METHOD_SIG_HASH=equals_ded257778a

Scenario 1: Testing equals for Same Object

Details:
TestName: equalityOfSameObject
Description: The test is meant to check the equals method when it is used to compare an instance to itself.
Execution:
Arrange: Instantiate a ToolResponseMessage object.
Act: Use the equals method to compare the instance to itself.
Assert: Assert that the result is true.
Validation:
The assertion verifies that an instance is equal to itself. This test is significant for verifying the reflexivity property of the equals method.

Scenario 2: Testing equals for Different Object Type

Details:
TestName: equalityWithDifferentObjectType
Description: The test is intended to check the equals method when the parameter object is not an instance of the ToolResponseMessage class.
Execution:
Arrange: Instantiate a ToolResponseMessage object and another object of a different class.
Act: Invoke the equals method using the ToolResponseMessage instance and the object of a different class.
Assert: Assert that the result is false.
Validation:
The assertion confirms whether the equals method correctly identifies that two different object types are not equal.

Scenario 3: Testing equals for Different Instances with Same Data

Details:
TestName: equalityOfDifferentInstancesWithSameData
Description: This test is meant to check the equals method with two different instances of the ToolResponseMessage that contain identical data.
Execution:
Arrange: Create two different instances of the ToolResponseMessage class, with identical responses.
Act: Use the equals method to compare the two instances.
Assert: Assert that the result is true.
Validation:
The test verifies that the equals method correctly identifies two objects as equal if their content is identical. This verifies the symmetric property of the equals method.

Scenario 4: Testing equals for Different Instances with Different Data

Details:
TestName: equalityOfDifferentInstancesWithDifferentData
Description: This test is meant to check the equals method with two different instances of the ToolResponseMessage that contain different data.
Execution:
Arrange: Create two different instances of the ToolResponseMessage class, with different responses.
Act: Use the equals method to compare the two instances.
Assert: Assert that the result is false.
Validation:
The test verifies that the equals method correctly identifies two objects as not equal if their content is not identical.

Scenario 5: Testing equals with Null

Details:
TestName: equalityWithNull
Description: The test is meant to check the equals method when the parameter object is null.
Execution:
Arrange: Instantiate a ToolResponseMessage object and a null reference.
Act: Invoke the equals method using the ToolResponseMessage instance and the null reference.
Assert: Assert that the result is false.
Validation:
The assertion confirms that the equals method correctly identifies that an object is not equal to a null reference.,54037bf6-726c-46ba-b825-ad9498a7269a
*/

// ********RoostGPT********

package org.springframework.ai.chat.messages;

import org.junit.Test;
import org.junit.experimental.categories.Category;
import java.util.Arrays;
import java.util.Collections;
import static org.junit.Assert.*;
import java.util.List;
import java.util.Map;
import java.util.Objects;

public class ToolResponseMessageEqualsTest {

	@Test
	@Category(Categories.valid.class)
	public void equalityOfSameObject() {
		ToolResponseMessage message1 = new ToolResponseMessage(Collections.singletonList(new ToolResponse()));
		assertTrue(message1.equals(message1));
	}

	@Test
	@Category(Categories.invalid.class)
	public void equalityWithDifferentObjectType() {
		ToolResponseMessage message1 = new ToolResponseMessage(Collections.singletonList(new ToolResponse()));
		assertFalse(message1.equals(new Object()));
	}

	@Test
	@Category(Categories.valid.class)
	public void equalityOfDifferentInstancesWithSameData() {
		ToolResponse response = new ToolResponse();
		ToolResponseMessage message1 = new ToolResponseMessage(Arrays.asList(response, response));
		ToolResponseMessage message2 = new ToolResponseMessage(Arrays.asList(response, response));
		assertTrue(message1.equals(message2));
	}

	@Test
	@Category(Categories.invalid.class)
	public void equalityOfDifferentInstancesWithDifferentData() {
		ToolResponseMessage message1 = new ToolResponseMessage(Arrays.asList(new ToolResponse(), new ToolResponse()));
		ToolResponseMessage message2 = new ToolResponseMessage(Arrays.asList(new ToolResponse(), new ToolResponse()));
		assertFalse(message1.equals(message2));
	}

	@Test
	@Category(Categories.invalid.class)
	public void equalityWithNull() {
		ToolResponseMessage message1 = new ToolResponseMessage(Collections.singletonList(new ToolResponse()));
		assertFalse(message1.equals(null));
	}

}