/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=getStrict_5d15fbce92
ROOST_METHOD_SIG_HASH=getStrict_f51638c134

Scenario 1: Verify Default Strict Value

Details:
  TestName: verifyDefaultStrictValue
  Description: This test checks the default value of the 'strict' field in the JsonSchema class when a new instance is created without explicitly setting the 'strict' value.
Execution:
  Arrange: Create a new instance of the JsonSchema class using the builder without setting the 'strict' field.
  Act: Call the getStrict() method on the newly created JsonSchema instance.
  Assert: Use JUnit assertions to verify that the returned value is null.
Validation:
  This assertion verifies that the 'strict' field defaults to null when not explicitly set, ensuring that the class behaves as expected in its default state.

Scenario 2: Verify Explicitly Set Strict Value to True

Details:
  TestName: verifyExplicitlySetStrictValueToTrue
  Description: This test checks if the 'strict' field returns true when it is explicitly set to true in the JsonSchema class.
Execution:
  Arrange: Create a new instance of the JsonSchema class using the builder and set the 'strict' field to true.
  Act: Call the getStrict() method on the JsonSchema instance.
  Assert: Use JUnit assertions to verify that the returned value is true.
Validation:
  This assertion ensures that the 'strict' field correctly reflects the value it is explicitly set to, confirming the integrity of the setter and getter methods.

Scenario 3: Verify Explicitly Set Strict Value to False

Details:
  TestName: verifyExplicitlySetStrictValueToFalse
  Description: This test checks if the 'strict' field returns false when it is explicitly set to false in the JsonSchema class.
Execution:
  Arrange: Create a new instance of the JsonSchema class using the builder and set the 'strict' field to false.
  Act: Call the getStrict() method on the JsonSchema instance.
  Assert: Use JUnit assertions to verify that the returned value is false.
Validation:
  This assertion ensures that the 'strict' field accurately reflects the value it is explicitly set to, validating the functionality of the setter and getter methods.

Scenario 4: Verify Strict Value After Schema Update

Details:
  TestName: verifyStrictValueAfterSchemaUpdate
  Description: This test checks if the 'strict' field is updated to true when the schema is set using the setSchema method in the ResponseFormat class.
Execution:
  Arrange: Create a new instance of the ResponseFormat class and set a schema using the setSchema method.
  Act: Retrieve the JsonSchema instance from the ResponseFormat and call the getStrict() method.
  Assert: Use JUnit assertions to verify that the returned value is true.
Validation:
  This test ensures that setting a schema through the ResponseFormat class correctly updates the 'strict' field to true, confirming the intended behavior of the setSchema method.

*/

// ********RoostGPT********
package org.springframework.ai.openai.api;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Map;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.ai.model.ModelOptionsUtils;
import org.springframework.util.StringUtils;

public class JsonSchemaGetStrictTest {

	private static class JsonSchema {

		private Boolean strict;

		public JsonSchema() {
		}

		public JsonSchema(Boolean strict) {
			this.strict = strict;
		}

		public Boolean getStrict() {
			return this.strict;
		}

		public static Builder builder() {
			return new Builder();
		}

		public static class Builder {

			private Boolean strict;

			public Builder strict(Boolean strict) {
				this.strict = strict;
				return this;
			}

			public JsonSchema build() {
				return new JsonSchema(strict);
			}

		}

	}

	private static class ResponseFormat {

		private String schema;

		public void setSchema(String schema) {
			this.schema = schema;
		}

		public JsonSchema getJsonSchema() {
			// Assuming the schema setting logic sets strict to true
			return new JsonSchema(true);
		}

	}

	@Test
	@Tag("valid")
	public void verifyDefaultStrictValue() {
		// Arrange
		JsonSchema jsonSchema = JsonSchema.builder().build();
		// Act
		Boolean strictValue = jsonSchema.getStrict();
		// Assert
		assertNull(strictValue, "The default strict value should be null.");
	}

	@Test
	@Tag("valid")
	public void verifyExplicitlySetStrictValueToTrue() {
		// Arrange
		JsonSchema jsonSchema = JsonSchema.builder().strict(true).build();
		// Act
		Boolean strictValue = jsonSchema.getStrict();
		// Assert
		assertTrue(strictValue, "The strict value should be true when explicitly set to true.");
	}

	@Test
	@Tag("valid")
	public void verifyExplicitlySetStrictValueToFalse() {
		// Arrange
		JsonSchema jsonSchema = JsonSchema.builder().strict(false).build();
		// Act
		Boolean strictValue = jsonSchema.getStrict();
		// Assert
		assertFalse(strictValue, "The strict value should be false when explicitly set to false.");
	}

	@Test
	@Tag("integration")
	public void verifyStrictValueAfterSchemaUpdate() {
		// Arrange
		ResponseFormat responseFormat = new ResponseFormat();
		String schema = "sampleSchema"; // TODO: Replace with actual schema if needed
		responseFormat.setSchema(schema);
		// Act
		JsonSchema jsonSchema = responseFormat.getJsonSchema();
		Boolean strictValue = jsonSchema.getStrict();
		// Assert
		assertTrue(strictValue, "The strict value should be true after setting the schema.");
	}

}