/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=merge_d787685d9c
ROOST_METHOD_SIG_HASH=merge_9c80129a0e

Scenario 1: Merging Two Non-Null ChatCompletionChunks

Details:
  TestName: mergeTwoNonNullChunks
  Description: This test checks the merging of two non-null ChatCompletionChunk objects. It ensures that the resulting object correctly combines attributes from both inputs, preferring non-null values from the current chunk.
Execution:
  Arrange: Create two ChatCompletionChunk objects with overlapping and distinct attributes.
  Act: Call the merge method with these two objects.
  Assert: Verify that the resulting ChatCompletionChunk has the expected attributes, combining values from both inputs.
Validation:
  This test verifies that the merge method correctly prioritizes non-null values from the current chunk over the previous chunk, ensuring accurate data consolidation.

Scenario 2: Merging with Previous Chunk as Null

Details:
  TestName: mergeWithPreviousChunkNull
  Description: This test checks the behavior of the merge method when the previous ChatCompletionChunk is null. The method should return the current chunk unchanged.
Execution:
  Arrange: Create a non-null ChatCompletionChunk object for the current parameter and set the previous parameter to null.
  Act: Call the merge method with the null previous chunk and the non-null current chunk.
  Assert: Verify that the returned ChatCompletionChunk is identical to the current chunk.
Validation:
  This test ensures that the method correctly handles a null previous chunk by returning the current chunk as is, maintaining data integrity.

Scenario 3: Merging with Current Chunk as Null

Details:
  TestName: mergeWithCurrentChunkNull
  Description: This test examines the behavior of the merge method when the current ChatCompletionChunk is null. The method should return the previous chunk unchanged.
Execution:
  Arrange: Create a non-null ChatCompletionChunk object for the previous parameter and set the current parameter to null.
  Act: Call the merge method with the non-null previous chunk and the null current chunk.
  Assert: Verify that the returned ChatCompletionChunk is identical to the previous chunk.
Validation:
  This test confirms that the method correctly handles a null current chunk by returning the previous chunk, ensuring no data loss.

Scenario 4: Merging with Both Chunks Null

Details:
  TestName: mergeWithBothChunksNull
  Description: This test checks the behavior of the merge method when both the previous and current ChatCompletionChunk objects are null. The method should return null.
Execution:
  Arrange: Set both the previous and current parameters to null.
  Act: Call the merge method with both parameters as null.
  Assert: Verify that the returned value is null.
Validation:
  This test ensures that the method correctly returns null when both input chunks are null, adhering to expected behavior for null inputs.

Scenario 5: Merging Chunks with Empty Choices

Details:
  TestName: mergeChunksWithEmptyChoices
  Description: This test evaluates the merging of ChatCompletionChunks where both have empty choices lists. The resulting chunk should also have an empty choices list.
Execution:
  Arrange: Create two ChatCompletionChunk objects with empty choices lists.
  Act: Call the merge method with these two objects.
  Assert: Verify that the resulting ChatCompletionChunk has an empty choices list.
Validation:
  This test confirms that the method correctly handles chunks with empty choices, maintaining the integrity of the choices list in the merged result.

Scenario 6: Merging Chunks with Different Choice Attributes

Details:
  TestName: mergeChunksWithDifferentChoiceAttributes
  Description: This test checks the merging of ChatCompletionChunks where the choices have different attributes. It ensures that the merge method correctly combines choice attributes.
Execution:
  Arrange: Create two ChatCompletionChunk objects with choices having different attributes.
  Act: Call the merge method with these two objects.
  Assert: Verify that the resulting ChatCompletionChunk has choices with correctly merged attributes.
Validation:
  This test ensures that the method accurately merges choice attributes, reflecting the correct combination of input data.

Scenario 7: Merging Chunks with Null Choice Attributes

Details:
  TestName: mergeChunksWithNullChoiceAttributes
  Description: This test examines the merging of ChatCompletionChunks where some choice attributes are null. The method should correctly handle null attributes.
Execution:
  Arrange: Create two ChatCompletionChunk objects with some choice attributes set to null.
  Act: Call the merge method with these two objects.
  Assert: Verify that the resulting ChatCompletionChunk has choices with non-null attributes correctly prioritized.
Validation:
  This test ensures that the method handles null choice attributes correctly, prioritizing non-null values and maintaining data integrity.

*/

// ********RoostGPT********

package org.springframework.ai.openai.api;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletion;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletion.Choice;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionChunk;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionChunk.ChunkChoice;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionFinishReason;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage.ChatCompletionFunction;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage.Role;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage.ToolCall;
import org.springframework.ai.openai.api.OpenAiApi.LogProbs;
import org.springframework.ai.openai.api.OpenAiApi.Usage;
import org.springframework.util.CollectionUtils;

class OpenAiStreamFunctionCallingHelperMergeTest {

	private final OpenAiStreamFunctionCallingHelper helper = new OpenAiStreamFunctionCallingHelper();

	@Test
	@Tag("valid")
	public void mergeTwoNonNullChunks() {
		ChatCompletionChunk previous = Mockito.mock(ChatCompletionChunk.class);
		ChatCompletionChunk current = Mockito.mock(ChatCompletionChunk.class);
		Mockito.when(previous.id()).thenReturn("prevId");
		Mockito.when(current.id()).thenReturn("currId");
		Mockito.when(previous.created()).thenReturn(123L);
		Mockito.when(current.created()).thenReturn(456L);
		Mockito.when(previous.model()).thenReturn("prevModel");
		Mockito.when(current.model()).thenReturn("currModel");
		Mockito.when(previous.choices()).thenReturn(List.of());
		Mockito.when(current.choices()).thenReturn(List.of());
		ChatCompletionChunk result = helper.merge(previous, current);
		assertEquals("currId", result.id());
		assertEquals(456L, result.created());
		assertEquals("currModel", result.model());
	}

	@Test
	@Tag("valid")
	public void mergeWithPreviousChunkNull() {
		ChatCompletionChunk current = Mockito.mock(ChatCompletionChunk.class);
		Mockito.when(current.id()).thenReturn("currId");
		Mockito.when(current.created()).thenReturn(456L);
		Mockito.when(current.model()).thenReturn("currModel");
		Mockito.when(current.choices()).thenReturn(List.of());
		ChatCompletionChunk result = helper.merge(null, current);
		assertEquals("currId", result.id());
		assertEquals(456L, result.created());
		assertEquals("currModel", result.model());
	}

	@Test
	@Tag("valid")
	public void mergeWithCurrentChunkNull() {
		ChatCompletionChunk previous = Mockito.mock(ChatCompletionChunk.class);
		Mockito.when(previous.id()).thenReturn("prevId");
		Mockito.when(previous.created()).thenReturn(123L);
		Mockito.when(previous.model()).thenReturn("prevModel");
		Mockito.when(previous.choices()).thenReturn(List.of());
		ChatCompletionChunk result = helper.merge(previous, null);
		assertEquals("prevId", result.id());
		assertEquals(123L, result.created());
		assertEquals("prevModel", result.model());
	}

	@Test
	@Tag("invalid")
	public void mergeWithBothChunksNull() {
		ChatCompletionChunk result = helper.merge(null, null);
		assertNull(result);
	}

	@Test
	@Tag("boundary")
	public void mergeChunksWithEmptyChoices() {
		ChatCompletionChunk previous = Mockito.mock(ChatCompletionChunk.class);
		ChatCompletionChunk current = Mockito.mock(ChatCompletionChunk.class);
		Mockito.when(previous.choices()).thenReturn(List.of());
		Mockito.when(current.choices()).thenReturn(List.of());
		ChatCompletionChunk result = helper.merge(previous, current);
		assertTrue(result.choices().isEmpty());
	}

	@Test
	@Tag("integration")
	public void mergeChunksWithDifferentChoiceAttributes() {
		ChunkChoice prevChoice = Mockito.mock(ChunkChoice.class);
		ChunkChoice currChoice = Mockito.mock(ChunkChoice.class);
		ChatCompletionChunk previous = Mockito.mock(ChatCompletionChunk.class);
		ChatCompletionChunk current = Mockito.mock(ChatCompletionChunk.class);
		Mockito.when(previous.choices()).thenReturn(List.of(prevChoice));
		Mockito.when(current.choices()).thenReturn(List.of(currChoice));
		ChatCompletionChunk result = helper.merge(previous, current);
		assertNotNull(result.choices());
	}

	@Test
	@Tag("boundary")
	public void mergeChunksWithNullChoiceAttributes() {
		ChunkChoice prevChoice = Mockito.mock(ChunkChoice.class);
		ChatCompletionChunk previous = Mockito.mock(ChatCompletionChunk.class);
		ChatCompletionChunk current = Mockito.mock(ChatCompletionChunk.class);
		Mockito.when(previous.choices()).thenReturn(List.of(prevChoice));
		Mockito.when(current.choices()).thenReturn(List.of());
		ChatCompletionChunk result = helper.merge(previous, current);
		assertNotNull(result.choices());
	}

}