/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=isStreamingToolFunctionCall_b8c0dc17a4
ROOST_METHOD_SIG_HASH=isStreamingToolFunctionCall_2197b0706f

Scenario 1: Null ChatCompletionChunk

Details:
  TestName: isStreamingToolFunctionCallWithNullChunk
  Description: This test checks the behavior of the method when the input ChatCompletionChunk is null. It ensures that the method correctly returns false in this scenario.
Execution:
  Arrange: Set the ChatCompletionChunk to null.
  Act: Call isStreamingToolFunctionCall with the null ChatCompletionChunk.
  Assert: Verify that the method returns false.
Validation:
  The assertion verifies that the method handles null inputs gracefully by returning false, which is important for preventing null pointer exceptions in the application.

Scenario 2: Empty Choices List

Details:
  TestName: isStreamingToolFunctionCallWithEmptyChoices
  Description: This test checks the method's behavior when the ChatCompletionChunk contains an empty list of choices. It ensures that the method returns false in this case.
Execution:
  Arrange: Create a ChatCompletionChunk with an empty list of choices.
  Act: Call isStreamingToolFunctionCall with this ChatCompletionChunk.
  Assert: Verify that the method returns false.
Validation:
  The assertion ensures that the method correctly identifies an empty choices list as a non-streaming tool function call scenario, which is crucial for accurate application logic.

Scenario 3: Null Choice in Choices List

Details:
  TestName: isStreamingToolFunctionCallWithNullChoice
  Description: This test checks the method's behavior when the first choice in the choices list is null. It ensures that the method returns false.
Execution:
  Arrange: Create a ChatCompletionChunk with a list containing a single null choice.
  Act: Call isStreamingToolFunctionCall with this ChatCompletionChunk.
  Assert: Verify that the method returns false.
Validation:
  The assertion confirms that the method correctly handles null choices by returning false, preventing potential null pointer exceptions.

Scenario 4: Null Delta in Choice

Details:
  TestName: isStreamingToolFunctionCallWithNullDelta
  Description: This test checks the method's behavior when the delta of the first choice is null. It ensures that the method returns false.
Execution:
  Arrange: Create a ChatCompletionChunk with a choice that has a null delta.
  Act: Call isStreamingToolFunctionCall with this ChatCompletionChunk.
  Assert: Verify that the method returns false.
Validation:
  The assertion verifies that the method correctly identifies a null delta as a non-streaming tool function call scenario, ensuring robust application behavior.

Scenario 5: Empty ToolCalls in Delta

Details:
  TestName: isStreamingToolFunctionCallWithEmptyToolCalls
  Description: This test checks the method's behavior when the delta contains an empty list of tool calls. It ensures that the method returns false.
Execution:
  Arrange: Create a ChatCompletionChunk with a choice whose delta has an empty list of tool calls.
  Act: Call isStreamingToolFunctionCall with this ChatCompletionChunk.
  Assert: Verify that the method returns false.
Validation:
  The assertion ensures that the method correctly identifies an empty tool calls list as a non-streaming tool function call scenario, which is important for accurate application logic.

Scenario 6: Valid ToolCalls in Delta

Details:
  TestName: isStreamingToolFunctionCallWithValidToolCalls
  Description: This test checks the method's behavior when the delta contains a non-empty list of tool calls. It ensures that the method returns true.
Execution:
  Arrange: Create a ChatCompletionChunk with a choice whose delta has a non-empty list of tool calls.
  Act: Call isStreamingToolFunctionCall with this ChatCompletionChunk.
  Assert: Verify that the method returns true.
Validation:
  The assertion confirms that the method correctly identifies a non-empty tool calls list as a streaming tool function call scenario, which is crucial for the correct functioning of the application.

*/

// ********RoostGPT********

package org.springframework.ai.openai.api;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import org.springframework.util.CollectionUtils;
import java.util.Collections;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletion;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletion.Choice;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionChunk;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionChunk.ChunkChoice;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionFinishReason;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage.ChatCompletionFunction;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage.Role;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage.ToolCall;
import org.springframework.ai.openai.api.OpenAiApi.LogProbs;
import org.springframework.ai.openai.api.OpenAiApi.Usage;

public class OpenAiStreamFunctionCallingHelperIsStreamingToolFunctionCallTest {

	private final OpenAiStreamFunctionCallingHelper helper = new OpenAiStreamFunctionCallingHelper();

	@Test
	@Tag("invalid")
	public void isStreamingToolFunctionCallWithNullChunk() {
		// Arrange
		ChatCompletionChunk chatCompletionChunk = null;
		// Act
		boolean result = helper.isStreamingToolFunctionCall(chatCompletionChunk);
		// Assert
		assertFalse(result);
	}

	@Test
	@Tag("invalid")
	public void isStreamingToolFunctionCallWithEmptyChoices() {
		// Arrange
		ChatCompletionChunk chatCompletionChunk = Mockito.mock(ChatCompletionChunk.class);
		Mockito.when(chatCompletionChunk.choices()).thenReturn(Collections.emptyList());
		// Act
		boolean result = helper.isStreamingToolFunctionCall(chatCompletionChunk);
		// Assert
		assertFalse(result);
	}

	@Test
	@Tag("invalid")
	public void isStreamingToolFunctionCallWithNullChoice() {
		// Arrange
		ChatCompletionChunk chatCompletionChunk = Mockito.mock(ChatCompletionChunk.class);
		Mockito.when(chatCompletionChunk.choices()).thenReturn(Collections.singletonList(null));
		// Act
		boolean result = helper.isStreamingToolFunctionCall(chatCompletionChunk);
		// Assert
		assertFalse(result);
	}

	@Test
	@Tag("invalid")
	public void isStreamingToolFunctionCallWithNullDelta() {
		// Arrange
		ChunkChoice choice = Mockito.mock(ChunkChoice.class);
		Mockito.when(choice.delta()).thenReturn(null);
		ChatCompletionChunk chatCompletionChunk = Mockito.mock(ChatCompletionChunk.class);
		Mockito.when(chatCompletionChunk.choices()).thenReturn(Collections.singletonList(choice));
		// Act
		boolean result = helper.isStreamingToolFunctionCall(chatCompletionChunk);
		// Assert
		assertFalse(result);
	}

	@Test
	@Tag("invalid")
	public void isStreamingToolFunctionCallWithEmptyToolCalls() {
		// Arrange
		ChatCompletionMessage delta = Mockito.mock(ChatCompletionMessage.class);
		Mockito.when(delta.toolCalls()).thenReturn(Collections.emptyList());
		ChunkChoice choice = Mockito.mock(ChunkChoice.class);
		Mockito.when(choice.delta()).thenReturn(delta);
		ChatCompletionChunk chatCompletionChunk = Mockito.mock(ChatCompletionChunk.class);
		Mockito.when(chatCompletionChunk.choices()).thenReturn(Collections.singletonList(choice));
		// Act
		boolean result = helper.isStreamingToolFunctionCall(chatCompletionChunk);
		// Assert
		assertFalse(result);
	}

	@Test
	@Tag("valid")
	public void isStreamingToolFunctionCallWithValidToolCalls() {
		// Arrange
		ToolCall toolCall = Mockito.mock(ToolCall.class);
		ChatCompletionMessage delta = Mockito.mock(ChatCompletionMessage.class);
		Mockito.when(delta.toolCalls()).thenReturn(List.of(toolCall));
		ChunkChoice choice = Mockito.mock(ChunkChoice.class);
		Mockito.when(choice.delta()).thenReturn(delta);
		ChatCompletionChunk chatCompletionChunk = Mockito.mock(ChatCompletionChunk.class);
		Mockito.when(chatCompletionChunk.choices()).thenReturn(Collections.singletonList(choice));
		// Act
		boolean result = helper.isStreamingToolFunctionCall(chatCompletionChunk);
		// Assert
		assertTrue(result);
	}

}