/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=chunkToChatCompletion_b2e840c139
ROOST_METHOD_SIG_HASH=chunkToChatCompletion_fede4f3383


Scenario 1: Convert a valid ChatCompletionChunk to ChatCompletion

Details:
  TestName: convertValidChunkToChatCompletion
  Description: This test checks the conversion of a valid ChatCompletionChunk object into a ChatCompletion object. It ensures that all fields are correctly mapped and transformed as expected.
Execution:
  Arrange: Create a ChatCompletionChunk object with valid data for all fields, including a list of ChunkChoice objects.
  Act: Call the chunkToChatCompletion method with the created ChatCompletionChunk object.
  Assert: Verify that the returned ChatCompletion object has the same id, created, model, serviceTier, and systemFingerprint as the input chunk. Also, check that the choices list is correctly transformed.
Validation:
  This assertion verifies that the method correctly maps and transforms a valid ChatCompletionChunk into a ChatCompletion, ensuring data integrity and correctness in the conversion process.

Scenario 2: Handle null ChatCompletionChunk input

Details:
  TestName: handleNullChunkInput
  Description: This test checks the behavior of the chunkToChatCompletion method when a null ChatCompletionChunk is passed as input. It ensures that the method handles null inputs gracefully.
Execution:
  Arrange: Set the ChatCompletionChunk input to null.
  Act: Call the chunkToChatCompletion method with the null input.
  Assert: Verify that the method returns null or throws an appropriate exception.
Validation:
  This assertion ensures that the method can handle null inputs without causing unexpected behavior or crashes, maintaining robustness in the application.

Scenario 3: Convert ChatCompletionChunk with empty choices list

Details:
  TestName: convertChunkWithEmptyChoices
  Description: This test checks the conversion of a ChatCompletionChunk object that has an empty choices list. It ensures that the method can handle chunks with no choices.
Execution:
  Arrange: Create a ChatCompletionChunk object with valid data but an empty list of ChunkChoice objects.
  Act: Call the chunkToChatCompletion method with the created ChatCompletionChunk object.
  Assert: Verify that the returned ChatCompletion object has an empty choices list.
Validation:
  This assertion verifies that the method correctly handles chunks with empty choices, ensuring that the conversion process does not introduce errors or unexpected data.

Scenario 4: Convert ChatCompletionChunk with null fields

Details:
  TestName: convertChunkWithNullFields
  Description: This test checks the conversion of a ChatCompletionChunk object where some fields are null. It ensures that the method can handle chunks with missing data.
Execution:
  Arrange: Create a ChatCompletionChunk object with some fields set to null, such as id or model.
  Act: Call the chunkToChatCompletion method with the created ChatCompletionChunk object.
  Assert: Verify that the returned ChatCompletion object has null values for the corresponding fields.
Validation:
  This assertion ensures that the method can handle chunks with null fields, maintaining data integrity and avoiding null pointer exceptions.

Scenario 5: Convert ChatCompletionChunk with multiple choices

Details:
  TestName: convertChunkWithMultipleChoices
  Description: This test checks the conversion of a ChatCompletionChunk object that contains multiple ChunkChoice objects. It ensures that all choices are correctly transformed and included in the ChatCompletion.
Execution:
  Arrange: Create a ChatCompletionChunk object with multiple valid ChunkChoice objects in the choices list.
  Act: Call the chunkToChatCompletion method with the created ChatCompletionChunk object.
  Assert: Verify that the returned ChatCompletion object contains all the choices, correctly transformed.
Validation:
  This assertion verifies that the method can handle chunks with multiple choices, ensuring that all data is accurately converted and included in the final ChatCompletion object.

*/

// ********RoostGPT********

package org.springframework.ai.openai.api;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletion;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionChunk;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionChunk.ChunkChoice;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionFinishReason;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage;
import org.springframework.ai.openai.api.OpenAiApi.LogProbs;
import org.springframework.util.CollectionUtils;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.util.ArrayList;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletion.Choice;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage.ChatCompletionFunction;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage.Role;
import org.springframework.ai.openai.api.OpenAiApi.ChatCompletionMessage.ToolCall;
import org.springframework.ai.openai.api.OpenAiApi.Usage;

class OpenAiStreamFunctionCallingHelperChunkToChatCompletionTest {

	private final OpenAiStreamFunctionCallingHelper helper = new OpenAiStreamFunctionCallingHelper();

	@Test
	@Tag("valid")
	public void convertValidChunkToChatCompletion() {
		// Arrange
		ChatCompletionChunk chunk = mock(ChatCompletionChunk.class);
		ChunkChoice choice = mock(ChunkChoice.class);
		when(chunk.choices()).thenReturn(List.of(choice));
		when(chunk.id()).thenReturn("test-id");
		when(chunk.created()).thenReturn(123456789L);
		when(chunk.model()).thenReturn("test-model");
		when(chunk.serviceTier()).thenReturn("test-tier");
		when(chunk.systemFingerprint()).thenReturn("test-fingerprint");
		// Act
		ChatCompletion result = helper.chunkToChatCompletion(chunk);
		// Assert
		assertNotNull(result);
		assertEquals("test-id", result.id());
		assertEquals(123456789L, result.created());
		assertEquals("test-model", result.model());
		assertEquals("test-tier", result.serviceTier());
		assertEquals("test-fingerprint", result.systemFingerprint());
		assertFalse(CollectionUtils.isEmpty(result.choices()));
	}

	@Test
	@Tag("invalid")
	public void handleNullChunkInput() {
		// Arrange
		ChatCompletionChunk chunk = null;
		// Act & Assert
		assertThrows(NullPointerException.class, () -> helper.chunkToChatCompletion(chunk));
	}

	@Test
	@Tag("boundary")
	public void convertChunkWithEmptyChoices() {
		// Arrange
		ChatCompletionChunk chunk = mock(ChatCompletionChunk.class);
		when(chunk.choices()).thenReturn(List.of());
		when(chunk.id()).thenReturn("test-id");
		when(chunk.created()).thenReturn(123456789L);
		when(chunk.model()).thenReturn("test-model");
		when(chunk.serviceTier()).thenReturn("test-tier");
		when(chunk.systemFingerprint()).thenReturn("test-fingerprint");
		// Act
		ChatCompletion result = helper.chunkToChatCompletion(chunk);
		// Assert
		assertNotNull(result);
		assertTrue(CollectionUtils.isEmpty(result.choices()));
	}

	@Test
	@Tag("boundary")
	public void convertChunkWithNullFields() {
		// Arrange
		ChatCompletionChunk chunk = mock(ChatCompletionChunk.class);
		when(chunk.choices()).thenReturn(List.of());
		when(chunk.id()).thenReturn(null);
		when(chunk.created()).thenReturn(null);
		when(chunk.model()).thenReturn(null);
		when(chunk.serviceTier()).thenReturn(null);
		when(chunk.systemFingerprint()).thenReturn(null);
		// Act
		ChatCompletion result = helper.chunkToChatCompletion(chunk);
		// Assert
		assertNotNull(result);
		assertNull(result.id());
		assertNull(result.created());
		assertNull(result.model());
		assertNull(result.serviceTier());
		assertNull(result.systemFingerprint());
	}

	@Test
	@Tag("valid")
	public void convertChunkWithMultipleChoices() {
		// Arrange
		ChatCompletionChunk chunk = mock(ChatCompletionChunk.class);
		ChunkChoice choice1 = mock(ChunkChoice.class);
		ChunkChoice choice2 = mock(ChunkChoice.class);
		when(chunk.choices()).thenReturn(List.of(choice1, choice2));
		when(chunk.id()).thenReturn("test-id");
		when(chunk.created()).thenReturn(123456789L);
		when(chunk.model()).thenReturn("test-model");
		when(chunk.serviceTier()).thenReturn("test-tier");
		when(chunk.systemFingerprint()).thenReturn("test-fingerprint");
		// Act
		ChatCompletion result = helper.chunkToChatCompletion(chunk);
		// Assert
		assertNotNull(result);
		assertEquals(2, result.choices().size());
	}

}