/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=hashCode_f3b02511e6
ROOST_METHOD_SIG_HASH=hashCode_44411a81c8

Scenario 1: Verify hashCode Consistency for Identical Objects

Details:
  TestName: hashCodeConsistencyForIdenticalObjects
  Description: This test checks that two identical ResponseFormat objects produce the same hash code, ensuring consistency in hash code generation for equal objects.
Execution:
  Arrange: Create two ResponseFormat objects with identical Type and JsonSchema values.
  Act: Call the hashCode method on both objects.
  Assert: Use JUnit assertions to verify that the hash codes of both objects are equal.
Validation:
  This assertion verifies that the hashCode method is consistent with the equals method, which is crucial for the correct functioning of hash-based collections like HashMap.

Scenario 2: Verify hashCode Difference for Different Objects

Details:
  TestName: hashCodeDifferenceForDifferentObjects
  Description: This test checks that two ResponseFormat objects with different Type or JsonSchema values produce different hash codes.
Execution:
  Arrange: Create two ResponseFormat objects with different Type or JsonSchema values.
  Act: Call the hashCode method on both objects.
  Assert: Use JUnit assertions to verify that the hash codes of both objects are not equal.
Validation:
  This assertion ensures that the hashCode method differentiates between non-equal objects, which is essential for maintaining the integrity of hash-based collections.

Scenario 3: Verify hashCode Consistency Over Multiple Calls

Details:
  TestName: hashCodeConsistencyOverMultipleCalls
  Description: This test checks that the hashCode method returns the same value when called multiple times on the same ResponseFormat object.
Execution:
  Arrange: Create a ResponseFormat object with specific Type and JsonSchema values.
  Act: Call the hashCode method multiple times on the same object.
  Assert: Use JUnit assertions to verify that all hash code values are equal.
Validation:
  This assertion confirms that the hashCode method is stable and consistent, which is a fundamental requirement for hash-based collections.

Scenario 4: Verify hashCode with Null Fields

Details:
  TestName: hashCodeWithNullFields
  Description: This test checks the behavior of the hashCode method when the Type and JsonSchema fields are null.
Execution:
  Arrange: Create a ResponseFormat object with null Type and JsonSchema fields.
  Act: Call the hashCode method on the object.
  Assert: Use JUnit assertions to verify the hash code value.
Validation:
  This assertion ensures that the hashCode method can handle null fields gracefully, which is important for robustness and error handling.

Scenario 5: Verify hashCode with Only Type Set

Details:
  TestName: hashCodeWithOnlyTypeSet
  Description: This test checks the behavior of the hashCode method when only the Type field is set, and JsonSchema is null.
Execution:
  Arrange: Create a ResponseFormat object with a specific Type value and a null JsonSchema.
  Act: Call the hashCode method on the object.
  Assert: Use JUnit assertions to verify the hash code value.
Validation:
  This assertion ensures that the hashCode method correctly incorporates the Type field into the hash code calculation, even when JsonSchema is null.

Scenario 6: Verify hashCode with Only JsonSchema Set

Details:
  TestName: hashCodeWithOnlyJsonSchemaSet
  Description: This test checks the behavior of the hashCode method when only the JsonSchema field is set, and Type is null.
Execution:
  Arrange: Create a ResponseFormat object with a specific JsonSchema value and a null Type.
  Act: Call the hashCode method on the object.
  Assert: Use JUnit assertions to verify the hash code value.
Validation:
  This assertion ensures that the hashCode method correctly incorporates the JsonSchema field into the hash code calculation, even when Type is null.

*/

// ********RoostGPT********
package org.springframework.ai.openai.api;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import org.junit.jupiter.api.*;
import java.util.Map;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.ai.model.ModelOptionsUtils;
import org.springframework.util.StringUtils;

public class ResponseFormatHashCodeTest {

	private enum Type {

		JSON, XML

	}

	private static class JsonSchema {

		private String schema;

		private boolean strict;

		private JsonSchema(String schema, boolean strict) {
			this.schema = schema;
			this.strict = strict;
		}

		public static Builder builder() {
			return new Builder();
		}

		public static class Builder {

			private String schema;

			private boolean strict;

			public Builder schema(String schema) {
				this.schema = schema;
				return this;
			}

			public Builder strict(boolean strict) {
				this.strict = strict;
				return this;
			}

			public JsonSchema build() {
				return new JsonSchema(schema, strict);
			}

		}

	}

	private static class ResponseFormat {

		private Type type;

		private JsonSchema jsonSchema;

		public ResponseFormat() {
		}

		private ResponseFormat(Type type, JsonSchema jsonSchema) {
			this.type = type;
			this.jsonSchema = jsonSchema;
		}

		public ResponseFormat(Type type, String schema) {
			this(type, StringUtils.hasText(schema) ? JsonSchema.builder().schema(schema).strict(true).build() : null);
		}

		@Override
		public int hashCode() {
			return Objects.hash(this.type, this.jsonSchema);
		}

	}

	@Test
	@Tag("valid")
	public void hashCodeConsistencyForIdenticalObjects() {
		Type type = Type.JSON;
		JsonSchema jsonSchema = JsonSchema.builder().schema("schema1").strict(true).build();
		ResponseFormat responseFormat1 = new ResponseFormat(type, jsonSchema);
		ResponseFormat responseFormat2 = new ResponseFormat(type, jsonSchema);
		assertEquals(responseFormat1.hashCode(), responseFormat2.hashCode());
	}

	@Test
	@Tag("valid")
	public void hashCodeDifferenceForDifferentObjects() {
		Type type1 = Type.JSON;
		Type type2 = Type.XML;
		JsonSchema jsonSchema1 = JsonSchema.builder().schema("schema1").strict(true).build();
		JsonSchema jsonSchema2 = JsonSchema.builder().schema("schema2").strict(false).build();
		ResponseFormat responseFormat1 = new ResponseFormat(type1, jsonSchema1);
		ResponseFormat responseFormat2 = new ResponseFormat(type2, jsonSchema2);
		assertNotEquals(responseFormat1.hashCode(), responseFormat2.hashCode());
	}

	@Test
	@Tag("valid")
	public void hashCodeConsistencyOverMultipleCalls() {
		Type type = Type.JSON;
		JsonSchema jsonSchema = JsonSchema.builder().schema("schema1").strict(true).build();
		ResponseFormat responseFormat = new ResponseFormat(type, jsonSchema);
		int hashCode1 = responseFormat.hashCode();
		int hashCode2 = responseFormat.hashCode();
		int hashCode3 = responseFormat.hashCode();
		assertEquals(hashCode1, hashCode2);
		assertEquals(hashCode2, hashCode3);
	}

	@Test
	@Tag("boundary")
	public void hashCodeWithNullFields() {
		ResponseFormat responseFormat = new ResponseFormat();
		int hashCode = responseFormat.hashCode();
		assertEquals(hashCode, responseFormat.hashCode());
	}

	@Test
	@Tag("boundary")
	public void hashCodeWithOnlyTypeSet() {
		Type type = Type.JSON;
		ResponseFormat responseFormat = new ResponseFormat(type, (JsonSchema) null);
		int hashCode = responseFormat.hashCode();
		assertEquals(hashCode, responseFormat.hashCode());
	}

	@Test
	@Tag("boundary")
	public void hashCodeWithOnlyJsonSchemaSet() {
		JsonSchema jsonSchema = JsonSchema.builder().schema("schema1").strict(true).build();
		ResponseFormat responseFormat = new ResponseFormat(null, jsonSchema);
		int hashCode = responseFormat.hashCode();
		assertEquals(hashCode, responseFormat.hashCode());
	}

}