/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=getText_5141af9b3b
ROOST_METHOD_SIG_HASH=getText_5a895d3c65

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientIT.java
Tests:
    "@Test
@Test
void call() {

    ChatResponse response = ChatClient.create(this.chatModel).prompt().advisors(new SimpleLoggerAdvisor()).system(s -> s.text(this.systemTextResource).param("name", "Bob").param("voice", "pirate")).user("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did").call().chatResponse();

    logger.info("" + response);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void beanStreamOutputConverterRecords() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);

    Flux<ChatResponse> chatResponse = ChatClient.create(this.chatModel).prompt().options(OpenAiChatOptions.builder().streamUsage(true).build()).advisors(new SimpleLoggerAdvisor()).user(u -> u.text("Generate the filmography of 5 movies for Tom Hanks. " + System.lineSeparator() + "{format}").param("format", outputConverter.getFormat())).stream().chatResponse();
    List<ChatResponse> chatResponses = chatResponse.collectList().block().stream().toList();
    String generationTextFromStream = chatResponses.stream().filter(cr -> cr.getResult() != null).map(cr -> cr.getResult().getOutput().getText()).collect(Collectors.joining());

    ActorsFilms actorsFilms = outputConverter.convert(generationTextFromStream);
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientProxyFunctionCallsIT.java
Tests:
    "@Test
@Test
void toolProxyFunctionCall() throws JsonMappingException, JsonProcessingException {
    List<Message> messages = List.of(new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?"));
    boolean isToolCall = false;
    ChatResponse chatResponse = null;
    var chatClient = ChatClient.builder(this.chatModel).build();
    do {
        chatResponse = chatClient.prompt().messages(messages).tools(this.functionDefinition).options(OpenAiChatOptions.builder().proxyToolCalls(true).build()).call().chatResponse();


        isToolCall = this.functionCallingHelper.isToolCall(chatResponse, Set.of(OpenAiApi.ChatCompletionFinishReason.TOOL_CALLS.name(), OpenAiApi.ChatCompletionFinishReason.STOP.name()));
        if (isToolCall) {
            Optional<Generation> toolCallGeneration = chatResponse.getResults().stream().filter(g -> !CollectionUtils.isEmpty(g.getOutput().getToolCalls())).findFirst();
            assertThat(toolCallGeneration).isNotEmpty();
            AssistantMessage assistantMessage = toolCallGeneration.get().getOutput();
            List<ToolResponseMessage.ToolResponse> toolResponses = new ArrayList<>();
            for (AssistantMessage.ToolCall toolCall : assistantMessage.getToolCalls()) {
                var functionName = toolCall.name();
                assertThat(functionName).isEqualTo("getWeatherInLocation");
                String functionArguments = toolCall.arguments();
                @SuppressWarnings("unchecked")
                Map<String, String> argumentsMap = new ObjectMapper().readValue(functionArguments, Map.class);
                String functionResponse = getWeatherInLocation(argumentsMap.get("location").toString(), argumentsMap.get("unit").toString());
                toolResponses.add(new ToolResponseMessage.ToolResponse(toolCall.id(), functionName, ModelOptionsUtils.toJsonString(functionResponse)));
            }
            ToolResponseMessage toolMessageResponse = new ToolResponseMessage(toolResponses, Map.of());
            messages = this.functionCallingHelper.buildToolCallConversation(messages, assistantMessage, toolMessageResponse);
            assertThat(messages).isNotEmpty();

        }
    } while (isToolCall);
    logger.info("Response: {}", chatResponse);
    assertThat(chatResponse.getResult().getOutput().getText()).contains("30", "10", "15");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/DeepSeekWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<DeepSeekWithOpenAiChatModelIT.ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(DeepSeekWithOpenAiChatModelIT.ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    DeepSeekWithOpenAiChatModelIT.ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("{}", actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@Test
@Disabled("The current version of the deepseek-chat model's Function Calling capability is unstable, which may result in looped calls or empty responses.")
void functionCallTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiRetryTests.java
Tests:
    "@Test
@Test
public void openAiChatTransientError() {
    var choice = new ChatCompletion.Choice(ChatCompletionFinishReason.STOP, 0, new ChatCompletionMessage("Response", Role.ASSISTANT), null);
    ChatCompletion expectedChatCompletion = new ChatCompletion("id", List.of(choice), 666L, "model", null, null, null, new OpenAiApi.Usage(10, 10, 10));
    given(this.openAiApi.chatCompletionEntity(isA(ChatCompletionRequest.class), any())).willThrow(new TransientAiException("Transient Error 1")).willThrow(new TransientAiException("Transient Error 2")).willReturn(ResponseEntity.of(Optional.of(expectedChatCompletion)));
    var result = this.chatModel.call(new Prompt("text"));
    assertThat(result).isNotNull();
    assertThat(result.getResult().getOutput().getText()).isSameAs("Response");
    assertThat(this.retryListener.onSuccessRetryCount).isEqualTo(2);
    assertThat(this.retryListener.onErrorRetryCount).isEqualTo(2);
}
"
    "@Test
@Test
@Disabled("Currently stream() does not implmement retry")
public void openAiChatStreamTransientError() {
    var choice = new ChatCompletionChunk.ChunkChoice(ChatCompletionFinishReason.STOP, 0, new ChatCompletionMessage("Response", Role.ASSISTANT), null);
    ChatCompletionChunk expectedChatCompletion = new ChatCompletionChunk("id", List.of(choice), 666L, "model", null, null, null, null);
    given(this.openAiApi.chatCompletionStream(isA(ChatCompletionRequest.class), any())).willThrow(new TransientAiException("Transient Error 1")).willThrow(new TransientAiException("Transient Error 2")).willReturn(Flux.just(expectedChatCompletion));
    var result = this.chatModel.stream(new Prompt("text"));
    assertThat(result).isNotNull();
    assertThat(result.collectList().block().get(0).getResult().getOutput().getText()).isSameAs("Response");
    assertThat(this.retryListener.onSuccessRetryCount).isEqualTo(2);
    assertThat(this.retryListener.onErrorRetryCount).isEqualTo(2);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/PerplexityWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {


    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    Prompt prompt = new Prompt(List.of(systemMessage, userMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under the key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
@Disabled("Perplexity gets confused with the 'Generate the filmography for a random actor.' prompt")
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelTypeReferenceBeanOutputConverterIT.java
Tests:
    "@Test
@Test
void typeRefOutputConverterRecords() {
    BeanOutputConverter<List<ActorsFilmsRecord>> outputConverter = new BeanOutputConverter<>(new ParameterizedTypeReference<List<ActorsFilmsRecord>>() {
    });
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks and Bill Murray.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<ActorsFilmsRecord> actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms).hasSize(2);
    assertThat(actorsFilms.get(0).actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.get(0).movies()).hasSize(5);
    assertThat(actorsFilms.get(1).actor()).isEqualTo("Bill Murray");
    assertThat(actorsFilms.get(1).movies()).hasSize(5);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiCompatibleChatModelIT.java
Tests:
    "@Test
@ParameterizedTest
@MethodSource("openAiCompatibleApis")
void chatCompletion(ChatModel chatModel) {
    Prompt prompt = new Prompt(this.conversation);
    ChatResponse response = chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/OllamaWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "llama3.1:latest", "llama3.2:latest" })
void functionCallTest(String modelName) {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris? Return the temperature in Celsius.");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().model(modelName).

    toolChoice("auto").toolCallbacks(List.of(FunctionToolCallback.builder("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "llava" })
void multiModalityEmbeddedImage(String modelName) throws IOException {
    var imageData = new ClassPathResource("/test.png");
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(new Media(MimeTypeUtils.IMAGE_PNG, imageData)));
    var response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"
    "@Test
@Disabled("Not supported by the current Ollama API")
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "llava" })
void multiModalityImageUrl(String modelName) throws IOException {
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(Media.builder().mimeType(MimeTypeUtils.IMAGE_PNG).data(new URL("https:
    ChatResponse response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/testutils/AbstractIT.java
Tests:
    "@Test
protected void evaluateQuestionAndAnswer(String question, ChatResponse response, boolean factBased) {
    assertThat(response).isNotNull();
    String answer = response.getResult().getOutput().getText();
    logger.info("Question: " + question);
    logger.info("Answer:" + answer);
    PromptTemplate userPromptTemplate = new PromptTemplate(this.userEvaluatorResource, Map.of("question", question, "answer", answer));
    SystemMessage systemMessage;
    if (factBased) {
        systemMessage = new SystemMessage(this.qaEvaluatorFactBasedAnswerResource);
    } else {
        systemMessage = new SystemMessage(this.qaEvaluatorAccurateAnswerResource);
    }
    Message userMessage = userPromptTemplate.createMessage();
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    String yesOrNo = this.chatModel.call(prompt).getResult().getOutput().getText();
    logger.info("Is Answer related to question: " + yesOrNo);
    if (yesOrNo.equalsIgnoreCase("no")) {
        SystemMessage notRelatedSystemMessage = new SystemMessage(this.qaEvaluatorNotRelatedResource);
        prompt = new Prompt(List.of(userMessage, notRelatedSystemMessage));
        String reasonForFailure = this.chatModel.call(prompt).getResult().getOutput().getText();
        fail(reasonForFailure);
    } else {
        logger.info("Answer is related to question.");
        assertThat(yesOrNo).isEqualTo("YES");
    }
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelObservationIT.java
Tests:
    "@Test
@Test
void observationForChatOperation() {
    var options = OpenAiChatOptions.builder().model(OpenAiApi.ChatModel.GPT_4_O_MINI.getValue()).frequencyPenalty(0.0).maxTokens(2048).presencePenalty(0.0).stop(List.of("this-is-the-end")).temperature(0.7).topP(1.0).build();
    Prompt prompt = new Prompt("Why does a raven look like a desk?", options);
    ChatResponse chatResponse = this.chatModel.call(prompt);
    assertThat(chatResponse.getResult().getOutput().getText()).isNotEmpty();
    ChatResponseMetadata responseMetadata = chatResponse.getMetadata();
    assertThat(responseMetadata).isNotNull();
    validate(responseMetadata);
}
"
    "@Test
@Test
void observationForStreamingChatOperation() {
    var options = OpenAiChatOptions.builder().model(OpenAiApi.ChatModel.GPT_4_O_MINI.getValue()).frequencyPenalty(0.0).maxTokens(2048).presencePenalty(0.0).stop(List.of("this-is-the-end")).temperature(0.7).topP(1.0).streamUsage(true).build();
    Prompt prompt = new Prompt("Why does a raven look like a desk?", options);
    Flux<ChatResponse> chatResponseFlux = this.chatModel.stream(prompt);
    List<ChatResponse> responses = chatResponseFlux.collectList().block();
    assertThat(responses).isNotEmpty();
    assertThat(responses).hasSizeGreaterThan(10);
    String aggregatedResponse = responses.subList(0, responses.size() - 1).stream().map(r -> r.getResult().getOutput().getText()).collect(Collectors.joining());
    assertThat(aggregatedResponse).isNotEmpty();
    ChatResponse lastChatResponse = responses.get(responses.size() - 1);
    ChatResponseMetadata responseMetadata = lastChatResponse.getMetadata();
    assertThat(responseMetadata).isNotNull();
    validate(responseMetadata);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelFunctionCallingIT.java
Tests:
    "@Test
void functionCallTest(OpenAiChatOptions promptOptions) {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/acme/AcmeIT.java
Tests:
    "@Test
private Message getSystemMessage(List<Document> similarDocuments) {
    String documents = similarDocuments.stream().map(entry -> entry.getText()).collect(Collectors.joining(System.lineSeparator()));
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemBikePrompt);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("documents", documents));
    return systemMessage;
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/MistralWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "mistral-small-latest", "mistral-large-latest" })
void functionCallTest(String modelName) {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris? Response in Celsius\"");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().model(modelName).toolCallbacks(List.of(FunctionToolCallback.builder("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"
    "@Test
@Disabled("Mistral AI does not support multi modality API")
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "mistral-small-latest" })
void multiModalityEmbeddedImage(String modelName) throws IOException {
    var imageData = new ClassPathResource("/test.png");
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(new Media(MimeTypeUtils.IMAGE_PNG, imageData)));
    var response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"
    "@Test
@Disabled("Mistral AI does not support multi modality API")
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "mistral-small-latest" })
void multiModalityImageUrl(String modelName) throws IOException {
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(Media.builder().mimeType(MimeTypeUtils.IMAGE_PNG).data(new URL("https:
    ChatResponse response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).contains("bananas", "apple");
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bowl", "basket");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/NvidiaWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@Test
void functionCallTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");

}
"
    "@Test
@Test
void testMessageHistory() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and why they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("Blackbeard", "Bartholomew");
    var promptWithMessageHistory = new Prompt(List.of(new UserMessage("Dummy"), response.getResult().getOutput(), new UserMessage("Repeat the last assistant message.")));
    response = this.chatModel.call(promptWithMessageHistory);
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("Blackbeard", "Bartholomew");
}
"
    "@Test
@Test
void streamCompletenessTest() throws InterruptedException {
    UserMessage userMessage = new UserMessage("List ALL natural numbers in range [1, 1000]. Make sure to not omit any.");
    Prompt prompt = new Prompt(List.of(userMessage));
    StringBuilder answer = new StringBuilder();
    CountDownLatch latch = new CountDownLatch(1);
    Flux<ChatResponse> chatResponseFlux = this.streamingChatModel.stream(prompt).doOnNext(chatResponse -> {
        String responseContent = chatResponse.getResults().get(0).getOutput().getText();
        answer.append(responseContent);
    }).doOnComplete(() -> {
        logger.info(answer.toString());
        latch.countDown();
    });
    chatResponseFlux.subscribe();
    assertThat(latch.await(120, TimeUnit.SECONDS)).isTrue();
    IntStream.rangeClosed(1, 1000).forEach(n -> assertThat(answer).contains(String.valueOf(n)));
}
"
    "@Test
@Test
void streamCompletenessTestWithChatResponse() throws InterruptedException {
    UserMessage userMessage = new UserMessage("Who is George Washington? - use first as 1st");
    Prompt prompt = new Prompt(List.of(userMessage));
    StringBuilder answer = new StringBuilder();
    CountDownLatch latch = new CountDownLatch(1);
    ChatClient chatClient = ChatClient.builder(this.openAiChatModel).build();
    Flux<ChatResponse> chatResponseFlux = chatClient.prompt(prompt).stream().chatResponse().doOnNext(chatResponse -> {
        String responseContent = chatResponse.getResults().get(0).getOutput().getText();
        answer.append(responseContent);
    }).doOnComplete(() -> {
        logger.info(answer.toString());
        latch.countDown();
    });
    chatResponseFlux.subscribe();
    assertThat(latch.await(120, TimeUnit.SECONDS)).isTrue();
    assertThat(answer).contains("1st ");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@Test
@Deprecated
void functionCallTestDeprecated() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().model(OpenAiApi.ChatModel.GPT_4_O.getValue()).functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("30.0", "30");
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("10.0", "10");
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("15.0", "15");
}
"
    "@Test
@Test
void functionCallTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().model(OpenAiApi.ChatModel.GPT_4_O.getValue()).toolCallbacks(List.of(FunctionToolCallback.builder("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "gpt-4o" })
void multiModalityEmbeddedImage(String modelName) throws IOException {
    var imageData = new ClassPathResource("/test.png");
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(new Media(MimeTypeUtils.IMAGE_PNG, imageData)));
    var response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "gpt-4o" })
void multiModalityImageUrl(String modelName) throws IOException {
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(Media.builder().mimeType(MimeTypeUtils.IMAGE_PNG).data(new URL("https:
    ChatResponse response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "gpt-4o-audio-preview" })
void multiModalityOutputAudio(String modelName) throws IOException {
    var userMessage = new UserMessage("Tell me joke about Spring Framework");
    ChatResponse response = chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).outputModalities(List.of("text", "audio")).outputAudio(new AudioParameters(Voice.ALLOY, AudioResponseFormat.WAV)).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).isNotEmpty();
    byte[] audio = response.getResult().getOutput().getMedia().get(0).getDataAsByteArray();
    assertThat(audio).isNotEmpty();

}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "gpt-4o-audio-preview" })
void multiModalityInputAudio(String modelName) {
    var audioResource = new ClassPathResource("speech1.mp3");
    var userMessage = new UserMessage("What is this recording about?", List.of(new Media(MimeTypeUtils.parseMimeType("audio/mp3"), audioResource)));
    ChatResponse response = chatModel.call(new Prompt(List.of(userMessage), ChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsIgnoringCase("hobbits");
    assertThat(response.getMetadata().getModel()).containsIgnoringCase(modelName);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/GroqWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@Test
void functionCallTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"
    "@Test
@Disabled("Groq does not support multi modality API")
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "llama3-70b-8192" })
void multiModalityEmbeddedImage(String modelName) throws IOException {
    var imageData = new ClassPathResource("/test.png");
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(new Media(MimeTypeUtils.IMAGE_PNG, imageData)));
    var response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"
    "@Test
@Disabled("Groq does not support multi modality API")
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "llama3-70b-8192" })
void multiModalityImageUrl(String modelName) throws IOException {
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(Media.builder().mimeType(MimeTypeUtils.IMAGE_PNG).data(new URL("https:
    ChatResponse response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelResponseFormatIT.java
Tests:
    "@Test
@Test
void jsonObject() throws JsonMappingException, JsonProcessingException {







    Prompt prompt = new Prompt("List 8 planets. Use JSON response", OpenAiChatOptions.builder().responseFormat(ResponseFormat.builder().type(ResponseFormat.Type.JSON_OBJECT).build()).build());
    ChatResponse response = this.openAiChatModel.call(prompt);
    assertThat(response).isNotNull();
    String content = response.getResult().getOutput().getText();
    logger.info("Response content: {}", content);
    assertThat(isValidJson(content)).isTrue();
}
"
    "@Test
@Test
void jsonSchema() throws JsonMappingException, JsonProcessingException {
    var jsonSchema = """
        {
        	"type": "object",
        	"properties": {
        		"steps": {
        			"type": "array",
        			"items": {
        				"type": "object",
        				"properties": {
        					"explanation": { "type": "string" },
        					"output": { "type": "string" }
        				},
        				"required": ["explanation", "output"],
        				"additionalProperties": false
        			}
        		},
        		"final_answer": { "type": "string" }
        	},
        	"required": ["steps", "final_answer"],
        	"additionalProperties": false
        }
        """;
    Prompt prompt = new Prompt("how can I solve 8x + 7 = -23", OpenAiChatOptions.builder().model(ChatModel.GPT_4_O_MINI).responseFormat(new ResponseFormat(ResponseFormat.Type.JSON_SCHEMA, jsonSchema)).build());
    ChatResponse response = this.openAiChatModel.call(prompt);
    assertThat(response).isNotNull();
    String content = response.getResult().getOutput().getText();
    logger.info("Response content: {}", content);
    assertThat(isValidJson(content)).isTrue();
}
"
    "@Test
@Test
void jsonSchemaBeanConverter() throws JsonMappingException, JsonProcessingException {
    @JsonPropertyOrder({ "steps", "final_answer" })
    record MathReasoning(@JsonProperty(required = true, value = "steps") Steps steps, @JsonProperty(required = true, value = "final_answer") String finalAnswer) {

        record Steps(@JsonProperty(required = true, value = "items") Items[] items) {

            @JsonPropertyOrder({ "output", "explanation" })
            record Items(@JsonProperty(required = true, value = "explanation") String explanation, @JsonProperty(required = true, value = "output") String output) {
            }
        }
    }
    var outputConverter = new BeanOutputConverter<>(MathReasoning.class);


    var expectedJsonSchema = """
        {
          "$schema" : "https:
          "type" : "object",
          "properties" : {
            "steps" : {
              "type" : "object",
              "properties" : {
                "items" : {
                  "type" : "array",
                  "items" : {
                    "type" : "object",
                    "properties" : {
                      "output" : {
                        "type" : "string"
                      },
                      "explanation" : {
                        "type" : "string"
                      }
                    },
                    "required" : [ "output", "explanation" ],
                    "additionalProperties" : false
                  }
                }
              },
              "required" : [ "items" ],
              "additionalProperties" : false
            },
            "final_answer" : {
              "type" : "string"
            }
          },
          "required" : [ "steps", "final_answer" ],
          "additionalProperties" : false
        }""";


    var jsonSchema1 = outputConverter.getJsonSchema();
    assertThat(jsonSchema1).isNotNull();
    assertThat(jsonSchema1).isEqualTo(expectedJsonSchema);
    Prompt prompt = new Prompt("how can I solve 8x + 7 = -23", OpenAiChatOptions.builder().model(ChatModel.GPT_4_O_MINI).responseFormat(new ResponseFormat(ResponseFormat.Type.JSON_SCHEMA, jsonSchema1)).build());
    ChatResponse response = this.openAiChatModel.call(prompt);
    assertThat(response).isNotNull();
    String content = response.getResult().getOutput().getText();
    logger.info("Response content: {}", content);
    assertThat(isValidJson(content)).isTrue();


    assertThat(content.startsWith("{\"steps\":{\"items\":["));
    MathReasoning mathReasoning = outputConverter.convert(content);
    assertThat(mathReasoning).isNotNull();
    logger.info(mathReasoning.toString());
}
"
Scenario 1: Retrieve Text When Text is Null

Details:
  TestName: retrieveTextWhenTextIsNull
  Description: This test checks the behavior of the getText method when the text field is null. It ensures that the method returns null in this scenario.
Execution:
  Arrange: Create an instance of the SpeechMessage class with the text field set to null.
  Act: Call the getText method on the instance.
  Assert: Use JUnit assertions to verify that the returned value is null.
Validation:
  This assertion verifies that the getText method correctly handles the case where the text field is null, which is important for ensuring robustness in scenarios where the text might not be initialized.

Scenario 2: Retrieve Text When Text is Empty String

Details:
  TestName: retrieveTextWhenTextIsEmptyString
  Description: This test checks the behavior of the getText method when the text field is an empty string. It ensures that the method returns an empty string in this scenario.
Execution:
  Arrange: Create an instance of the SpeechMessage class with the text field set to an empty string.
  Act: Call the getText method on the instance.
  Assert: Use JUnit assertions to verify that the returned value is an empty string.
Validation:
  This assertion verifies that the getText method correctly handles the case where the text field is an empty string, which is important for ensuring that the method can handle edge cases gracefully.

Scenario 3: Retrieve Text When Text is a Non-Empty String

Details:
  TestName: retrieveTextWhenTextIsNonEmptyString
  Description: This test checks the behavior of the getText method when the text field contains a non-empty string. It ensures that the method returns the correct string.
Execution:
  Arrange: Create an instance of the SpeechMessage class with the text field set to a non-empty string, such as "Hello, World!".
  Act: Call the getText method on the instance.
  Assert: Use JUnit assertions to verify that the returned value matches the string "Hello, World!".
Validation:
  This assertion verifies that the getText method correctly returns the value of the text field when it contains a valid string, which is crucial for the method's primary functionality.

Scenario 4: Retrieve Text After Setting a New Value

Details:
  TestName: retrieveTextAfterSettingNewValue
  Description: This test checks the behavior of the getText method after the text field has been updated using the setText method. It ensures that the method returns the updated string.
Execution:
  Arrange: Create an instance of the SpeechMessage class and set the text field to a specific string using the setText method.
  Act: Call the getText method on the instance.
  Assert: Use JUnit assertions to verify that the returned value matches the string set by the setText method.
Validation:
  This assertion verifies that the getText method reflects changes made to the text field, ensuring that the class maintains consistency between its methods.

Scenario 5: Retrieve Text After Setting Null Value

Details:
  TestName: retrieveTextAfterSettingNullValue
  Description: This test checks the behavior of the getText method after the text field has been set to null using the setText method. It ensures that the method returns null.
Execution:
  Arrange: Create an instance of the SpeechMessage class and set the text field to null using the setText method.
  Act: Call the getText method on the instance.
  Assert: Use JUnit assertions to verify that the returned value is null.
Validation:
  This assertion verifies that the getText method correctly handles the scenario where the text field is explicitly set to null, ensuring that the method can handle null values appropriately.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class SpeechMessageGetTextTest {

	@Test
	@Tag("valid")
	public void retrieveTextWhenTextIsNull() {
		// Arrange
		SpeechMessage message = new SpeechMessage(null);

		// Act
		String result = message.getText();

		// Assert
		assertNull(result);
	}

	@Test
	@Tag("boundary")
	public void retrieveTextWhenTextIsEmptyString() {
		// Arrange
		SpeechMessage message = new SpeechMessage("");

		// Act
		String result = message.getText();

		// Assert
		assertEquals("", result);
	}

	@Test
	@Tag("valid")
	public void retrieveTextWhenTextIsNonEmptyString() {
		// Arrange
		SpeechMessage message = new SpeechMessage("Hello, World!");

		// Act
		String result = message.getText();

		// Assert
		assertEquals("Hello, World!", result);
	}

	@Test
	@Tag("valid")
	public void retrieveTextAfterSettingNewValue() {
		// Arrange
		SpeechMessage message = new SpeechMessage("Initial Text");
		message.setText("Updated Text");

		// Act
		String result = message.getText();

		// Assert
		assertEquals("Updated Text", result);
	}

	@Test
	@Tag("invalid")
	public void retrieveTextAfterSettingNullValue() {
		// Arrange
		SpeechMessage message = new SpeechMessage("Some Text");
		message.setText(null);

		// Act
		String result = message.getText();

		// Assert
		assertNull(result);
	}

}