/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=getOutput_c67006ea9e
ROOST_METHOD_SIG_HASH=getOutput_83d08162e3

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/speech/OpenAiSpeechModelWithSpeechResponseMetadataTests.java
Tests:
    "@Test
@Test
void aiResponseContainsImageResponseMetadata() {
    prepareMock();
    OpenAiAudioSpeechOptions speechOptions = OpenAiAudioSpeechOptions.builder().voice(OpenAiAudioApi.SpeechRequest.Voice.ALLOY).speed(SPEED).responseFormat(OpenAiAudioApi.SpeechRequest.AudioResponseFormat.MP3).model(OpenAiAudioApi.TtsModel.TTS_1.value).build();
    SpeechPrompt speechPrompt = new SpeechPrompt("Today is a wonderful day to build something people love!", speechOptions);
    SpeechResponse response = this.openAiSpeechClient.call(speechPrompt);
    byte[] audioBytes = response.getResult().getOutput();
    assertThat(audioBytes).hasSizeGreaterThan(0);
    OpenAiAudioSpeechResponseMetadata speechResponseMetadata = response.getMetadata();
    assertThat(speechResponseMetadata).isNotNull();
    var requestLimit = speechResponseMetadata.getRateLimit();
    Long requestsLimit = requestLimit.getRequestsLimit();
    Long tokensLimit = requestLimit.getTokensLimit();
    Long tokensRemaining = requestLimit.getTokensRemaining();
    Long requestsRemaining = requestLimit.getRequestsRemaining();
    Duration requestsReset = requestLimit.getRequestsReset();
    assertThat(requestsLimit).isNotNull();
    assertThat(requestsLimit).isEqualTo(4000L);
    assertThat(tokensLimit).isEqualTo(725000L);
    assertThat(tokensRemaining).isEqualTo(112358L);
    assertThat(requestsRemaining).isEqualTo(999L);
    assertThat(requestsReset).isEqualTo(Duration.parse("PT64H15M29S"));
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientIT.java
Tests:
    "@Test
@Test
void call() {

    ChatResponse response = ChatClient.create(this.chatModel).prompt().advisors(new SimpleLoggerAdvisor()).system(s -> s.text(this.systemTextResource).param("name", "Bob").param("voice", "pirate")).user("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did").call().chatResponse();

    logger.info("" + response);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void beanStreamOutputConverterRecords() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);

    Flux<ChatResponse> chatResponse = ChatClient.create(this.chatModel).prompt().options(OpenAiChatOptions.builder().streamUsage(true).build()).advisors(new SimpleLoggerAdvisor()).user(u -> u.text("Generate the filmography of 5 movies for Tom Hanks. " + System.lineSeparator() + "{format}").param("format", outputConverter.getFormat())).stream().chatResponse();
    List<ChatResponse> chatResponses = chatResponse.collectList().block().stream().toList();
    String generationTextFromStream = chatResponses.stream().filter(cr -> cr.getResult() != null).map(cr -> cr.getResult().getOutput().getText()).collect(Collectors.joining());

    ActorsFilms actorsFilms = outputConverter.convert(generationTextFromStream);
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@Test
void multiModalityAudioResponse() {
    ChatResponse response = ChatClient.create(this.chatModel).prompt("Tell me joke about Spring Framework").options(OpenAiChatOptions.builder().model(OpenAiApi.ChatModel.GPT_4_O_AUDIO_PREVIEW).outputAudio(new AudioParameters(AudioParameters.Voice.ALLOY, AudioParameters.AudioResponseFormat.WAV)).outputModalities(List.of("text", "audio")).build()).call().chatResponse();
    assertThat(response).isNotNull();
    assertThat(response.getResult().getOutput().getMedia().get(0).getDataAsByteArray()).isNotEmpty();
    logger.info("Response: " + response);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientProxyFunctionCallsIT.java
Tests:
    "@Test
@Test
void toolProxyFunctionCall() throws JsonMappingException, JsonProcessingException {
    List<Message> messages = List.of(new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?"));
    boolean isToolCall = false;
    ChatResponse chatResponse = null;
    var chatClient = ChatClient.builder(this.chatModel).build();
    do {
        chatResponse = chatClient.prompt().messages(messages).tools(this.functionDefinition).options(OpenAiChatOptions.builder().proxyToolCalls(true).build()).call().chatResponse();


        isToolCall = this.functionCallingHelper.isToolCall(chatResponse, Set.of(OpenAiApi.ChatCompletionFinishReason.TOOL_CALLS.name(), OpenAiApi.ChatCompletionFinishReason.STOP.name()));
        if (isToolCall) {
            Optional<Generation> toolCallGeneration = chatResponse.getResults().stream().filter(g -> !CollectionUtils.isEmpty(g.getOutput().getToolCalls())).findFirst();
            assertThat(toolCallGeneration).isNotEmpty();
            AssistantMessage assistantMessage = toolCallGeneration.get().getOutput();
            List<ToolResponseMessage.ToolResponse> toolResponses = new ArrayList<>();
            for (AssistantMessage.ToolCall toolCall : assistantMessage.getToolCalls()) {
                var functionName = toolCall.name();
                assertThat(functionName).isEqualTo("getWeatherInLocation");
                String functionArguments = toolCall.arguments();
                @SuppressWarnings("unchecked")
                Map<String, String> argumentsMap = new ObjectMapper().readValue(functionArguments, Map.class);
                String functionResponse = getWeatherInLocation(argumentsMap.get("location").toString(), argumentsMap.get("unit").toString());
                toolResponses.add(new ToolResponseMessage.ToolResponse(toolCall.id(), functionName, ModelOptionsUtils.toJsonString(functionResponse)));
            }
            ToolResponseMessage toolMessageResponse = new ToolResponseMessage(toolResponses, Map.of());
            messages = this.functionCallingHelper.buildToolCallConversation(messages, assistantMessage, toolMessageResponse);
            assertThat(messages).isNotEmpty();

        }
    } while (isToolCall);
    logger.info("Response: {}", chatResponse);
    assertThat(chatResponse.getResult().getOutput().getText()).contains("30", "10", "15");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/transcription/TranscriptionModelTests.java
Tests:
    "@Test
@Test
void transcrbeRequestReturnsResponseCorrectly() {
    Resource mockAudioFile = Mockito.mock(Resource.class);
    OpenAiAudioTranscriptionModel mockClient = Mockito.mock(OpenAiAudioTranscriptionModel.class);
    String mockTranscription = "All your bases are belong to us";

    AudioTranscription transcript = Mockito.mock(AudioTranscription.class);
    given(transcript.getOutput()).willReturn(mockTranscription);

    AudioTranscriptionResponse response = Mockito.mock(AudioTranscriptionResponse.class);
    given(response.getResult()).willReturn(transcript);



    doCallRealMethod().when(mockClient).call(any(Resource.class));
    given(mockClient.call(any(AudioTranscriptionPrompt.class))).will(invocation -> {
        AudioTranscriptionPrompt transcriptionRequest = invocation.getArgument(0);
        assertThat(transcriptionRequest).isNotNull();
        assertThat(transcriptionRequest.getInstructions()).isEqualTo(mockAudioFile);
        return response;
    });
    assertThat(mockClient.call(mockAudioFile)).isEqualTo(mockTranscription);
    verify(mockClient, times(1)).call(eq(mockAudioFile));
    verify(mockClient, times(1)).call(isA(AudioTranscriptionPrompt.class));
    verify(response, times(1)).getResult();
    verify(transcript, times(1)).getOutput();
    verifyNoMoreInteractions(mockClient, transcript, response);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/moderation/OpenAiModerationModelIT.java
Tests:
    "@Test
@Test
void moderationAsUrlTestPositive() {
    var options = ModerationOptionsBuilder.builder().model("text-moderation-stable").build();
    var instructions = """
        I want to kill them.!".""";
    ModerationPrompt moderationPrompt = new ModerationPrompt(instructions, options);
    ModerationResponse moderationResponse = this.openAiModerationModel.call(moderationPrompt);
    assertThat(moderationResponse.getResults()).hasSize(1);
    var generation = moderationResponse.getResult();
    Moderation moderation = generation.getOutput();
    assertThat(moderation.getId()).isNotEmpty();
    assertThat(moderation.getResults()).isNotNull();
    assertThat(moderation.getResults().size()).isNotZero();
    System.out.println(moderation.getResults().toString());
    assertThat(moderation.getId()).isNotNull();
    assertThat(moderation.getModel()).isNotNull();
    ModerationResult result = moderation.getResults().get(0);
    assertThat(result.isFlagged()).isTrue();
    Categories categories = result.getCategories();
    assertThat(categories).isNotNull();
    assertThat(categories.isSexual()).isNotNull();
    assertThat(categories.isHate()).isNotNull();
    assertThat(categories.isHarassment()).isNotNull();
    assertThat(categories.isSelfHarm()).isNotNull();
    assertThat(categories.isSexualMinors()).isNotNull();
    assertThat(categories.isHateThreatening()).isNotNull();
    assertThat(categories.isViolenceGraphic()).isNotNull();
    assertThat(categories.isSelfHarmIntent()).isNotNull();
    assertThat(categories.isSelfHarmInstructions()).isNotNull();
    assertThat(categories.isHarassmentThreatening()).isNotNull();
    assertThat(categories.isViolence()).isTrue();
    CategoryScores scores = result.getCategoryScores();
    assertThat(scores.getSexual()).isNotNull();
    assertThat(scores.getHate()).isNotNull();
    assertThat(scores.getHarassment()).isNotNull();
    assertThat(scores.getSelfHarm()).isNotNull();
    assertThat(scores.getSexualMinors()).isNotNull();
    assertThat(scores.getHateThreatening()).isNotNull();
    assertThat(scores.getViolenceGraphic()).isNotNull();
    assertThat(scores.getSelfHarmIntent()).isNotNull();
    assertThat(scores.getSelfHarmInstructions()).isNotNull();
    assertThat(scores.getHarassmentThreatening()).isNotNull();
    assertThat(scores.getViolence()).isNotNull();
}
"
    "@Test
@Test
void moderationAsUrlTestNegative() {
    var options = ModerationOptionsBuilder.builder().model("text-moderation-stable").build();
    var instructions = """
        A light cream colored mini golden doodle with a sign that contains the message "I'm on my way to BARCADE!".""";
    ModerationPrompt moderationPrompt = new ModerationPrompt(instructions, options);
    ModerationResponse moderationResponse = this.openAiModerationModel.call(moderationPrompt);
    assertThat(moderationResponse.getResults()).hasSize(1);
    var generation = moderationResponse.getResult();
    Moderation moderation = generation.getOutput();
    assertThat(moderation.getId()).isNotEmpty();
    assertThat(moderation.getResults()).isNotNull();
    assertThat(moderation.getResults().size()).isNotZero();
    System.out.println(moderation.getResults().toString());
    assertThat(moderation.getId()).isNotNull();
    assertThat(moderation.getModel()).isNotNull();
    ModerationResult result = moderation.getResults().get(0);
    assertThat(result.isFlagged()).isFalse();
    Categories categories = result.getCategories();
    assertThat(categories.isSexual()).isFalse();
    assertThat(categories.isHate()).isFalse();
    assertThat(categories.isHarassment()).isFalse();
    assertThat(categories.isSelfHarm()).isFalse();
    assertThat(categories.isSexualMinors()).isFalse();
    assertThat(categories.isHateThreatening()).isFalse();
    assertThat(categories.isViolenceGraphic()).isFalse();
    assertThat(categories.isSelfHarmIntent()).isFalse();
    assertThat(categories.isSelfHarmInstructions()).isFalse();
    assertThat(categories.isHarassmentThreatening()).isFalse();
    assertThat(categories.isViolence()).isFalse();
    CategoryScores scores = result.getCategoryScores();
    assertThat(scores.getSexual()).isNotNull();
    assertThat(scores.getHate()).isNotNull();
    assertThat(scores.getHarassment()).isNotNull();
    assertThat(scores.getSelfHarm()).isNotNull();
    assertThat(scores.getSexualMinors()).isNotNull();
    assertThat(scores.getHateThreatening()).isNotNull();
    assertThat(scores.getViolenceGraphic()).isNotNull();
    assertThat(scores.getSelfHarmIntent()).isNotNull();
    assertThat(scores.getSelfHarmInstructions()).isNotNull();
    assertThat(scores.getHarassmentThreatening()).isNotNull();
    assertThat(scores.getViolence()).isNotNull();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/DeepSeekWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<DeepSeekWithOpenAiChatModelIT.ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(DeepSeekWithOpenAiChatModelIT.ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    DeepSeekWithOpenAiChatModelIT.ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("{}", actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@Test
@Disabled("The current version of the deepseek-chat model's Function Calling capability is unstable, which may result in looped calls or empty responses.")
void functionCallTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiRetryTests.java
Tests:
    "@Test
@Test
public void openAiChatTransientError() {
    var choice = new ChatCompletion.Choice(ChatCompletionFinishReason.STOP, 0, new ChatCompletionMessage("Response", Role.ASSISTANT), null);
    ChatCompletion expectedChatCompletion = new ChatCompletion("id", List.of(choice), 666L, "model", null, null, null, new OpenAiApi.Usage(10, 10, 10));
    given(this.openAiApi.chatCompletionEntity(isA(ChatCompletionRequest.class), any())).willThrow(new TransientAiException("Transient Error 1")).willThrow(new TransientAiException("Transient Error 2")).willReturn(ResponseEntity.of(Optional.of(expectedChatCompletion)));
    var result = this.chatModel.call(new Prompt("text"));
    assertThat(result).isNotNull();
    assertThat(result.getResult().getOutput().getText()).isSameAs("Response");
    assertThat(this.retryListener.onSuccessRetryCount).isEqualTo(2);
    assertThat(this.retryListener.onErrorRetryCount).isEqualTo(2);
}
"
    "@Test
@Test
@Disabled("Currently stream() does not implmement retry")
public void openAiChatStreamTransientError() {
    var choice = new ChatCompletionChunk.ChunkChoice(ChatCompletionFinishReason.STOP, 0, new ChatCompletionMessage("Response", Role.ASSISTANT), null);
    ChatCompletionChunk expectedChatCompletion = new ChatCompletionChunk("id", List.of(choice), 666L, "model", null, null, null, null);
    given(this.openAiApi.chatCompletionStream(isA(ChatCompletionRequest.class), any())).willThrow(new TransientAiException("Transient Error 1")).willThrow(new TransientAiException("Transient Error 2")).willReturn(Flux.just(expectedChatCompletion));
    var result = this.chatModel.stream(new Prompt("text"));
    assertThat(result).isNotNull();
    assertThat(result.collectList().block().get(0).getResult().getOutput().getText()).isSameAs("Response");
    assertThat(this.retryListener.onSuccessRetryCount).isEqualTo(2);
    assertThat(this.retryListener.onErrorRetryCount).isEqualTo(2);
}
"
    "@Test
@Test
public void openAiEmbeddingTransientError() {
    EmbeddingList<Embedding> expectedEmbeddings = new EmbeddingList<>("list", List.of(new Embedding(0, new float[] { 9.9f, 8.8f })), "model", new OpenAiApi.Usage(10, 10, 10));
    given(this.openAiApi.embeddings(isA(EmbeddingRequest.class))).willThrow(new TransientAiException("Transient Error 1")).willThrow(new TransientAiException("Transient Error 2")).willReturn(ResponseEntity.of(Optional.of(expectedEmbeddings)));
    var result = this.embeddingModel.call(new org.springframework.ai.embedding.EmbeddingRequest(List.of("text1", "text2"), null));
    assertThat(result).isNotNull();
    assertThat(result.getResult().getOutput()).isEqualTo(new float[] { 9.9f, 8.8f });
    assertThat(this.retryListener.onSuccessRetryCount).isEqualTo(2);
    assertThat(this.retryListener.onErrorRetryCount).isEqualTo(2);
}
"
    "@Test
@Test
public void openAiAudioTranscriptionTransientError() {
    var expectedResponse = new StructuredResponse("nl", 6.7f, "Transcription Text", List.of(), List.of());
    given(this.openAiAudioApi.createTranscription(isA(TranscriptionRequest.class), isA(Class.class))).willThrow(new TransientAiException("Transient Error 1")).willThrow(new TransientAiException("Transient Error 2")).willReturn(ResponseEntity.of(Optional.of(expectedResponse)));
    AudioTranscriptionResponse result = this.audioTranscriptionModel.call(new AudioTranscriptionPrompt(new ClassPathResource("speech/jfk.flac")));
    assertThat(result).isNotNull();
    assertThat(result.getResult().getOutput()).isEqualTo(expectedResponse.text());
    assertThat(this.retryListener.onSuccessRetryCount).isEqualTo(2);
    assertThat(this.retryListener.onErrorRetryCount).isEqualTo(2);
}
"
    "@Test
@Test
public void openAiImageTransientError() {
    var expectedResponse = new OpenAiImageResponse(678L, List.of(new Data("url678", "b64", "prompt")));
    given(this.openAiImageApi.createImage(isA(OpenAiImageRequest.class))).willThrow(new TransientAiException("Transient Error 1")).willThrow(new TransientAiException("Transient Error 2")).willReturn(ResponseEntity.of(Optional.of(expectedResponse)));
    var result = this.imageModel.call(new ImagePrompt(List.of(new ImageMessage("Image Message"))));
    assertThat(result).isNotNull();
    assertThat(result.getResult().getOutput().getUrl()).isEqualTo("url678");
    assertThat(this.retryListener.onSuccessRetryCount).isEqualTo(2);
    assertThat(this.retryListener.onErrorRetryCount).isEqualTo(2);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/PerplexityWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {


    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    Prompt prompt = new Prompt(List.of(systemMessage, userMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under the key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
@Disabled("Perplexity gets confused with the 'Generate the filmography for a random actor.' prompt")
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@Test
void functionCallTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResults().stream().mapToLong(r -> r.getOutput().getToolCalls().size()).sum()).isZero();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelTypeReferenceBeanOutputConverterIT.java
Tests:
    "@Test
@Test
void typeRefOutputConverterRecords() {
    BeanOutputConverter<List<ActorsFilmsRecord>> outputConverter = new BeanOutputConverter<>(new ParameterizedTypeReference<List<ActorsFilmsRecord>>() {
    });
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks and Bill Murray.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<ActorsFilmsRecord> actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms).hasSize(2);
    assertThat(actorsFilms.get(0).actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.get(0).movies()).hasSize(5);
    assertThat(actorsFilms.get(1).actor()).isEqualTo("Bill Murray");
    assertThat(actorsFilms.get(1).movies()).hasSize(5);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiCompatibleChatModelIT.java
Tests:
    "@Test
@ParameterizedTest
@MethodSource("openAiCompatibleApis")
void chatCompletion(ChatModel chatModel) {
    Prompt prompt = new Prompt(this.conversation);
    ChatResponse response = chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/OllamaWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "llama3.1:latest", "llama3.2:latest" })
void functionCallTest(String modelName) {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris? Return the temperature in Celsius.");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().model(modelName).

    toolChoice("auto").toolCallbacks(List.of(FunctionToolCallback.builder("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "llava" })
void multiModalityEmbeddedImage(String modelName) throws IOException {
    var imageData = new ClassPathResource("/test.png");
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(new Media(MimeTypeUtils.IMAGE_PNG, imageData)));
    var response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"
    "@Test
@Disabled("Not supported by the current Ollama API")
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "llava" })
void multiModalityImageUrl(String modelName) throws IOException {
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(Media.builder().mimeType(MimeTypeUtils.IMAGE_PNG).data(new URL("https:
    ChatResponse response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/image/OpenAiImageModelIT.java
Tests:
    "@Test
@Test
void imageAsUrlTest() {
    var options = ImageOptionsBuilder.builder().height(1024).width(1024).build();
    var instructions = """
        A light cream colored mini golden doodle with a sign that contains the message "I'm on my way to BARCADE!".""";
    ImagePrompt imagePrompt = new ImagePrompt(instructions, options);
    ImageResponse imageResponse = this.imageModel.call(imagePrompt);
    assertThat(imageResponse.getResults()).hasSize(1);
    ImageResponseMetadata imageResponseMetadata = imageResponse.getMetadata();
    assertThat(imageResponseMetadata.getCreated()).isPositive();
    var generation = imageResponse.getResult();
    Image image = generation.getOutput();
    assertThat(image.getUrl()).isNotEmpty();

    assertThat(image.getB64Json()).isNull();
    var imageGenerationMetadata = generation.getMetadata();
    Assertions.assertThat(imageGenerationMetadata).isInstanceOf(OpenAiImageGenerationMetadata.class);
    OpenAiImageGenerationMetadata openAiImageGenerationMetadata = (OpenAiImageGenerationMetadata) imageGenerationMetadata;
    assertThat(openAiImageGenerationMetadata).isNotNull();
    assertThat(openAiImageGenerationMetadata.getRevisedPrompt()).isNotBlank();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/testutils/AbstractIT.java
Tests:
    "@Test
protected void evaluateQuestionAndAnswer(String question, ChatResponse response, boolean factBased) {
    assertThat(response).isNotNull();
    String answer = response.getResult().getOutput().getText();
    logger.info("Question: " + question);
    logger.info("Answer:" + answer);
    PromptTemplate userPromptTemplate = new PromptTemplate(this.userEvaluatorResource, Map.of("question", question, "answer", answer));
    SystemMessage systemMessage;
    if (factBased) {
        systemMessage = new SystemMessage(this.qaEvaluatorFactBasedAnswerResource);
    } else {
        systemMessage = new SystemMessage(this.qaEvaluatorAccurateAnswerResource);
    }
    Message userMessage = userPromptTemplate.createMessage();
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    String yesOrNo = this.chatModel.call(prompt).getResult().getOutput().getText();
    logger.info("Is Answer related to question: " + yesOrNo);
    if (yesOrNo.equalsIgnoreCase("no")) {
        SystemMessage notRelatedSystemMessage = new SystemMessage(this.qaEvaluatorNotRelatedResource);
        prompt = new Prompt(List.of(userMessage, notRelatedSystemMessage));
        String reasonForFailure = this.chatModel.call(prompt).getResult().getOutput().getText();
        fail(reasonForFailure);
    } else {
        logger.info("Answer is related to question.");
        assertThat(yesOrNo).isEqualTo("YES");
    }
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/transcription/OpenAiTranscriptionModelIT.java
Tests:
    "@Test
@Test
void transcriptionTest() {
    OpenAiAudioTranscriptionOptions transcriptionOptions = OpenAiAudioTranscriptionOptions.builder().responseFormat(TranscriptResponseFormat.TEXT).temperature(0f).build();
    AudioTranscriptionPrompt transcriptionRequest = new AudioTranscriptionPrompt(this.audioFile, transcriptionOptions);
    AudioTranscriptionResponse response = this.transcriptionModel.call(transcriptionRequest);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().toLowerCase().contains("fellow")).isTrue();
}
"
    "@Test
@Test
void transcriptionTestWithOptions() {
    OpenAiAudioApi.TranscriptResponseFormat responseFormat = OpenAiAudioApi.TranscriptResponseFormat.VTT;
    OpenAiAudioTranscriptionOptions transcriptionOptions = OpenAiAudioTranscriptionOptions.builder().language("en").prompt("Ask not this, but ask that").temperature(0f).responseFormat(responseFormat).build();
    AudioTranscriptionPrompt transcriptionRequest = new AudioTranscriptionPrompt(this.audioFile, transcriptionOptions);
    AudioTranscriptionResponse response = this.transcriptionModel.call(transcriptionRequest);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().toLowerCase().contains("fellow")).isTrue();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelObservationIT.java
Tests:
    "@Test
@Test
void observationForChatOperation() {
    var options = OpenAiChatOptions.builder().model(OpenAiApi.ChatModel.GPT_4_O_MINI.getValue()).frequencyPenalty(0.0).maxTokens(2048).presencePenalty(0.0).stop(List.of("this-is-the-end")).temperature(0.7).topP(1.0).build();
    Prompt prompt = new Prompt("Why does a raven look like a desk?", options);
    ChatResponse chatResponse = this.chatModel.call(prompt);
    assertThat(chatResponse.getResult().getOutput().getText()).isNotEmpty();
    ChatResponseMetadata responseMetadata = chatResponse.getMetadata();
    assertThat(responseMetadata).isNotNull();
    validate(responseMetadata);
}
"
    "@Test
@Test
void observationForStreamingChatOperation() {
    var options = OpenAiChatOptions.builder().model(OpenAiApi.ChatModel.GPT_4_O_MINI.getValue()).frequencyPenalty(0.0).maxTokens(2048).presencePenalty(0.0).stop(List.of("this-is-the-end")).temperature(0.7).topP(1.0).streamUsage(true).build();
    Prompt prompt = new Prompt("Why does a raven look like a desk?", options);
    Flux<ChatResponse> chatResponseFlux = this.chatModel.stream(prompt);
    List<ChatResponse> responses = chatResponseFlux.collectList().block();
    assertThat(responses).isNotEmpty();
    assertThat(responses).hasSizeGreaterThan(10);
    String aggregatedResponse = responses.subList(0, responses.size() - 1).stream().map(r -> r.getResult().getOutput().getText()).collect(Collectors.joining());
    assertThat(aggregatedResponse).isNotEmpty();
    ChatResponse lastChatResponse = responses.get(responses.size() - 1);
    ChatResponseMetadata responseMetadata = lastChatResponse.getMetadata();
    assertThat(responseMetadata).isNotNull();
    validate(responseMetadata);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelFunctionCallingIT.java
Tests:
    "@Test
void functionCallTest(OpenAiChatOptions promptOptions) {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/MistralWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "mistral-small-latest", "mistral-large-latest" })
void functionCallTest(String modelName) {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris? Response in Celsius\"");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().model(modelName).toolCallbacks(List.of(FunctionToolCallback.builder("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"
    "@Test
@Disabled("Mistral AI does not support multi modality API")
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "mistral-small-latest" })
void multiModalityEmbeddedImage(String modelName) throws IOException {
    var imageData = new ClassPathResource("/test.png");
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(new Media(MimeTypeUtils.IMAGE_PNG, imageData)));
    var response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"
    "@Test
@Disabled("Mistral AI does not support multi modality API")
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "mistral-small-latest" })
void multiModalityImageUrl(String modelName) throws IOException {
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(Media.builder().mimeType(MimeTypeUtils.IMAGE_PNG).data(new URL("https:
    ChatResponse response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).contains("bananas", "apple");
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bowl", "basket");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/NvidiaWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@Test
void functionCallTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/speech/OpenAiSpeechModelIT.java
Tests:
    "@Test
@Test
void shouldGenerateNonEmptyMp3AudioFromSpeechPrompt() {
    OpenAiAudioSpeechOptions speechOptions = OpenAiAudioSpeechOptions.builder().voice(OpenAiAudioApi.SpeechRequest.Voice.ALLOY).speed(SPEED).responseFormat(OpenAiAudioApi.SpeechRequest.AudioResponseFormat.MP3).model(OpenAiAudioApi.TtsModel.TTS_1.value).build();
    SpeechPrompt speechPrompt = new SpeechPrompt("Today is a wonderful day to build something people love!", speechOptions);
    SpeechResponse response = this.speechModel.call(speechPrompt);
    byte[] audioBytes = response.getResult().getOutput();
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput()).isNotEmpty();
    assertThat(audioBytes).hasSizeGreaterThan(0);
}
"
    "@Test
@Test
void shouldStreamNonEmptyResponsesForValidSpeechPrompts() {
    OpenAiAudioSpeechOptions speechOptions = OpenAiAudioSpeechOptions.builder().voice(OpenAiAudioApi.SpeechRequest.Voice.ALLOY).speed(SPEED).responseFormat(OpenAiAudioApi.SpeechRequest.AudioResponseFormat.MP3).model(OpenAiAudioApi.TtsModel.TTS_1.value).build();
    SpeechPrompt speechPrompt = new SpeechPrompt("Today is a wonderful day to build something people love!", speechOptions);
    Flux<SpeechResponse> responseFlux = this.speechModel.stream(speechPrompt);
    assertThat(responseFlux).isNotNull();
    List<SpeechResponse> responses = responseFlux.collectList().block();
    assertThat(responses).isNotNull();
    responses.forEach(response -> assertThat(response.getResult().getOutput()).isNotEmpty());
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "alloy", "echo", "fable", "onyx", "nova", "shimmer", "sage", "coral", "ash" })
void speechVoicesTest(String voice) {
    OpenAiAudioSpeechOptions speechOptions = OpenAiAudioSpeechOptions.builder().voice(OpenAiAudioApi.SpeechRequest.Voice.valueOf(voice.toUpperCase())).speed(SPEED).responseFormat(OpenAiAudioApi.SpeechRequest.AudioResponseFormat.MP3).model(OpenAiAudioApi.TtsModel.TTS_1.value).build();
    SpeechPrompt speechPrompt = new SpeechPrompt("Today is a wonderful day to build something people love!", speechOptions);
    SpeechResponse response = this.speechModel.call(speechPrompt);
    byte[] audioBytes = response.getResult().getOutput();
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput()).isNotEmpty();
    assertThat(audioBytes).hasSizeGreaterThan(0);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/embedding/EmbeddingIT.java
Tests:
    "@Test
@Test
void defaultEmbedding() {
    assertThat(this.embeddingModel).isNotNull();
    EmbeddingResponse embeddingResponse = this.embeddingModel.embedForResponse(List.of("Hello World"));
    assertThat(embeddingResponse.getResults()).hasSize(1);
    assertThat(embeddingResponse.getResults().get(0)).isNotNull();
    assertThat(embeddingResponse.getResults().get(0).getOutput()).hasSize(1536);
    assertThat(embeddingResponse.getMetadata().getModel()).isEqualTo("text-embedding-ada-002-v2");
    assertThat(embeddingResponse.getMetadata().getUsage().getTotalTokens()).isEqualTo(2);
    assertThat(embeddingResponse.getMetadata().getUsage().getPromptTokens()).isEqualTo(2);
    assertThat(this.embeddingModel.dimensions()).isEqualTo(1536);
}
"
    "@Test
@Test
void embedding3Large() {
    EmbeddingResponse embeddingResponse = this.embeddingModel.call(new EmbeddingRequest(List.of("Hello World"), OpenAiEmbeddingOptions.builder().model("text-embedding-3-large").build()));
    assertThat(embeddingResponse.getResults()).hasSize(1);
    assertThat(embeddingResponse.getResults().get(0)).isNotNull();
    assertThat(embeddingResponse.getResults().get(0).getOutput()).hasSize(3072);
    assertThat(embeddingResponse.getMetadata().getModel()).isEqualTo("text-embedding-3-large");
    assertThat(embeddingResponse.getMetadata().getUsage().getTotalTokens()).isEqualTo(2);
    assertThat(embeddingResponse.getMetadata().getUsage().getPromptTokens()).isEqualTo(2);

}
"
    "@Test
@Test
void textEmbeddingAda002() {
    EmbeddingResponse embeddingResponse = this.embeddingModel.call(new EmbeddingRequest(List.of("Hello World"), OpenAiEmbeddingOptions.builder().model("text-embedding-3-small").build()));
    assertThat(embeddingResponse.getResults()).hasSize(1);
    assertThat(embeddingResponse.getResults().get(0)).isNotNull();
    assertThat(embeddingResponse.getResults().get(0).getOutput()).hasSize(1536);
    assertThat(embeddingResponse.getMetadata().getModel()).isEqualTo("text-embedding-3-small");
    assertThat(embeddingResponse.getMetadata().getUsage().getTotalTokens()).isEqualTo(2);
    assertThat(embeddingResponse.getMetadata().getUsage().getPromptTokens()).isEqualTo(2);

}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");

}
"
    "@Test
@Test
void testMessageHistory() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and why they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("Blackbeard", "Bartholomew");
    var promptWithMessageHistory = new Prompt(List.of(new UserMessage("Dummy"), response.getResult().getOutput(), new UserMessage("Repeat the last assistant message.")));
    response = this.chatModel.call(promptWithMessageHistory);
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("Blackbeard", "Bartholomew");
}
"
    "@Test
@Test
void streamCompletenessTest() throws InterruptedException {
    UserMessage userMessage = new UserMessage("List ALL natural numbers in range [1, 1000]. Make sure to not omit any.");
    Prompt prompt = new Prompt(List.of(userMessage));
    StringBuilder answer = new StringBuilder();
    CountDownLatch latch = new CountDownLatch(1);
    Flux<ChatResponse> chatResponseFlux = this.streamingChatModel.stream(prompt).doOnNext(chatResponse -> {
        String responseContent = chatResponse.getResults().get(0).getOutput().getText();
        answer.append(responseContent);
    }).doOnComplete(() -> {
        logger.info(answer.toString());
        latch.countDown();
    });
    chatResponseFlux.subscribe();
    assertThat(latch.await(120, TimeUnit.SECONDS)).isTrue();
    IntStream.rangeClosed(1, 1000).forEach(n -> assertThat(answer).contains(String.valueOf(n)));
}
"
    "@Test
@Test
void streamCompletenessTestWithChatResponse() throws InterruptedException {
    UserMessage userMessage = new UserMessage("Who is George Washington? - use first as 1st");
    Prompt prompt = new Prompt(List.of(userMessage));
    StringBuilder answer = new StringBuilder();
    CountDownLatch latch = new CountDownLatch(1);
    ChatClient chatClient = ChatClient.builder(this.openAiChatModel).build();
    Flux<ChatResponse> chatResponseFlux = chatClient.prompt(prompt).stream().chatResponse().doOnNext(chatResponse -> {
        String responseContent = chatResponse.getResults().get(0).getOutput().getText();
        answer.append(responseContent);
    }).doOnComplete(() -> {
        logger.info(answer.toString());
        latch.countDown();
    });
    chatResponseFlux.subscribe();
    assertThat(latch.await(120, TimeUnit.SECONDS)).isTrue();
    assertThat(answer).contains("1st ");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@Test
@Deprecated
void functionCallTestDeprecated() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().model(OpenAiApi.ChatModel.GPT_4_O.getValue()).functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("30.0", "30");
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("10.0", "10");
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("15.0", "15");
}
"
    "@Test
@Test
void functionCallTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().model(OpenAiApi.ChatModel.GPT_4_O.getValue()).toolCallbacks(List.of(FunctionToolCallback.builder("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "gpt-4o" })
void multiModalityEmbeddedImage(String modelName) throws IOException {
    var imageData = new ClassPathResource("/test.png");
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(new Media(MimeTypeUtils.IMAGE_PNG, imageData)));
    var response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "gpt-4o" })
void multiModalityImageUrl(String modelName) throws IOException {
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(Media.builder().mimeType(MimeTypeUtils.IMAGE_PNG).data(new URL("https:
    ChatResponse response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "gpt-4o-audio-preview" })
void multiModalityOutputAudio(String modelName) throws IOException {
    var userMessage = new UserMessage("Tell me joke about Spring Framework");
    ChatResponse response = chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).outputModalities(List.of("text", "audio")).outputAudio(new AudioParameters(Voice.ALLOY, AudioResponseFormat.WAV)).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).isNotEmpty();
    byte[] audio = response.getResult().getOutput().getMedia().get(0).getDataAsByteArray();
    assertThat(audio).isNotEmpty();

}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "gpt-4o-audio-preview" })
void multiModalityInputAudio(String modelName) {
    var audioResource = new ClassPathResource("speech1.mp3");
    var userMessage = new UserMessage("What is this recording about?", List.of(new Media(MimeTypeUtils.parseMimeType("audio/mp3"), audioResource)));
    ChatResponse response = chatModel.call(new Prompt(List.of(userMessage), ChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsIgnoringCase("hobbits");
    assertThat(response.getMetadata().getModel()).containsIgnoringCase(modelName);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/moderation/OpenAiModerationModelTests.java
Tests:
    "@Test
@Test
void aiResponseContainsModerationResponseMetadata() {
    prepareMock();
    ModerationPrompt prompt = new ModerationPrompt("I want to kill them..");
    ModerationResponse response = this.openAiModerationModel.call(prompt);
    assertThat(response).isNotNull();
    Generation generation = response.getResult();
    assertThat(generation).isNotNull();
    Moderation moderation = response.getResult().getOutput();
    assertThat(moderation).isNotNull();
    assertThat(moderation.getId()).isEqualTo("modr-XXXXX");
    assertThat(moderation.getModel()).isEqualTo("text-moderation-005");
    List<ModerationResult> results = moderation.getResults();
    ModerationResult result = results.get(0);
    assertThat(result.isFlagged()).isTrue();

    Categories categories = result.getCategories();
    assertThat(categories.isSexual()).isFalse();
    assertThat(categories.isHate()).isFalse();
    assertThat(categories.isHarassment()).isFalse();
    assertThat(categories.isSelfHarm()).isFalse();
    assertThat(categories.isSexualMinors()).isFalse();
    assertThat(categories.isHateThreatening()).isFalse();
    assertThat(categories.isViolenceGraphic()).isFalse();
    assertThat(categories.isSelfHarmIntent()).isFalse();
    assertThat(categories.isSelfHarmInstructions()).isFalse();
    assertThat(categories.isHarassmentThreatening()).isTrue();
    assertThat(categories.isViolence()).isTrue();

    CategoryScores scores = result.getCategoryScores();
    assertThat(scores.getSexual()).isEqualTo(1.2282071E-6);
    assertThat(scores.getHate()).isEqualTo(0.010696256);
    assertThat(scores.getHarassment()).isEqualTo(0.29842457);
    assertThat(scores.getSelfHarm()).isEqualTo(1.5236925E-8);
    assertThat(scores.getSexualMinors()).isEqualTo(5.7246268E-8);
    assertThat(scores.getHateThreatening()).isEqualTo(0.0060676364);
    assertThat(scores.getViolenceGraphic()).isEqualTo(4.435014E-6);
    assertThat(scores.getSelfHarmIntent()).isEqualTo(8.098441E-10);
    assertThat(scores.getSelfHarmInstructions()).isEqualTo(2.8498655E-11);
    assertThat(scores.getHarassmentThreatening()).isEqualTo(0.63055265);
    assertThat(scores.getViolence()).isEqualTo(0.99011886);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/GroqWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void listOutputConverter() {
    DefaultConversionService conversionService = new DefaultConversionService();
    ListOutputConverter outputConverter = new ListOutputConverter(conversionService);
    String format = outputConverter.getFormat();
    String template = """
        List five {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "ice cream flavors", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    List<String> list = outputConverter.convert(generation.getOutput().getText());
    assertThat(list).hasSize(5);
}
"
    "@Test
@Test
void mapOutputConverter() {
    MapOutputConverter outputConverter = new MapOutputConverter();
    String format = outputConverter.getFormat();
    String template = """
        Provide me a List of {subject}
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("subject", "numbers from 1 to 9 under they key name 'numbers'", "format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    Map<String, Object> result = outputConverter.convert(generation.getOutput().getText());
    assertThat(result.get("numbers")).isEqualTo(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9));
}
"
    "@Test
@Test
void beanOutputConverter() {
    BeanOutputConverter<ActorsFilms> outputConverter = new BeanOutputConverter<>(ActorsFilms.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography for a random actor.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilms actorsFilms = outputConverter.convert(generation.getOutput().getText());
    assertThat(actorsFilms.getActor()).isNotEmpty();
}
"
    "@Test
@Test
void beanOutputConverterRecords() {
    BeanOutputConverter<ActorsFilmsRecord> outputConverter = new BeanOutputConverter<>(ActorsFilmsRecord.class);
    String format = outputConverter.getFormat();
    String template = """
        Generate the filmography of 5 movies for Tom Hanks.
        {format}
        """;
    PromptTemplate promptTemplate = new PromptTemplate(template, Map.of("format", format));
    Prompt prompt = new Prompt(promptTemplate.createMessage());
    Generation generation = this.chatModel.call(prompt).getResult();
    ActorsFilmsRecord actorsFilms = outputConverter.convert(generation.getOutput().getText());
    logger.info("" + actorsFilms);
    assertThat(actorsFilms.actor()).isEqualTo("Tom Hanks");
    assertThat(actorsFilms.movies()).hasSize(5);
}
"
    "@Test
@Test
void functionCallTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResult().getOutput().getText()).contains("30", "10", "15");
}
"
    "@Test
@Disabled("Groq does not support multi modality API")
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "llama3-70b-8192" })
void multiModalityEmbeddedImage(String modelName) throws IOException {
    var imageData = new ClassPathResource("/test.png");
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(new Media(MimeTypeUtils.IMAGE_PNG, imageData)));
    var response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"
    "@Test
@Disabled("Groq does not support multi modality API")
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "llama3-70b-8192" })
void multiModalityImageUrl(String modelName) throws IOException {
    var userMessage = new UserMessage("Explain what do you see on this picture?", List.of(Media.builder().mimeType(MimeTypeUtils.IMAGE_PNG).data(new URL("https:
    ChatResponse response = this.chatModel.call(new Prompt(List.of(userMessage), OpenAiChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsAnyOf("bananas", "apple", "bowl", "basket", "fruit stand");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelResponseFormatIT.java
Tests:
    "@Test
@Test
void jsonObject() throws JsonMappingException, JsonProcessingException {







    Prompt prompt = new Prompt("List 8 planets. Use JSON response", OpenAiChatOptions.builder().responseFormat(ResponseFormat.builder().type(ResponseFormat.Type.JSON_OBJECT).build()).build());
    ChatResponse response = this.openAiChatModel.call(prompt);
    assertThat(response).isNotNull();
    String content = response.getResult().getOutput().getText();
    logger.info("Response content: {}", content);
    assertThat(isValidJson(content)).isTrue();
}
"
    "@Test
@Test
void jsonSchema() throws JsonMappingException, JsonProcessingException {
    var jsonSchema = """
        {
        	"type": "object",
        	"properties": {
        		"steps": {
        			"type": "array",
        			"items": {
        				"type": "object",
        				"properties": {
        					"explanation": { "type": "string" },
        					"output": { "type": "string" }
        				},
        				"required": ["explanation", "output"],
        				"additionalProperties": false
        			}
        		},
        		"final_answer": { "type": "string" }
        	},
        	"required": ["steps", "final_answer"],
        	"additionalProperties": false
        }
        """;
    Prompt prompt = new Prompt("how can I solve 8x + 7 = -23", OpenAiChatOptions.builder().model(ChatModel.GPT_4_O_MINI).responseFormat(new ResponseFormat(ResponseFormat.Type.JSON_SCHEMA, jsonSchema)).build());
    ChatResponse response = this.openAiChatModel.call(prompt);
    assertThat(response).isNotNull();
    String content = response.getResult().getOutput().getText();
    logger.info("Response content: {}", content);
    assertThat(isValidJson(content)).isTrue();
}
"
    "@Test
@Test
void jsonSchemaBeanConverter() throws JsonMappingException, JsonProcessingException {
    @JsonPropertyOrder({ "steps", "final_answer" })
    record MathReasoning(@JsonProperty(required = true, value = "steps") Steps steps, @JsonProperty(required = true, value = "final_answer") String finalAnswer) {

        record Steps(@JsonProperty(required = true, value = "items") Items[] items) {

            @JsonPropertyOrder({ "output", "explanation" })
            record Items(@JsonProperty(required = true, value = "explanation") String explanation, @JsonProperty(required = true, value = "output") String output) {
            }
        }
    }
    var outputConverter = new BeanOutputConverter<>(MathReasoning.class);


    var expectedJsonSchema = """
        {
          "$schema" : "https:
          "type" : "object",
          "properties" : {
            "steps" : {
              "type" : "object",
              "properties" : {
                "items" : {
                  "type" : "array",
                  "items" : {
                    "type" : "object",
                    "properties" : {
                      "output" : {
                        "type" : "string"
                      },
                      "explanation" : {
                        "type" : "string"
                      }
                    },
                    "required" : [ "output", "explanation" ],
                    "additionalProperties" : false
                  }
                }
              },
              "required" : [ "items" ],
              "additionalProperties" : false
            },
            "final_answer" : {
              "type" : "string"
            }
          },
          "required" : [ "steps", "final_answer" ],
          "additionalProperties" : false
        }""";


    var jsonSchema1 = outputConverter.getJsonSchema();
    assertThat(jsonSchema1).isNotNull();
    assertThat(jsonSchema1).isEqualTo(expectedJsonSchema);
    Prompt prompt = new Prompt("how can I solve 8x + 7 = -23", OpenAiChatOptions.builder().model(ChatModel.GPT_4_O_MINI).responseFormat(new ResponseFormat(ResponseFormat.Type.JSON_SCHEMA, jsonSchema1)).build());
    ChatResponse response = this.openAiChatModel.call(prompt);
    assertThat(response).isNotNull();
    String content = response.getResult().getOutput().getText();
    logger.info("Response content: {}", content);
    assertThat(isValidJson(content)).isTrue();


    assertThat(content.startsWith("{\"steps\":{\"items\":["));
    MathReasoning mathReasoning = outputConverter.convert(content);
    assertThat(mathReasoning).isNotNull();
    logger.info(mathReasoning.toString());
}
"
Scenario 1: Verify Default Output When Audio is Null

Details:
  TestName: verifyDefaultOutputWhenAudioIsNull
  Description: This test checks the behavior of the getOutput method when the audio field is null. It ensures that the method returns null as expected when no audio data is present.
Execution:
  Arrange: Create an instance of the Speech class with the audio field set to null.
  Act: Call the getOutput method on the Speech instance.
  Assert: Use JUnit assertions to verify that the returned value is null.
Validation:
  This assertion verifies that the method correctly handles the scenario where no audio data is available, which is crucial for preventing null pointer exceptions in the application.

Scenario 2: Verify Output When Audio is Non-Empty

Details:
  TestName: verifyOutputWhenAudioIsNonEmpty
  Description: This test checks the behavior of the getOutput method when the audio field contains non-empty byte array data. It ensures that the method returns the correct audio data.
Execution:
  Arrange: Create an instance of the Speech class with the audio field set to a non-empty byte array.
  Act: Call the getOutput method on the Speech instance.
  Assert: Use JUnit assertions to verify that the returned byte array matches the expected audio data.
Validation:
  This assertion ensures that the method returns the correct audio data, which is essential for the functionality of audio playback features in the application.

Scenario 3: Verify Output Consistency Across Multiple Calls

Details:
  TestName: verifyOutputConsistencyAcrossMultipleCalls
  Description: This test checks that the getOutput method consistently returns the same audio data across multiple calls, ensuring stability and reliability of the method.
Execution:
  Arrange: Create an instance of the Speech class with the audio field set to a specific byte array.
  Act: Call the getOutput method multiple times on the Speech instance.
  Assert: Use JUnit assertions to verify that the returned byte array is the same for each call.
Validation:
  This assertion confirms that the method consistently returns the same data, which is important for ensuring predictable behavior in applications that rely on repeated audio data retrieval.

Scenario 4: Verify Output with Large Audio Data

Details:
  TestName: verifyOutputWithLargeAudioData
  Description: This test checks the behavior of the getOutput method when handling a large byte array in the audio field, ensuring that the method can handle large data efficiently.
Execution:
  Arrange: Create an instance of the Speech class with the audio field set to a large byte array.
  Act: Call the getOutput method on the Speech instance.
  Assert: Use JUnit assertions to verify that the returned byte array matches the expected large audio data.
Validation:
  This assertion ensures that the method can handle large audio data without performance degradation, which is critical for applications dealing with extensive audio files.

Scenario 5: Verify Output with Edge Case of Empty Byte Array

Details:
  TestName: verifyOutputWithEdgeCaseOfEmptyByteArray
  Description: This test checks the behavior of the getOutput method when the audio field is set to an empty byte array, ensuring that the method handles this edge case correctly.
Execution:
  Arrange: Create an instance of the Speech class with the audio field set to an empty byte array.
  Act: Call the getOutput method on the Speech instance.
  Assert: Use JUnit assertions to verify that the returned byte array is empty.
Validation:
  This assertion confirms that the method correctly handles the edge case of an empty byte array, which is important for preventing unexpected behavior in applications that process audio data.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Arrays;
import java.util.Objects;
import org.springframework.ai.model.ModelResult;
import org.springframework.ai.openai.metadata.audio.OpenAiAudioSpeechMetadata;
import org.springframework.lang.Nullable;

public class SpeechGetOutputTest {

	@Test
	@Tag("invalid")
	public void verifyDefaultOutputWhenAudioIsNull() {
		// Arrange
		Speech speech = new Speech(null);
		// Act
		byte[] output = speech.getOutput();
		// Assert
		assertNull(output, "Expected output to be null when audio is null");
	}

	@Test
	@Tag("valid")
	public void verifyOutputWhenAudioIsNonEmpty() {
		// Arrange
		byte[] expectedAudio = new byte[] { 1, 2, 3 };
		Speech speech = new Speech(expectedAudio);
		// Act
		byte[] output = speech.getOutput();
		// Assert
		assertArrayEquals(expectedAudio, output, "Expected output to match the non-empty audio data");
	}

	@Test
	@Tag("valid")
	public void verifyOutputConsistencyAcrossMultipleCalls() {
		// Arrange
		byte[] expectedAudio = new byte[] { 4, 5, 6 };
		Speech speech = new Speech(expectedAudio);
		// Act
		byte[] firstCallOutput = speech.getOutput();
		byte[] secondCallOutput = speech.getOutput();
		// Assert
		assertArrayEquals(expectedAudio, firstCallOutput, "Expected output to be consistent on first call");
		assertArrayEquals(expectedAudio, secondCallOutput, "Expected output to be consistent on second call");
	}

	@Test
	@Tag("boundary")
	public void verifyOutputWithLargeAudioData() {
		// Arrange
		byte[] largeAudio = new byte[10000]; // TODO: Adjust size if needed
		for (int i = 0; i < largeAudio.length; i++) {
			largeAudio[i] = (byte) (i % 256);
		}
		Speech speech = new Speech(largeAudio);
		// Act
		byte[] output = speech.getOutput();
		// Assert
		assertArrayEquals(largeAudio, output, "Expected output to match the large audio data");
	}

	@Test
	@Tag("boundary")
	public void verifyOutputWithEdgeCaseOfEmptyByteArray() {
		// Arrange
		byte[] emptyAudio = new byte[] {};
		Speech speech = new Speech(emptyAudio);
		// Act
		byte[] output = speech.getOutput();
		// Assert
		assertArrayEquals(emptyAudio, output, "Expected output to be an empty byte array");
	}

}