/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=hashCode_c31f5d7b71
ROOST_METHOD_SIG_HASH=hashCode_44411a81c8

Scenario 1: HashCode for Null Audio and Null Metadata

Details:
  TestName: hashCodeWithNullAudioAndMetadata
  Description: This test checks the hashCode method when both audio and speechMetadata are null. It ensures that the method handles null values gracefully and returns a consistent hash code.
Execution:
  Arrange: Create a Speech instance with both audio and speechMetadata set to null.
  Act: Call the hashCode method on the Speech instance.
  Assert: Verify that the hashCode method returns a consistent integer value.
Validation:
  This test verifies that the hashCode method can handle null fields without throwing exceptions and returns a consistent hash code, which is crucial for maintaining the integrity of hash-based collections.

Scenario 2: HashCode for Non-Null Audio and Null Metadata

Details:
  TestName: hashCodeWithNonNullAudioAndNullMetadata
  Description: This test checks the hashCode method when audio is non-null and speechMetadata is null. It ensures that the method computes the hash code based on the audio array.
Execution:
  Arrange: Create a Speech instance with a non-null audio array and null speechMetadata.
  Act: Call the hashCode method on the Speech instance.
  Assert: Verify that the hashCode method returns a consistent integer value based on the audio array.
Validation:
  This test ensures that the hashCode method correctly incorporates the audio array into the hash code calculation, which is important for distinguishing objects in hash-based collections.

Scenario 3: HashCode for Null Audio and Non-Null Metadata

Details:
  TestName: hashCodeWithNullAudioAndNonNullMetadata
  Description: This test checks the hashCode method when audio is null and speechMetadata is non-null. It ensures that the method computes the hash code based on the speechMetadata.
Execution:
  Arrange: Create a Speech instance with null audio and a non-null speechMetadata.
  Act: Call the hashCode method on the Speech instance.
  Assert: Verify that the hashCode method returns a consistent integer value based on the speechMetadata.
Validation:
  This test ensures that the hashCode method correctly incorporates the speechMetadata into the hash code calculation, which is important for object uniqueness in hash-based collections.

Scenario 4: HashCode for Non-Null Audio and Non-Null Metadata

Details:
  TestName: hashCodeWithNonNullAudioAndNonNullMetadata
  Description: This test checks the hashCode method when both audio and speechMetadata are non-null. It ensures that the method computes the hash code based on both fields.
Execution:
  Arrange: Create a Speech instance with non-null audio and non-null speechMetadata.
  Act: Call the hashCode method on the Speech instance.
  Assert: Verify that the hashCode method returns a consistent integer value based on both audio and speechMetadata.
Validation:
  This test ensures that the hashCode method correctly incorporates both audio and speechMetadata into the hash code calculation, which is crucial for maintaining object uniqueness and integrity in hash-based collections.

Scenario 5: HashCode Consistency

Details:
  TestName: hashCodeConsistency
  Description: This test checks the consistency of the hashCode method. It ensures that multiple calls to hashCode on the same object return the same value.
Execution:
  Arrange: Create a Speech instance with specific audio and speechMetadata values.
  Act: Call the hashCode method multiple times on the same Speech instance.
  Assert: Verify that all calls to hashCode return the same integer value.
Validation:
  This test ensures the consistency of the hashCode method, which is a fundamental requirement for objects used in hash-based collections to maintain their integrity and performance.

Scenario 6: HashCode Equality for Equal Objects

Details:
  TestName: hashCodeEqualityForEqualObjects
  Description: This test checks that two equal Speech objects have the same hash code. It ensures that the hashCode method is consistent with the equals method.
Execution:
  Arrange: Create two Speech instances with the same audio and speechMetadata values.
  Act: Call the hashCode method on both Speech instances.
  Assert: Verify that both instances return the same hash code.
Validation:
  This test ensures that the hashCode method is consistent with the equals method, which is essential for the correct functioning of hash-based collections like HashSet and HashMap.

Scenario 7: HashCode Inequality for Unequal Objects

Details:
  TestName: hashCodeInequalityForUnequalObjects
  Description: This test checks that two unequal Speech objects have different hash codes. It ensures that the hashCode method differentiates between objects with different field values.
Execution:
  Arrange: Create two Speech instances with different audio or speechMetadata values.
  Act: Call the hashCode method on both Speech instances.
  Assert: Verify that both instances return different hash codes.
Validation:
  This test ensures that the hashCode method correctly differentiates between objects with different field values, which is crucial for maintaining the uniqueness of keys in hash-based collections.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import java.util.Arrays;
import java.util.Objects;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import org.mockito.Mockito;
import org.springframework.ai.model.ModelResult;
import org.springframework.ai.openai.metadata.audio.OpenAiAudioSpeechMetadata;
import org.springframework.lang.Nullable;
import org.junit.jupiter.api.*;

public class SpeechHashCodeTest {

	@Test
	@Tag("valid")
	public void hashCodeWithNullAudioAndMetadata() {
		Speech speech = new Speech(null).withSpeechMetadata(null);
		int hashCode = speech.hashCode();
		assertEquals(hashCode, speech.hashCode());
	}

	@Test
	@Tag("valid")
	public void hashCodeWithNonNullAudioAndNullMetadata() {
		byte[] audio = new byte[] { 1, 2, 3 };
		Speech speech = new Speech(audio).withSpeechMetadata(null);
		int hashCode = speech.hashCode();
		assertEquals(hashCode, speech.hashCode());
	}

	@Test
	@Tag("valid")
	public void hashCodeWithNullAudioAndNonNullMetadata() {
		OpenAiAudioSpeechMetadata metadata = Mockito.mock(OpenAiAudioSpeechMetadata.class);
		Speech speech = new Speech(null).withSpeechMetadata(metadata);
		int hashCode = speech.hashCode();
		assertEquals(hashCode, speech.hashCode());
	}

	@Test
	@Tag("valid")
	public void hashCodeWithNonNullAudioAndNonNullMetadata() {
		byte[] audio = new byte[] { 1, 2, 3 };
		OpenAiAudioSpeechMetadata metadata = Mockito.mock(OpenAiAudioSpeechMetadata.class);
		Speech speech = new Speech(audio).withSpeechMetadata(metadata);
		int hashCode = speech.hashCode();
		assertEquals(hashCode, speech.hashCode());
	}

	@Test
	@Tag("valid")
	public void hashCodeConsistency() {
		byte[] audio = new byte[] { 1, 2, 3 };
		OpenAiAudioSpeechMetadata metadata = Mockito.mock(OpenAiAudioSpeechMetadata.class);
		Speech speech = new Speech(audio).withSpeechMetadata(metadata);
		int hashCode1 = speech.hashCode();
		int hashCode2 = speech.hashCode();
		assertEquals(hashCode1, hashCode2);
	}

	@Test
	@Tag("valid")
	public void hashCodeEqualityForEqualObjects() {
		byte[] audio = new byte[] { 1, 2, 3 };
		OpenAiAudioSpeechMetadata metadata = Mockito.mock(OpenAiAudioSpeechMetadata.class);
		Speech speech1 = new Speech(audio).withSpeechMetadata(metadata);
		Speech speech2 = new Speech(audio).withSpeechMetadata(metadata);
		assertEquals(speech1.hashCode(), speech2.hashCode());
	}

	@Test
	@Tag("valid")
	public void hashCodeInequalityForUnequalObjects() {
		byte[] audio1 = new byte[] { 1, 2, 3 };
		byte[] audio2 = new byte[] { 4, 5, 6 };
		OpenAiAudioSpeechMetadata metadata1 = Mockito.mock(OpenAiAudioSpeechMetadata.class);
		OpenAiAudioSpeechMetadata metadata2 = Mockito.mock(OpenAiAudioSpeechMetadata.class);
		Speech speech1 = new Speech(audio1).withSpeechMetadata(metadata1);
		Speech speech2 = new Speech(audio2).withSpeechMetadata(metadata2);
		assertNotEquals(speech1.hashCode(), speech2.hashCode());
	}

}