/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=hashCode_16f2a0577d
ROOST_METHOD_SIG_HASH=hashCode_44411a81c8

Scenario 1: Verify hashCode for Default Initialization

Details:
  TestName: verifyHashCodeForDefaultInitialization
  Description: This test checks the hashCode method when the SpeechResponse object is initialized with default values (null for both speech and speechResponseMetadata). It ensures that the hashCode is computed correctly for null fields.
Execution:
  Arrange: Create a SpeechResponse object with default initialization where both speech and speechResponseMetadata are null.
  Act: Call the hashCode method on the SpeechResponse object.
  Assert: Use JUnit assertions to verify that the hashCode is consistent with the expected value for null fields.
Validation:
  This test verifies that the hashCode method handles null values correctly, which is crucial for ensuring consistent behavior in collections like HashMap or HashSet where null fields might be present.

Scenario 2: Verify hashCode with Non-null Speech and Null Metadata

Details:
  TestName: verifyHashCodeWithNonNullSpeechAndNullMetadata
  Description: This test checks the hashCode method when the SpeechResponse object has a non-null speech field and a null speechResponseMetadata field. It ensures that the hashCode is computed correctly when only one field is non-null.
Execution:
  Arrange: Create a SpeechResponse object with a non-null Speech object and a null speechResponseMetadata.
  Act: Call the hashCode method on the SpeechResponse object.
  Assert: Use JUnit assertions to verify that the hashCode is consistent with the expected value when one field is non-null.
Validation:
  This test ensures that the hashCode method correctly incorporates non-null fields into its computation, which is important for maintaining object uniqueness in hash-based collections.

Scenario 3: Verify hashCode with Null Speech and Non-null Metadata

Details:
  TestName: verifyHashCodeWithNullSpeechAndNonNullMetadata
  Description: This test checks the hashCode method when the SpeechResponse object has a null speech field and a non-null speechResponseMetadata field. It ensures that the hashCode is computed correctly when only one field is non-null.
Execution:
  Arrange: Create a SpeechResponse object with a null Speech object and a non-null OpenAiAudioSpeechResponseMetadata.
  Act: Call the hashCode method on the SpeechResponse object.
  Assert: Use JUnit assertions to verify that the hashCode is consistent with the expected value when one field is non-null.
Validation:
  This test ensures that the hashCode method correctly incorporates non-null fields into its computation, which is important for maintaining object uniqueness in hash-based collections.

Scenario 4: Verify hashCode with Non-null Speech and Metadata

Details:
  TestName: verifyHashCodeWithNonNullSpeechAndMetadata
  Description: This test checks the hashCode method when the SpeechResponse object has both non-null speech and speechResponseMetadata fields. It ensures that the hashCode is computed correctly when both fields are non-null.
Execution:
  Arrange: Create a SpeechResponse object with non-null Speech and OpenAiAudioSpeechResponseMetadata objects.
  Act: Call the hashCode method on the SpeechResponse object.
  Assert: Use JUnit assertions to verify that the hashCode is consistent with the expected value when both fields are non-null.
Validation:
  This test ensures that the hashCode method correctly incorporates all non-null fields into its computation, which is crucial for maintaining object uniqueness and consistency in hash-based collections.

Scenario 5: Verify Consistency of hashCode

Details:
  TestName: verifyConsistencyOfHashCode
  Description: This test checks the consistency of the hashCode method by ensuring that multiple invocations on the same SpeechResponse object return the same hash code.
Execution:
  Arrange: Create a SpeechResponse object with specific values for speech and speechResponseMetadata.
  Act: Call the hashCode method multiple times on the same SpeechResponse object.
  Assert: Use JUnit assertions to verify that the hashCode remains consistent across multiple invocations.
Validation:
  This test ensures that the hashCode method adheres to the contract of returning the same hash code for the same object state, which is essential for reliable behavior in hash-based collections.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.*;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import org.springframework.ai.model.ModelResponse;
import org.springframework.ai.openai.metadata.audio.OpenAiAudioSpeechResponseMetadata;

public class SpeechResponseHashCodeTest {

	@Test
	@Tag("boundary")
	public void verifyHashCodeForDefaultInitialization() {
		// Arrange
		SpeechResponse speechResponse = new SpeechResponse(null, null);
		// Act
		int hashCode = speechResponse.hashCode();
		// Assert
		assertEquals(Objects.hash(null, null), hashCode);
	}

	@Test
	@Tag("valid")
	public void verifyHashCodeWithNonNullSpeechAndNullMetadata() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio bytes
		Speech speech = new Speech(audio);
		SpeechResponse speechResponse = new SpeechResponse(speech, null);
		// Act
		int hashCode = speechResponse.hashCode();
		// Assert
		assertEquals(Objects.hash(speech, null), hashCode);
	}

	@Test
	@Tag("valid")
	public void verifyHashCodeWithNullSpeechAndNonNullMetadata() {
		// Arrange
		OpenAiAudioSpeechResponseMetadata metadata = Mockito.mock(OpenAiAudioSpeechResponseMetadata.class);
		SpeechResponse speechResponse = new SpeechResponse(null, metadata);
		// Act
		int hashCode = speechResponse.hashCode();
		// Assert
		assertEquals(Objects.hash(null, metadata), hashCode);
	}

	@Test
	@Tag("valid")
	public void verifyHashCodeWithNonNullSpeechAndMetadata() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio bytes
		Speech speech = new Speech(audio);
		OpenAiAudioSpeechResponseMetadata metadata = Mockito.mock(OpenAiAudioSpeechResponseMetadata.class);
		SpeechResponse speechResponse = new SpeechResponse(speech, metadata);
		// Act
		int hashCode = speechResponse.hashCode();
		// Assert
		assertEquals(Objects.hash(speech, metadata), hashCode);
	}

	@Test
	@Tag("valid")
	public void verifyConsistencyOfHashCode() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio bytes
		Speech speech = new Speech(audio);
		OpenAiAudioSpeechResponseMetadata metadata = Mockito.mock(OpenAiAudioSpeechResponseMetadata.class);
		SpeechResponse speechResponse = new SpeechResponse(speech, metadata);
		// Act
		int firstHashCode = speechResponse.hashCode();
		int secondHashCode = speechResponse.hashCode();
		// Assert
		assertEquals(firstHashCode, secondHashCode);
	}

}