/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=equals_940db09f62
ROOST_METHOD_SIG_HASH=equals_ded257778a

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/api/tool/OpenAiApiToolFunctionCallIT.java
Tests:
    "@Test
@SuppressWarnings("null")
@Test
public void toolFunctionCall() {

    var message = new ChatCompletionMessage("What's the weather like in San Francisco, Tokyo, and Paris?", Role.USER);
    var functionTool = new OpenAiApi.FunctionTool(OpenAiApi.FunctionTool.Type.FUNCTION, new OpenAiApi.FunctionTool.Function("Get the weather in location. Return temperature in Celsius.", "getCurrentWeather", ModelOptionsUtils.jsonToMap("""
        {
        	"type": "object",
        	"properties": {
        		"location": {
        			"type": "string",
        			"description": "The city and state e.g. San Francisco, CA"
        		},
        		"lat": {
        			"type": "number",
        			"description": "The city latitude"
        		},
        		"lon": {
        			"type": "number",
        			"description": "The city longitude"
        		},
        		"unit": {
        			"type": "string",
        			"enum": ["C", "F"]
        		}
        	},
        	"required": ["location", "lat", "lon", "unit"]
        }
        """), null));
    List<ChatCompletionMessage> messages = new ArrayList<>(List.of(message));
    ChatCompletionRequest chatCompletionRequest = new ChatCompletionRequest(messages, "gpt-4o", List.of(functionTool), ToolChoiceBuilder.AUTO);

    ResponseEntity<ChatCompletion> chatCompletion = this.completionApi.chatCompletionEntity(chatCompletionRequest);
    assertThat(chatCompletion.getBody()).isNotNull();
    assertThat(chatCompletion.getBody().choices()).isNotEmpty();
    ChatCompletionMessage responseMessage = chatCompletion.getBody().choices().get(0).message();

    assertThat(responseMessage.role()).isEqualTo(Role.ASSISTANT);
    assertThat(responseMessage.toolCalls()).isNotNull();

    messages.add(responseMessage);

    for (ToolCall toolCall : responseMessage.toolCalls()) {
        var functionName = toolCall.function().name();
        if ("getCurrentWeather".equals(functionName)) {
            MockWeatherService.Request weatherRequest = fromJson(toolCall.function().arguments(), MockWeatherService.Request.class);
            MockWeatherService.Response weatherResponse = this.weatherService.apply(weatherRequest);

            messages.add(new ChatCompletionMessage("" + weatherResponse.temp() + weatherRequest.unit(), Role.TOOL, functionName, toolCall.id(), null, null, null));
        }
    }
    var functionResponseRequest = new ChatCompletionRequest(messages, "gpt-4o", 0.5);
    ResponseEntity<ChatCompletion> chatCompletion2 = this.completionApi.chatCompletionEntity(functionResponseRequest);
    logger.info("Final response: " + chatCompletion2.getBody());
    assertThat(chatCompletion2.getBody().choices()).isNotEmpty();
    assertThat(chatCompletion2.getBody().choices().get(0).message().role()).isEqualTo(Role.ASSISTANT);
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("San Francisco").containsAnyOf("30.0°C", "30°C");
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("Tokyo").containsAnyOf("10.0°C", "10°C");
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("Paris").containsAnyOf("15.0°C", "15°C");
}
"Scenario 1: Equality with Same Object Reference

Details:
  TestName: equalsWithSameObjectReference
  Description: This test checks if the equals method returns true when the same object reference is passed as the parameter. This is a basic identity check.
Execution:
  Arrange: Create an instance of SpeechResponse.
  Act: Call the equals method on the instance with itself as the parameter.
  Assert: Verify that the result is true.
Validation:
  This assertion verifies that the equals method correctly identifies when the same object reference is used, which should always return true according to the contract of the equals method. This is fundamental to ensuring object identity is respected.

Scenario 2: Equality with Null Parameter

Details:
  TestName: equalsWithNullParameter
  Description: This test checks if the equals method returns false when null is passed as the parameter. This tests the method's ability to handle null inputs.
Execution:
  Arrange: Create an instance of SpeechResponse.
  Act: Call the equals method on the instance with null as the parameter.
  Assert: Verify that the result is false.
Validation:
  This assertion ensures that the equals method correctly handles null inputs by returning false, which is essential for robustness in null-safe operations.

Scenario 3: Equality with Different Class Type

Details:
  TestName: equalsWithDifferentClassType
  Description: This test checks if the equals method returns false when an object of a different class is passed as the parameter. This tests type safety.
Execution:
  Arrange: Create an instance of SpeechResponse and an instance of a different class (e.g., String).
  Act: Call the equals method on the SpeechResponse instance with the different class instance as the parameter.
  Assert: Verify that the result is false.
Validation:
  This assertion ensures that the equals method correctly identifies objects of different types and returns false, maintaining type safety and preventing incorrect equality checks.

Scenario 4: Equality with Different SpeechResponse Objects with Same Data

Details:
  TestName: equalsWithDifferentObjectsSameData
  Description: This test checks if the equals method returns true when two different SpeechResponse objects with identical data are compared.
Execution:
  Arrange: Create two instances of SpeechResponse with the same speech and speechResponseMetadata values.
  Act: Call the equals method on one instance with the other instance as the parameter.
  Assert: Verify that the result is true.
Validation:
  This assertion verifies that the equals method correctly identifies two different objects as equal when their internal state is identical, which is crucial for logical equality.

Scenario 5: Equality with Different SpeechResponse Objects with Different Data

Details:
  TestName: equalsWithDifferentObjectsDifferentData
  Description: This test checks if the equals method returns false when two different SpeechResponse objects with different data are compared.
Execution:
  Arrange: Create two instances of SpeechResponse with different speech or speechResponseMetadata values.
  Act: Call the equals method on one instance with the other instance as the parameter.
  Assert: Verify that the result is false.
Validation:
  This assertion ensures that the equals method correctly identifies two objects as not equal when their internal state differs, which is essential for accurate equality checks.

Scenario 6: Equality with Null Fields in SpeechResponse

Details:
  TestName: equalsWithNullFields
  Description: This test checks if the equals method handles null fields correctly when comparing two SpeechResponse objects.
Execution:
  Arrange: Create two instances of SpeechResponse with null values for speech and speechResponseMetadata.
  Act: Call the equals method on one instance with the other instance as the parameter.
  Assert: Verify that the result is true.
Validation:
  This assertion ensures that the equals method can handle null fields gracefully and still determine equality, which is important for robustness in scenarios where fields may be uninitialized.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import org.springframework.ai.model.ModelResponse;
import org.springframework.ai.openai.metadata.audio.OpenAiAudioSpeechResponseMetadata;

public class SpeechResponseEqualsTest {

	@Test
	@Tag("valid")
	public void equalsWithSameObjectReference() {
		// Arrange
		Speech speech = mock(Speech.class);
		OpenAiAudioSpeechResponseMetadata metadata = mock(OpenAiAudioSpeechResponseMetadata.class);
		SpeechResponse speechResponse = new SpeechResponse(speech, metadata);
		// Act
		boolean result = speechResponse.equals(speechResponse);
		// Assert
		assertTrue(result);
	}

	@Test
	@Tag("invalid")
	public void equalsWithNullParameter() {
		// Arrange
		Speech speech = mock(Speech.class);
		OpenAiAudioSpeechResponseMetadata metadata = mock(OpenAiAudioSpeechResponseMetadata.class);
		SpeechResponse speechResponse = new SpeechResponse(speech, metadata);
		// Act
		boolean result = speechResponse.equals(null);
		// Assert
		assertFalse(result);
	}

	@Test
	@Tag("invalid")
	public void equalsWithDifferentClassType() {
		// Arrange
		Speech speech = mock(Speech.class);
		OpenAiAudioSpeechResponseMetadata metadata = mock(OpenAiAudioSpeechResponseMetadata.class);
		SpeechResponse speechResponse = new SpeechResponse(speech, metadata);
		String differentClassObject = "Different Class Object";
		// Act
		boolean result = speechResponse.equals(differentClassObject);
		// Assert
		assertFalse(result);
	}

	@Test
	@Tag("valid")
	public void equalsWithDifferentObjectsSameData() {
		// Arrange
		Speech speech = mock(Speech.class);
		OpenAiAudioSpeechResponseMetadata metadata = mock(OpenAiAudioSpeechResponseMetadata.class);
		SpeechResponse speechResponse1 = new SpeechResponse(speech, metadata);
		SpeechResponse speechResponse2 = new SpeechResponse(speech, metadata);
		// Act
		boolean result = speechResponse1.equals(speechResponse2);
		// Assert
		assertTrue(result);
	}

	@Test
	@Tag("invalid")
	public void equalsWithDifferentObjectsDifferentData() {
		// Arrange
		Speech speech1 = mock(Speech.class);
		Speech speech2 = mock(Speech.class);
		OpenAiAudioSpeechResponseMetadata metadata1 = mock(OpenAiAudioSpeechResponseMetadata.class);
		OpenAiAudioSpeechResponseMetadata metadata2 = mock(OpenAiAudioSpeechResponseMetadata.class);
		SpeechResponse speechResponse1 = new SpeechResponse(speech1, metadata1);
		SpeechResponse speechResponse2 = new SpeechResponse(speech2, metadata2);
		// Act
		boolean result = speechResponse1.equals(speechResponse2);
		// Assert
		assertFalse(result);
	}

	@Test
	@Tag("boundary")
	public void equalsWithNullFields() {
		// Arrange
		SpeechResponse speechResponse1 = new SpeechResponse(null, null);
		SpeechResponse speechResponse2 = new SpeechResponse(null, null);
		// Act
		boolean result = speechResponse1.equals(speechResponse2);
		// Assert
		assertTrue(result);
	}

}