/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=hashCode_b578478f36
ROOST_METHOD_SIG_HASH=hashCode_44411a81c8

Scenario 1: HashCode Calculation with Null Fields

Details:
  TestName: hashCodeWithNullFields
  Description: This test checks the hashCode method when both speechOptions and message fields are null. It verifies that the method handles null values correctly and returns a consistent hash code.
Execution:
  Arrange: Create an instance of SpeechPrompt with both speechOptions and message set to null.
  Act: Call the hashCode method on the instance.
  Assert: Use JUnit assertions to verify that the hash code is consistent and does not throw any exceptions.
Validation:
  This test ensures that the hashCode method can handle null fields gracefully, which is crucial for avoiding NullPointerExceptions and ensuring consistent behavior in collections like HashSet or HashMap.

Scenario 2: HashCode Calculation with Non-Null Fields

Details:
  TestName: hashCodeWithNonNullFields
  Description: This test checks the hashCode method when both speechOptions and message fields are non-null. It ensures that the method returns a consistent hash code based on the field values.
Execution:
  Arrange: Create an instance of SpeechPrompt with non-null values for speechOptions and message.
  Act: Call the hashCode method on the instance.
  Assert: Use JUnit assertions to verify that the hash code is consistent with the expected value based on the field values.
Validation:
  This test verifies that the hashCode method correctly incorporates non-null field values into the hash code calculation, ensuring proper behavior in collections.

Scenario 3: HashCode Consistency Across Multiple Calls

Details:
  TestName: hashCodeConsistency
  Description: This test checks that the hashCode method returns the same value when called multiple times on the same object instance, ensuring consistency.
Execution:
  Arrange: Create an instance of SpeechPrompt with specific values for speechOptions and message.
  Act: Call the hashCode method multiple times on the same instance.
  Assert: Use JUnit assertions to verify that the hash code remains the same across multiple calls.
Validation:
  Consistency in hash code values is crucial for maintaining the integrity of collections like HashSet or HashMap, where hash codes are used to determine object placement.

Scenario 4: HashCode Difference for Different Objects

Details:
  TestName: hashCodeDifferenceForDifferentObjects
  Description: This test checks that the hashCode method returns different values for different SpeechPrompt instances with different field values.
Execution:
  Arrange: Create two instances of SpeechPrompt with different values for speechOptions and message.
  Act: Call the hashCode method on both instances.
  Assert: Use JUnit assertions to verify that the hash codes are different for the two instances.
Validation:
  This test ensures that the hashCode method provides a good distribution of hash codes, which is important for the performance of hash-based collections.

Scenario 5: HashCode Equality for Equal Objects

Details:
  TestName: hashCodeEqualityForEqualObjects
  Description: This test checks that the hashCode method returns the same value for two different SpeechPrompt instances that are considered equal.
Execution:
  Arrange: Create two instances of SpeechPrompt with identical values for speechOptions and message.
  Act: Call the hashCode method on both instances.
  Assert: Use JUnit assertions to verify that the hash codes are the same for the two instances.
Validation:
  This test ensures that the hashCode method is consistent with the equals method, which is a requirement for objects used in hash-based collections.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.ai.model.ModelOptions;
import org.springframework.ai.model.ModelRequest;
import org.springframework.ai.openai.OpenAiAudioSpeechOptions;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class SpeechPromptHashCodeTest {

	@Test
	@Tag("valid")
	public void hashCodeWithNullFields() {
		SpeechPrompt speechPrompt = new SpeechPrompt((SpeechMessage) null, (OpenAiAudioSpeechOptions) null);
		int hashCode = speechPrompt.hashCode();
		assertNotNull(hashCode);
	}

	@Test
	@Tag("valid")
	public void hashCodeWithNonNullFields() {
		SpeechMessage message = new SpeechMessage("Test message");
		OpenAiAudioSpeechOptions options = OpenAiAudioSpeechOptions.builder().build();
		SpeechPrompt speechPrompt = new SpeechPrompt(message, options);
		int hashCode = speechPrompt.hashCode();
		assertNotNull(hashCode);
	}

	@Test
	@Tag("valid")
	public void hashCodeConsistency() {
		SpeechMessage message = new SpeechMessage("Consistency test");
		OpenAiAudioSpeechOptions options = OpenAiAudioSpeechOptions.builder().build();
		SpeechPrompt speechPrompt = new SpeechPrompt(message, options);
		int firstHashCode = speechPrompt.hashCode();
		int secondHashCode = speechPrompt.hashCode();
		assertEquals(firstHashCode, secondHashCode);
	}

	@Test
	@Tag("valid")
	public void hashCodeDifferenceForDifferentObjects() {
		SpeechMessage message1 = new SpeechMessage("Message 1");
		OpenAiAudioSpeechOptions options1 = OpenAiAudioSpeechOptions.builder().build();
		SpeechPrompt speechPrompt1 = new SpeechPrompt(message1, options1);
		SpeechMessage message2 = new SpeechMessage("Message 2");
		OpenAiAudioSpeechOptions options2 = OpenAiAudioSpeechOptions.builder().build();
		SpeechPrompt speechPrompt2 = new SpeechPrompt(message2, options2);
		int hashCode1 = speechPrompt1.hashCode();
		int hashCode2 = speechPrompt2.hashCode();
		assertNotEquals(hashCode1, hashCode2);
	}

	@Test
	@Tag("valid")
	public void hashCodeEqualityForEqualObjects() {
		SpeechMessage message1 = new SpeechMessage("Equal message");
		OpenAiAudioSpeechOptions options1 = OpenAiAudioSpeechOptions.builder().build();
		SpeechPrompt speechPrompt1 = new SpeechPrompt(message1, options1);
		SpeechMessage message2 = new SpeechMessage("Equal message");
		OpenAiAudioSpeechOptions options2 = OpenAiAudioSpeechOptions.builder().build();
		SpeechPrompt speechPrompt2 = new SpeechPrompt(message2, options2);
		int hashCode1 = speechPrompt1.hashCode();
		int hashCode2 = speechPrompt2.hashCode();
		assertEquals(hashCode1, hashCode2);
	}

}