/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=withSpeechMetadata_4baa68b533
ROOST_METHOD_SIG_HASH=withSpeechMetadata_86d24000f0

Scenario 1: Setting Speech Metadata to a Non-Null Value

Details:
  TestName: setSpeechMetadataToNonNullValue
  Description: This test checks if the method correctly assigns a non-null OpenAiAudioSpeechMetadata object to the speechMetadata field and returns the Speech object itself.
Execution:
  Arrange: Create an instance of Speech and a non-null OpenAiAudioSpeechMetadata object.
  Act: Call the withSpeechMetadata method with the non-null OpenAiAudioSpeechMetadata object.
  Assert: Verify that the speechMetadata field of the Speech instance is set to the provided non-null object and the method returns the same Speech instance.
Validation:
  This assertion verifies that the method correctly updates the speechMetadata field when a valid metadata object is provided. It ensures the method's functionality aligns with expected behavior when handling non-null inputs.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.ai.openai.metadata.audio.OpenAiAudioSpeechMetadata;
import org.junit.jupiter.api.*;
import java.util.Arrays;
import java.util.Objects;
import org.springframework.ai.model.ModelResult;
import org.springframework.lang.Nullable;

public class SpeechWithSpeechMetadataTest {

	@Test
	@Tag("valid")
	public void setSpeechMetadataToNonNullValue() {
		// Arrange
		byte[] audioData = new byte[] { 1, 2, 3 }; // TODO: Change to actual audio data if
													// needed
		Speech speech = new Speech(audioData);
		OpenAiAudioSpeechMetadata mockMetadata = Mockito.mock(OpenAiAudioSpeechMetadata.class);
		// Act
		Speech result = speech.withSpeechMetadata(mockMetadata);
		// Assert
		assertSame(speech, result, "The method should return the same Speech instance.");
		assertEquals(mockMetadata, result.getMetadata(),
				"The speechMetadata should be set to the provided non-null object.");
	}

}