/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=getMetadata_301c24b6d3
ROOST_METHOD_SIG_HASH=getMetadata_f4c80e8c88

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/speech/OpenAiSpeechModelWithSpeechResponseMetadataTests.java
Tests:
    "@Test
@Test
void aiResponseContainsImageResponseMetadata() {
    prepareMock();
    OpenAiAudioSpeechOptions speechOptions = OpenAiAudioSpeechOptions.builder().voice(OpenAiAudioApi.SpeechRequest.Voice.ALLOY).speed(SPEED).responseFormat(OpenAiAudioApi.SpeechRequest.AudioResponseFormat.MP3).model(OpenAiAudioApi.TtsModel.TTS_1.value).build();
    SpeechPrompt speechPrompt = new SpeechPrompt("Today is a wonderful day to build something people love!", speechOptions);
    SpeechResponse response = this.openAiSpeechClient.call(speechPrompt);
    byte[] audioBytes = response.getResult().getOutput();
    assertThat(audioBytes).hasSizeGreaterThan(0);
    OpenAiAudioSpeechResponseMetadata speechResponseMetadata = response.getMetadata();
    assertThat(speechResponseMetadata).isNotNull();
    var requestLimit = speechResponseMetadata.getRateLimit();
    Long requestsLimit = requestLimit.getRequestsLimit();
    Long tokensLimit = requestLimit.getTokensLimit();
    Long tokensRemaining = requestLimit.getTokensRemaining();
    Long requestsRemaining = requestLimit.getRequestsRemaining();
    Duration requestsReset = requestLimit.getRequestsReset();
    assertThat(requestsLimit).isNotNull();
    assertThat(requestsLimit).isEqualTo(4000L);
    assertThat(tokensLimit).isEqualTo(725000L);
    assertThat(tokensRemaining).isEqualTo(112358L);
    assertThat(requestsRemaining).isEqualTo(999L);
    assertThat(requestsReset).isEqualTo(Duration.parse("PT64H15M29S"));
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/transcription/OpenAiTranscriptionModelWithTranscriptionResponseMetadataTests.java
Tests:
    "@Test
@Test
void aiResponseContainsAiMetadata() {
    prepareMock();
    Resource audioFile = new ClassPathResource("speech/jfk.flac");
    AudioTranscriptionPrompt transcriptionRequest = new AudioTranscriptionPrompt(audioFile);
    AudioTranscriptionResponse response = this.openAiTranscriptionModel.call(transcriptionRequest);
    assertThat(response).isNotNull();
    OpenAiAudioTranscriptionResponseMetadata transcriptionResponseMetadata = (OpenAiAudioTranscriptionResponseMetadata) response.getMetadata();
    assertThat(transcriptionResponseMetadata).isNotNull();
    RateLimit rateLimit = transcriptionResponseMetadata.getRateLimit();
    Duration expectedRequestsReset = Duration.ofDays(2L).plus(Duration.ofHours(16L)).plus(Duration.ofMinutes(15)).plus(Duration.ofSeconds(29L));
    Duration expectedTokensReset = Duration.ofHours(27L).plus(Duration.ofSeconds(55L)).plus(Duration.ofMillis(451L));
    assertThat(rateLimit).isNotNull();
    assertThat(rateLimit.getRequestsLimit()).isEqualTo(4000L);
    assertThat(rateLimit.getRequestsRemaining()).isEqualTo(999);
    assertThat(rateLimit.getRequestsReset()).isEqualTo(expectedRequestsReset);
    assertThat(rateLimit.getTokensLimit()).isEqualTo(725_000L);
    assertThat(rateLimit.getTokensRemaining()).isEqualTo(112_358L);
    assertThat(rateLimit.getTokensReset()).isEqualTo(expectedTokensReset);
    response.getResults().forEach(transcript -> {
        AudioTranscriptionMetadata transcriptionMetadata = transcript.getMetadata();
        assertThat(transcriptionMetadata).isNotNull();
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/DeepSeekWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void streamingWithTokenUsage() {
    var promptOptions = OpenAiChatOptions.builder().streamUsage(true).seed(1).build();
    var prompt = new Prompt("List two colors of the Polish flag. Be brief.", promptOptions);
    var streamingTokenUsage = this.chatModel.stream(prompt).blockLast().getMetadata().getUsage();
    var referenceTokenUsage = this.chatModel.call(prompt).getMetadata().getUsage();
    assertThat(streamingTokenUsage.getPromptTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getCompletionTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getTotalTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getPromptTokens()).isEqualTo(referenceTokenUsage.getPromptTokens());
    assertThat(streamingTokenUsage.getCompletionTokens()).isEqualTo(referenceTokenUsage.getCompletionTokens());
    assertThat(streamingTokenUsage.getTotalTokens()).isEqualTo(referenceTokenUsage.getTotalTokens());
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "deepseek-chat", "deepseek-reasoner" })
void validateCallResponseMetadata(String model) {

    ChatResponse response = ChatClient.create(this.chatModel).prompt().options(OpenAiChatOptions.builder().model(model).build()).user("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did").call().chatResponse();

    logger.info(response.toString());
    assertThat(response.getMetadata().getId()).isNotEmpty();
    assertThat(response.getMetadata().getModel()).containsIgnoringCase(model);
    assertThat(response.getMetadata().getUsage().getPromptTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getCompletionTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getTotalTokens()).isPositive();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/transformer/MetadataTransformerIT.java
Tests:
    "@Test
@Test
public void testKeywordExtractor() {
    var updatedDocuments = this.keywordMetadataEnricher.apply(List.of(this.document1, this.document2));
    List<Map<String, Object>> keywords = updatedDocuments.stream().map(d -> d.getMetadata()).toList();
    assertThat(updatedDocuments.size()).isEqualTo(2);
    var keywords1 = keywords.get(0);
    var keywords2 = keywords.get(1);
    assertThat(keywords1).containsKeys("excerpt_keywords");
    assertThat(keywords2).containsKeys("excerpt_keywords");
    assertThat((String) keywords1.get("excerpt_keywords")).contains("Andes", "Aymara");
    assertThat(((String) keywords2.get("excerpt_keywords")).toLowerCase()).containsAnyOf("spring mvc", "dependency injection");
}
"
    "@Test
@Test
public void testSummaryExtractor() {
    var updatedDocuments = this.summaryMetadataEnricher.apply(List.of(this.document1, this.document2));
    List<Map<String, Object>> summaries = updatedDocuments.stream().map(d -> d.getMetadata()).toList();
    assertThat(summaries.size()).isEqualTo(2);
    var summary1 = summaries.get(0);
    var summary2 = summaries.get(1);
    assertThat(summary1).containsKeys("section_summary", "next_section_summary");
    assertThat(summary1).doesNotContainKeys("prev_section_summary");
    assertThat(summary2).containsKeys("section_summary", "prev_section_summary");
    assertThat(summary2).doesNotContainKeys("next_section_summary");
    assertThat((String) summary1.get("section_summary")).isNotEmpty();
    assertThat((String) summary1.get("next_section_summary")).isNotEmpty();
    assertThat((String) summary2.get("section_summary")).isNotEmpty();
    assertThat((String) summary2.get("prev_section_summary")).isNotEmpty();
    assertThat((String) summary1.get("section_summary")).isEqualTo((String) summary2.get("prev_section_summary"));
    assertThat((String) summary1.get("next_section_summary")).isEqualTo((String) summary2.get("section_summary"));
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/PerplexityWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void streamingWithTokenUsage() {
    var promptOptions = OpenAiChatOptions.builder().streamUsage(true).seed(1).build();
    var prompt = new Prompt("List two colors of the Polish flag. Be brief.", promptOptions);
    var streamingTokenUsage = this.chatModel.stream(prompt).blockLast().getMetadata().getUsage();
    var referenceTokenUsage = this.chatModel.call(prompt).getMetadata().getUsage();
    assertThat(streamingTokenUsage.getPromptTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getCompletionTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getTotalTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getPromptTokens()).isEqualTo(referenceTokenUsage.getPromptTokens());
    assertThat(streamingTokenUsage.getCompletionTokens()).isGreaterThanOrEqualTo(referenceTokenUsage.getCompletionTokens());
    assertThat(streamingTokenUsage.getTotalTokens()).isGreaterThanOrEqualTo(referenceTokenUsage.getTotalTokens());
}
"
    "@Test
@Test
void validateCallResponseMetadata() {
    ChatResponse response = ChatClient.create(this.chatModel).prompt().options(OpenAiChatOptions.builder().model(DEFAULT_PERPLEXITY_MODEL).build()).user("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did").call().chatResponse();
    logger.info(response.toString());
    assertThat(response.getMetadata().getId()).isNotEmpty();
    assertThat(response.getMetadata().getModel()).containsIgnoringCase(DEFAULT_PERPLEXITY_MODEL);
    assertThat(response.getMetadata().getUsage().getPromptTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getCompletionTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getTotalTokens()).isPositive();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/OllamaWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
@Disabled("Not supported by the current Ollama API")
void streamingWithTokenUsage() {
    var promptOptions = OpenAiChatOptions.builder().streamUsage(true).seed(1).build();
    var prompt = new Prompt("List two colors of the Polish flag. Be brief.", promptOptions);
    var streamingTokenUsage = this.chatModel.stream(prompt).blockLast().getMetadata().getUsage();
    var referenceTokenUsage = this.chatModel.call(prompt).getMetadata().getUsage();

    assertThat(streamingTokenUsage.getCompletionTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getTotalTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getPromptTokens()).isEqualTo(referenceTokenUsage.getPromptTokens());
    assertThat(streamingTokenUsage.getCompletionTokens()).isEqualTo(referenceTokenUsage.getCompletionTokens());
    assertThat(streamingTokenUsage.getTotalTokens()).isEqualTo(referenceTokenUsage.getTotalTokens());
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "mistral" })
void validateCallResponseMetadata(String model) {

    ChatResponse response = ChatClient.create(this.chatModel).prompt().options(OpenAiChatOptions.builder().model(model).build()).user("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did").call().chatResponse();

    logger.info(response.toString());
    assertThat(response.getMetadata().getId()).isNotEmpty();
    assertThat(response.getMetadata().getModel()).containsIgnoringCase(model);
    assertThat(response.getMetadata().getUsage().getPromptTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getCompletionTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getTotalTokens()).isPositive();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/image/OpenAiImageModelIT.java
Tests:
    "@Test
@Test
void imageAsUrlTest() {
    var options = ImageOptionsBuilder.builder().height(1024).width(1024).build();
    var instructions = """
        A light cream colored mini golden doodle with a sign that contains the message "I'm on my way to BARCADE!".""";
    ImagePrompt imagePrompt = new ImagePrompt(instructions, options);
    ImageResponse imageResponse = this.imageModel.call(imagePrompt);
    assertThat(imageResponse.getResults()).hasSize(1);
    ImageResponseMetadata imageResponseMetadata = imageResponse.getMetadata();
    assertThat(imageResponseMetadata.getCreated()).isPositive();
    var generation = imageResponse.getResult();
    Image image = generation.getOutput();
    assertThat(image.getUrl()).isNotEmpty();

    assertThat(image.getB64Json()).isNull();
    var imageGenerationMetadata = generation.getMetadata();
    Assertions.assertThat(imageGenerationMetadata).isInstanceOf(OpenAiImageGenerationMetadata.class);
    OpenAiImageGenerationMetadata openAiImageGenerationMetadata = (OpenAiImageGenerationMetadata) imageGenerationMetadata;
    assertThat(openAiImageGenerationMetadata).isNotNull();
    assertThat(openAiImageGenerationMetadata.getRevisedPrompt()).isNotBlank();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelObservationIT.java
Tests:
    "@Test
@Test
void observationForChatOperation() {
    var options = OpenAiChatOptions.builder().model(OpenAiApi.ChatModel.GPT_4_O_MINI.getValue()).frequencyPenalty(0.0).maxTokens(2048).presencePenalty(0.0).stop(List.of("this-is-the-end")).temperature(0.7).topP(1.0).build();
    Prompt prompt = new Prompt("Why does a raven look like a desk?", options);
    ChatResponse chatResponse = this.chatModel.call(prompt);
    assertThat(chatResponse.getResult().getOutput().getText()).isNotEmpty();
    ChatResponseMetadata responseMetadata = chatResponse.getMetadata();
    assertThat(responseMetadata).isNotNull();
    validate(responseMetadata);
}
"
    "@Test
@Test
void observationForStreamingChatOperation() {
    var options = OpenAiChatOptions.builder().model(OpenAiApi.ChatModel.GPT_4_O_MINI.getValue()).frequencyPenalty(0.0).maxTokens(2048).presencePenalty(0.0).stop(List.of("this-is-the-end")).temperature(0.7).topP(1.0).streamUsage(true).build();
    Prompt prompt = new Prompt("Why does a raven look like a desk?", options);
    Flux<ChatResponse> chatResponseFlux = this.chatModel.stream(prompt);
    List<ChatResponse> responses = chatResponseFlux.collectList().block();
    assertThat(responses).isNotEmpty();
    assertThat(responses).hasSizeGreaterThan(10);
    String aggregatedResponse = responses.subList(0, responses.size() - 1).stream().map(r -> r.getResult().getOutput().getText()).collect(Collectors.joining());
    assertThat(aggregatedResponse).isNotEmpty();
    ChatResponse lastChatResponse = responses.get(responses.size() - 1);
    ChatResponseMetadata responseMetadata = lastChatResponse.getMetadata();
    assertThat(responseMetadata).isNotNull();
    validate(responseMetadata);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/vectorstore/SimplePersistentVectorStoreIT.java
Tests:
    "@Test
@Test
void persist() {
    JsonReader jsonReader = new JsonReader(this.bikesJsonResource, new ProductMetadataGenerator(), "price", "name", "shortDescription", "description", "tags");
    List<Document> documents = jsonReader.get();
    SimpleVectorStore vectorStore = SimpleVectorStore.builder(this.embeddingModel).build();
    vectorStore.add(documents);
    File tempFile = new File(this.workingDir.toFile(), "temp.txt");
    vectorStore.save(tempFile);
    assertThat(tempFile).isNotEmpty();
    assertThat(tempFile).content().contains("Velo 99 XR1 AXS");
    SimpleVectorStore vectorStore2 = SimpleVectorStore.builder(this.embeddingModel).build();
    vectorStore2.load(tempFile);
    List<Document> similaritySearch = vectorStore2.similaritySearch("Velo 99 XR1 AXS");
    assertThat(similaritySearch).isNotEmpty();
    assertThat(similaritySearch.get(0).getMetadata()).containsEntry("name", "Velo 99 XR1 AXS");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/embedding/OpenAiEmbeddingModelObservationIT.java
Tests:
    "@Test
@Test
void observationForEmbeddingOperation() {
    var options = OpenAiEmbeddingOptions.builder().model(OpenAiApi.EmbeddingModel.TEXT_EMBEDDING_3_SMALL.getValue()).dimensions(1536).encodingFormat("float").build();
    EmbeddingRequest embeddingRequest = new EmbeddingRequest(List.of("Here comes the sun"), options);
    EmbeddingResponse embeddingResponse = this.embeddingModel.call(embeddingRequest);
    assertThat(embeddingResponse.getResults()).isNotEmpty();
    EmbeddingResponseMetadata responseMetadata = embeddingResponse.getMetadata();
    assertThat(responseMetadata).isNotNull();
    TestObservationRegistryAssert.assertThat(this.observationRegistry).doesNotHaveAnyRemainingCurrentObservation().hasObservationWithNameEqualTo(DefaultEmbeddingModelObservationConvention.DEFAULT_NAME).that().hasContextualNameEqualTo("embedding " + OpenAiApi.EmbeddingModel.TEXT_EMBEDDING_3_SMALL.getValue()).hasLowCardinalityKeyValue(LowCardinalityKeyNames.AI_OPERATION_TYPE.asString(), AiOperationType.EMBEDDING.value()).hasLowCardinalityKeyValue(LowCardinalityKeyNames.AI_PROVIDER.asString(), AiProvider.OPENAI.value()).hasLowCardinalityKeyValue(LowCardinalityKeyNames.REQUEST_MODEL.asString(), OpenAiApi.EmbeddingModel.TEXT_EMBEDDING_3_SMALL.getValue()).hasLowCardinalityKeyValue(LowCardinalityKeyNames.RESPONSE_MODEL.asString(), responseMetadata.getModel()).hasHighCardinalityKeyValue(HighCardinalityKeyNames.REQUEST_EMBEDDING_DIMENSIONS.asString(), "1536").hasHighCardinalityKeyValue(HighCardinalityKeyNames.USAGE_INPUT_TOKENS.asString(), String.valueOf(responseMetadata.getUsage().getPromptTokens())).hasHighCardinalityKeyValue(HighCardinalityKeyNames.USAGE_TOTAL_TOKENS.asString(), String.valueOf(responseMetadata.getUsage().getTotalTokens())).hasBeenStarted().hasBeenStopped();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/image/OpenAiImageModelWithImageResponseMetadataTests.java
Tests:
    "@Test
@Test
void aiResponseContainsImageResponseMetadata() {
    prepareMock();
    ImagePrompt prompt = new ImagePrompt("Create an image of a mini golden doodle dog.");
    ImageResponse response = this.openAiImageModel.call(prompt);
    assertThat(response).isNotNull();
    List<ImageGeneration> imageGenerations = response.getResults();
    assertThat(imageGenerations).isNotNull();
    assertThat(imageGenerations).hasSize(2);
    ImageResponseMetadata imageResponseMetadata = response.getMetadata();
    assertThat(imageResponseMetadata).isNotNull();
    Long created = imageResponseMetadata.getCreated();
    assertThat(created).isNotNull();
    assertThat(created).isEqualTo(1589478378);
    ImageResponseMetadata responseMetadata = response.getMetadata();
    assertThat(responseMetadata).isNotNull();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/MistralWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
@Disabled("Not supported by the current Mistral AI API")
void streamingWithTokenUsage() {
    var promptOptions = OpenAiChatOptions.builder().streamUsage(true).seed(1).build();
    var prompt = new Prompt("List two colors of the Polish flag. Be brief.", promptOptions);
    var streamingTokenUsage = this.chatModel.stream(prompt).blockLast().getMetadata().getUsage();
    var referenceTokenUsage = this.chatModel.call(prompt).getMetadata().getUsage();
    assertThat(streamingTokenUsage.getPromptTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getCompletionTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getTotalTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getPromptTokens()).isEqualTo(referenceTokenUsage.getPromptTokens());
    assertThat(streamingTokenUsage.getCompletionTokens()).isEqualTo(referenceTokenUsage.getCompletionTokens());
    assertThat(streamingTokenUsage.getTotalTokens()).isEqualTo(referenceTokenUsage.getTotalTokens());
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "mistral-small-latest", "mistral-large-latest", "open-mistral-7b", "open-mixtral-8x7b", "open-mixtral-8x22b" })
void validateCallResponseMetadata(String model) {

    ChatResponse response = ChatClient.create(this.chatModel).prompt().options(OpenAiChatOptions.builder().model(model).build()).user("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did").call().chatResponse();

    logger.info(response.toString());
    assertThat(response.getMetadata().getId()).isNotEmpty();
    assertThat(response.getMetadata().getModel()).containsIgnoringCase(model);
    assertThat(response.getMetadata().getUsage().getPromptTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getCompletionTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getTotalTokens()).isPositive();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/NvidiaWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void streamingWithTokenUsage() {
    var promptOptions = OpenAiChatOptions.builder().streamUsage(true).seed(1).build();
    var prompt = new Prompt("List two colors of the Polish flag. Be brief.", promptOptions);
    var streamingTokenUsage = this.chatModel.stream(prompt).blockLast().getMetadata().getUsage();
    var referenceTokenUsage = this.chatModel.call(prompt).getMetadata().getUsage();
    assertThat(streamingTokenUsage.getPromptTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getCompletionTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getTotalTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getPromptTokens()).isEqualTo(referenceTokenUsage.getPromptTokens());
    assertThat(streamingTokenUsage.getCompletionTokens()).isEqualTo(referenceTokenUsage.getCompletionTokens());
    assertThat(streamingTokenUsage.getTotalTokens()).isEqualTo(referenceTokenUsage.getTotalTokens());
}
"
    "@Test
@Test
void validateCallResponseMetadata() {

    ChatResponse response = ChatClient.create(this.chatModel).prompt().options(OpenAiChatOptions.builder().model(DEFAULT_NVIDIA_MODEL).build()).user("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did").call().chatResponse();

    logger.info(response.toString());
    assertThat(response.getMetadata().getId()).isNotEmpty();
    assertThat(response.getMetadata().getModel()).containsIgnoringCase(DEFAULT_NVIDIA_MODEL);
    assertThat(response.getMetadata().getUsage().getPromptTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getCompletionTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getTotalTokens()).isPositive();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/speech/OpenAiSpeechModelIT.java
Tests:
    "@Test
@Test
void speechRateLimitTest() {
    OpenAiAudioSpeechOptions speechOptions = OpenAiAudioSpeechOptions.builder().voice(OpenAiAudioApi.SpeechRequest.Voice.ALLOY).speed(SPEED).responseFormat(OpenAiAudioApi.SpeechRequest.AudioResponseFormat.MP3).model(OpenAiAudioApi.TtsModel.TTS_1.value).build();
    SpeechPrompt speechPrompt = new SpeechPrompt("Today is a wonderful day to build something people love!", speechOptions);
    SpeechResponse response = this.speechModel.call(speechPrompt);
    OpenAiAudioSpeechResponseMetadata metadata = response.getMetadata();
    assertThat(metadata).isNotNull();
    assertThat(metadata.getRateLimit()).isNotNull();
    assertThat(metadata.getRateLimit().getRequestsLimit()).isPositive();
    assertThat(metadata.getRateLimit().getRequestsLimit()).isPositive();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/embedding/EmbeddingIT.java
Tests:
    "@Test
@Test
void defaultEmbedding() {
    assertThat(this.embeddingModel).isNotNull();
    EmbeddingResponse embeddingResponse = this.embeddingModel.embedForResponse(List.of("Hello World"));
    assertThat(embeddingResponse.getResults()).hasSize(1);
    assertThat(embeddingResponse.getResults().get(0)).isNotNull();
    assertThat(embeddingResponse.getResults().get(0).getOutput()).hasSize(1536);
    assertThat(embeddingResponse.getMetadata().getModel()).isEqualTo("text-embedding-ada-002-v2");
    assertThat(embeddingResponse.getMetadata().getUsage().getTotalTokens()).isEqualTo(2);
    assertThat(embeddingResponse.getMetadata().getUsage().getPromptTokens()).isEqualTo(2);
    assertThat(this.embeddingModel.dimensions()).isEqualTo(1536);
}
"
    "@Test
@Test
void embedding3Large() {
    EmbeddingResponse embeddingResponse = this.embeddingModel.call(new EmbeddingRequest(List.of("Hello World"), OpenAiEmbeddingOptions.builder().model("text-embedding-3-large").build()));
    assertThat(embeddingResponse.getResults()).hasSize(1);
    assertThat(embeddingResponse.getResults().get(0)).isNotNull();
    assertThat(embeddingResponse.getResults().get(0).getOutput()).hasSize(3072);
    assertThat(embeddingResponse.getMetadata().getModel()).isEqualTo("text-embedding-3-large");
    assertThat(embeddingResponse.getMetadata().getUsage().getTotalTokens()).isEqualTo(2);
    assertThat(embeddingResponse.getMetadata().getUsage().getPromptTokens()).isEqualTo(2);

}
"
    "@Test
@Test
void textEmbeddingAda002() {
    EmbeddingResponse embeddingResponse = this.embeddingModel.call(new EmbeddingRequest(List.of("Hello World"), OpenAiEmbeddingOptions.builder().model("text-embedding-3-small").build()));
    assertThat(embeddingResponse.getResults()).hasSize(1);
    assertThat(embeddingResponse.getResults().get(0)).isNotNull();
    assertThat(embeddingResponse.getResults().get(0).getOutput()).hasSize(1536);
    assertThat(embeddingResponse.getMetadata().getModel()).isEqualTo("text-embedding-3-small");
    assertThat(embeddingResponse.getMetadata().getUsage().getTotalTokens()).isEqualTo(2);
    assertThat(embeddingResponse.getMetadata().getUsage().getPromptTokens()).isEqualTo(2);

}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelIT.java
Tests:
    "@Test
@Test
void streamingWithTokenUsage() {
    var promptOptions = OpenAiChatOptions.builder().streamUsage(true).seed(1).build();
    var prompt = new Prompt("List two colors of the Polish flag. Be brief.", promptOptions);
    var streamingTokenUsage = this.chatModel.stream(prompt).blockLast().getMetadata().getUsage();
    var referenceTokenUsage = this.chatModel.call(prompt).getMetadata().getUsage();
    assertThat(streamingTokenUsage.getPromptTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getCompletionTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getTotalTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getPromptTokens()).isCloseTo(referenceTokenUsage.getPromptTokens(), Percentage.withPercentage(25));
    assertThat(streamingTokenUsage.getCompletionTokens()).isCloseTo(referenceTokenUsage.getCompletionTokens(), Percentage.withPercentage(25));
    assertThat(streamingTokenUsage.getTotalTokens()).isCloseTo(referenceTokenUsage.getTotalTokens(), Percentage.withPercentage(25));
}
"
    "@Test
@Test
void functionCallUsageTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().
    functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse chatResponse = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", chatResponse);
    Usage usage = chatResponse.getMetadata().getUsage();
    logger.info("Usage: {}", usage);
    assertThat(usage).isNotNull();
    assertThat(usage).isNotInstanceOf(EmptyUsage.class);
    assertThat(usage).isInstanceOf(DefaultUsage.class);
    assertThat(usage.getPromptTokens()).isGreaterThan(450).isLessThan(600);
    assertThat(usage.getCompletionTokens()).isGreaterThan(230).isLessThan(360);
    assertThat(usage.getTotalTokens()).isGreaterThan(680).isLessThan(900);
}
"
    "@Test
@Test
void streamFunctionCallUsageTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().
    functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).streamUsage(true).build();
    Flux<ChatResponse> response = this.streamingChatModel.stream(new Prompt(messages, promptOptions));
    Usage usage = response.last().block().getMetadata().getUsage();
    logger.info("Usage: {}", usage);
    assertThat(usage).isNotNull();
    assertThat(usage).isNotInstanceOf(EmptyUsage.class);
    assertThat(usage).isInstanceOf(DefaultUsage.class);
    assertThat(usage.getPromptTokens()).isGreaterThan(450).isLessThan(600);
    assertThat(usage.getCompletionTokens()).isGreaterThan(230).isLessThan(360);
    assertThat(usage.getTotalTokens()).isGreaterThan(680).isLessThan(960);
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "gpt-4o-audio-preview" })
void multiModalityInputAudio(String modelName) {
    var audioResource = new ClassPathResource("speech1.mp3");
    var userMessage = new UserMessage("What is this recording about?", List.of(new Media(MimeTypeUtils.parseMimeType("audio/mp3"), audioResource)));
    ChatResponse response = chatModel.call(new Prompt(List.of(userMessage), ChatOptions.builder().model(modelName).build()));
    logger.info(response.getResult().getOutput().getText());
    assertThat(response.getResult().getOutput().getText()).containsIgnoringCase("hobbits");
    assertThat(response.getMetadata().getModel()).containsIgnoringCase(modelName);
}
"
    "@Test
@Test
void validateCallResponseMetadata() {
    String model = OpenAiApi.ChatModel.GPT_3_5_TURBO.getName();

    ChatResponse response = ChatClient.create(this.chatModel).prompt().options(OpenAiChatOptions.builder().model(model).build()).user("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did").call().chatResponse();

    logger.info(response.toString());
    assertThat(response.getMetadata().getId()).isNotEmpty();
    assertThat(response.getMetadata().getModel()).containsIgnoringCase(model);
    assertThat(response.getMetadata().getUsage().getPromptTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getCompletionTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getTotalTokens()).isPositive();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/GroqWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
@Disabled("Not supported by the current Groq API")
void streamingWithTokenUsage() {
    var promptOptions = OpenAiChatOptions.builder().streamUsage(true).seed(1).build();
    var prompt = new Prompt("List two colors of the Polish flag. Be brief.", promptOptions);
    var streamingTokenUsage = this.chatModel.stream(prompt).blockLast().getMetadata().getUsage();
    var referenceTokenUsage = this.chatModel.call(prompt).getMetadata().getUsage();
    assertThat(streamingTokenUsage.getPromptTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getCompletionTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getTotalTokens()).isGreaterThan(0);
    assertThat(streamingTokenUsage.getPromptTokens()).isEqualTo(referenceTokenUsage.getPromptTokens());
    assertThat(streamingTokenUsage.getCompletionTokens()).isEqualTo(referenceTokenUsage.getCompletionTokens());
    assertThat(streamingTokenUsage.getTotalTokens()).isEqualTo(referenceTokenUsage.getTotalTokens());
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "llama3-8b-8192", "llama3-70b-8192", "mixtral-8x7b-32768", "gemma-7b-it" })
void validateCallResponseMetadata(String model) {

    ChatResponse response = ChatClient.create(this.chatModel).prompt().options(OpenAiChatOptions.builder().model(model).build()).user("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did").call().chatResponse();

    logger.info(response.toString());
    assertThat(response.getMetadata().getId()).isNotEmpty();
    assertThat(response.getMetadata().getModel()).containsIgnoringCase(model);
    assertThat(response.getMetadata().getUsage().getPromptTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getCompletionTokens()).isPositive();
    assertThat(response.getMetadata().getUsage().getTotalTokens()).isPositive();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelWithChatResponseMetadataTests.java
Tests:
    "@Test
@Test
void aiResponseContainsAiMetadata() {
    prepareMock();
    Prompt prompt = new Prompt("Reach for the sky.");
    ChatResponse response = this.openAiChatClient.call(prompt);
    assertThat(response).isNotNull();
    ChatResponseMetadata chatResponseMetadata = response.getMetadata();
    assertThat(chatResponseMetadata).isNotNull();
    Usage usage = chatResponseMetadata.getUsage();
    assertThat(usage).isNotNull();
    assertThat(usage.getPromptTokens()).isEqualTo(9L);
    assertThat(usage.getCompletionTokens()).isEqualTo(12L);
    assertThat(usage.getTotalTokens()).isEqualTo(21L);
    RateLimit rateLimit = chatResponseMetadata.getRateLimit();
    Duration expectedRequestsReset = Duration.ofDays(2L).plus(Duration.ofHours(16L)).plus(Duration.ofMinutes(15)).plus(Duration.ofSeconds(29L));
    Duration expectedTokensReset = Duration.ofHours(27L).plus(Duration.ofSeconds(55L)).plus(Duration.ofMillis(451L));
    assertThat(rateLimit).isNotNull();
    assertThat(rateLimit.getRequestsLimit()).isEqualTo(4000L);
    assertThat(rateLimit.getRequestsRemaining()).isEqualTo(999);
    assertThat(rateLimit.getRequestsReset()).isEqualTo(expectedRequestsReset);
    assertThat(rateLimit.getTokensLimit()).isEqualTo(725_000L);
    assertThat(rateLimit.getTokensRemaining()).isEqualTo(112_358L);
    assertThat(rateLimit.getTokensReset()).isEqualTo(expectedTokensReset);
    PromptMetadata promptMetadata = response.getMetadata().getPromptMetadata();
    assertThat(promptMetadata).isNotNull();
    assertThat(promptMetadata).isEmpty();
    response.getResults().forEach(generation -> {
        ChatGenerationMetadata chatGenerationMetadata = generation.getMetadata();
        assertThat(chatGenerationMetadata).isNotNull();
        assertThat(chatGenerationMetadata.getFinishReason()).isEqualTo("STOP");
        assertThat(chatGenerationMetadata.getContentFilters()).isEmpty();
    });
}
"
Scenario 1: Return Non-Null Metadata When speechMetadata Is Set

Details:
  TestName: returnNonNullMetadataWhenSpeechMetadataIsSet
  Description: This test checks that the getMetadata method returns the non-null speechMetadata when it is set in the Speech object.
Execution:
  Arrange: Create a Speech object and set a non-null OpenAiAudioSpeechMetadata instance to its speechMetadata field using the withSpeechMetadata method.
  Act: Call the getMetadata method on the Speech object.
  Assert: Verify that the returned metadata is the same instance as the one set in the speechMetadata field.
Validation:
  This assertion verifies that the method correctly returns the actual metadata when it is available, ensuring the method's functionality aligns with expected behavior when speechMetadata is not null.

Scenario 2: Return Null Metadata When speechMetadata Is Null

Details:
  TestName: returnNullMetadataWhenSpeechMetadataIsNull
  Description: This test checks that the getMetadata method returns OpenAiAudioSpeechMetadata.NULL when the speechMetadata field is null.
Execution:
  Arrange: Create a Speech object without setting the speechMetadata field, leaving it null.
  Act: Call the getMetadata method on the Speech object.
  Assert: Verify that the returned metadata is OpenAiAudioSpeechMetadata.NULL.
Validation:
  This assertion ensures that the method correctly handles the case where speechMetadata is null, returning a default null object as expected, which is crucial for preventing null pointer exceptions in client code.

Scenario 3: Consistent Metadata Return After Multiple Calls

Details:
  TestName: consistentMetadataReturnAfterMultipleCalls
  Description: This test checks that the getMetadata method consistently returns the same metadata instance after multiple calls.
Execution:
  Arrange: Create a Speech object and set a non-null OpenAiAudioSpeechMetadata instance to its speechMetadata field using the withSpeechMetadata method.
  Act: Call the getMetadata method multiple times on the Speech object.
  Assert: Verify that each call returns the same metadata instance.
Validation:
  This assertion confirms the method's consistency and reliability in returning the same metadata instance across multiple invocations, which is important for maintaining stable application behavior.

Scenario 4: Handle Null Metadata Gracefully

Details:
  TestName: handleNullMetadataGracefully
  Description: This test checks that the getMetadata method handles null metadata gracefully without throwing exceptions.
Execution:
  Arrange: Create a Speech object without setting the speechMetadata field, leaving it null.
  Act: Call the getMetadata method on the Speech object.
  Assert: Verify that no exceptions are thrown and the returned metadata is OpenAiAudioSpeechMetadata.NULL.
Validation:
  This assertion ensures that the method is robust against null values, preventing runtime errors and ensuring smooth application operation even when metadata is not set.

Scenario 5: Verify Metadata Type Consistency

Details:
  TestName: verifyMetadataTypeConsistency
  Description: This test checks that the getMetadata method always returns an instance of OpenAiAudioSpeechMetadata, either the actual metadata or the NULL object.
Execution:
  Arrange: Create a Speech object and optionally set a non-null OpenAiAudioSpeechMetadata instance to its speechMetadata field.
  Act: Call the getMetadata method on the Speech object.
  Assert: Verify that the returned object is an instance of OpenAiAudioSpeechMetadata.
Validation:
  This assertion ensures type consistency, confirming that the method always returns a valid metadata object, which is critical for type safety and preventing class cast exceptions in client code.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.util.Arrays;
import java.util.Objects;
import org.springframework.ai.model.ModelResult;
import org.springframework.ai.openai.metadata.audio.OpenAiAudioSpeechMetadata;
import org.springframework.lang.Nullable;

public class SpeechGetMetadataTest {

	@Test
	@Tag("valid")
	public void returnNonNullMetadataWhenSpeechMetadataIsSet() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio bytes
		OpenAiAudioSpeechMetadata expectedMetadata = mock(OpenAiAudioSpeechMetadata.class);
		Speech speech = new Speech(audio).withSpeechMetadata(expectedMetadata);
		// Act
		OpenAiAudioSpeechMetadata actualMetadata = speech.getMetadata();
		// Assert
		assertSame(expectedMetadata, actualMetadata);
	}

	@Test
	@Tag("valid")
	public void returnNullMetadataWhenSpeechMetadataIsNull() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio bytes
		Speech speech = new Speech(audio);
		// Act
		OpenAiAudioSpeechMetadata actualMetadata = speech.getMetadata();
		// Assert
		assertSame(OpenAiAudioSpeechMetadata.NULL, actualMetadata);
	}

	@Test
	@Tag("valid")
	public void consistentMetadataReturnAfterMultipleCalls() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio bytes
		OpenAiAudioSpeechMetadata expectedMetadata = mock(OpenAiAudioSpeechMetadata.class);
		Speech speech = new Speech(audio).withSpeechMetadata(expectedMetadata);
		// Act
		OpenAiAudioSpeechMetadata firstCallMetadata = speech.getMetadata();
		OpenAiAudioSpeechMetadata secondCallMetadata = speech.getMetadata();
		// Assert
		assertSame(firstCallMetadata, secondCallMetadata);
	}

	@Test
	@Tag("valid")
	public void handleNullMetadataGracefully() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio bytes
		Speech speech = new Speech(audio);
		// Act & Assert
		assertDoesNotThrow(() -> {
			OpenAiAudioSpeechMetadata metadata = speech.getMetadata();
			assertSame(OpenAiAudioSpeechMetadata.NULL, metadata);
		});
	}

	@Test
	@Tag("valid")
	public void verifyMetadataTypeConsistency() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio bytes
		Speech speech = new Speech(audio);
		// Act
		OpenAiAudioSpeechMetadata metadata = speech.getMetadata();
		// Assert
		assertTrue(metadata instanceof OpenAiAudioSpeechMetadata);
	}

}