/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=equals_26c796038c
ROOST_METHOD_SIG_HASH=equals_ded257778a

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/api/tool/OpenAiApiToolFunctionCallIT.java
Tests:
    "@Test
@SuppressWarnings("null")
@Test
public void toolFunctionCall() {

    var message = new ChatCompletionMessage("What's the weather like in San Francisco, Tokyo, and Paris?", Role.USER);
    var functionTool = new OpenAiApi.FunctionTool(OpenAiApi.FunctionTool.Type.FUNCTION, new OpenAiApi.FunctionTool.Function("Get the weather in location. Return temperature in Celsius.", "getCurrentWeather", ModelOptionsUtils.jsonToMap("""
        {
        	"type": "object",
        	"properties": {
        		"location": {
        			"type": "string",
        			"description": "The city and state e.g. San Francisco, CA"
        		},
        		"lat": {
        			"type": "number",
        			"description": "The city latitude"
        		},
        		"lon": {
        			"type": "number",
        			"description": "The city longitude"
        		},
        		"unit": {
        			"type": "string",
        			"enum": ["C", "F"]
        		}
        	},
        	"required": ["location", "lat", "lon", "unit"]
        }
        """), null));
    List<ChatCompletionMessage> messages = new ArrayList<>(List.of(message));
    ChatCompletionRequest chatCompletionRequest = new ChatCompletionRequest(messages, "gpt-4o", List.of(functionTool), ToolChoiceBuilder.AUTO);

    ResponseEntity<ChatCompletion> chatCompletion = this.completionApi.chatCompletionEntity(chatCompletionRequest);
    assertThat(chatCompletion.getBody()).isNotNull();
    assertThat(chatCompletion.getBody().choices()).isNotEmpty();
    ChatCompletionMessage responseMessage = chatCompletion.getBody().choices().get(0).message();

    assertThat(responseMessage.role()).isEqualTo(Role.ASSISTANT);
    assertThat(responseMessage.toolCalls()).isNotNull();

    messages.add(responseMessage);

    for (ToolCall toolCall : responseMessage.toolCalls()) {
        var functionName = toolCall.function().name();
        if ("getCurrentWeather".equals(functionName)) {
            MockWeatherService.Request weatherRequest = fromJson(toolCall.function().arguments(), MockWeatherService.Request.class);
            MockWeatherService.Response weatherResponse = this.weatherService.apply(weatherRequest);

            messages.add(new ChatCompletionMessage("" + weatherResponse.temp() + weatherRequest.unit(), Role.TOOL, functionName, toolCall.id(), null, null, null));
        }
    }
    var functionResponseRequest = new ChatCompletionRequest(messages, "gpt-4o", 0.5);
    ResponseEntity<ChatCompletion> chatCompletion2 = this.completionApi.chatCompletionEntity(functionResponseRequest);
    logger.info("Final response: " + chatCompletion2.getBody());
    assertThat(chatCompletion2.getBody().choices()).isNotEmpty();
    assertThat(chatCompletion2.getBody().choices().get(0).message().role()).isEqualTo(Role.ASSISTANT);
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("San Francisco").containsAnyOf("30.0°C", "30°C");
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("Tokyo").containsAnyOf("10.0°C", "10°C");
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("Paris").containsAnyOf("15.0°C", "15°C");
}
"Scenario 1: Equality of Identical Speech Objects

Details:
  TestName: equalsIdenticalSpeechObjects
  Description: This test checks if the equals method returns true when comparing a Speech object to itself. This scenario verifies the reflexivity property of the equals method.
Execution:
  Arrange: Create a Speech object with specific audio and speechMetadata values.
  Act: Call the equals method on the Speech object, passing itself as the parameter.
  Assert: Use JUnit assertions to verify that the method returns true.
Validation:
  This assertion verifies that an object is always equal to itself, which is a fundamental property of the equals method. It ensures the method's reflexivity.

Scenario 2: Equality with Null Object

Details:
  TestName: equalsWithNullObject
  Description: This test checks if the equals method returns false when comparing a Speech object to null. This scenario verifies that the method correctly handles null comparisons.
Execution:
  Arrange: Create a Speech object with specific audio and speechMetadata values.
  Act: Call the equals method on the Speech object, passing null as the parameter.
  Assert: Use JUnit assertions to verify that the method returns false.
Validation:
  This assertion verifies that an object is not equal to null, which is a fundamental property of the equals method. It ensures the method's null handling.

Scenario 3: Equality with Different Class Object

Details:
  TestName: equalsWithDifferentClassObject
  Description: This test checks if the equals method returns false when comparing a Speech object to an object of a different class. This scenario verifies that the method correctly handles comparisons with different types.
Execution:
  Arrange: Create a Speech object and an object of a different class (e.g., String).
  Act: Call the equals method on the Speech object, passing the different class object as the parameter.
  Assert: Use JUnit assertions to verify that the method returns false.
Validation:
  This assertion verifies that an object is not equal to an instance of a different class, ensuring type safety in the equals method.

Scenario 4: Equality with Different Audio Arrays

Details:
  TestName: equalsWithDifferentAudioArrays
  Description: This test checks if the equals method returns false when comparing two Speech objects with different audio arrays but identical speechMetadata. This scenario verifies the method's behavior with differing audio data.
Execution:
  Arrange: Create two Speech objects with different audio arrays but the same speechMetadata.
  Act: Call the equals method on the first Speech object, passing the second Speech object as the parameter.
  Assert: Use JUnit assertions to verify that the method returns false.
Validation:
  This assertion verifies that the equals method correctly identifies differences in audio data, ensuring accurate equality checks based on content.

Scenario 5: Equality with Different SpeechMetadata

Details:
  TestName: equalsWithDifferentSpeechMetadata
  Description: This test checks if the equals method returns false when comparing two Speech objects with identical audio arrays but different speechMetadata. This scenario verifies the method's behavior with differing metadata.
Execution:
  Arrange: Create two Speech objects with the same audio arrays but different speechMetadata.
  Act: Call the equals method on the first Speech object, passing the second Speech object as the parameter.
  Assert: Use JUnit assertions to verify that the method returns false.
Validation:
  This assertion verifies that the equals method correctly identifies differences in metadata, ensuring accurate equality checks based on metadata content.

Scenario 6: Equality with Identical Audio and Metadata

Details:
  TestName: equalsWithIdenticalAudioAndMetadata
  Description: This test checks if the equals method returns true when comparing two Speech objects with identical audio arrays and speechMetadata. This scenario verifies the method's behavior with completely identical objects.
Execution:
  Arrange: Create two Speech objects with identical audio arrays and speechMetadata.
  Act: Call the equals method on the first Speech object, passing the second Speech object as the parameter.
  Assert: Use JUnit assertions to verify that the method returns true.
Validation:
  This assertion verifies that the equals method correctly identifies identical objects, ensuring accurate equality checks when all attributes match.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.util.Arrays;
import java.util.Objects;
import org.springframework.ai.model.ModelResult;
import org.springframework.ai.openai.metadata.audio.OpenAiAudioSpeechMetadata;
import org.springframework.lang.Nullable;

public class SpeechEqualsTest {

	@Test
	@Tag("valid")
	public void equalsIdenticalSpeechObjects() {
		byte[] audio = new byte[] { 1, 2, 3 };
		OpenAiAudioSpeechMetadata metadata = mock(OpenAiAudioSpeechMetadata.class);
		Speech speech = new Speech(audio).withSpeechMetadata(metadata);
		assertTrue(speech.equals(speech));
	}

	@Test
	@Tag("invalid")
	public void equalsWithNullObject() {
		byte[] audio = new byte[] { 1, 2, 3 };
		OpenAiAudioSpeechMetadata metadata = mock(OpenAiAudioSpeechMetadata.class);
		Speech speech = new Speech(audio).withSpeechMetadata(metadata);
		assertFalse(speech.equals(null));
	}

	@Test
	@Tag("invalid")
	public void equalsWithDifferentClassObject() {
		byte[] audio = new byte[] { 1, 2, 3 };
		OpenAiAudioSpeechMetadata metadata = mock(OpenAiAudioSpeechMetadata.class);
		Speech speech = new Speech(audio).withSpeechMetadata(metadata);
		assertFalse(speech.equals("DifferentClassObject"));
	}

	@Test
	@Tag("invalid")
	public void equalsWithDifferentAudioArrays() {
		byte[] audio1 = new byte[] { 1, 2, 3 };
		byte[] audio2 = new byte[] { 4, 5, 6 };
		OpenAiAudioSpeechMetadata metadata = mock(OpenAiAudioSpeechMetadata.class);
		Speech speech1 = new Speech(audio1).withSpeechMetadata(metadata);
		Speech speech2 = new Speech(audio2).withSpeechMetadata(metadata);
		assertFalse(speech1.equals(speech2));
	}

	@Test
	@Tag("invalid")
	public void equalsWithDifferentSpeechMetadata() {
		byte[] audio = new byte[] { 1, 2, 3 };
		OpenAiAudioSpeechMetadata metadata1 = mock(OpenAiAudioSpeechMetadata.class);
		OpenAiAudioSpeechMetadata metadata2 = mock(OpenAiAudioSpeechMetadata.class);
		Speech speech1 = new Speech(audio).withSpeechMetadata(metadata1);
		Speech speech2 = new Speech(audio).withSpeechMetadata(metadata2);
		assertFalse(speech1.equals(speech2));
	}

	@Test
	@Tag("valid")
	public void equalsWithIdenticalAudioAndMetadata() {
		byte[] audio = new byte[] { 1, 2, 3 };
		OpenAiAudioSpeechMetadata metadata = mock(OpenAiAudioSpeechMetadata.class);
		Speech speech1 = new Speech(audio).withSpeechMetadata(metadata);
		Speech speech2 = new Speech(audio).withSpeechMetadata(metadata);
		assertTrue(speech1.equals(speech2));
	}

}