/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=getResults_017a6aa35a
ROOST_METHOD_SIG_HASH=getResults_f51cd93df9

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientIT.java
Tests:
    "@Test
@Test
void call() {

    ChatResponse response = ChatClient.create(this.chatModel).prompt().advisors(new SimpleLoggerAdvisor()).system(s -> s.text(this.systemTextResource).param("name", "Bob").param("voice", "pirate")).user("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did").call().chatResponse();

    logger.info("" + response);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientProxyFunctionCallsIT.java
Tests:
    "@Test
@Test
void toolProxyFunctionCall() throws JsonMappingException, JsonProcessingException {
    List<Message> messages = List.of(new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?"));
    boolean isToolCall = false;
    ChatResponse chatResponse = null;
    var chatClient = ChatClient.builder(this.chatModel).build();
    do {
        chatResponse = chatClient.prompt().messages(messages).tools(this.functionDefinition).options(OpenAiChatOptions.builder().proxyToolCalls(true).build()).call().chatResponse();


        isToolCall = this.functionCallingHelper.isToolCall(chatResponse, Set.of(OpenAiApi.ChatCompletionFinishReason.TOOL_CALLS.name(), OpenAiApi.ChatCompletionFinishReason.STOP.name()));
        if (isToolCall) {
            Optional<Generation> toolCallGeneration = chatResponse.getResults().stream().filter(g -> !CollectionUtils.isEmpty(g.getOutput().getToolCalls())).findFirst();
            assertThat(toolCallGeneration).isNotEmpty();
            AssistantMessage assistantMessage = toolCallGeneration.get().getOutput();
            List<ToolResponseMessage.ToolResponse> toolResponses = new ArrayList<>();
            for (AssistantMessage.ToolCall toolCall : assistantMessage.getToolCalls()) {
                var functionName = toolCall.name();
                assertThat(functionName).isEqualTo("getWeatherInLocation");
                String functionArguments = toolCall.arguments();
                @SuppressWarnings("unchecked")
                Map<String, String> argumentsMap = new ObjectMapper().readValue(functionArguments, Map.class);
                String functionResponse = getWeatherInLocation(argumentsMap.get("location").toString(), argumentsMap.get("unit").toString());
                toolResponses.add(new ToolResponseMessage.ToolResponse(toolCall.id(), functionName, ModelOptionsUtils.toJsonString(functionResponse)));
            }
            ToolResponseMessage toolMessageResponse = new ToolResponseMessage(toolResponses, Map.of());
            messages = this.functionCallingHelper.buildToolCallConversation(messages, assistantMessage, toolMessageResponse);
            assertThat(messages).isNotEmpty();

        }
    } while (isToolCall);
    logger.info("Response: {}", chatResponse);
    assertThat(chatResponse.getResult().getOutput().getText()).contains("30", "10", "15");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/transcription/OpenAiTranscriptionModelWithTranscriptionResponseMetadataTests.java
Tests:
    "@Test
@Test
void aiResponseContainsAiMetadata() {
    prepareMock();
    Resource audioFile = new ClassPathResource("speech/jfk.flac");
    AudioTranscriptionPrompt transcriptionRequest = new AudioTranscriptionPrompt(audioFile);
    AudioTranscriptionResponse response = this.openAiTranscriptionModel.call(transcriptionRequest);
    assertThat(response).isNotNull();
    OpenAiAudioTranscriptionResponseMetadata transcriptionResponseMetadata = (OpenAiAudioTranscriptionResponseMetadata) response.getMetadata();
    assertThat(transcriptionResponseMetadata).isNotNull();
    RateLimit rateLimit = transcriptionResponseMetadata.getRateLimit();
    Duration expectedRequestsReset = Duration.ofDays(2L).plus(Duration.ofHours(16L)).plus(Duration.ofMinutes(15)).plus(Duration.ofSeconds(29L));
    Duration expectedTokensReset = Duration.ofHours(27L).plus(Duration.ofSeconds(55L)).plus(Duration.ofMillis(451L));
    assertThat(rateLimit).isNotNull();
    assertThat(rateLimit.getRequestsLimit()).isEqualTo(4000L);
    assertThat(rateLimit.getRequestsRemaining()).isEqualTo(999);
    assertThat(rateLimit.getRequestsReset()).isEqualTo(expectedRequestsReset);
    assertThat(rateLimit.getTokensLimit()).isEqualTo(725_000L);
    assertThat(rateLimit.getTokensRemaining()).isEqualTo(112_358L);
    assertThat(rateLimit.getTokensReset()).isEqualTo(expectedTokensReset);
    response.getResults().forEach(transcript -> {
        AudioTranscriptionMetadata transcriptionMetadata = transcript.getMetadata();
        assertThat(transcriptionMetadata).isNotNull();
    });
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/moderation/OpenAiModerationModelIT.java
Tests:
    "@Test
@Test
void moderationAsUrlTestPositive() {
    var options = ModerationOptionsBuilder.builder().model("text-moderation-stable").build();
    var instructions = """
        I want to kill them.!".""";
    ModerationPrompt moderationPrompt = new ModerationPrompt(instructions, options);
    ModerationResponse moderationResponse = this.openAiModerationModel.call(moderationPrompt);
    assertThat(moderationResponse.getResults()).hasSize(1);
    var generation = moderationResponse.getResult();
    Moderation moderation = generation.getOutput();
    assertThat(moderation.getId()).isNotEmpty();
    assertThat(moderation.getResults()).isNotNull();
    assertThat(moderation.getResults().size()).isNotZero();
    System.out.println(moderation.getResults().toString());
    assertThat(moderation.getId()).isNotNull();
    assertThat(moderation.getModel()).isNotNull();
    ModerationResult result = moderation.getResults().get(0);
    assertThat(result.isFlagged()).isTrue();
    Categories categories = result.getCategories();
    assertThat(categories).isNotNull();
    assertThat(categories.isSexual()).isNotNull();
    assertThat(categories.isHate()).isNotNull();
    assertThat(categories.isHarassment()).isNotNull();
    assertThat(categories.isSelfHarm()).isNotNull();
    assertThat(categories.isSexualMinors()).isNotNull();
    assertThat(categories.isHateThreatening()).isNotNull();
    assertThat(categories.isViolenceGraphic()).isNotNull();
    assertThat(categories.isSelfHarmIntent()).isNotNull();
    assertThat(categories.isSelfHarmInstructions()).isNotNull();
    assertThat(categories.isHarassmentThreatening()).isNotNull();
    assertThat(categories.isViolence()).isTrue();
    CategoryScores scores = result.getCategoryScores();
    assertThat(scores.getSexual()).isNotNull();
    assertThat(scores.getHate()).isNotNull();
    assertThat(scores.getHarassment()).isNotNull();
    assertThat(scores.getSelfHarm()).isNotNull();
    assertThat(scores.getSexualMinors()).isNotNull();
    assertThat(scores.getHateThreatening()).isNotNull();
    assertThat(scores.getViolenceGraphic()).isNotNull();
    assertThat(scores.getSelfHarmIntent()).isNotNull();
    assertThat(scores.getSelfHarmInstructions()).isNotNull();
    assertThat(scores.getHarassmentThreatening()).isNotNull();
    assertThat(scores.getViolence()).isNotNull();
}
"
    "@Test
@Test
void moderationAsUrlTestNegative() {
    var options = ModerationOptionsBuilder.builder().model("text-moderation-stable").build();
    var instructions = """
        A light cream colored mini golden doodle with a sign that contains the message "I'm on my way to BARCADE!".""";
    ModerationPrompt moderationPrompt = new ModerationPrompt(instructions, options);
    ModerationResponse moderationResponse = this.openAiModerationModel.call(moderationPrompt);
    assertThat(moderationResponse.getResults()).hasSize(1);
    var generation = moderationResponse.getResult();
    Moderation moderation = generation.getOutput();
    assertThat(moderation.getId()).isNotEmpty();
    assertThat(moderation.getResults()).isNotNull();
    assertThat(moderation.getResults().size()).isNotZero();
    System.out.println(moderation.getResults().toString());
    assertThat(moderation.getId()).isNotNull();
    assertThat(moderation.getModel()).isNotNull();
    ModerationResult result = moderation.getResults().get(0);
    assertThat(result.isFlagged()).isFalse();
    Categories categories = result.getCategories();
    assertThat(categories.isSexual()).isFalse();
    assertThat(categories.isHate()).isFalse();
    assertThat(categories.isHarassment()).isFalse();
    assertThat(categories.isSelfHarm()).isFalse();
    assertThat(categories.isSexualMinors()).isFalse();
    assertThat(categories.isHateThreatening()).isFalse();
    assertThat(categories.isViolenceGraphic()).isFalse();
    assertThat(categories.isSelfHarmIntent()).isFalse();
    assertThat(categories.isSelfHarmInstructions()).isFalse();
    assertThat(categories.isHarassmentThreatening()).isFalse();
    assertThat(categories.isViolence()).isFalse();
    CategoryScores scores = result.getCategoryScores();
    assertThat(scores.getSexual()).isNotNull();
    assertThat(scores.getHate()).isNotNull();
    assertThat(scores.getHarassment()).isNotNull();
    assertThat(scores.getSelfHarm()).isNotNull();
    assertThat(scores.getSexualMinors()).isNotNull();
    assertThat(scores.getHateThreatening()).isNotNull();
    assertThat(scores.getViolenceGraphic()).isNotNull();
    assertThat(scores.getSelfHarmIntent()).isNotNull();
    assertThat(scores.getSelfHarmInstructions()).isNotNull();
    assertThat(scores.getHarassmentThreatening()).isNotNull();
    assertThat(scores.getViolence()).isNotNull();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/DeepSeekWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/PerplexityWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {


    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    Prompt prompt = new Prompt(List.of(systemMessage, userMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"
    "@Test
@Test
void functionCallTest() {
    UserMessage userMessage = new UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?");
    List<Message> messages = new ArrayList<>(List.of(userMessage));
    var promptOptions = OpenAiChatOptions.builder().functionCallbacks(List.of(FunctionCallback.builder().function("getCurrentWeather", new MockWeatherService()).description("Get the weather in location").inputType(MockWeatherService.Request.class).build())).build();
    ChatResponse response = this.chatModel.call(new Prompt(messages, promptOptions));
    logger.info("Response: {}", response);
    assertThat(response.getResults().stream().mapToLong(r -> r.getOutput().getToolCalls().size()).sum()).isZero();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiCompatibleChatModelIT.java
Tests:
    "@Test
@ParameterizedTest
@MethodSource("openAiCompatibleApis")
void chatCompletion(ChatModel chatModel) {
    Prompt prompt = new Prompt(this.conversation);
    ChatResponse response = chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/OllamaWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/image/OpenAiImageModelIT.java
Tests:
    "@Test
@Test
void imageAsUrlTest() {
    var options = ImageOptionsBuilder.builder().height(1024).width(1024).build();
    var instructions = """
        A light cream colored mini golden doodle with a sign that contains the message "I'm on my way to BARCADE!".""";
    ImagePrompt imagePrompt = new ImagePrompt(instructions, options);
    ImageResponse imageResponse = this.imageModel.call(imagePrompt);
    assertThat(imageResponse.getResults()).hasSize(1);
    ImageResponseMetadata imageResponseMetadata = imageResponse.getMetadata();
    assertThat(imageResponseMetadata.getCreated()).isPositive();
    var generation = imageResponse.getResult();
    Image image = generation.getOutput();
    assertThat(image.getUrl()).isNotEmpty();

    assertThat(image.getB64Json()).isNull();
    var imageGenerationMetadata = generation.getMetadata();
    Assertions.assertThat(imageGenerationMetadata).isInstanceOf(OpenAiImageGenerationMetadata.class);
    OpenAiImageGenerationMetadata openAiImageGenerationMetadata = (OpenAiImageGenerationMetadata) imageGenerationMetadata;
    assertThat(openAiImageGenerationMetadata).isNotNull();
    assertThat(openAiImageGenerationMetadata.getRevisedPrompt()).isNotBlank();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/transcription/OpenAiTranscriptionModelIT.java
Tests:
    "@Test
@Test
void transcriptionTest() {
    OpenAiAudioTranscriptionOptions transcriptionOptions = OpenAiAudioTranscriptionOptions.builder().responseFormat(TranscriptResponseFormat.TEXT).temperature(0f).build();
    AudioTranscriptionPrompt transcriptionRequest = new AudioTranscriptionPrompt(this.audioFile, transcriptionOptions);
    AudioTranscriptionResponse response = this.transcriptionModel.call(transcriptionRequest);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().toLowerCase().contains("fellow")).isTrue();
}
"
    "@Test
@Test
void transcriptionTestWithOptions() {
    OpenAiAudioApi.TranscriptResponseFormat responseFormat = OpenAiAudioApi.TranscriptResponseFormat.VTT;
    OpenAiAudioTranscriptionOptions transcriptionOptions = OpenAiAudioTranscriptionOptions.builder().language("en").prompt("Ask not this, but ask that").temperature(0f).responseFormat(responseFormat).build();
    AudioTranscriptionPrompt transcriptionRequest = new AudioTranscriptionPrompt(this.audioFile, transcriptionOptions);
    AudioTranscriptionResponse response = this.transcriptionModel.call(transcriptionRequest);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().toLowerCase().contains("fellow")).isTrue();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/embedding/OpenAiEmbeddingModelObservationIT.java
Tests:
    "@Test
@Test
void observationForEmbeddingOperation() {
    var options = OpenAiEmbeddingOptions.builder().model(OpenAiApi.EmbeddingModel.TEXT_EMBEDDING_3_SMALL.getValue()).dimensions(1536).encodingFormat("float").build();
    EmbeddingRequest embeddingRequest = new EmbeddingRequest(List.of("Here comes the sun"), options);
    EmbeddingResponse embeddingResponse = this.embeddingModel.call(embeddingRequest);
    assertThat(embeddingResponse.getResults()).isNotEmpty();
    EmbeddingResponseMetadata responseMetadata = embeddingResponse.getMetadata();
    assertThat(responseMetadata).isNotNull();
    TestObservationRegistryAssert.assertThat(this.observationRegistry).doesNotHaveAnyRemainingCurrentObservation().hasObservationWithNameEqualTo(DefaultEmbeddingModelObservationConvention.DEFAULT_NAME).that().hasContextualNameEqualTo("embedding " + OpenAiApi.EmbeddingModel.TEXT_EMBEDDING_3_SMALL.getValue()).hasLowCardinalityKeyValue(LowCardinalityKeyNames.AI_OPERATION_TYPE.asString(), AiOperationType.EMBEDDING.value()).hasLowCardinalityKeyValue(LowCardinalityKeyNames.AI_PROVIDER.asString(), AiProvider.OPENAI.value()).hasLowCardinalityKeyValue(LowCardinalityKeyNames.REQUEST_MODEL.asString(), OpenAiApi.EmbeddingModel.TEXT_EMBEDDING_3_SMALL.getValue()).hasLowCardinalityKeyValue(LowCardinalityKeyNames.RESPONSE_MODEL.asString(), responseMetadata.getModel()).hasHighCardinalityKeyValue(HighCardinalityKeyNames.REQUEST_EMBEDDING_DIMENSIONS.asString(), "1536").hasHighCardinalityKeyValue(HighCardinalityKeyNames.USAGE_INPUT_TOKENS.asString(), String.valueOf(responseMetadata.getUsage().getPromptTokens())).hasHighCardinalityKeyValue(HighCardinalityKeyNames.USAGE_TOTAL_TOKENS.asString(), String.valueOf(responseMetadata.getUsage().getTotalTokens())).hasBeenStarted().hasBeenStopped();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/image/OpenAiImageModelObservationIT.java
Tests:
    "@Test
@Test
void observationForImageOperation() {
    var options = OpenAiImageOptions.builder().model(OpenAiImageApi.ImageModel.DALL_E_3.getValue()).height(1024).width(1024).responseFormat("url").style("natural").build();
    var instructions = "Here comes the sun";
    ImagePrompt imagePrompt = new ImagePrompt(instructions, options);
    ImageResponse imageResponse = this.imageModel.call(imagePrompt);
    assertThat(imageResponse.getResults()).hasSize(1);
    TestObservationRegistryAssert.assertThat(this.observationRegistry).doesNotHaveAnyRemainingCurrentObservation().hasObservationWithNameEqualTo(DefaultImageModelObservationConvention.DEFAULT_NAME).that().hasContextualNameEqualTo("image " + OpenAiImageApi.ImageModel.DALL_E_3.getValue()).hasLowCardinalityKeyValue(LowCardinalityKeyNames.AI_OPERATION_TYPE.asString(), AiOperationType.IMAGE.value()).hasLowCardinalityKeyValue(LowCardinalityKeyNames.AI_PROVIDER.asString(), AiProvider.OPENAI.value()).hasLowCardinalityKeyValue(LowCardinalityKeyNames.REQUEST_MODEL.asString(), OpenAiImageApi.ImageModel.DALL_E_3.getValue()).hasHighCardinalityKeyValue(HighCardinalityKeyNames.REQUEST_IMAGE_SIZE.asString(), "1024x1024").hasHighCardinalityKeyValue(HighCardinalityKeyNames.REQUEST_IMAGE_RESPONSE_FORMAT.asString(), "url").hasBeenStarted().hasBeenStopped();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/image/OpenAiImageModelWithImageResponseMetadataTests.java
Tests:
    "@Test
@Test
void aiResponseContainsImageResponseMetadata() {
    prepareMock();
    ImagePrompt prompt = new ImagePrompt("Create an image of a mini golden doodle dog.");
    ImageResponse response = this.openAiImageModel.call(prompt);
    assertThat(response).isNotNull();
    List<ImageGeneration> imageGenerations = response.getResults();
    assertThat(imageGenerations).isNotNull();
    assertThat(imageGenerations).hasSize(2);
    ImageResponseMetadata imageResponseMetadata = response.getMetadata();
    assertThat(imageResponseMetadata).isNotNull();
    Long created = imageResponseMetadata.getCreated();
    assertThat(created).isNotNull();
    assertThat(created).isEqualTo(1589478378);
    ImageResponseMetadata responseMetadata = response.getMetadata();
    assertThat(responseMetadata).isNotNull();
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/MistralWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/NvidiaWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/speech/OpenAiSpeechModelIT.java
Tests:
    "@Test
@Test
void shouldGenerateNonEmptyMp3AudioFromSpeechPrompt() {
    OpenAiAudioSpeechOptions speechOptions = OpenAiAudioSpeechOptions.builder().voice(OpenAiAudioApi.SpeechRequest.Voice.ALLOY).speed(SPEED).responseFormat(OpenAiAudioApi.SpeechRequest.AudioResponseFormat.MP3).model(OpenAiAudioApi.TtsModel.TTS_1.value).build();
    SpeechPrompt speechPrompt = new SpeechPrompt("Today is a wonderful day to build something people love!", speechOptions);
    SpeechResponse response = this.speechModel.call(speechPrompt);
    byte[] audioBytes = response.getResult().getOutput();
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput()).isNotEmpty();
    assertThat(audioBytes).hasSizeGreaterThan(0);
}
"
    "@Test
@ParameterizedTest(name = "{0} : {displayName} ")
@ValueSource(strings = { "alloy", "echo", "fable", "onyx", "nova", "shimmer", "sage", "coral", "ash" })
void speechVoicesTest(String voice) {
    OpenAiAudioSpeechOptions speechOptions = OpenAiAudioSpeechOptions.builder().voice(OpenAiAudioApi.SpeechRequest.Voice.valueOf(voice.toUpperCase())).speed(SPEED).responseFormat(OpenAiAudioApi.SpeechRequest.AudioResponseFormat.MP3).model(OpenAiAudioApi.TtsModel.TTS_1.value).build();
    SpeechPrompt speechPrompt = new SpeechPrompt("Today is a wonderful day to build something people love!", speechOptions);
    SpeechResponse response = this.speechModel.call(speechPrompt);
    byte[] audioBytes = response.getResult().getOutput();
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput()).isNotEmpty();
    assertThat(audioBytes).hasSizeGreaterThan(0);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/embedding/EmbeddingIT.java
Tests:
    "@Test
@Test
void defaultEmbedding() {
    assertThat(this.embeddingModel).isNotNull();
    EmbeddingResponse embeddingResponse = this.embeddingModel.embedForResponse(List.of("Hello World"));
    assertThat(embeddingResponse.getResults()).hasSize(1);
    assertThat(embeddingResponse.getResults().get(0)).isNotNull();
    assertThat(embeddingResponse.getResults().get(0).getOutput()).hasSize(1536);
    assertThat(embeddingResponse.getMetadata().getModel()).isEqualTo("text-embedding-ada-002-v2");
    assertThat(embeddingResponse.getMetadata().getUsage().getTotalTokens()).isEqualTo(2);
    assertThat(embeddingResponse.getMetadata().getUsage().getPromptTokens()).isEqualTo(2);
    assertThat(this.embeddingModel.dimensions()).isEqualTo(1536);
}
"
    "@Test
@Test
void embedding3Large() {
    EmbeddingResponse embeddingResponse = this.embeddingModel.call(new EmbeddingRequest(List.of("Hello World"), OpenAiEmbeddingOptions.builder().model("text-embedding-3-large").build()));
    assertThat(embeddingResponse.getResults()).hasSize(1);
    assertThat(embeddingResponse.getResults().get(0)).isNotNull();
    assertThat(embeddingResponse.getResults().get(0).getOutput()).hasSize(3072);
    assertThat(embeddingResponse.getMetadata().getModel()).isEqualTo("text-embedding-3-large");
    assertThat(embeddingResponse.getMetadata().getUsage().getTotalTokens()).isEqualTo(2);
    assertThat(embeddingResponse.getMetadata().getUsage().getPromptTokens()).isEqualTo(2);

}
"
    "@Test
@Test
void textEmbeddingAda002() {
    EmbeddingResponse embeddingResponse = this.embeddingModel.call(new EmbeddingRequest(List.of("Hello World"), OpenAiEmbeddingOptions.builder().model("text-embedding-3-small").build()));
    assertThat(embeddingResponse.getResults()).hasSize(1);
    assertThat(embeddingResponse.getResults().get(0)).isNotNull();
    assertThat(embeddingResponse.getResults().get(0).getOutput()).hasSize(1536);
    assertThat(embeddingResponse.getMetadata().getModel()).isEqualTo("text-embedding-3-small");
    assertThat(embeddingResponse.getMetadata().getUsage().getTotalTokens()).isEqualTo(2);
    assertThat(embeddingResponse.getMetadata().getUsage().getPromptTokens()).isEqualTo(2);

}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");

}
"
    "@Test
@Test
void streamCompletenessTest() throws InterruptedException {
    UserMessage userMessage = new UserMessage("List ALL natural numbers in range [1, 1000]. Make sure to not omit any.");
    Prompt prompt = new Prompt(List.of(userMessage));
    StringBuilder answer = new StringBuilder();
    CountDownLatch latch = new CountDownLatch(1);
    Flux<ChatResponse> chatResponseFlux = this.streamingChatModel.stream(prompt).doOnNext(chatResponse -> {
        String responseContent = chatResponse.getResults().get(0).getOutput().getText();
        answer.append(responseContent);
    }).doOnComplete(() -> {
        logger.info(answer.toString());
        latch.countDown();
    });
    chatResponseFlux.subscribe();
    assertThat(latch.await(120, TimeUnit.SECONDS)).isTrue();
    IntStream.rangeClosed(1, 1000).forEach(n -> assertThat(answer).contains(String.valueOf(n)));
}
"
    "@Test
@Test
void streamCompletenessTestWithChatResponse() throws InterruptedException {
    UserMessage userMessage = new UserMessage("Who is George Washington? - use first as 1st");
    Prompt prompt = new Prompt(List.of(userMessage));
    StringBuilder answer = new StringBuilder();
    CountDownLatch latch = new CountDownLatch(1);
    ChatClient chatClient = ChatClient.builder(this.openAiChatModel).build();
    Flux<ChatResponse> chatResponseFlux = chatClient.prompt(prompt).stream().chatResponse().doOnNext(chatResponse -> {
        String responseContent = chatResponse.getResults().get(0).getOutput().getText();
        answer.append(responseContent);
    }).doOnComplete(() -> {
        logger.info(answer.toString());
        latch.countDown();
    });
    chatResponseFlux.subscribe();
    assertThat(latch.await(120, TimeUnit.SECONDS)).isTrue();
    assertThat(answer).contains("1st ");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/moderation/OpenAiModerationModelTests.java
Tests:
    "@Test
@Test
void aiResponseContainsModerationResponseMetadata() {
    prepareMock();
    ModerationPrompt prompt = new ModerationPrompt("I want to kill them..");
    ModerationResponse response = this.openAiModerationModel.call(prompt);
    assertThat(response).isNotNull();
    Generation generation = response.getResult();
    assertThat(generation).isNotNull();
    Moderation moderation = response.getResult().getOutput();
    assertThat(moderation).isNotNull();
    assertThat(moderation.getId()).isEqualTo("modr-XXXXX");
    assertThat(moderation.getModel()).isEqualTo("text-moderation-005");
    List<ModerationResult> results = moderation.getResults();
    ModerationResult result = results.get(0);
    assertThat(result.isFlagged()).isTrue();

    Categories categories = result.getCategories();
    assertThat(categories.isSexual()).isFalse();
    assertThat(categories.isHate()).isFalse();
    assertThat(categories.isHarassment()).isFalse();
    assertThat(categories.isSelfHarm()).isFalse();
    assertThat(categories.isSexualMinors()).isFalse();
    assertThat(categories.isHateThreatening()).isFalse();
    assertThat(categories.isViolenceGraphic()).isFalse();
    assertThat(categories.isSelfHarmIntent()).isFalse();
    assertThat(categories.isSelfHarmInstructions()).isFalse();
    assertThat(categories.isHarassmentThreatening()).isTrue();
    assertThat(categories.isViolence()).isTrue();

    CategoryScores scores = result.getCategoryScores();
    assertThat(scores.getSexual()).isEqualTo(1.2282071E-6);
    assertThat(scores.getHate()).isEqualTo(0.010696256);
    assertThat(scores.getHarassment()).isEqualTo(0.29842457);
    assertThat(scores.getSelfHarm()).isEqualTo(1.5236925E-8);
    assertThat(scores.getSexualMinors()).isEqualTo(5.7246268E-8);
    assertThat(scores.getHateThreatening()).isEqualTo(0.0060676364);
    assertThat(scores.getViolenceGraphic()).isEqualTo(4.435014E-6);
    assertThat(scores.getSelfHarmIntent()).isEqualTo(8.098441E-10);
    assertThat(scores.getSelfHarmInstructions()).isEqualTo(2.8498655E-11);
    assertThat(scores.getHarassmentThreatening()).isEqualTo(0.63055265);
    assertThat(scores.getViolence()).isEqualTo(0.99011886);
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/GroqWithOpenAiChatModelIT.java
Tests:
    "@Test
@Test
void roleTest() {
    UserMessage userMessage = new UserMessage("Tell me about 3 famous pirates from the Golden Age of Piracy and what they did.");
    SystemPromptTemplate systemPromptTemplate = new SystemPromptTemplate(this.systemResource);
    Message systemMessage = systemPromptTemplate.createMessage(Map.of("name", "Bob", "voice", "pirate"));
    Prompt prompt = new Prompt(List.of(userMessage, systemMessage));
    ChatResponse response = this.chatModel.call(prompt);
    assertThat(response.getResults()).hasSize(1);
    assertThat(response.getResults().get(0).getOutput().getText()).contains("Blackbeard");
}
"

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelWithChatResponseMetadataTests.java
Tests:
    "@Test
@Test
void aiResponseContainsAiMetadata() {
    prepareMock();
    Prompt prompt = new Prompt("Reach for the sky.");
    ChatResponse response = this.openAiChatClient.call(prompt);
    assertThat(response).isNotNull();
    ChatResponseMetadata chatResponseMetadata = response.getMetadata();
    assertThat(chatResponseMetadata).isNotNull();
    Usage usage = chatResponseMetadata.getUsage();
    assertThat(usage).isNotNull();
    assertThat(usage.getPromptTokens()).isEqualTo(9L);
    assertThat(usage.getCompletionTokens()).isEqualTo(12L);
    assertThat(usage.getTotalTokens()).isEqualTo(21L);
    RateLimit rateLimit = chatResponseMetadata.getRateLimit();
    Duration expectedRequestsReset = Duration.ofDays(2L).plus(Duration.ofHours(16L)).plus(Duration.ofMinutes(15)).plus(Duration.ofSeconds(29L));
    Duration expectedTokensReset = Duration.ofHours(27L).plus(Duration.ofSeconds(55L)).plus(Duration.ofMillis(451L));
    assertThat(rateLimit).isNotNull();
    assertThat(rateLimit.getRequestsLimit()).isEqualTo(4000L);
    assertThat(rateLimit.getRequestsRemaining()).isEqualTo(999);
    assertThat(rateLimit.getRequestsReset()).isEqualTo(expectedRequestsReset);
    assertThat(rateLimit.getTokensLimit()).isEqualTo(725_000L);
    assertThat(rateLimit.getTokensRemaining()).isEqualTo(112_358L);
    assertThat(rateLimit.getTokensReset()).isEqualTo(expectedTokensReset);
    PromptMetadata promptMetadata = response.getMetadata().getPromptMetadata();
    assertThat(promptMetadata).isNotNull();
    assertThat(promptMetadata).isEmpty();
    response.getResults().forEach(generation -> {
        ChatGenerationMetadata chatGenerationMetadata = generation.getMetadata();
        assertThat(chatGenerationMetadata).isNotNull();
        assertThat(chatGenerationMetadata.getFinishReason()).isEqualTo("STOP");
        assertThat(chatGenerationMetadata.getContentFilters()).isEmpty();
    });
}
"Scenario 1: Verify getResults returns a list containing the speech object when speech is not null

Details:
  TestName: getResultsReturnsListWithSpeechWhenNotNull
  Description: This test checks that the getResults method returns a list containing the speech object when the speech field is not null.
Execution:
  Arrange: Create an instance of SpeechResponse with a non-null Speech object assigned to the speech field.
  Act: Call the getResults method on the SpeechResponse instance.
  Assert: Verify that the returned list contains exactly one element, which is the same as the speech object.
Validation:
  This assertion verifies that the method correctly encapsulates the speech object in a list when it is not null, ensuring the method's intended functionality is preserved.

Scenario 2: Verify getResults returns a list containing null when speech is null

Details:
  TestName: getResultsReturnsListWithNullWhenSpeechIsNull
  Description: This test checks that the getResults method returns a list containing null when the speech field is null.
Execution:
  Arrange: Create an instance of SpeechResponse with the speech field set to null.
  Act: Call the getResults method on the SpeechResponse instance.
  Assert: Verify that the returned list contains exactly one element, which is null.
Validation:
  This assertion ensures that the method handles the case where the speech object is null, maintaining the expected behavior of returning a list with a single null element.

Scenario 3: Verify getResults returns a singleton list

Details:
  TestName: getResultsReturnsSingletonList
  Description: This test checks that the getResults method always returns a singleton list, regardless of the speech field's state.
Execution:
  Arrange: Create an instance of SpeechResponse with any state of the speech field (null or non-null).
  Act: Call the getResults method on the SpeechResponse instance.
  Assert: Verify that the returned list has a size of one.
Validation:
  This assertion confirms that the method consistently returns a singleton list, which is crucial for maintaining predictable behavior in the application logic.

Scenario 4: Verify getResults method does not modify the speech field

Details:
  TestName: getResultsDoesNotModifySpeechField
  Description: This test checks that the getResults method does not alter the state of the speech field.
Execution:
  Arrange: Create an instance of SpeechResponse with a specific Speech object assigned to the speech field.
  Act: Call the getResults method on the SpeechResponse instance.
  Assert: Verify that the speech field remains unchanged after the method call.
Validation:
  This assertion ensures that the method is side-effect-free concerning the speech field, preserving the integrity of the object's state.

Scenario 5: Verify getResults method's consistency with equals method

Details:
  TestName: getResultsConsistencyWithEquals
  Description: This test checks that the list returned by getResults is consistent with the equals method of SpeechResponse.
Execution:
  Arrange: Create two instances of SpeechResponse with identical Speech objects assigned to their speech fields.
  Act: Call the getResults method on both instances.
  Assert: Verify that the lists returned by getResults are equal according to the equals method.
Validation:
  This assertion ensures that the method's output is consistent with the equals method, which is important for maintaining logical equivalence between SpeechResponse objects.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Collections;
import java.util.Objects;
import org.springframework.ai.model.ModelResponse;
import org.springframework.ai.openai.metadata.audio.OpenAiAudioSpeechResponseMetadata;

public class SpeechResponseGetResultsTest {

	@Test
	@Tag("valid")
	public void getResultsReturnsListWithSpeechWhenNotNull() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio data
		Speech speech = new Speech(audio);
		SpeechResponse speechResponse = new SpeechResponse(speech);
		// Act
		List<Speech> results = speechResponse.getResults();
		// Assert
		assertNotNull(results);
		assertEquals(1, results.size());
		assertSame(speech, results.get(0));
	}

	@Test
	@Tag("valid")
	public void getResultsReturnsListWithNullWhenSpeechIsNull() {
		// Arrange
		SpeechResponse speechResponse = new SpeechResponse(null);
		// Act
		List<Speech> results = speechResponse.getResults();
		// Assert
		assertNotNull(results);
		assertEquals(1, results.size());
		assertNull(results.get(0));
	}

	@Test
	@Tag("boundary")
	public void getResultsReturnsSingletonList() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio data
		Speech speech = new Speech(audio);
		SpeechResponse speechResponse = new SpeechResponse(speech);
		// Act
		List<Speech> results = speechResponse.getResults();
		// Assert
		assertNotNull(results);
		assertEquals(1, results.size());
	}

	@Test
	@Tag("valid")
	public void getResultsDoesNotModifySpeechField() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio data
		Speech speech = new Speech(audio);
		SpeechResponse speechResponse = new SpeechResponse(speech);
		// Act
		speechResponse.getResults();
		// Assert
		assertSame(speech, speechResponse.getResult());
	}

	@Test
	@Tag("integration")
	public void getResultsConsistencyWithEquals() {
		// Arrange
		byte[] audio = new byte[] { 1, 2, 3 }; // TODO: Change to appropriate audio data
		Speech speech1 = new Speech(audio);
		Speech speech2 = new Speech(audio);
		SpeechResponse speechResponse1 = new SpeechResponse(speech1);
		SpeechResponse speechResponse2 = new SpeechResponse(speech2);
		// Act
		List<Speech> results1 = speechResponse1.getResults();
		List<Speech> results2 = speechResponse2.getResults();
		// Assert
		assertEquals(results1, results2);
		assertTrue(speechResponse1.equals(speechResponse2));
	}

}