/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=equals_d9818de36e
ROOST_METHOD_SIG_HASH=equals_ded257778a

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/api/tool/OpenAiApiToolFunctionCallIT.java
Tests:
    "@Test
@SuppressWarnings("null")
@Test
public void toolFunctionCall() {

    var message = new ChatCompletionMessage("What's the weather like in San Francisco, Tokyo, and Paris?", Role.USER);
    var functionTool = new OpenAiApi.FunctionTool(OpenAiApi.FunctionTool.Type.FUNCTION, new OpenAiApi.FunctionTool.Function("Get the weather in location. Return temperature in Celsius.", "getCurrentWeather", ModelOptionsUtils.jsonToMap("""
        {
        	"type": "object",
        	"properties": {
        		"location": {
        			"type": "string",
        			"description": "The city and state e.g. San Francisco, CA"
        		},
        		"lat": {
        			"type": "number",
        			"description": "The city latitude"
        		},
        		"lon": {
        			"type": "number",
        			"description": "The city longitude"
        		},
        		"unit": {
        			"type": "string",
        			"enum": ["C", "F"]
        		}
        	},
        	"required": ["location", "lat", "lon", "unit"]
        }
        """), null));
    List<ChatCompletionMessage> messages = new ArrayList<>(List.of(message));
    ChatCompletionRequest chatCompletionRequest = new ChatCompletionRequest(messages, "gpt-4o", List.of(functionTool), ToolChoiceBuilder.AUTO);

    ResponseEntity<ChatCompletion> chatCompletion = this.completionApi.chatCompletionEntity(chatCompletionRequest);
    assertThat(chatCompletion.getBody()).isNotNull();
    assertThat(chatCompletion.getBody().choices()).isNotEmpty();
    ChatCompletionMessage responseMessage = chatCompletion.getBody().choices().get(0).message();

    assertThat(responseMessage.role()).isEqualTo(Role.ASSISTANT);
    assertThat(responseMessage.toolCalls()).isNotNull();

    messages.add(responseMessage);

    for (ToolCall toolCall : responseMessage.toolCalls()) {
        var functionName = toolCall.function().name();
        if ("getCurrentWeather".equals(functionName)) {
            MockWeatherService.Request weatherRequest = fromJson(toolCall.function().arguments(), MockWeatherService.Request.class);
            MockWeatherService.Response weatherResponse = this.weatherService.apply(weatherRequest);

            messages.add(new ChatCompletionMessage("" + weatherResponse.temp() + weatherRequest.unit(), Role.TOOL, functionName, toolCall.id(), null, null, null));
        }
    }
    var functionResponseRequest = new ChatCompletionRequest(messages, "gpt-4o", 0.5);
    ResponseEntity<ChatCompletion> chatCompletion2 = this.completionApi.chatCompletionEntity(functionResponseRequest);
    logger.info("Final response: " + chatCompletion2.getBody());
    assertThat(chatCompletion2.getBody().choices()).isNotEmpty();
    assertThat(chatCompletion2.getBody().choices().get(0).message().role()).isEqualTo(Role.ASSISTANT);
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("San Francisco").containsAnyOf("30.0°C", "30°C");
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("Tokyo").containsAnyOf("10.0°C", "10°C");
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("Paris").containsAnyOf("15.0°C", "15°C");
}
"
Scenario 1: Test Equality with Identical Objects

Details:
  TestName: equalsWithIdenticalObjects
  Description: This test checks if the equals method returns true when comparing an object to itself. This is a basic identity check to ensure the method correctly identifies an object as equal to itself.
Execution:
  Arrange: Create an instance of the SpeechPrompt class.
  Act: Call the equals method on the instance, passing the same instance as the parameter.
  Assert: Verify that the equals method returns true.
Validation:
  This assertion verifies that the equals method correctly implements the reflexive property of equality, which is a fundamental requirement for any equals method implementation.

Scenario 2: Test Equality with Null Object

Details:
  TestName: equalsWithNullObject
  Description: This test checks if the equals method returns false when comparing an object to null. This ensures that the method can handle null inputs gracefully.
Execution:
  Arrange: Create an instance of the SpeechPrompt class.
  Act: Call the equals method on the instance, passing null as the parameter.
  Assert: Verify that the equals method returns false.
Validation:
  This assertion ensures that the equals method correctly handles null inputs, which is essential for robustness and preventing NullPointerExceptions.

Scenario 3: Test Equality with Different Class Object

Details:
  TestName: equalsWithDifferentClassObject
  Description: This test checks if the equals method returns false when comparing a SpeechPrompt object with an object of a different class. This ensures type safety in the equality check.
Execution:
  Arrange: Create an instance of the SpeechPrompt class and an instance of a different class (e.g., String).
  Act: Call the equals method on the SpeechPrompt instance, passing the different class instance as the parameter.
  Assert: Verify that the equals method returns false.
Validation:
  This assertion verifies that the equals method correctly identifies objects of different classes as not equal, ensuring type safety and logical consistency.

Scenario 4: Test Equality with Different SpeechPrompt Objects with Same Values

Details:
  TestName: equalsWithDifferentObjectsSameValues
  Description: This test checks if the equals method returns true when comparing two different SpeechPrompt objects that have the same values for their fields. This ensures that equality is based on field values rather than object identity.
Execution:
  Arrange: Create two different instances of the SpeechPrompt class with identical values for speechOptions and message fields.
  Act: Call the equals method on one instance, passing the other instance as the parameter.
  Assert: Verify that the equals method returns true.
Validation:
  This assertion ensures that the equals method correctly implements value-based equality, which is crucial for comparing objects based on their state rather than their identity.

Scenario 5: Test Equality with Different SpeechPrompt Objects with Different Values

Details:
  TestName: equalsWithDifferentObjectsDifferentValues
  Description: This test checks if the equals method returns false when comparing two different SpeechPrompt objects that have different values for their fields. This ensures that the method correctly identifies objects with different states as not equal.
Execution:
  Arrange: Create two different instances of the SpeechPrompt class with different values for speechOptions and message fields.
  Act: Call the equals method on one instance, passing the other instance as the parameter.
  Assert: Verify that the equals method returns false.
Validation:
  This assertion verifies that the equals method correctly distinguishes between objects with different field values, ensuring logical consistency in equality checks.

Scenario 6: Test Equality with Null Fields

Details:
  TestName: equalsWithNullFields
  Description: This test checks if the equals method can handle cases where the fields of the SpeechPrompt objects being compared are null. This ensures robustness in handling null field values.
Execution:
  Arrange: Create two instances of the SpeechPrompt class with null values for speechOptions and message fields.
  Act: Call the equals method on one instance, passing the other instance as the parameter.
  Assert: Verify that the equals method returns true.
Validation:
  This assertion ensures that the equals method can correctly handle null field values, which is important for robustness and preventing NullPointerExceptions.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Objects;
import org.springframework.ai.model.ModelOptions;
import org.springframework.ai.model.ModelRequest;
import org.springframework.ai.openai.OpenAiAudioSpeechOptions;

public class SpeechPromptEqualsTest {

	@Test
	@Tag("valid")
	public void equalsWithIdenticalObjects() {
		SpeechPrompt prompt = new SpeechPrompt("Test Instructions");
		assertTrue(prompt.equals(prompt));
	}

	@Test
	@Tag("invalid")
	public void equalsWithNullObject() {
		SpeechPrompt prompt = new SpeechPrompt("Test Instructions");
		assertFalse(prompt.equals(null));
	}

	@Test
	@Tag("invalid")
	public void equalsWithDifferentClassObject() {
		SpeechPrompt prompt = new SpeechPrompt("Test Instructions");
		String differentClassObject = "Different Class Object";
		assertFalse(prompt.equals(differentClassObject));
	}

	@Test
	@Tag("valid")
	public void equalsWithDifferentObjectsSameValues() {
		SpeechPrompt prompt1 = new SpeechPrompt("Test Instructions");
		SpeechPrompt prompt2 = new SpeechPrompt("Test Instructions");
		assertTrue(prompt1.equals(prompt2));
	}

	@Test
	@Tag("invalid")
	public void equalsWithDifferentObjectsDifferentValues() {
		SpeechPrompt prompt1 = new SpeechPrompt("Test Instructions 1");
		SpeechPrompt prompt2 = new SpeechPrompt("Test Instructions 2");
		assertFalse(prompt1.equals(prompt2));
	}

	@Test
	@Tag("boundary")
	public void equalsWithNullFields() {
		SpeechPrompt prompt1 = new SpeechPrompt((SpeechMessage) null, null);
		SpeechPrompt prompt2 = new SpeechPrompt((SpeechMessage) null, null);
		assertTrue(prompt1.equals(prompt2));
	}

}