/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=equals_b04767db1b
ROOST_METHOD_SIG_HASH=equals_ded257778a

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/amanProjectPath10thJuly/b518c0b2-46c7-4f77-a273-619309d22700/source/spring-ai/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/api/tool/OpenAiApiToolFunctionCallIT.java
Tests:
    "@Test
@SuppressWarnings("null")
@Test
public void toolFunctionCall() {

    var message = new ChatCompletionMessage("What's the weather like in San Francisco, Tokyo, and Paris?", Role.USER);
    var functionTool = new OpenAiApi.FunctionTool(OpenAiApi.FunctionTool.Type.FUNCTION, new OpenAiApi.FunctionTool.Function("Get the weather in location. Return temperature in Celsius.", "getCurrentWeather", ModelOptionsUtils.jsonToMap("""
        {
        	"type": "object",
        	"properties": {
        		"location": {
        			"type": "string",
        			"description": "The city and state e.g. San Francisco, CA"
        		},
        		"lat": {
        			"type": "number",
        			"description": "The city latitude"
        		},
        		"lon": {
        			"type": "number",
        			"description": "The city longitude"
        		},
        		"unit": {
        			"type": "string",
        			"enum": ["C", "F"]
        		}
        	},
        	"required": ["location", "lat", "lon", "unit"]
        }
        """), null));
    List<ChatCompletionMessage> messages = new ArrayList<>(List.of(message));
    ChatCompletionRequest chatCompletionRequest = new ChatCompletionRequest(messages, "gpt-4o", List.of(functionTool), ToolChoiceBuilder.AUTO);

    ResponseEntity<ChatCompletion> chatCompletion = this.completionApi.chatCompletionEntity(chatCompletionRequest);
    assertThat(chatCompletion.getBody()).isNotNull();
    assertThat(chatCompletion.getBody().choices()).isNotEmpty();
    ChatCompletionMessage responseMessage = chatCompletion.getBody().choices().get(0).message();

    assertThat(responseMessage.role()).isEqualTo(Role.ASSISTANT);
    assertThat(responseMessage.toolCalls()).isNotNull();

    messages.add(responseMessage);

    for (ToolCall toolCall : responseMessage.toolCalls()) {
        var functionName = toolCall.function().name();
        if ("getCurrentWeather".equals(functionName)) {
            MockWeatherService.Request weatherRequest = fromJson(toolCall.function().arguments(), MockWeatherService.Request.class);
            MockWeatherService.Response weatherResponse = this.weatherService.apply(weatherRequest);

            messages.add(new ChatCompletionMessage("" + weatherResponse.temp() + weatherRequest.unit(), Role.TOOL, functionName, toolCall.id(), null, null, null));
        }
    }
    var functionResponseRequest = new ChatCompletionRequest(messages, "gpt-4o", 0.5);
    ResponseEntity<ChatCompletion> chatCompletion2 = this.completionApi.chatCompletionEntity(functionResponseRequest);
    logger.info("Final response: " + chatCompletion2.getBody());
    assertThat(chatCompletion2.getBody().choices()).isNotEmpty();
    assertThat(chatCompletion2.getBody().choices().get(0).message().role()).isEqualTo(Role.ASSISTANT);
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("San Francisco").containsAnyOf("30.0°C", "30°C");
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("Tokyo").containsAnyOf("10.0°C", "10°C");
    assertThat(chatCompletion2.getBody().choices().get(0).message().content()).contains("Paris").containsAnyOf("15.0°C", "15°C");
}
"
Scenario 1: Test Equality of Identical Objects

Details:
  TestName: equalsWithIdenticalObjects
  Description: This test checks if the equals method returns true when comparing an object to itself, ensuring that the method correctly identifies identical objects.
Execution:
  Arrange: Create an instance of SpeechMessage and set its text field to a specific value.
  Act: Call the equals method on the instance, passing itself as the parameter.
  Assert: Verify that the equals method returns true.
Validation:
  This assertion verifies that the equals method correctly identifies an object as equal to itself, which is a fundamental property of equality in Java.

Scenario 2: Test Equality with Null

Details:
  TestName: equalsWithNull
  Description: This test checks if the equals method returns false when comparing an object to null, ensuring that the method handles null inputs correctly.
Execution:
  Arrange: Create an instance of SpeechMessage.
  Act: Call the equals method on the instance, passing null as the parameter.
  Assert: Verify that the equals method returns false.
Validation:
  This assertion ensures that the equals method correctly handles null inputs, which is important for robustness and preventing null pointer exceptions.

Scenario 3: Test Equality with Different Class

Details:
  TestName: equalsWithDifferentClass
  Description: This test checks if the equals method returns false when comparing an object to an instance of a different class, ensuring type safety.
Execution:
  Arrange: Create an instance of SpeechMessage and an instance of a different class (e.g., String).
  Act: Call the equals method on the SpeechMessage instance, passing the different class instance as the parameter.
  Assert: Verify that the equals method returns false.
Validation:
  This assertion ensures that the equals method correctly identifies objects of different classes as not equal, maintaining type safety.

Scenario 4: Test Equality with Different Text Values

Details:
  TestName: equalsWithDifferentTextValues
  Description: This test checks if the equals method returns false when comparing two SpeechMessage objects with different text values.
Execution:
  Arrange: Create two instances of SpeechMessage with different text values.
  Act: Call the equals method on one instance, passing the other instance as the parameter.
  Assert: Verify that the equals method returns false.
Validation:
  This assertion ensures that the equals method correctly identifies objects with different text values as not equal, which is crucial for accurate comparison.

Scenario 5: Test Equality with Same Text Values

Details:
  TestName: equalsWithSameTextValues
  Description: This test checks if the equals method returns true when comparing two SpeechMessage objects with identical text values.
Execution:
  Arrange: Create two instances of SpeechMessage with the same text value.
  Act: Call the equals method on one instance, passing the other instance as the parameter.
  Assert: Verify that the equals method returns true.
Validation:
  This assertion ensures that the equals method correctly identifies objects with identical text values as equal, which is essential for consistent behavior.

Scenario 6: Test Equality with Both Text Values Null

Details:
  TestName: equalsWithBothTextValuesNull
  Description: This test checks if the equals method returns true when comparing two SpeechMessage objects where both have null text values.
Execution:
  Arrange: Create two instances of SpeechMessage without setting their text values (default to null).
  Act: Call the equals method on one instance, passing the other instance as the parameter.
  Assert: Verify that the equals method returns true.
Validation:
  This assertion ensures that the equals method correctly identifies objects with both text values as null as equal, which is important for handling null values consistently.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class SpeechMessageEqualsTest {

	@Test
	@Tag("valid")
	public void equalsWithIdenticalObjects() {
		// Arrange
		SpeechMessage message = new SpeechMessage("Hello World");

		// Act
		boolean result = message.equals(message);

		// Assert
		assertTrue(result);
	}

	@Test
	@Tag("invalid")
	public void equalsWithNull() {
		// Arrange
		SpeechMessage message = new SpeechMessage("Hello World");

		// Act
		boolean result = message.equals(null);

		// Assert
		assertFalse(result);
	}

	@Test
	@Tag("invalid")
	public void equalsWithDifferentClass() {
		// Arrange
		SpeechMessage message = new SpeechMessage("Hello World");
		String differentClassObject = "Hello World";

		// Act
		boolean result = message.equals(differentClassObject);

		// Assert
		assertFalse(result);
	}

	@Test
	@Tag("invalid")
	public void equalsWithDifferentTextValues() {
		// Arrange
		SpeechMessage message1 = new SpeechMessage("Hello World");
		SpeechMessage message2 = new SpeechMessage("Goodbye World");

		// Act
		boolean result = message1.equals(message2);

		// Assert
		assertFalse(result);
	}

	@Test
	@Tag("valid")
	public void equalsWithSameTextValues() {
		// Arrange
		SpeechMessage message1 = new SpeechMessage("Hello World");
		SpeechMessage message2 = new SpeechMessage("Hello World");

		// Act
		boolean result = message1.equals(message2);

		// Assert
		assertTrue(result);
	}

	@Test
	@Tag("valid")
	public void equalsWithBothTextValuesNull() {
		// Arrange
		SpeechMessage message1 = new SpeechMessage(null);
		SpeechMessage message2 = new SpeechMessage(null);

		// Act
		boolean result = message1.equals(message2);

		// Assert
		assertTrue(result);
	}

}