/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=hashCode_8c73be2899
ROOST_METHOD_SIG_HASH=hashCode_44411a81c8

Scenario 1: Verify hashCode for Null Text

Details:
  TestName: hashCodeForNullText
  Description: This test checks the hashCode method when the text field is null. It ensures that the method can handle null values without throwing exceptions and returns a consistent hash code.
Execution:
  Arrange: Create a SpeechMessage instance with the text field set to null.
  Act: Call the hashCode method on the instance.
  Assert: Verify that the hashCode method returns a valid integer.
Validation:
  This assertion verifies that the hashCode method can handle null values gracefully, which is crucial for ensuring robustness and preventing runtime errors in applications that use SpeechMessage objects.

Scenario 2: Verify hashCode for Non-Null Text

Details:
  TestName: hashCodeForNonNullText
  Description: This test checks the hashCode method when the text field contains a non-null string. It ensures that the method returns a consistent hash code for the same text value.
Execution:
  Arrange: Create a SpeechMessage instance with the text field set to a specific non-null string, e.g., "Hello".
  Act: Call the hashCode method on the instance.
  Assert: Verify that the hashCode method returns a consistent integer value for the same text.
Validation:
  This assertion ensures that the hashCode method provides consistent results for non-null text values, which is important for maintaining the integrity of hash-based collections like HashMap.

Scenario 3: Verify hashCode Consistency with Equals

Details:
  TestName: hashCodeConsistencyWithEquals
  Description: This test checks the consistency between the hashCode and equals methods. It ensures that if two SpeechMessage instances are equal, they must have the same hash code.
Execution:
  Arrange: Create two SpeechMessage instances with the same text value, e.g., "Hello".
  Act: Call the hashCode method on both instances.
  Assert: Verify that the hash codes of both instances are equal.
Validation:
  This assertion verifies the contract between equals and hashCode, which is essential for the correct functioning of hash-based collections. If two objects are equal, they must have the same hash code.

Scenario 4: Verify hashCode for Different Text Values

Details:
  TestName: hashCodeForDifferentTextValues
  Description: This test checks the hashCode method for different text values. It ensures that different text values produce different hash codes.
Execution:
  Arrange: Create two SpeechMessage instances with different text values, e.g., "Hello" and "World".
  Act: Call the hashCode method on both instances.
  Assert: Verify that the hash codes of the two instances are different.
Validation:
  This assertion ensures that the hashCode method generates distinct hash codes for different text values, which is important for the performance and correctness of hash-based collections.

Scenario 5: Verify hashCode for Empty String

Details:
  TestName: hashCodeForEmptyString
  Description: This test checks the hashCode method when the text field is an empty string. It ensures that the method can handle empty strings and returns a consistent hash code.
Execution:
  Arrange: Create a SpeechMessage instance with the text field set to an empty string "".
  Act: Call the hashCode method on the instance.
  Assert: Verify that the hashCode method returns a valid integer.
Validation:
  This assertion verifies that the hashCode method can handle empty strings correctly, which is important for applications that may encounter empty input values.

*/

// ********RoostGPT********

package org.springframework.ai.openai.audio.speech;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class SpeechMessageHashCodeTest {

	@Test
	@Tag("boundary")
	public void hashCodeForNullText() {
		// Arrange
		SpeechMessage message = new SpeechMessage(null);
		// Act
		int hashCode = message.hashCode();
		// Assert
		assertNotNull((Integer) hashCode);
	}

	@Test
	@Tag("valid")
	public void hashCodeForNonNullText() {
		// Arrange
		SpeechMessage message = new SpeechMessage("Hello");
		// Act
		int hashCode = message.hashCode();
		// Assert
		assertEquals((Integer) "Hello".hashCode(), (Integer) hashCode);
	}

	@Test
	@Tag("valid")
	public void hashCodeConsistencyWithEquals() {
		// Arrange
		SpeechMessage message1 = new SpeechMessage("Hello");
		SpeechMessage message2 = new SpeechMessage("Hello");
		// Act
		int hashCode1 = message1.hashCode();
		int hashCode2 = message2.hashCode();
		// Assert
		assertEquals((Integer) hashCode1, (Integer) hashCode2);
	}

	@Test
	@Tag("valid")
	public void hashCodeForDifferentTextValues() {
		// Arrange
		SpeechMessage message1 = new SpeechMessage("Hello");
		SpeechMessage message2 = new SpeechMessage("World");
		// Act
		int hashCode1 = message1.hashCode();
		int hashCode2 = message2.hashCode();
		// Assert
		assertNotEquals((Integer) hashCode1, (Integer) hashCode2);
	}

	@Test
	@Tag("boundary")
	public void hashCodeForEmptyString() {
		// Arrange
		SpeechMessage message = new SpeechMessage("");
		// Act
		int hashCode = message.hashCode();
		// Assert
		assertNotNull((Integer) hashCode);
	}

}