/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getMaxAttempts_c3437e4d13
ROOST_METHOD_SIG_HASH=getMaxAttempts_f4af28669e

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-report-test/1743050154/source/spring-ai/auto-configurations/common/spring-ai-autoconfigure-retry/src/test/java/org/springframework/ai/retry/autoconfigure/SpringAiRetryPropertiesTests.java
Tests:
    "@Test
@Test
public void retryDefaultProperties() {
    new ApplicationContextRunner().withConfiguration(AutoConfigurations.of(SpringAiRetryAutoConfiguration.class)).run(context -> {
        var retryProperties = context.getBean(SpringAiRetryProperties.class);
        assertThat(retryProperties.getMaxAttempts()).isEqualTo(10);

        assertThat(retryProperties.isOnClientErrors()).isFalse();
        assertThat(retryProperties.getExcludeOnHttpCodes()).isEmpty();
        assertThat(retryProperties.getOnHttpCodes()).isEmpty();
        assertThat(retryProperties.getBackoff().getInitialInterval().toMillis()).isEqualTo(2000);
        assertThat(retryProperties.getBackoff().getMultiplier()).isEqualTo(5);
        assertThat(retryProperties.getBackoff().getMaxInterval().toMillis()).isEqualTo(3 * 60000);
    });
}
"
    "@Test
@Test
public void retryCustomProperties() {
    new ApplicationContextRunner().withPropertyValues(
    "spring.ai.retry.max-attempts=100", "spring.ai.retry.on-client-errors=false", "spring.ai.retry.exclude-on-http-codes=404,500", "spring.ai.retry.on-http-codes=429", "spring.ai.retry.backoff.initial-interval=1000", "spring.ai.retry.backoff.multiplier=2", "spring.ai.retry.backoff.max-interval=60000").
    withConfiguration(AutoConfigurations.of(SpringAiRetryAutoConfiguration.class)).run(context -> {
        var retryProperties = context.getBean(SpringAiRetryProperties.class);
        assertThat(retryProperties.getMaxAttempts()).isEqualTo(100);
        assertThat(retryProperties.isOnClientErrors()).isFalse();
        assertThat(retryProperties.getExcludeOnHttpCodes()).containsExactly(404, 500);
        assertThat(retryProperties.getOnHttpCodes()).containsExactly(429);
        assertThat(retryProperties.getBackoff().getInitialInterval().toMillis()).isEqualTo(1000);
        assertThat(retryProperties.getBackoff().getMultiplier()).isEqualTo(2);
        assertThat(retryProperties.getBackoff().getMaxInterval().toMillis()).isEqualTo(60000);
    });
}
"
Scenario 1: Test getMaxAttempts to check the return value after default initiation

Details:
  TestName: getMaxAttemptsAfterDefaultInitiation
  Description: This test will ensure that the default value of maxAttempts is returned accurately after the instance creation.
Execution:
  Arrange: Create an instance of SpringAiRetryProperties class.
  Act: Call the getMaxAttempts() method.
  Assert: Verify that the returned value is 10.
Validation:
   The test asserts that the default value for maxAttempts on instance creation is 10 (as it is set initially). This would ensure that the default behavior of the application remains consistent.

Scenario 2: Test getMaxAttempts() after invoking setMaxAttempts()

Details:
  TestName: getMaxAttemptsAfterSettingNewValue
  Description: This test will ensure that if the value of maxAttempts is updated by calling setMaxAttempts(int), the updated value is fetched correctly by getMaxAttempts() method.
Execution:
  Arrange: Create an instance of SpringAiRetryProperties class and invoke setMaxAttempts() method with a new value (for instance: 20).
  Act: Call the getMaxAttempts() method.
  Assert: Check the return value is equal to 20.
Validation:
  The test validates that the maxAttempts value is updated correctly in the object and the same value is fetched by the getter method. This contributes to the assurance on component's state management ability.

Scenario 3: Test getMaxAttempts() when it's incorrectly assumed to have a negative value

Details:
  TestName: getMaxAttemptsAfterSettingInvalidValue
  Description: This test will ensure that maxAttempts() cannot hold a negative value. (Though the setter/getter code does not suggest this, it would be a beneficial addition for enforcing data validity).
Execution:
  Arrange: Create an instance of SpringAiRetryProperties class and try to use setMaxAttempts() method to set a negative value.
  Act: Call the getMaxAttempts() method.
  Assert: Validate that it doesn't store a negative value and that the value returned is the last valid value set or the default one.
Validation:
  This test will check the validation of the input provided to the setMaxAttempts() method and will ensure that invalid inputs do not corrupt the application data. (Consider this only if additional data validity checks are being planned to include.)

Scenario 4: Test getMaxAttempts() for thread-safety with parallel updates

Details:
  TestName: getMaxAttemptsThreadSafetyTest
  Description: This test will check if the getMaxAttempts() method works properly even when multiple threads are trying to update maxAttempts simultaneously.
Execution:
  Arrange: Spawn multiple threads. Each thread creates a SpringAiRetryProperties instance and invokes setMaxAttempts() with different values.
  Act: All threads call the getMaxAttempts() method.
  Assert: Ensure each thread gets the correct value that it set.
Validation:
  This test is vital in multi-threaded environments to ensure thread-safety while setting and getting the values of maxAttempts. This will validate the concurrent access behavior of the component.
,
*/

// ********RoostGPT********

package org.springframework.ai.retry.autoconfigure;

import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import org.junit.Before;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.springframework.ai.retry.autoconfigure.SpringAiRetryProperties;
import static org.junit.Assert.assertEquals;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.NestedConfigurationProperty;

public class SpringAiRetryPropertiesGetMaxAttemptsTest {

	private SpringAiRetryProperties properties;

	@Before
	public void setUp() {
		properties = new SpringAiRetryProperties();
	}

	@Test
	@Category(Categories.valid.class)
	public void getMaxAttemptsAfterDefaultInitiation() {
		int maxAttempts = properties.getMaxAttempts();
		assertEquals(10, maxAttempts);
	}

	@Test
	@Category(Categories.valid.class)
	public void getMaxAttemptsAfterSettingNewValue() {
		properties.setMaxAttempts(20);
		assertEquals(20, properties.getMaxAttempts());
	}

	@Test
	@Category(Categories.invalid.class)
	public void getMaxAttemptsAfterSettingInvalidValue() {
		properties.setMaxAttempts(30); // ensure a valid default
		properties.setMaxAttempts(-10);
		assertEquals(30, properties.getMaxAttempts());
	}

	@Test
	@Category(Categories.integration.class)
	public void getMaxAttemptsThreadSafetyTest() throws Exception {
		ExecutorService executor = Executors.newFixedThreadPool(3);
		Callable<Void> task1 = () -> {
			properties.setMaxAttempts(40);
			return null;
		};
		Callable<Void> task2 = () -> {
			properties.setMaxAttempts(50);
			return null;
		};
		Callable<Void> task3 = () -> {
			properties.setMaxAttempts(60);
			return null;
		};
		Future<Void> future1 = executor.submit(task1);
		Future<Void> future2 = executor.submit(task2);
		Future<Void> future3 = executor.submit(task3);

		// runs after all tasks have executed
		future1.get();
		future2.get();
		future3.get();
		// it verifies the last set value as set by task3
		assertEquals(60, properties.getMaxAttempts());
	}

}