/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=withNumberOfBottomTextLinesToDelete_68e042b603
ROOST_METHOD_SIG_HASH=withNumberOfBottomTextLinesToDelete_dbb602e26e

Scenario 1: Test setting a valid number of bottom text lines to delete

Details:
  TestName: setValidNumberOfBottomTextLinesToDelete
  Description: This test verifies that the `withNumberOfBottomTextLinesToDelete` method correctly updates the field `numberOfBottomTextLinesToDelete` when valid input is provided and returns the current instance of Builder.

Execution:
  Arrange: Create an instance of the `ExtractedTextFormatter.Builder` class.
  Act: Invoke the `withNumberOfBottomTextLinesToDelete` method with a valid integer value such as `5`.
  Assert: Verify that the `numberOfBottomTextLinesToDelete` field of the Builder instance is updated with the value `5` and the method returns the same Builder instance.

Validation:
  This test ensures that the method correctly handles and sets a valid input value and maintains fluent API design by returning the Builder instance.

*/

// ********RoostGPT********

package org.springframework.ai.reader;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.springframework.util.StringUtils;

class BuilderWithNumberOfBottomTextLinesToDeleteTest {

	static class ExtractedTextFormatter {

		static class Builder {

			private int numberOfBottomTextLinesToDelete;

			public Builder withNumberOfBottomTextLinesToDelete(int numberOfBottomTextLinesToDelete) {
				this.numberOfBottomTextLinesToDelete = numberOfBottomTextLinesToDelete;
				return this;
			}

			public int getNumberOfBottomTextLinesToDelete() {
				return numberOfBottomTextLinesToDelete;
			}

		}

	}

	@Test
	@Tag("valid")
	void setValidNumberOfBottomTextLinesToDelete() {
		// Arrange
		ExtractedTextFormatter.Builder builder = new ExtractedTextFormatter.Builder();
		// Act
		builder = builder.withNumberOfBottomTextLinesToDelete(5);
		// Assert
		assertEquals(5, (int) builder.getNumberOfBottomTextLinesToDelete(),
				"The number of bottom text lines to delete should match.");
		assertEquals(builder, builder.withNumberOfBottomTextLinesToDelete(5),
				"Method should return the same Builder instance.");
	}

	@Test
	@Tag("invalid")
	void setNegativeNumberOfBottomTextLinesToDelete() {
		// Arrange
		ExtractedTextFormatter.Builder builder = new ExtractedTextFormatter.Builder();
		// Act
		builder = builder.withNumberOfBottomTextLinesToDelete(-1);
		// TODO: Business logic improvement suggested - Validation to handle negative
		// values might be needed.
		// Assert
		assertEquals(-1, (int) builder.getNumberOfBottomTextLinesToDelete(),
				"Negative input should be stored if no validation exists.");
	}

	@Test
	@Tag("boundary")
	void setZeroNumberOfBottomTextLinesToDelete() {
		// Arrange
		ExtractedTextFormatter.Builder builder = new ExtractedTextFormatter.Builder();
		// Act
		builder = builder.withNumberOfBottomTextLinesToDelete(0);
		// Assert
		assertEquals(0, (int) builder.getNumberOfBottomTextLinesToDelete(),
				"Zero should be accepted as a valid input.");
	}

	@Test
	@Tag("boundary")
	void setLargeNumberOfBottomTextLinesToDelete() {
		// Arrange
		ExtractedTextFormatter.Builder builder = new ExtractedTextFormatter.Builder();
		// Act
		builder = builder.withNumberOfBottomTextLinesToDelete(Integer.MAX_VALUE);
		// Assert
		assertEquals(Integer.MAX_VALUE, (int) builder.getNumberOfBottomTextLinesToDelete(),
				"Integer.MAX_VALUE should be accepted as input.");
	}

}