/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=build_52f87c0d00
ROOST_METHOD_SIG_HASH=build_fadc523f56


Scenario 1: Verify that the build method returns a valid ExtractedTextFormatter object initialized with the Builder instance.

Details:
  TestName: validateBuilderInitialization
  Description: Ensure that the build method constructs an ExtractedTextFormatter object and initializes it using the Builder instance parameters. This test validates that the proper configuration provided in the Builder is passed into the ExtractedTextFormatter.

Execution:
  Arrange: Instantiate the Builder class and configure its fields using methods like withLeftAlignment, withNumberOfTopPagesToSkipBeforeDelete, etc.
  Act: Call the build method on the Builder instance.
  Assert: Assert that the returned object is not null and is an instance of ExtractedTextFormatter.

Validation:
  Verify that the build method correctly initializes and passes Builder properties to the ExtractedTextFormatter constructor, ensuring configuration integrity.

*/

// ********RoostGPT********

package org.springframework.ai.reader;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.util.StringUtils;

public class BuilderBuildTest {

	@Test
	@Tag("valid")
	public void validateBuilderInitialization() {
		// Arrange
		ExtractedTextFormatter.Builder builder = new ExtractedTextFormatter.Builder().withLeftAlignment(true)
			.withNumberOfTopPagesToSkipBeforeDelete(2)
			.withNumberOfTopTextLinesToDelete(3)
			.withNumberOfBottomTextLinesToDelete(4)
			.overrideLineSeparator(System.lineSeparator()); // TODO: Change separator if a
															// custom one is required
		// Act
		ExtractedTextFormatter formatter = builder.build();
		// Assert
		assertNotNull(formatter);
		assertTrue(formatter instanceof ExtractedTextFormatter);
	}

}