/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=build_52f87c0d00
ROOST_METHOD_SIG_HASH=build_fadc523f56

Scenario 1: Validate creation of ExtractedTextFormatter with default Builder values

Details:
  TestName: createWithDefaultBuilderValues
  Description: Verify that calling build() on a Builder instance creates an ExtractedTextFormatter object with default values. This ensures that the object is properly instantiated even when no customization is applied to the Builder.

Execution:
  Arrange: Create an instance of the Builder class without setting any properties.
  Act: Invoke the build() method to create an ExtractedTextFormatter object.
  Assert: Check that the returned object is not null and verify that its properties match the default values of the Builder.

Validation:
  Ensure that the test confirms the correctness of the default object creation process and guarantees stable handling of default Builder configurations without any modifications.

*/

// ********RoostGPT********

package org.springframework.ai.reader;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.*;
import org.springframework.util.StringUtils;

public class BuilderBuildTest {

	@Test
	@Tag("valid")
	public void createWithDefaultBuilderValues() {
		// Arrange
		ExtractedTextFormatter.Builder builder = new ExtractedTextFormatter.Builder();
		// Act
		ExtractedTextFormatter formatter = builder.build();
		// Assert
		assertNotNull(formatter, "ExtractedTextFormatter instance should not be null");
	}

	@Test
	@Tag("valid")
	public void customBuilderValuesWithValidData() {
		// TODO: Update values as needed
		// Arrange
		ExtractedTextFormatter.Builder builder = new ExtractedTextFormatter.Builder().withLeftAlignment(true)
			.withNumberOfTopPagesToSkipBeforeDelete(3)
			.withNumberOfTopTextLinesToDelete(2)
			.withNumberOfBottomTextLinesToDelete(2)
			.overrideLineSeparator("\n");
		// Act
		ExtractedTextFormatter formatter = builder.build();
		// Assert
		assertNotNull(formatter, "ExtractedTextFormatter instance should not be null");
	}

	@Test
	@Tag("invalid")
	public void invalidBuilderValuesWithBoundaryConditions() {
		// TODO: Update values as per boundary cases
		// Arrange
		ExtractedTextFormatter.Builder builder = new ExtractedTextFormatter.Builder()
			.withNumberOfTopTextLinesToDelete(-1) // Invalid value
			.withNumberOfBottomTextLinesToDelete(-1); // Invalid value
		// Act
		ExtractedTextFormatter formatter = builder.build();
		// Assert
		assertNotNull(formatter, "ExtractedTextFormatter instance should not be null despite invalid values");
	}

	@Test
	@Tag("boundary")
	public void extremelyHighTopLinesToDelete() {
		// Arrange
		ExtractedTextFormatter.Builder builder = new ExtractedTextFormatter.Builder()
			.withNumberOfTopTextLinesToDelete(Integer.MAX_VALUE);
		// Act
		ExtractedTextFormatter formatter = builder.build();
		// Assert
		assertNotNull(formatter, "ExtractedTextFormatter instance should not be null");
	}

	@Test
	@Tag("boundary")
	public void extremelyHighBottomLinesToDelete() {
		// Arrange
		ExtractedTextFormatter.Builder builder = new ExtractedTextFormatter.Builder()
			.withNumberOfBottomTextLinesToDelete(Integer.MAX_VALUE);
		// Act
		ExtractedTextFormatter formatter = builder.build();
		// Assert
		assertNotNull(formatter, "ExtractedTextFormatter instance should not be null");
	}

}