/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=deleteBottomTextLines_8fcef2fc0a
ROOST_METHOD_SIG_HASH=deleteBottomTextLines_f8db3f6dc4

Scenario [1]: Verify method handles an empty string

Details:
  TestName: handleEmptyStringInput
  Description: This test checks whether the method properly handles cases where the input "pageText" is an empty or null string. It assesses the functionality related to input validation and bypassing operations if input is void of meaningful content.
Execution:
  Arrange: Provide an empty string or null as "pageText". Set "numberOfLines" to any integer (e.g., 3). Use default "lineSeparator" like "\n".
  Act: Invoke "deleteBottomTextLines" with the arranged parameters.
  Assert: Validate that the returned value matches the original "pageText".
Validation:
  The assertion ensures the method avoids modifying input when "pageText" is empty or null. This behavior is critical as it indicates proper validation logic and avoids unnecessary processes for empty content.

*/

// ********RoostGPT********

package org.springframework.ai.reader;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.*;
import org.springframework.util.StringUtils;

public class ExtractedTextFormatterDeleteBottomTextLinesTest {

	@Test
	@Tag("valid")
	public void handleEmptyStringInput() {
		// Arrange
		String pageText = ""; // Empty string input
		int numberOfLines = 3;
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals((String) pageText, (String) result, "Expected output should match the input for empty strings.");
	}

	@Test
	@Tag("valid")
	public void handleValidTextInCaseLinesCanBeDeleted() {
		// Arrange
		String pageText = "Line1\nLine2\nLine3\nLine4\nLine5"; // Example multiline string
		int numberOfLines = 2; // Number of lines to delete from the bottom
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals((String) "Line1\nLine2\nLine3", (String) result,
				"Expected only the remaining lines after bottom deletion.");
	}

	@Test
	@Tag("boundary")
	public void handleSingleLineSeparatorWithDeletion() {
		// Arrange
		String pageText = "Line1\nLine2"; // Text with fewer lines than numberOfLines
		int numberOfLines = 3; // Number of lines to delete exceeds the total lines
								// available
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals((String) "", (String) result, "Expected output should be empty if all lines are deleted.");
	}

	@Test
	@Tag("invalid")
	public void handleNullInput() {
		// Arrange
		String pageText = null; // Null input case
		int numberOfLines = 2;
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals(null, result, "Expected output for null input should be null itself.");
	}

	@Test
	@Tag("boundary")
	public void verifyValidLineSeparatorLogic() {
		// Arrange
		String pageText = "Line1,Line2,Line3,Line4"; // Example text with a custom
														// separator
		int numberOfLines = 2;
		String lineSeparator = ","; // Custom separator
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals((String) "Line1,Line2", (String) result,
				"Expected behavior when deleting bottom lines with custom separators.");
	}

	@Test
	@Tag("valid")
	public void checkNoChangeWhenZeroLinesToDelete() {
		// Arrange
		String pageText = "Line1\nLine2\nLine3"; // Text with multiple lines
		int numberOfLines = 0; // Zero lines to delete
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals((String) pageText, (String) result,
				"Expected output matches original text when no deletion is performed.");
	}

	@Test
	@Tag("boundary")
	public void handleWhenTextHasNoLineSeparator() {
		// Arrange
		String pageText = "SingleLineWithoutSeparator"; // Text without any separator
		int numberOfLines = 3; // Try deleting lines when no separator exists
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals((String) pageText, (String) result,
				"Expected output matches input as no separator is present in the text.");
	}

	@Test
	@Tag("valid")
	public void verifyTextNotComingNull() {
		// Arrange
		String pageText = "Line1\nLine2\nLine3"; // Multiline valid text
		int numberOfLines = 1; // Delete only one line
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertNotNull(result, "Result must not be null.");
		assertEquals((String) "Line1\nLine2", (String) result,
				"Expected the text without the bottom line after deletion.");
	}

}