/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=format_e971973ad9
ROOST_METHOD_SIG_HASH=format_43022e43fc


Scenario 1: Verify formatting with default settings and valid input text

Details:
  TestName: formatWithDefaultSettingsValidInput
  Description: Checks whether the `format(String pageText)` method correctly processes valid input text using default settings with no specific property overrides.

Execution:
  Arrange: Use a sample text containing multiple lines with valid text. Ensure the text has adjacent blank lines in some sections.
  Act: Call the `format(String pageText)` method with the sample text as a parameter.
  Assert: Verify that the returned text has adjacent blank lines removed and remains consistent with expected formatting.

Validation:
  This test validates the `trimAdjacentBlankLines` functionality and ensures that the method correctly processes text with its default behavior when the nested Builder class fields are uninitialized.

*/

// ********RoostGPT********

package org.springframework.ai.reader;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.*;
import org.springframework.util.StringUtils;

public class ExtractedTextFormatterFormatTest {

	@Test
	@Tag("valid")
	public void formatWithDefaultSettingsValidInput() {
		// Arrange
		String sampleText = "Line1\n\nLine2\n\n\nLine3\nLine4"; // TODO: Update with
																// actual valid text if
																// needed
		ExtractedTextFormatter formatter = new ExtractedTextFormatter.Builder().withLeftAlignment(false)
			.withNumberOfTopPagesToSkipBeforeDelete(0)
			.withNumberOfTopTextLinesToDelete(0)
			.withNumberOfBottomTextLinesToDelete(0)
			.overrideLineSeparator("\n")
			.build();
		// Act
		String formattedText = formatter.format(sampleText);
		// Assert
		assertNotNull(formattedText, "Formatted text should not be null.");
		assertEquals("Line1\nLine2\nLine3\nLine4", formattedText, "Format should remove adjacent blank lines.");
	}

	@Test
	@Tag("invalid")
	public void formatWithNullInput() {
		// Arrange
		ExtractedTextFormatter formatter = new ExtractedTextFormatter.Builder().withLeftAlignment(true)
			.withNumberOfTopPagesToSkipBeforeDelete(1)
			.withNumberOfTopTextLinesToDelete(0)
			.withNumberOfBottomTextLinesToDelete(0)
			.overrideLineSeparator("\n")
			.build();
		// Act
		String formattedText = formatter.format(null);
		// Assert
		assertEquals(null, formattedText, "Format should return null for null input.");
	}

	@Test
	@Tag("boundary")
	public void formatWithEmptyStringInput() {
		// Arrange
		ExtractedTextFormatter formatter = new ExtractedTextFormatter.Builder().withLeftAlignment(false)
			.withNumberOfTopPagesToSkipBeforeDelete(0)
			.withNumberOfTopTextLinesToDelete(1)
			.withNumberOfBottomTextLinesToDelete(0)
			.overrideLineSeparator("\n")
			.build();
		// Act
		String formattedText = formatter.format("");
		// Assert
		assertEquals("", formattedText, "Format should return an empty string for an empty input.");
	}

	@Test
	@Tag("boundary")
	public void formatWithSingleLineOfText() {
		// Arrange
		String sampleText = "Single Line";
		ExtractedTextFormatter formatter = new ExtractedTextFormatter.Builder().withLeftAlignment(false)
			.withNumberOfTopPagesToSkipBeforeDelete(0)
			.withNumberOfTopTextLinesToDelete(0)
			.withNumberOfBottomTextLinesToDelete(0)
			.overrideLineSeparator("\n")
			.build();
		// Act
		String formattedText = formatter.format(sampleText);
		// Assert
		assertEquals("Single Line", formattedText,
				"Format should return the input unchanged for a single line of text.");
	}

	@Test
	@Tag("boundary")
	public void formatWithMultipleBlankLinesInput() {
		// Arrange
		String sampleText = "\n\n\nLine1\n\nLine2\n\n\n";
		ExtractedTextFormatter formatter = new ExtractedTextFormatter.Builder().withLeftAlignment(false)
			.withNumberOfTopPagesToSkipBeforeDelete(0)
			.withNumberOfTopTextLinesToDelete(0)
			.withNumberOfBottomTextLinesToDelete(0)
			.overrideLineSeparator("\n")
			.build();
		// Act
		String formattedText = formatter.format(sampleText);
		// Assert
		assertNotNull(formattedText, "Formatted text should not be null.");
		assertEquals("Line1\nLine2", formattedText, "Format should return text without adjacent blank lines.");
	}

}