/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=deleteBottomTextLines_8fcef2fc0a
ROOST_METHOD_SIG_HASH=deleteBottomTextLines_f8db3f6dc4


Scenario [1]: Verify handling of null pageText input

Details:
  TestName: handleNullInput
  Description: This test verifies that the deleteBottomTextLines method correctly handles a null input for the parameter pageText, ensuring no exceptions are thrown and the method returns null.

Execution:
  Arrange: Set pageText as null, numberOfLines as 5, and lineSeparator as "\n".
  Act: Call deleteBottomTextLines(pageText, numberOfLines, lineSeparator).
  Assert: Assert that the method returns null.

Validation:
  Ensure the method gracefully handles null inputs without throwing exceptions. This behavior confirms the robustness of input validation in the method’s implementation.

*/

// ********RoostGPT********

package org.springframework.ai.reader;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.util.StringUtils;

class ExtractedTextFormatterDeleteBottomTextLinesTest {

	@Test
	@Tag("invalid")
	public void handleNullInput() {
		// Arrange
		String pageText = null;
		int numberOfLines = 5;
		String lineSeparator = "\n";

		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);

		// Assert
		assertNull(result);
	}

	@Test
	@Tag("invalid")
	public void handleEmptyInput() {
		// Arrange
		String pageText = "";
		int numberOfLines = 3;
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals("", result);
	}

	@Test
	@Tag("valid")
	public void handleSingleLineInput() {
		// Arrange
		String pageText = "Single Line Text";
		int numberOfLines = 1;
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals("", result); // Single line should be deleted
	}

	@Test
	@Tag("valid")
	public void handleMultiLineInput() {
		// Arrange
		String pageText = "Line1\nLine2\nLine3\nLine4";
		int numberOfLines = 2;
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals("Line1\nLine2", result); // Bottom two lines should be removed
	}

	@Test
	@Tag("boundary")
	public void handleNumberOfLinesExceedingLineCount() {
		// Arrange
		String pageText = "Line1\nLine2";
		int numberOfLines = 5; // Exceeds the total lines in pageText
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals("", result); // All lines should be removed
	}

	@Test
	@Tag("valid")
	public void handleCustomLineSeparator() {
		// Arrange
		String pageText = "Line1|Line2|Line3|Line4";
		int numberOfLines = 3;
		String lineSeparator = "|";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals("Line1", result); // Bottom three lines should be removed
	}

	@Test
	@Tag("boundary")
	public void handleZeroLinesToDelete() {
		// Arrange
		String pageText = "Line1\nLine2\nLine3";
		int numberOfLines = 0;
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals("Line1\nLine2\nLine3", result); // No lines should be removed
	}

	@Test
	@Tag("boundary")
	public void handleNegativeLinesToDelete() {
		// Arrange
		String pageText = "Line1\nLine2\nLine3";
		int numberOfLines = -1; // Invalid input
		String lineSeparator = "\n";
		// Act
		String result = ExtractedTextFormatter.deleteBottomTextLines(pageText, numberOfLines, lineSeparator);
		// Assert
		assertEquals("Line1\nLine2\nLine3", result); // Behavior should ensure no lines
														// are removed
	}

}