/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=get_3e6c791c39
ROOST_METHOD_SIG_HASH=get_41813161f9


Scenario 1: Valid Input Resources Produce Correct Documents

Details:
  TestName: validResourceProducesCorrectDocument
  Description: Validates if the `get` method correctly processes a valid resource and returns a `Document` object containing the expected content and metadata.

Execution:
  Arrange: Create a mock `Resource` object that simulates returning an `InputStream` and filename. Set up the mock to return a string representation of the content when read. Ensure the `charset` is set to UTF-8.
  Act: Invoke the `get` method of the `TextReader` instance.
  Assert: Verify that the returned `Document` object contains the correct content and metadata values corresponding to `CHARSET_METADATA`, `SOURCE_METADATA`, and the filename from the resource.

Validation:
  This test ensures that the `get` method functions correctly when valid resources are provided, producing accurate document content and metadata. The behavior validates adherence to the business expectations of document generation.

*/

// ********RoostGPT********

package org.springframework.ai.reader;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import org.springframework.ai.document.Document;
import org.springframework.core.io.Resource;
import org.springframework.util.StreamUtils;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;
import java.net.URI;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.Objects;
import org.springframework.ai.document.DocumentReader;
import org.springframework.core.io.DefaultResourceLoader;

class TextReaderGetTest {

	private static final String CHARSET_METADATA = "charset";

	private static final String SOURCE_METADATA = "source";

	@Test
	@Tag("valid")
	public void validResourceProducesCorrectDocument() throws IOException {
		// Arrange
		String mockContent = "Test Document Content";
		String mockFilename = "test-file.txt";
		Resource mockResource = Mockito.mock(Resource.class);
		when(mockResource.getInputStream())
			.thenReturn(new ByteArrayInputStream(mockContent.getBytes(StandardCharsets.UTF_8)));
		when(mockResource.getFilename()).thenReturn(mockFilename);
		TextReader textReader = new TextReader(mockResource);
		// Act
		List<Document> documents = textReader.get();
		// Assert
		assertEquals(1, documents.size());
		Document document = documents.get(0);
		assertEquals(mockContent, (String) document.getText()); // Updated to match
																// correct attribute from
																// Document class
		assertEquals(StandardCharsets.UTF_8.name(), document.getMetadata().get(CHARSET_METADATA));
		assertEquals(mockFilename, document.getMetadata().get(SOURCE_METADATA));
	}

	@Test
	@Tag("invalid")
	public void resourceInputStreamThrowsIOException() throws IOException {
		// Arrange
		Resource mockResource = Mockito.mock(Resource.class);
		when(mockResource.getInputStream()).thenThrow(new IOException("Simulated IOException"));
		TextReader textReader = new TextReader(mockResource);
		// Act & Assert
		assertThrows(RuntimeException.class, textReader::get);
	}

	@Test
	@Tag("invalid")
	public void resourceHasNullFilename() throws IOException {
		// Arrange
		String mockContent = "Test Document Content";
		Resource mockResource = Mockito.mock(Resource.class);
		when(mockResource.getInputStream())
			.thenReturn(new ByteArrayInputStream(mockContent.getBytes(StandardCharsets.UTF_8)));
		when(mockResource.getFilename()).thenReturn(null); // Simulate null filename
		TextReader textReader = new TextReader(mockResource);
		// Act
		List<Document> documents = textReader.get();
		// Assert
		assertEquals(1, documents.size());
		Document document = documents.get(0);
		assertEquals(mockContent, (String) document.getText()); // Updated to match
																// correct attribute from
																// Document class
		assertEquals(StandardCharsets.UTF_8.name(), document.getMetadata().get(CHARSET_METADATA));
		assertEquals(null, document.getMetadata().get(SOURCE_METADATA));
	}

	@Test
	@Tag("boundary")
	public void emptyResourceContentCreatesDocument() throws IOException {
		// Arrange
		String mockContent = ""; // Simulate empty document content
		String mockFilename = "test-file-empty.txt";
		Resource mockResource = Mockito.mock(Resource.class);
		when(mockResource.getInputStream())
			.thenReturn(new ByteArrayInputStream(mockContent.getBytes(StandardCharsets.UTF_8)));
		when(mockResource.getFilename()).thenReturn(mockFilename);
		TextReader textReader = new TextReader(mockResource);
		// Act
		List<Document> documents = textReader.get();
		// Assert
		assertEquals(1, documents.size());
		Document document = documents.get(0);
		assertEquals(mockContent, (String) document.getText()); // Updated to match
																// correct attribute from
																// Document class
		assertEquals(StandardCharsets.UTF_8.name(), document.getMetadata().get(CHARSET_METADATA));
		assertEquals(mockFilename, document.getMetadata().get(SOURCE_METADATA));
	}

}