/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanProjectPath10thJuly using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=extractAiResponseHeaders_8fb66a66da
ROOST_METHOD_SIG_HASH=extractAiResponseHeaders_96c93ba4a9

Scenario 1: Extract Headers Successfully

Details:
  TestName: extractHeadersSuccessfully
  Description: This test verifies that the method correctly extracts all rate limit headers from a ResponseEntity and returns a populated OpenAiRateLimit object.
Execution:
  Arrange: Create a mock ResponseEntity with all necessary headers set to valid long and duration values.
  Act: Call extractAiResponseHeaders with the mock ResponseEntity.
  Assert: Check that the returned OpenAiRateLimit object contains the expected values for requestsLimit, requestsRemaining, requestsReset, tokensLimit, tokensRemaining, and tokensReset.
Validation:
  This test ensures that the method correctly parses and returns all header values when they are present and valid, which is crucial for accurate rate limiting in the application.

Scenario 2: Missing Headers

Details:
  TestName: handleMissingHeadersGracefully
  Description: This test checks the method's behavior when some headers are missing from the ResponseEntity.
Execution:
  Arrange: Create a mock ResponseEntity with some headers missing.
  Act: Call extractAiResponseHeaders with the mock ResponseEntity.
  Assert: Verify that the returned OpenAiRateLimit object has null values for the missing headers.
Validation:
  The test confirms that the method can handle missing headers without throwing exceptions, which is important for robustness in real-world scenarios where headers might be absent.

Scenario 3: Invalid Long Header Value

Details:
  TestName: handleInvalidLongHeaderValue
  Description: This test examines the method's response to a header containing an invalid long value.
Execution:
  Arrange: Create a mock ResponseEntity with one of the long headers set to a non-numeric string.
  Act: Call extractAiResponseHeaders with the mock ResponseEntity.
  Assert: Ensure that the returned OpenAiRateLimit object has a null value for the invalid header and logs a warning.
Validation:
  This test verifies that the method logs a warning and returns null for invalid long values, maintaining application stability and providing diagnostic information.

Scenario 4: Invalid Duration Header Value

Details:
  TestName: handleInvalidDurationHeaderValue
  Description: This test checks how the method handles a header with an invalid duration value.
Execution:
  Arrange: Create a mock ResponseEntity with one of the duration headers set to an invalid format.
  Act: Call extractAiResponseHeaders with the mock ResponseEntity.
  Assert: Confirm that the returned OpenAiRateLimit object has a null value for the invalid duration header.
Validation:
  The test ensures that the method can handle invalid duration values gracefully, which is essential for preventing runtime errors and ensuring reliable operation.

Scenario 5: All Headers Missing

Details:
  TestName: handleAllHeadersMissing
  Description: This test assesses the method's behavior when all expected headers are missing from the ResponseEntity.
Execution:
  Arrange: Create a mock ResponseEntity with no headers set.
  Act: Call extractAiResponseHeaders with the mock ResponseEntity.
  Assert: Verify that the returned OpenAiRateLimit object has all fields set to null.
Validation:
  This test confirms that the method can handle a completely missing header scenario without errors, which is crucial for robustness and error handling in the application.

Scenario 6: Mixed Valid and Invalid Headers

Details:
  TestName: handleMixedValidAndInvalidHeaders
  Description: This test evaluates the method's ability to process a mix of valid and invalid headers.
Execution:
  Arrange: Create a mock ResponseEntity with some headers set to valid values and others set to invalid values.
  Act: Call extractAiResponseHeaders with the mock ResponseEntity.
  Assert: Check that the returned OpenAiRateLimit object contains correct values for valid headers and null for invalid ones.
Validation:
  The test ensures that the method can selectively parse valid headers while ignoring invalid ones, maintaining functionality and reliability in diverse input scenarios.

*/

// ********RoostGPT********

package org.springframework.ai.openai.metadata.support;

import java.time.Duration;
import java.util.Collections;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseEntity;
import org.springframework.util.CollectionUtils;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.time.temporal.ChronoUnit;
import java.util.Arrays;
import java.util.function.Predicate;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.metadata.RateLimit;
import org.springframework.ai.openai.metadata.OpenAiRateLimit;
import org.springframework.util.Assert;
import org.springframework.util.StringUtils;
import static org.springframework.ai.openai.metadata.support.OpenAiApiResponseHeaders.REQUESTS_LIMIT_HEADER;
import static org.springframework.ai.openai.metadata.support.OpenAiApiResponseHeaders.REQUESTS_REMAINING_HEADER;
import static org.springframework.ai.openai.metadata.support.OpenAiApiResponseHeaders.REQUESTS_RESET_HEADER;
import static org.springframework.ai.openai.metadata.support.OpenAiApiResponseHeaders.TOKENS_LIMIT_HEADER;
import static org.springframework.ai.openai.metadata.support.OpenAiApiResponseHeaders.TOKENS_REMAINING_HEADER;
import static org.springframework.ai.openai.metadata.support.OpenAiApiResponseHeaders.TOKENS_RESET_HEADER;

public class OpenAiResponseHeaderExtractorExtractAiResponseHeadersTest {

	private ResponseEntity<?> mockResponseEntity;

	@BeforeEach
	public void setUp() {
		mockResponseEntity = Mockito.mock(ResponseEntity.class);
	}

	@Test
	@Tag("valid")
	public void extractHeadersSuccessfully() {
		HttpHeaders headers = new HttpHeaders();
		headers.add(REQUESTS_LIMIT_HEADER.getName(), "1000");
		headers.add(REQUESTS_REMAINING_HEADER.getName(), "500");
		headers.add(TOKENS_LIMIT_HEADER.getName(), "2000");
		headers.add(TOKENS_REMAINING_HEADER.getName(), "1500");
		headers.add(REQUESTS_RESET_HEADER.getName(), "PT1H");
		headers.add(TOKENS_RESET_HEADER.getName(), "PT2H");
		when(mockResponseEntity.getHeaders()).thenReturn(headers);
		RateLimit rateLimit = OpenAiResponseHeaderExtractor.extractAiResponseHeaders(mockResponseEntity);
		assertNotNull(rateLimit);
		assertEquals(1000L, (long) rateLimit.getRequestsLimit());
		assertEquals(500L, (long) rateLimit.getRequestsRemaining());
		assertEquals(Duration.ofHours(1), rateLimit.getRequestsReset());
		assertEquals(2000L, (long) rateLimit.getTokensLimit());
		assertEquals(1500L, (long) rateLimit.getTokensRemaining());
		assertEquals(Duration.ofHours(2), rateLimit.getTokensReset());
	}

	@Test
	@Tag("invalid")
	public void handleMissingHeadersGracefully() {
		HttpHeaders headers = new HttpHeaders();
		headers.add(REQUESTS_LIMIT_HEADER.getName(), "1000");
		// Missing other headers
		when(mockResponseEntity.getHeaders()).thenReturn(headers);
		RateLimit rateLimit = OpenAiResponseHeaderExtractor.extractAiResponseHeaders(mockResponseEntity);
		assertNotNull(rateLimit);
		assertEquals(1000L, (long) rateLimit.getRequestsLimit());
		assertNull(rateLimit.getRequestsRemaining());
		assertNull(rateLimit.getRequestsReset());
		assertNull(rateLimit.getTokensLimit());
		assertNull(rateLimit.getTokensRemaining());
		assertNull(rateLimit.getTokensReset());
	}

	@Test
	@Tag("invalid")
	public void handleInvalidLongHeaderValue() {
		HttpHeaders headers = new HttpHeaders();
		headers.add(REQUESTS_LIMIT_HEADER.getName(), "invalid");
		when(mockResponseEntity.getHeaders()).thenReturn(headers);
		RateLimit rateLimit = OpenAiResponseHeaderExtractor.extractAiResponseHeaders(mockResponseEntity);
		assertNotNull(rateLimit);
		assertNull(rateLimit.getRequestsLimit());
	}

	@Test
	@Tag("invalid")
	public void handleInvalidDurationHeaderValue() {
		HttpHeaders headers = new HttpHeaders();
		headers.add(REQUESTS_RESET_HEADER.getName(), "invalid");
		when(mockResponseEntity.getHeaders()).thenReturn(headers);
		RateLimit rateLimit = OpenAiResponseHeaderExtractor.extractAiResponseHeaders(mockResponseEntity);
		assertNotNull(rateLimit);
		assertNull(rateLimit.getRequestsReset());
	}

	@Test
	@Tag("invalid")
	public void handleAllHeadersMissing() {
		HttpHeaders headers = new HttpHeaders();
		// No headers set
		when(mockResponseEntity.getHeaders()).thenReturn(headers);
		RateLimit rateLimit = OpenAiResponseHeaderExtractor.extractAiResponseHeaders(mockResponseEntity);
		assertNotNull(rateLimit);
		assertNull(rateLimit.getRequestsLimit());
		assertNull(rateLimit.getRequestsRemaining());
		assertNull(rateLimit.getRequestsReset());
		assertNull(rateLimit.getTokensLimit());
		assertNull(rateLimit.getTokensRemaining());
		assertNull(rateLimit.getTokensReset());
	}

	@Test
	@Tag("invalid")
	public void handleMixedValidAndInvalidHeaders() {
		HttpHeaders headers = new HttpHeaders();
		headers.add(REQUESTS_LIMIT_HEADER.getName(), "1000");
		headers.add(REQUESTS_REMAINING_HEADER.getName(), "invalid");
		headers.add(TOKENS_LIMIT_HEADER.getName(), "2000");
		headers.add(TOKENS_RESET_HEADER.getName(), "invalid");
		when(mockResponseEntity.getHeaders()).thenReturn(headers);
		RateLimit rateLimit = OpenAiResponseHeaderExtractor.extractAiResponseHeaders(mockResponseEntity);
		assertNotNull(rateLimit);
		assertEquals(1000L, (long) rateLimit.getRequestsLimit());
		assertNull(rateLimit.getRequestsRemaining());
		assertNull(rateLimit.getRequestsReset());
		assertEquals(2000L, (long) rateLimit.getTokensLimit());
		assertNull(rateLimit.getTokensRemaining());
		assertNull(rateLimit.getTokensReset());
	}

}