/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=toString_18d2135bd3
ROOST_METHOD_SIG_HASH=toString_632cc030bd

Scenario 1: Verify toString method returns correctly formatted string when 'text' field is set to a valid non-null value

Details:
  TestName: toStringReturnsFormattedStringWithValidText
  Description: This test ensures that the toString method correctly formats the output string when the 'text' field is set to a valid non-null String value. The functionality verifies whether the output string contains the expected components and matches the prescribed format.
Execution:
  Arrange: Create an instance of ModerationMessage and set the 'text' field to a valid non-null String value (e.g., "Hello, World!").
  Act: Invoke the toString method on the ModerationMessage instance.
  Assert: Use JUnit assertions to check if the output string matches the expected format: "ModerationMessage{text='Hello, World!'}".
Validation:
  Verify the correctness of the string format returned by the toString method. This ensures that string concatenation within the method is implemented properly for non-null values.

*/

// ********RoostGPT********

package org.springframework.ai.moderation;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class ModerationMessageToStringTest {

	@Test
	@Tag("valid")
	public void toStringReturnsFormattedStringWithValidText() {
		// Arrange
		ModerationMessage moderationMessage = new ModerationMessage("Hello, World!");
		// Act
		String result = moderationMessage.toString();
		// Assert
		assertEquals("ModerationMessage{text='Hello, World!'}", result);
	}

	@Test
	@Tag("invalid")
	public void toStringReturnsFormattedStringWithNullText() {
		// Arrange
		ModerationMessage moderationMessage = new ModerationMessage(null);
		// Act
		String result = moderationMessage.toString();
		// Assert
		assertEquals("ModerationMessage{text='null'}", result);
	}

	@Test
	@Tag("boundary")
	public void toStringReturnsFormattedStringWithEmptyText() {
		// Arrange
		ModerationMessage moderationMessage = new ModerationMessage("");
		// Act
		String result = moderationMessage.toString();
		// Assert
		assertEquals("ModerationMessage{text=''}", result);
	}

	@Test
	@Tag("boundary")
	public void toStringReturnsFormattedStringWithWhitespaceText() {
		// Arrange
		ModerationMessage moderationMessage = new ModerationMessage("   "); // TODO Update
																			// test value
																			// when
																			// required.
		// Act
		String result = moderationMessage.toString();
		// Assert
		assertEquals("ModerationMessage{text='   '}", result);
	}

}