/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=hashCode_8c73be2899
ROOST_METHOD_SIG_HASH=hashCode_114496c04f

Scenario 1: Verify hashCode returns consistent values for identical objects

Details:
  TestName: verifyHashCodeConsistencyWithIdenticalObjects
  Description: This test is meant to ensure that the `hashCode` method returns the same value for two objects that are considered equal according to their `equals()` implementation. The test validates the consistency of the hash code for objects with identical `text` fields.

Execution:
  Arrange: Create two instances of `ModerationMessage` with identical `text` values (e.g., "Sample text").
  Act: Call the `hashCode` method on both instances.
  Assert: Use assertions to confirm that the hash code values returned by both objects are equal.

Validation:
  The assertion verifies that `hashCode` is consistent with `equals()`, which is a fundamental requirement in Java for using objects in data structures like `HashMap` and `HashSet`. This test is significant to ensure that the application's behavior adheres to Java object contract rules.

*/

// ********RoostGPT********

package org.springframework.ai.moderation;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import java.util.Objects;

class ModerationMessageHashCodeTest {

	@Test
	@Tag("valid")
	public void verifyHashCodeConsistencyWithIdenticalObjects() {
		// Arrange
		ModerationMessage message1 = new ModerationMessage("Sample text");
		ModerationMessage message2 = new ModerationMessage("Sample text");
		// Act
		int hashCode1 = message1.hashCode();
		int hashCode2 = message2.hashCode();
		// Assert
		assertEquals(hashCode1, hashCode2, "Hash codes for identical objects should be equal.");
	}

}